//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_ar.properties
define( {
            "Games.label.level": "المستوي:\n{0}",
            "Common.updates.errorMessage": "حصل خطأ أثناء محاولة التحديث. <br>الرجاء المحاولة مرة أخرى أو زيارة {0}.",
            "XMLPersistenceManager.save.error.encode": "<html>خطأ في ترميز الملف:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>خطأ في تشفير الملف\n<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "f",
            "Common.softwareAgreement.decline": "إنهاء",
            "Common.statistics.host_os_name": "اسم نظام التشغيل",
            "Common.statistics.user_total_sessions": "مجموع عدد مرات تشغيل كل برامج المحاكاة ",
            "Common.statistics.host_java_version_major": "نسخة جافا (الرئيسة",
            "FileChooser.openDialogTitleText": "فتح",
            "Common.WhiteBackground": "خلفية بيضاء",
            "Common.statistics.host_java_version_maintenance": "نسخة جافا (الصيانة",
            "FileChooser.lookInLabelText": "البحث في:",
            "Common.choice.cancel": "إلغاء",
            "Common.updates.seePreferences": "اذهب إلى ملف --> التفضيلات لتغيير التفضيلات.",
            "Common.About.CreditsDialog.software-development": "تطوير البرنامج",
            "Common.About.JavaVersion": "نسخة جافا",
            "ColorChooser.resetText": "إعادة الضبط",
            "wavelength.ir": "تحت الحمراء",
            "translation.credits": "KSU",
            "Common.WhiteBackground.mnemonic": "w",
            "Common.About.CreditsDialog.design-team": "فريق التصميم",
            "Common.statistics.sim_total_sessions": "مجموع عدد مرات تشغيل المحاكاة ",
            "Common.FileMenu.PreferencesMnemonic": "p",
            "wavelength.uv": "فوق البنفسجية",
            "Games.title.gameSettings": "إعدادات اللعبة",
            "XMLPersistenceManager.save.title": "حفظ الترتيب",
            "XMLPersistenceManager.load.error.contents": "الملف غير صالح أو لم يتم إنشاؤه عن طريق المحاكاة",
            "Common.statistics.details.title": "المعلومات",
            "Common.statistics.sim_dev_version": "نسخة المحاكاة (المطور",
            "FileChooser.saveInLabelText": "حفظ في:",
            "Common.statistics.sim_name": "اسم المحاكاة",
            "Save.confirm.message": "<html>الملف الذي اخترته موجود. \n<br>\nهل تريد استبدال الملف بالملف الذي تريد حفظه؟\n</html>",
            "Games.label.score": "النتيجة\n: {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "فريق التطوير بمشروع تقنيات تعليم الفيزياء بجامعة كلورادو -بولدر",
            "Games.button.start": "ابدآ",
            "Common.statistics.sim_deployment": "نوع النشر ",
            "Common.FileMenu.Save": "حفظ الترتيب",
            "Common.About.CreditsDialog.licenseDetails": "تفاصيل الرخصة",
            "ColorChooser.hsbSaturationText": "التشبع",
            "Games.radioButton.on": "مفتوح",
            "FileChooser.acceptAllFileFilterText": "كل الملفات (*.*)",
            "ColorChooser.hsbNameText": "تدرج اللون والتشبع وشدة النصوع",
            "Common.ModelSlider.Minimum": "أقل",
            "Common.FileMenu.Preferences": "التفضيلات",
            "Common.FileMenu.Load": "تحميل الترتيب",
            "Common.updates.downloadingSimJar": "تحميل ملف المحاكاة JAR",
            "Games.radioButton.off": "مغلق",
            "Jme.copyThisToTheClipboard": "نسخ إلى الذاكرة",
            "ColorChooser.swatchesRecentText": "الحالي",
            "Common.updates.updateAvailable": "التحديث متوفر",
            "Common.statistics.host_locale_language": "لغة البلد",
            "Common.clear": "مسح",
            "Games.title.gameOver": "اللعبة انتهت",
            "FileChooser.filesOfTypeLabelText": "نوع الملف:",
            "Common.ErrorDialog.detailsTitle": "تفاصيل الخطأ",
            "Common.HelpMenu.MegaHelp": "مساعدة مكثفة ...",
            "Common.ClockControlPanel.Step": "خطوة",
            "Common.statistics.sim_revision": "نسخة المحاكاة (تحديث",
            "Common.choice.yes": "نعم",
            "PiccoloPhet.VelocitySensorNode.unknown": "?",
            "Common.FileMenu.Title": "ملف",
            "Common.value_units": "{0} {1}",
            "Common.statistics.sim_dev": "هل هذه نسخة المطور؟",
            "Common.updates.installer.message": "<html>محمل موقع فت بدون اتصال قديم{0}، \n<br>النسخة الأحدث متوفرة وتاريخها \n{1}.<br><br>\nهل تريد أخر نسخة من مثبت موقع فت بدون اتصال؟  \n</html>",
            "Common.updates.updateNow": "قم بالتحديث الآن",
            "Common.record": "تسجيل",
            "Common.About.CreditsDialog.Title": "شكر",
            "Common.updates.error.internetConnection": "<html>لايمكن الاتصال. \n{0},<br>\nفضلا تأكد من اتصالك بالشبكة </html>",
            "Common.time.fast": "سريع",
            "XMLPersistenceManager.load.error.message": "<html>خطأ في القرأة من الملف:\n<br>{0}</html>",
            "Common.ModelSlider.Maximum": "أقصى",
            "Common.OptionsMenu": "الخيارات",
            "Common.ClockControlPanel.Restart": "إعادة التشغيل",
            "Common.statistics.sim_version_timestamp": "نسخة المحاكاة (الختم الزمني",
            "Common.updates.installer.yes": "نعم!",
            "Common.phetInstaller": "مثبت موقع فت بدون اتصال ",
            "Jme.thisSimulationWasUnableToStart": "لم تعمل المحاكاة",
            "Common.HelpMenu.About": "حول ...",
            "Common.ModelSlider.OutOfRange": "القيمة خارج النطاق",
            "Common.About.CreditsDialog.TranslationCreditsTitle": "قام بالترجمة",
            "ColorChooser.previewText": "معاينة",
            "Common.BasicPhetPanel.Title": "عودة",
            "Common.HelpPanel.HideHelp": "إخفاء المساعدة",
            "Common.statistics.host_os_arch": "نوع المعالج",
            "Common.preferences.title": "التفضيلات",
            "Games.button.newGame": "لعبة جديدة",
            "ColorChooser.hsbRedText": "أحمر",
            "ColorChooser.hsbBlueText": "أزرق",
            "Common.ModelSlider.YouEntered": "أدخلت",
            "Games.label.newBest": "الأفضل",
            "Common.About.BuildDate": "تاريخ الإنشاء",
            "Common.FileMenu.ExitMnemonic": "x",
            "Common.statistics.sim_project": "اسم المشروع",
            "Games.label.best": "الأفضل: \n{0}",
            "Common.title.message": "رسالة",
            "Common.updates.downloadingBootstrap": "تحميل محدث بدء التشغيل",
            "Common.title.error": "خطأ",
            "Common.FileMenu.Exit": "إنهاء",
            "Common.statistics.sim_major_version": "نسخة المحاكاة (الرئيسية",
            "Common.updates.askMeLater": "اسألني مرة أخرى",
            "chart-time-control.go": "اذهب!",
            "Common.HelpMenu.HelpMnemonic": "h",
            "Common.confirm.clear.graphs": "هل تريد بالتأكيد  مسح الرسوم البيانية؟",
            "ColorChooser.swatchesNameText": "سلسلة نماذج",
            "Common.updates.progressDialogMessage": "تحديث \"{0}\" إلى {1}",
            "Common.updates.installer.more": "اخبرني أكثر ...",
            "XMLPersistenceManager.title.error": "خطأ",
            "ColorChooser.hsbHueText": "تدرج اللون",
            "ControlPanel.button.resetAll": "إعادة الضبط للجميع",
            "Common.About.AgreementButton": "اتفاقية البرنامج .....",
            "Common.FileMenu.Load.mnemonic": "L",
            "Common.ErrorDialog.detailsButton": "التفاصيل",
            "Common.updates.errorMissingJar": "<html>هذا التحديث لايمكن أن يعمل. \n<br>\nلم يتم الوصول إلى ملف الجافا \n {0}.<br> الرجاء\nالاتصال بمدير النظام للمساعدة\n<br></html>",
            "Common.preferences.privacy": "خصوصية",
            "Common.HelpMenu.AboutTitle": "حول",
            "ColorChooser.rgbRedText": "أحمر",
            "Common.statistics.sim_locale_country": "البلد",
            "ColorChooser.hsbGreenText": "أخضر",
            "ColorChooser.rgbGreenText": "أخضر",
            "Games.format.time.best": "{0} ({1})",
            "Common.HelpPanel.ShowHelp": "مساعدة!",
            "PiccoloPhet.VelocitySensorNode.speed": "السرعة",
            "Common.statistics.sim_distribution_tag": "نسخة المحاكاة (التوزيع",
            "Common.statistics.description": "برنامج \"فت\" برنامج مجاني مدعوم من منح تتطلب <br> تجميع قليل من المعلومات <br>مجهولة المصدر <a href=\"{0}\"></a> للمساعدة في رصد<br> كمية استخدام برامج المحاكاة <br> وخدمة المستخدمين",
            "Common.softwareAgreement.message": "في كل برامج المحاكاة، يتم تجميع قليل من المعلومات  <br> مجهولة الاسم <a href=\"{0}\"> </a> في كل مرة تبدأ المحاكاة، <br> مثل: نسخة المحاكاة، نظام التشغيل..<br> بإمكانك عدم السماح بإرسال هذه المعلومات <br> في أي وقت عن طريق قائمة ملف-->التفضيلات <br><br> بالنقر على \"موافق واستمرار\" أنت موافق على <br> اتفاقية البرنامج والتي تحتوي على أنظمة الخصوصية، <br> لهذه ولكل برامج المحاكاة. <br>( لتفاصيل أكثر، انقر هنا.\n<a href=\"{1}\">here</a>).\n",
            "Common.choice.ok": "موافق",
            "Common.About.Version": "نسخة",
            "Common.ErrorDialog.contactPhet": "إذا تكررت المشكلة، أرسل التفاصيل في الأسفل إلى {0}",
            "Common.About.CreditsDialog.lead-design": "المصمم الرئيس",
            "Common.OptionsMenu.mnemonic": "O",
            "Jme.moreInformation": "<html><body>تحديث كرت الفيديو قد يحل المشكلة لديك<br/>لمعلومات أكثر قم بزيارة {0},<br/> أو انسخ والصق الأتي ببريد الكتروني إلى {1}.<br/></body></html>",
            "Common.statistics.user_preference_file_creation_time": "الختم الزمني لاستحداث ملف التفضيلات",
            "Common.HelpMenu.AboutMnemonic": "a",
            "Common.updates.errorWritePermissions": "<html>هذا التحديث لايمكن أن يعمل. <br>لاتملك إذن الكتابة إلى {0}. الرجاء الاتصال بمدير النظام للمساعدة\n<br></html>",
            "ColorChooser.hsbBrightnessText": "شدة النصوع",
            "Common.choice.no": "لا",
            "Common.About.WebLink": "قم بزيارة موقع مشروع فت   ",
            "Common.About.OSVersion": "نسخة برنامج التشغيل",
            "Common.title.warning": "تحذير",
            "Common.updates.versionComparison": "<html>نسختك الحالية من  \"{0}\" هي \n{1}.<br>\nالنسخة الأحدث ({2}) متوفرة\n</html>",
            "Common.statistics.sim_locale_language": "اللغة",
            "Common.statistics.user_installation_timestamp": "الختم الزمني لتحميل مشروع فت",
            "Common.statistics.message_version": "نسخة الرسالة",
            "Common.ModelSlider.Description": "قيمة غير مسموح بها",
            "Common.updates.installer.moreMessage": "<html>تحميل آخر نسخة محدثة من موقع فت بدون اتصال\n<br>\n يجعل لك مدخل لأحدث برامج المحاكاة\n<br>\n من فت واللوازم الأخرى. \n<br><br>\nإذا اخترت الحصول على آخر نسخة، سيفتح المتصفح \n<br>\nعلى موقع \" الفت\" بحيث تحمل مثبت \n<br>\nموقع فت بدون اتصال\n</html>  ",
            "Common.HelpMenu.Help": "مساعدة",
            "Common.updates.errorNotAJar": "{0}  ليس ملف جافا",
            "ControlPanel.message.confirmResetAll": "إعادة الضبط للإعدادات",
            "Games.label.levelControl": "المستوى:",
            "Common.updates.automaticallyCheck": "البحث عن آخر تحديث تلقائيا",
            "Common.sim.speed": "... سرعة المحاكاة ...",
            "Common.updates.checkForSimUpdate": "تأكد من آخرتحديث للمحاكاة",
            "XMLPersistenceManager.save.confirm.message": "<html>\nالملف الذي اخترته موجود. \n<br>\nهل تريد استبدال الملف بالملف الذي تريد حفظه؟\n</html>",
            "FileChooser.newFolderErrorText": "خطأ في إنشاء مجلد جديد",
            "Common.About.CreditsButton": "شكر ...",
            "Common.updates.skipThisUpdate": "تخطي هذه النسخة",
            "Common.FileMenu.Save.mnemonic": "S",
            "Common.TeacherMenu": "المعلم",
            "FileChooser.saveDialogTitleText": "حفظ",
            "XMLPersistenceManager.load.title": "تحميل الترتيب",
            "Common.updates.checkForInstallerUpdate": "تأكد من تحديث مثبت موقع فت الذي يعمل بدون اتصال ...",
            "timeseries.control.panel.playback": "أعد التشغيل",
            "Common.updates.progressDialogTitle": "تحديث",
            "Common.HelpMenu.Title": "مساعدة",
            "Common.TeacherMenu.mnemonic": "م",
            "ColorChooser.rgbNameText": "نموذج اللون(أحمر،أخضر،أزرق",
            "FileChooser.fileNameLabelText": "اسم الملف:",
            "Common.softwareAgreement.title": "اتفاقية البرنامج",
            "Common.statistics.host_java_version_minor": "نسخة جافا (الفرعية",
            "Common.HelpMenu.TitleMnemonic": "h",
            "Common.About.CreditsDialog.interviews": "المقابلات",
            "Common.About.Distribution": "التوزيع",
            "Common.statistics.host_java_webstart_version": "نسخة جافا (الشبكة",
            "XMLPersistenceManager.save.error.message": "\n<html>خطأ في الكتابة إلى الملف:<br>{0}</html>",
            "Games.label.time": "الزمن\n: {0}",
            "FileChooser.openButtonText": "فتح",
            "ColorChooser.sampleText": "عينة من النص",
            "Common.statistics.details.description": "<html>المعلومات أدناه سيتم إرسالها إلى فريق البرنامج \"فت\" في كل مرة تبدأ المحاكاة.</html>",
            "Common.statistics.host_os_version": "نسخة نظام التشغيل",
            "ksu.credits": "تم إعداد وتهيئة برمجيات المحاكاة والموقع الخاص بها باللغة العربية عن طريق<br><a href=\"http://ecsme.ksu.edu.sa\" target=\"_blank\">مركز التميز البحثي في تطوير تعليم العلوم والرياضيات</a><br>(أفكر)<br>بجامعة الملك سعود، الرياض، المملكة العربية السعودية",
            "Common.title.confirm": "تأكيد",
            "Common.BasicPhetPanel.LogoToolTip": "عدم السماح بالإطار الكامل",
            "Games.label.score.max": "النتيجة\n: {0} out of {1}",
            "Common.statistics.host_java_timezone": "نطاق الوقت",
            "Common.time.slow": "بطئ",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.ClockControlPanel.Rewind": "إعادة اللف",
            "Common.softwareAgreement.accept": "قبول واستمرار",
            "message.valueOutOfRange": "القيمة لابد أن تكون بين {0} و\n{1}.\n",
            "Common.updates.updateToDate": "محدث",
            "Common.ClockControlPanel.Pause": "توقف مؤقتا",
            "PhetApplication.StartupDialog.message": "\"{0}\" في حالة البدء",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "هذا البرنامج يستخدم البرامج التالية من طرف ثالث",
            "XMLPersistenceManager.message.notAConfigFile": "هذا الملف لايحتوي على ترتيب للمحاكاة",
            "Common.preferences.updates": "تحديث",
            "Games.label.score.max.perfect": "النتيجة\n: {0} out of {1}\nكامل",
            "Common.HelpMenu.MegaHelpMnemonic": "m",
            "Common.statistics.enabled": "السماح بإرسال المعلومات إلى فريق برنامج فت",
            "Common.ClockControlPanel.StepBack": "خطوة للخلف",
            "Common.StopwatchPanel.stop": "إيقاف",
            "Common.HelpPanel.MegaHelp": "مساعدة مكثفة ...",
            "Common.statistics.host_locale_country": "البلد المستضيف",
            "Common.StopwatchPanel.reset": "إعادة الضبط",
            "Common.playback": "إعادة التشغيل",
            "Common.statistics.sim_minor_version": "نسخة المحاكاة (الفرعية",
            "Games.message.confirmNewGame": "<html>لم تنه اللعبة بعد<br>هل أنت متأكد من رغبتك في البدء بلعبة جديدة؟</html>",
            "Common.updates.tryIt": "تجريب النسخة الجديدة قبل التحديث",
            "ColorChooser.rgbBlueText": "أزرق",
            "Common.choice.close": "إغلاق",
            "Common.ClockControlPanel.Play": "تشغيل",
            "Common.statistics.sim_type": "نوع المحاكاة",
            "FileChooser.saveButtonText": "حفظ",
            "Common.rewind": "إعادة اللف",
            "Common.StopwatchPanel.start": "ابدأ",
            "Common.updates.youHaveCurrent": "لديك آخر نسخة محدثة ({0}) من \n{1}. ",
            "Common.statistics.sim_sessions_since": "عدد المرات التي تم تشغيل المحاكاة منذ آخر مرة",
            "Common.statistics.host_java_vendor": "مورد جافا",
            "charts.show-graphs": "اظهر الرسوم البيانية:",
            "Common.statistics.message_type": "نوع الرسالة"
        } );