//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_da.properties
define( {
            "Games.label.levelControl": "Niveau:",
            "Common.time.fast": "hurtig",
            "Common.About.LicenseDialog.Title": "License",
            "XMLPersistenceManager.save.error.xmlencoder": "Fejl ved XLM oversættelsen ",
            "Common.live-mode": "Livagtigt",
            "Common.HelpMenu.AboutTitle": "Om",
            "Common.choice.ok": "OK",
            "Games.label.score.max.perfect": "Score: {0} ud af {1} (Perfekt!)",
            "Common.HelpMenu.MegaHelpMnemonic": "m",
            "Common.confirm.clear.graphs": "Er du sikker på at du vil fjerne al grafikken?",
            "XMLPersistenceManager.save.error.encode": "<html>Fejl ved oversættelse af filen:<br>{0}</html>",
            "Games.message.confirmNewGame": "<html>Du har ikke færdiggjort dette spil.<br>Er du sikker på, at du vil starte et nyt spil?</html>",
            "Games.button.newGame": "Nyt spil",
            "Common.OptionsMenu": "Valgmuligheder",
            "Common.About.CreditsButton": "Tak til",
            "Save.confirm.message": "<html>Filen du valgte eksisterer allerede.<br>Vil du erstatte den med den fil du vil gemme?<html>",
            "Common.HelpPanel.HideHelp": "Skjul Hjælp",
            "Common.FileMenu.TitleMnemonic": "f",
            "Common.About.OSVersion": "OS Version:",
            "XMLPersistenceManager.save.title": "Gem indstillingerne",
            "Common.choice.no": "Nej",
            "XMLPersistenceManager.title.error": "Fejl",
            "XMLPersistenceManager.save.error.message": "<html>Fejlskrivning til filen:<br>{0}</html>",
            "Common.OptionsMenu.mnemonic": "V",
            "Common.pause.recording": "Pause Optag",
            "Common.FileMenu.Title": "Fil",
            "XMLPersistenceManager.load.error.contents": "Filen er ødelagt eller er ikke lavet i dette program.",
            "Common.rewind": "Tilbagespoling",
            "Games.label.newBest": "Ny rekord!",
            "Games.title.gameSettings": "Indstillinger",
            "Games.radioButton.on": "On",
            "Common.HelpMenu.TitleMnemonic": "h",
            "Common.ModelSlider.Maximum": "Maksimum",
            "Common.ClockControlPanel.Play": "Afspil",
            "Common.ModelSlider.YouEntered": "Du indtastede",
            "XMLPersistenceManager.save.confirm.message": "<html>Filen du valgte eksisterer allerede.<br>Vil du erstatte den med den fil du vil gemme?<html>",
            "Common.slow.motion": "Langsom",
            "Games.label.score": "Score: {0}",
            "Common.choice.cancel": "Afbryd",
            "Common.pause.playback": "Pause Tilbagespoling",
            "Common.ClockControlPanel.Pause": "Pause",
            "Games.label.best": "Bedste: {0}",
            "Common.HelpMenu.Help": "Hjælp",
            "Common.HelpPanel.MegaHelp": "Udvidet hjælp",
            "XMLPersistenceManager.load.title": "Hent indstillinger",
            "Common.ModelSlider.Minimum": "Minimum",
            "Common.ModelSlider.OutOfRange": "Værdien passer ikke",
            "ControlPanel.message.confirmResetAll": "Nulstil alle indstillinger?",
            "Common.sim.speed": "...simuleret hastighed...",
            "Common.FileMenu.Exit": "Afslut",
            "Common.StopwatchPanel.start": "Start",
            "ControlPanel.button.resetAll": "Nulstil alt",
            "Games.radioButton.off": "Off",
            "Common.HelpMenu.Title": "Hjælp",
            "Common.ClockControlPanel.Step": "Trin",
            "Common.HelpMenu.About": "Om..",
            "Common.HelpMenu.AboutMnemonic": "a",
            "Games.label.level": "Niveau: {0}",
            "Common.clear": "Rens",
            "Games.format.time.best": "{0} ({1})",
            "Common.time.slow": "langsom",
            "Common.HelpMenu.MegaHelp": "Udvidet hjælp",
            "PhetApplication.StartupDialog.message": "\"{0}\" starter",
            "Common.About.CreditsDialog.Title": "Tak til",
            "Common.StopwatchPanel.stop": "Stop",
            "Common.BasicPhetPanel.Title": "Retur",
            "Common.ModelSlider.Description": "Ukorrekt værdi",
            "Common.About.WebLink": "Besøg PhET's hjemmeside",
            "Games.button.start": "Start!",
            "Common.About.Version": "Version:",
            "Common.ClockControlPanel.Restart": "Genstart",
            "Common.About.LicenseButton": "License...",
            "Common.choice.yes": "Ja",
            "Games.label.time": "Tid: {0}",
            "Common.BasicPhetPanel.LogoToolTip": "Slå *Fuld skærm* fra",
            "Games.title.gameOver": "Spillet er slut",
            "Common.slow.playback": "Vis baglæns langsomt",
            "Common.About.OKButton": "OK",
            "Common.About.JavaVersion": "Java Version:",
            "Common.HelpPanel.ShowHelp": "Hjælp!",
            "Common.StopwatchPanel.reset": "Gendan",
            "XMLPersistenceManager.load.error.message": "<htlm>Fejl ved læsning af filen:<br>{0}</html>",
            "Common.FileMenu.ExitMnemonic": "x",
            "Games.label.score.max": "Score: {0} ud af {1}",
            "Common.record": "OPTAG",
            "XMLPersistenceManager.load.error.decode": "<htlm>Fejl ved afkodningen af filen:<br>{0}<html>",
            "Common.title.confirm": "Bekræft",
            "Common.HelpMenu.HelpMnemonic": "h"
        } );