// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.sugarandsaltsolutions;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Translated strings for "SugarAndSaltSolutions" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator$6 on Thu Jun 23 09:51:44 MDT 2011
 * See #2967
 */
public class SugarAndSaltSolutionsResources {
    private static final PhetResources RESOURCES = new PhetResources( "sugar-and-salt-solutions" );

    public static final String SUGAR_AND_SALT_SOLUTIONS_COMBINED_BUTTON_NAME = RESOURCES.getLocalizedString( "sugar-and-salt-solutions-combined-button.name" );
    public static final String SUGAR_AND_SALT_SOLUTIONS_NAME = RESOURCES.getLocalizedString( "sugar-and-salt-solutions.name" );
}