// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.sugarandsaltsolutions;

import java.awt.image.BufferedImage;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Resources (images and translated strings) for "SugarAndSaltSolutions" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator
 */
public class SugarAndSaltSolutionsResources {
    public static final String PROJECT_NAME = "sugar-and-salt-solutions";
    public static final PhetResources RESOURCES = new PhetResources( PROJECT_NAME );

    //Strings
    public static class Strings {
        public static final String BALL_AND_STICK = RESOURCES.getLocalizedString( "ballAndStick" );
        public static final String CALCIUM = RESOURCES.getLocalizedString( "calcium" );
        public static final String CALCIUM_CHLORIDE_CA_CL_2 = RESOURCES.getLocalizedString( "calciumChlorideCaCl2" );
        public static final String CALCIUM_CHLORIDE_NEW_LINE = RESOURCES.getLocalizedString( "calciumChlorideNewLine" );
        public static final String CHLORIDE = RESOURCES.getLocalizedString( "chloride" );
        public static final String CONCENTRATION = RESOURCES.getLocalizedString( "concentration" );
        public static final String CONDUCTIVITY = RESOURCES.getLocalizedString( "conductivity" );
        public static final String EVAPORATION = RESOURCES.getLocalizedString( "evaporation" );
        public static final String GLUCOSE = RESOURCES.getLocalizedString( "glucose" );
        public static final String GLUCOSE_C_6_H_12_O_6 = RESOURCES.getLocalizedString( "glucoseC6H12O6" );
        public static final String LOADING = RESOURCES.getLocalizedString( "loading" );
        public static final String LOTS = RESOURCES.getLocalizedString( "lots" );
        public static final String MACRO = RESOURCES.getLocalizedString( "macro" );
        public static final String METAL = RESOURCES.getLocalizedString( "metal" );
        public static final String MICRO = RESOURCES.getLocalizedString( "micro" );
        public static final String NITRATE = RESOURCES.getLocalizedString( "nitrate" );
        public static final String NON_METAL = RESOURCES.getLocalizedString( "nonMetal" );
        public static final String NONE = RESOURCES.getLocalizedString( "none" );
        public static final String PATTERN__BEAKER_TICK_LABEL = RESOURCES.getLocalizedString( "pattern.beakerTickLabel" );
        public static final String PATTERN__LITERS_SOLUTION = RESOURCES.getLocalizedString( "pattern.litersSolution" );
        public static final String PATTERN__LITERS_WATER = RESOURCES.getLocalizedString( "pattern.litersWater" );
        public static final String PATTERN__MOLES_PER_LITER = RESOURCES.getLocalizedString( "pattern.molesPerLiter" );
        public static final String PATTERN__MOLES_PER_LITER_MULTILINE = RESOURCES.getLocalizedString( "pattern.molesPerLiterMultiline" );
        public static final String PERIODIC_TABLE = RESOURCES.getLocalizedString( "periodicTable" );
        public static final String REMOVE_SALT = RESOURCES.getLocalizedString( "removeSalt" );
        public static final String REMOVE_SOLUTE = RESOURCES.getLocalizedString( "removeSolute" );
        public static final String REMOVE_SOLUTES = RESOURCES.getLocalizedString( "removeSolutes" );
        public static final String REMOVE_SUGAR = RESOURCES.getLocalizedString( "removeSugar" );
        public static final String SALT = RESOURCES.getLocalizedString( "salt" );
        public static final String SHORT_CIRCUIT = RESOURCES.getLocalizedString( "shortCircuit" );
        public static final String SHOW = RESOURCES.getLocalizedString( "show" );
        public static final String SHOW_VALUES = RESOURCES.getLocalizedString( "showValues" );
        public static final String SODIUM = RESOURCES.getLocalizedString( "sodium" );
        public static final String SODIUM_CHLORIDE_NA_CL = RESOURCES.getLocalizedString( "sodiumChlorideNaCl" );
        public static final String SODIUM_CHLORIDE_NEW_LINE = RESOURCES.getLocalizedString( "sodiumChlorideNewLine" );
        public static final String SODIUM_NITRATE_NA_NO_3 = RESOURCES.getLocalizedString( "sodiumNitrateNaNO3" );
        public static final String SODIUM_NITRATE_NEW_LINE = RESOURCES.getLocalizedString( "sodiumNitrateNewLine" );
        public static final String SOLUTE = RESOURCES.getLocalizedString( "solute" );
        public static final String SPACE_FILL = RESOURCES.getLocalizedString( "spaceFill" );
        public static final String SUCROSE = RESOURCES.getLocalizedString( "sucrose" );
        public static final String SUCROSE_C_12_H_22_O_11 = RESOURCES.getLocalizedString( "sucroseC12H22O11" );
        public static final String SUGAR = RESOURCES.getLocalizedString( "sugar" );
        public static final String SUGAR_HIGHLIGHT = RESOURCES.getLocalizedString( "sugarHighlight" );
        public static final String SUGAR_IN_3_D = RESOURCES.getLocalizedString( "sugarIn3D" );
        public static final String WATER = RESOURCES.getLocalizedString( "water" );
        public static final String WATER_PARTIAL_CHARGES = RESOURCES.getLocalizedString( "waterPartialCharges" );
    }

    //Images
    public static class Images {
        public static final BufferedImage SALT_EMPTY = RESOURCES.getImage( "salt_empty.png" );
        public static final BufferedImage SALT_FULL = RESOURCES.getImage( "salt_full.png" );
        public static final BufferedImage SALT_MICRO = RESOURCES.getImage( "salt_micro.png" );
        public static final BufferedImage SUGAR_CLOSED = RESOURCES.getImage( "sugar_closed.png" );
        public static final BufferedImage SUGAR_EMPTY_CLOSED = RESOURCES.getImage( "sugar_empty_closed.png" );
        public static final BufferedImage SUGAR_EMPTY_OPEN = RESOURCES.getImage( "sugar_empty_open.png" );
        public static final BufferedImage SUGAR_MICRO_CLOSED = RESOURCES.getImage( "sugar_micro_closed.png" );
        public static final BufferedImage SUGAR_MICRO_OPEN = RESOURCES.getImage( "sugar_micro_open.png" );
        public static final BufferedImage SUGAR_OPEN = RESOURCES.getImage( "sugar_open.png" );
    }
}