//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_fa.properties
define( {
            "Games.label.level": "سطح : {0}",
            "Common.updates.errorMessage": "یک خطا در هنگام بروز رسانی رخ داد.<br>لطفا بعدا امتحان کنید یا به اینجا سر بزنید {0}.",
            "XMLPersistenceManager.save.error.encode": "<html>خطا در به رمز در آوردن فایل:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>خطا در رمز گشایی فایل:<br>{0}</html>",
            "Common.softwareAgreement.decline": "خروج",
            "Common.statistics.host_os_name": "نام سیستم عامل",
            "Common.statistics.user_total_sessions": "مجموع دفعاتی که شبیه سازی اجرا شده است",
            "FileChooser.openDialogTitleText": "باز کردن",
            "FileChooser.lookInLabelText": "در مکان:",
            "Common.choice.cancel": "انصراف",
            "Common.updates.seePreferences": "رفتن به سند->تنظیمات برای تغییر تنظیمات",
            "Common.About.CreditsDialog.software-development": "توسعه نرم افزار",
            "Common.About.JavaVersion": "نسخه جاوا",
            "ColorChooser.resetText": "بازنشانی",
            "wavelength.ir": "ایران",
            "Common.About.CreditsDialog.design-team": "تیم طراحی",
            "Common.statistics.sim_total_sessions": "مجموع دفعاتی که این شبیه سازی اجرا شده است",
            "Games.title.gameSettings": " تنظيمات بازی",
            "XMLPersistenceManager.save.title": "ذحیره پیکربندی",
            "XMLPersistenceManager.load.error.contents": "فایل خراب شده است یا با این شبیه ساز ایجاد نشده است",
            "Common.statistics.details.title": "اطلاعات",
            "Common.statistics.sim_dev_version": "نسخه شبیه ساز(توسعه)",
            "FileChooser.saveInLabelText": "ذخیره در:",
            "Common.statistics.sim_name": "نام شبیه سازی",
            "Save.confirm.message": "<html>نام سندی که انتخاب کرده اید قبلا وجود دارد.<br>آیا تمایل دارید که فایل کنونی جایگزین شود؟</html>",
            "Games.label.score": " حساب : {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "تیم توسعه پی اچ ای تی",
            "Games.button.start": "شروع كردن",
            "Common.statistics.sim_deployment": "نوع توسعه",
            "Games.radioButton.on": "روشن",
            "FileChooser.acceptAllFileFilterText": "همه سندها",
            "Common.ModelSlider.Minimum": "حداقل",
            "Common.FileMenu.Preferences": "تنظیمات",
            "Common.updates.downloadingSimJar": "دریافت فایل جاوا شبیه سازی",
            "Games.radioButton.off": "خاموش ",
            "ColorChooser.swatchesRecentText": "اخیر:",
            "Common.updates.updateAvailable": "بروز رسانی های در دسترس",
            "Common.statistics.host_locale_language": "زبان میزبان",
            "Common.clear": "پاک کردن",
            "Games.title.gameOver": "بازى دوباره",
            "FileChooser.filesOfTypeLabelText": "نوع فایل:",
            "Common.ErrorDialog.detailsTitle": "جزییات خظا",
            "Common.ClockControlPanel.Step": "مرحله",
            "Common.statistics.sim_revision": "نسخه شبیه سازی",
            "Common.choice.yes": "بله",
            "Common.FileMenu.Title": "سند",
            "Common.statistics.sim_dev": "آیا این یک نسخه در دست توسعه است؟",
            "Common.updates.installer.message": "<html>نسخه برنامه شما برای این تاریخ است {0}.<br>نسخه  جدید با این تاریخ در دسترس است {1}.<br><br>آیا تمایل به دریافت آخرین نسخه برنامه را دارید؟</html>",
            "Common.updates.updateNow": "بروز رسانی!",
            "Common.About.CreditsDialog.Title": "سازندگان",
            "Common.updates.error.internetConnection": "<html>ناتوان در اتصال به {0},<br>لطفا اتصال اینترنت خود را بررسی کنیدn.</html>",
            "Common.time.fast": "سریع",
            "XMLPersistenceManager.load.error.message": "<html>خطا در خواندن فایل<br>{0}</html>",
            "Common.ModelSlider.Maximum": "حداکثر",
            "Common.ClockControlPanel.Restart": "شروع دوباره",
            "Common.updates.installer.yes": "بله!",
            "Common.phetInstaller": "نصاب آفلاین وب سایت پی اچ ای تی",
            "Common.HelpMenu.About": "درباره...",
            "Common.ModelSlider.OutOfRange": "مقدار خارج از محدوده",
            "ColorChooser.previewText": "پیش نمایش",
            "Common.BasicPhetPanel.Title": "برگشت",
            "Common.HelpPanel.HideHelp": "مخفی کردن راهنما",
            "Common.statistics.host_os_arch": "نوع پردازش",
            "Common.preferences.title": "تنظیمات",
            "Games.button.newGame": "بازی جدید",
            "Common.ModelSlider.YouEntered": "شما وارد کردید",
            "Games.label.newBest": "بهترين تازه به دست آمده",
            "Common.About.BuildDate": "تاریخ ساخت:",
            "Games.label.best": "بهترين : {0}",
            "Common.statistics.sim_project": "نام پروژه",
            "Common.title.error": "خطا",
            "Common.FileMenu.Exit": "خروج",
            "Common.updates.askMeLater": "بعدا بپرس",
            "chart-time-control.go": "برو!",
            "Common.confirm.clear.graphs": "آیا قصد دارید نمودار را پاک کنید؟",
            "Common.updates.progressDialogMessage": "بروزرسانی نسخه \"{0}\" به نسخه {1}",
            "Common.updates.installer.more": "اطلاعات بیشتر...",
            "XMLPersistenceManager.title.error": "خطا",
            "ControlPanel.button.resetAll": "بازنشانی همه",
            "Common.About.AgreementButton": "جواز استفاده...",
            "Common.ErrorDialog.detailsButton": "چزییات",
            "Common.updates.errorMissingJar": "<html>ناتوان در اعمال بروز رسانی.<br>فایل مقابل پیدا نشد: {0}.<br>Pلطفا با مدیر سیستم تماس بگیرید.<br></html>",
            "Common.preferences.privacy": "حریم شخصی",
            "Common.HelpMenu.AboutTitle": "درباره",
            "ColorChooser.rgbRedText": "قرمز",
            "Common.statistics.sim_locale_country": "کشور",
            "ColorChooser.rgbGreenText": "سبز",
            "Games.format.time.best": "{0} ({1})",
            "Common.HelpPanel.ShowHelp": "راهنما!",
            "Common.statistics.sim_distribution_tag": "نسخه شبیه ساز(نهایی)",
            "Common.statistics.description": "پی اچ ای تی به صورت رایگان به شما هدیه می شود<br>ما کسب می کنیم  از  <br>استفاده کننده <a href=\"{0}\">اطلاعاتی</a> برای کسب جزییاتی<br>که کمک می کند به مابرای استفاده شبیه ساز ها<br>و بهبود خدماتی که کاربران نیاز دارند",
            "Common.softwareAgreement.message": "در تمام شبیه سازی ها حداقل اطلاعات کسب <br>of مراجعه کننده <a href=\"{0}\">دریافت می شود</a> هر زمان که شبیه سازی آغاز می شود<br>(مثلا نسخه شبیه سازیو سیستم عامل).<br>شما می توانید ارسال این اطلاعات را غیر فعال کنید<br>در منوی سند->بخش تنظیمات.<br><br>با کلیک بر روی قبول و ادامه شما قبول می کنید<br>جواز استفاده از نرم افزار را, که شامل قوانین حریم خصوصی نیز می شود,<br>fبرای هر شبیه سازی که اجرا می کنید<br>(برای اطلاعات بیشتر کلیک کنید روی  <a href=\"{1}\">اینجا</a>).",
            "Common.choice.ok": "تایید",
            "Common.About.Version": "نسخه:",
            "Common.ErrorDialog.contactPhet": "اگر این مشکل دوباره رخ داد اطلاعات زیر را به ارسال کنید به {0}",
            "Common.About.CreditsDialog.lead-design": "رهبر تیم طراحی",
            "Common.updates.errorWritePermissions": "<html>ناتوان در اعمال بروز رسانی.<br>شما اجازه دسترسی به این فایل را ندارید {0}.<br>لطفا برای راهنمایی با مدیر سیستم تماس بگیرید.<br></html>",
            "Common.choice.no": "نه",
            "Common.About.WebLink": "بازدید از سایت phet",
            "Common.About.OSVersion": "نسخه سیستم عامل",
            "Common.updates.versionComparison": "<html>نسخه جاری شما \"{0}\" هست {1}.<br>نسخه جدید ({2}) در دسترس است.</html>",
            "Common.statistics.sim_locale_language": "زبان",
            "Common.statistics.message_version": "نسخه پیغام",
            "Common.ModelSlider.Description": "مقدار نا معتبر",
            "Common.updates.installer.moreMessage": "<html>نسخه آفلاین وب سایت پی اچ ای تی را به روز نگه دارید<br>مطمئن شوید که از آخرین نسخه پی اچ ای تی استفاده می کنید<br>و تمام امکانات در دسترس شماست<br><br>اگر شما آخرین نسخه را اتنخاب کنید یک مرورگر باز خواهد شد<br>که شما را به سایت هدایت خواهد کرد،جایی که می توانید آخرین نسخه <br>نرم افزار را دریافت کنید.</html>",
            "ControlPanel.message.confirmResetAll": "بازنشانی همه تنظیمات؟",
            "Common.HelpMenu.Help": "راهنما",
            "Common.updates.errorNotAJar": "{0} یک فایل جاوا نیست.",
            "Games.label.levelControl": "سطح :",
            "Common.updates.automaticallyCheck": "برای بروز رسانی خودکار بررسی کن",
            "Common.sim.speed": "...سرعت...",
            "Common.updates.checkForSimUpdate": "بررسی برای بروز رسانی شبیه سازی",
            "XMLPersistenceManager.save.confirm.message": "<html>نام سندی که انتخاب کرده اید قبلا وجود دارد.<br>آیا تمایل دارید که فایل کنونی جایگزین شود؟</html>",
            "FileChooser.newFolderErrorText": "خطا در ایجاد پوشه",
            "Common.updates.skipThisUpdate": "رد کردن این نسخه",
            "Common.About.CreditsButton": "سازندگان...",
            "FileChooser.saveDialogTitleText": "ذخیره",
            "XMLPersistenceManager.load.title": "بارگزاری پیکربندی",
            "Common.updates.checkForInstallerUpdate": "بررسی برای بروز رسانی نصاب آفلاین وب سایت پی اچ ای تی",
            "timeseries.control.panel.playback": "بازنمایش",
            "Common.updates.progressDialogTitle": "بروز رسانی",
            "Common.HelpMenu.Title": "راهنما",
            "FileChooser.fileNameLabelText": "نام فایل:",
            "Common.softwareAgreement.title": "شرایط استفاده",
            "Common.About.CreditsDialog.interviews": "مذاکره",
            "Common.About.Distribution": "نسخه",
            "XMLPersistenceManager.save.error.message": "<html>خطا در نوشتن درفایل:<br>{0}</html>",
            "Games.label.time": "زمان: {0}",
            "FileChooser.openButtonText": "باز کردن",
            "Common.statistics.details.description": "<html>هر بار که شبیه سازی شروع می شود ازاطلاعات زیر برای پی اچ ای تی ارسال می گردد.</html>",
            "ColorChooser.sampleText": "متن نمونه متن نمونه",
            "Common.statistics.host_os_version": "نسخه سیستم عامل",
            "Common.title.confirm": "اعمال",
            "Games.label.score.max": "حساب : {0} out of {1}",
            "Common.BasicPhetPanel.LogoToolTip": "غیر فعال کردن تمام فریم",
            "Common.statistics.host_java_timezone": "منطقه زمانی",
            "Common.time.slow": "آهسته",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.softwareAgreement.accept": "قبول و ادامه",
            "Common.ClockControlPanel.Rewind": "حرکت از نو",
            "Common.updates.updateToDate": "بروز",
            "Common.ClockControlPanel.Pause": "مکث",
            "PhetApplication.StartupDialog.message": "\"{0}\"آغاز شد",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "جواز استفاده از نرم افزار",
            "Common.preferences.updates": "بروزرسانی",
            "Games.label.score.max.perfect": "حساب : {0} out of {1}",
            "Common.statistics.enabled": "اجازه می دهید اطلاعات برای پی اچ ای تی ارسال شود",
            "Common.StopwatchPanel.stop": "توقف",
            "Common.statistics.host_locale_country": "کشور میزبان",
            "Common.StopwatchPanel.reset": "بازنشانی",
            "Games.message.confirmNewGame": "شما این بازی را تمام نکرده اید! .<br>شما مطمئنید که<html> میخواهید بازی جدید را شروع کنید؟</html>",
            "Common.updates.tryIt": "آخرین نسخه را قبل از بروز رسانی ببینید",
            "ColorChooser.rgbBlueText": "آبی",
            "Common.choice.close": "بستن",
            "Common.ClockControlPanel.Play": "اجرا",
            "FileChooser.saveButtonText": "ذخیره",
            "Common.statistics.sim_type": "نوع شبیه سازی",
            "Common.rewind": "حرکت از نو",
            "Common.updates.youHaveCurrent": "شما نسخه جاری  ({0}) از {1} در دسترس دارید.",
            "Common.StopwatchPanel.start": "شروع",
            "Common.statistics.sim_sessions_since": "تعداد دفعاتی که این شبیه سازی تا آخرین اتصال اجرا شده است",
            "charts.show-graphs": "نمایش نمودار:",
            "Common.statistics.message_type": "نوع پیغام"
        } );