//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_es.properties
define( {
            "Games.label.level": "Nivel: {0}",
            "Common.updates.errorMessage": "Se encontró un error al tratar de actualizar <br> Por favor inténtelo de nuevo, o visite {0}.",
            "XMLPersistenceManager.save.error.encode": "<html>Error al codificar el archivo:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Error al descifrar el archivo:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "f",
            "Common.softwareAgreement.decline": "Salir",
            "Common.statistics.host_os_name": "Nombre del systema operativo",
            "Common.statistics.user_total_sessions": "Número total de veces que se han ejecutado todas las simulaciónes",
            "Common.statistics.host_java_version_major": "Versión de Java (mayor)",
            "FileChooser.openDialogTitleText": "Abrir",
            "Common.statistics.host_java_version_maintenance": "Versión de Java (mantenimiento)",
            "FileChooser.lookInLabelText": "Buque en:",
            "Common.choice.cancel": "Cancelar",
            "Common.updates.seePreferences": "Vaya al Archivo -> Preferencias para cambiar sus preferencias.",
            "Common.About.CreditsDialog.software-development": "Desarrollo de software",
            "Common.About.JavaVersion": "Versión de Java:",
            "ColorChooser.resetText": "Riniciar",
            "wavelength.ir": "IR",
            "Common.About.CreditsDialog.design-team": "Equipo de diseño",
            "Common.statistics.sim_total_sessions": "Número total de veces que esta simulación ha sido ejecutada",
            "Games.title.gameSettings": "Condiciones de Juego",
            "Common.FileMenu.PreferencesMnemonic": "p",
            "wavelength.uv": "UV",
            "XMLPersistenceManager.save.title": "Guarde configuración",
            "XMLPersistenceManager.load.error.contents": "El archivo es corrupto o no fue creado por esta simulación.",
            "Common.statistics.details.title": "Información",
            "Common.statistics.sim_dev_version": "Versión de simulación (desarollo)",
            "FileChooser.saveInLabelText": "Guardar en:",
            "Common.statistics.sim_name": "Nombre de simulación",
            "Save.confirm.message": "<html>El archivo seleccionado ya existe.<br>¿Desea reemplazarlo por el archivo que está grabando?</html>",
            "Games.label.score": "Puntaje: {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "Equipo de desarrollo de PhET",
            "Games.button.start": "¡Comenzar!",
            "Common.statistics.sim_deployment": "Typo de despliegue",
            "Common.FileMenu.Save": "Guardar configuración...",
            "ColorChooser.hsbSaturationText": "S",
            "Games.radioButton.on": "encender",
            "FileChooser.acceptAllFileFilterText": "Todo los archivos (*.*)",
            "ColorChooser.hsbNameText": "HSB",
            "Common.ModelSlider.Minimum": "Mínimo",
            "Common.FileMenu.Load": "Cargar configuración...",
            "Common.FileMenu.Preferences": "Preferencias...",
            "Common.updates.downloadingSimJar": "Descargando simulación del archivo JAR...",
            "Games.radioButton.off": "apagar",
            "ColorChooser.swatchesRecentText": "Reciente:",
            "Common.updates.updateAvailable": "Actualización disponible",
            "Common.statistics.host_locale_language": "Lengua anfitriona",
            "Common.clear": "Borrar",
            "Games.title.gameOver": "Juego terminado",
            "FileChooser.filesOfTypeLabelText": "Archivos del tipo:",
            "Common.ErrorDialog.detailsTitle": "Detalles de error",
            "Common.HelpMenu.MegaHelp": "Ayuda Mega...",
            "Common.ClockControlPanel.Step": "Paso",
            "Common.statistics.sim_revision": "Versión de simulación (revisión)",
            "Common.choice.yes": "Sí",
            "Common.FileMenu.Title": "Archivo",
            "Common.statistics.sim_dev": "¿Es esta una versión de desarollo?",
            "Common.updates.installer.message": "<html>La instalación de la pagina web de PhET offline tiene la fecha {0}. <br> Una versión nueva está disponible, con fecha de {1}. ¿Le gustaria obtener el ultimo instalador de la pagina web de PhET offline? </html>",
            "Common.updates.updateNow": "Actualice ahora",
            "Common.record": "GRAB",
            "Common.About.CreditsDialog.Title": "Créditos",
            "Common.time.fast": "rápido",
            "Common.OptionsMenu": "Opciones",
            "XMLPersistenceManager.load.error.message": "<html>Error de lectura del archivo:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Máximo",
            "Common.ClockControlPanel.Restart": "Reiniciar",
            "Common.statistics.sim_version_timestamp": "Versión de simulación (sello de tiempo)",
            "Common.updates.installer.yes": "¡Sí!",
            "Common.phetInstaller": "instalador de la pagina de PhET Offline",
            "Common.HelpMenu.About": "Acerca de...",
            "Common.ModelSlider.OutOfRange": "Valor fuera de rango",
            "ColorChooser.previewText": "Vista previa",
            "Common.BasicPhetPanel.Title": "Volver",
            "Common.HelpPanel.HideHelp": "Ocultar ayuda",
            "Common.statistics.host_os_arch": "Typo de procesador",
            "Common.preferences.title": "Preferencias",
            "Games.button.newGame": "Juego Nuevo",
            "ColorChooser.hsbRedText": "R",
            "ColorChooser.hsbBlueText": "A",
            "Common.ModelSlider.YouEntered": "Has introducido",
            "Games.label.newBest": "!Nuevo MEJOR!",
            "Common.About.BuildDate": "Fecha de constucción",
            "Common.FileMenu.ExitMnemonic": "x",
            "Games.label.best": "Mejor: {0}",
            "Common.statistics.sim_project": "Nombre del proyecto",
            "Common.updates.downloadingBootstrap": "Descargando actualizador...",
            "Common.title.error": "Error",
            "Common.FileMenu.Exit": "Salir",
            "Common.statistics.sim_major_version": "Versión de simulación (mayor)",
            "Common.updates.askMeLater": "Pregúnteme después",
            "chart-time-control.go": "¡Vaya!",
            "Common.HelpMenu.HelpMnemonic": "h",
            "Common.confirm.clear.graphs": "¿Está seguro de querer borrar los gráficos?",
            "ColorChooser.swatchesNameText": "Swatches",
            "Common.updates.progressDialogMessage": "Actualizando \"{0}\" a versión {1}",
            "Common.updates.installer.more": "Más información...",
            "XMLPersistenceManager.title.error": "Error",
            "ColorChooser.hsbHueText": "H",
            "ControlPanel.button.resetAll": "Reiniciar todo",
            "Common.About.AgreementButton": "Acuerdo de utilización de software",
            "Common.FileMenu.Load.mnemonic": "C",
            "Common.ErrorDialog.detailsButton": "Detalles...",
            "Common.updates.errorMissingJar": "<html>Esta actualización no puede realizarse.<br> No se podia situar el archivo JAR: {0} <br> Por favor contacte al administrador de systema para ayuda.<br></html>",
            "Common.preferences.privacy": "Privacidad",
            "Common.HelpMenu.AboutTitle": "Acerca de",
            "ColorChooser.rgbRedText": "R",
            "Common.statistics.sim_locale_country": "País",
            "ColorChooser.hsbGreenText": "V",
            "ColorChooser.rgbGreenText": "Verde",
            "Games.format.time.best": "{0} ({1})",
            "Common.HelpPanel.ShowHelp": "¡Ayuda!",
            "Common.statistics.sim_distribution_tag": "Versión de simulación (distribución)",
            "Common.statistics.description": "<html>PhET se distribuye gratuitamente gracias a ayudas <br>que requieren que recogamos una quantidad minima<br>de <a href=\"{0}\">información</a> anónima para permitir documentar el<br>uso de las simulaciónes de PhET y para servier<br>mejor las necesidades de nuestros usuarios.</html>",
            "Common.softwareAgreement.message": "<html>En todas las simulaciónes de PhET, recogemos una cantidad minima<br>de <a href=\"{0}\">información</a> anónima caundo la simulación comienza<br>(por ejemplo, versión de simulación y systema operativo).<br>Usted puede invalidar el envio de esta información<br>en qualquier momento a través del archivo Menu de Preferencias. <br><br>Al pinchar \"Acceptar y continuar\" usted accepta las normas<br>de licencia y privacidad de PhET.  (Para más detalles, pinche <a href=\"{1}\">aquí</a>).</html>",
            "Common.choice.ok": "OK",
            "Common.About.Version": "Versión:",
            "Common.ErrorDialog.contactPhet": "Si este problema persiste, envie los detalles abajo a {0}",
            "Common.OptionsMenu.mnemonic": "O",
            "Common.About.CreditsDialog.lead-design": "Jefe de diseño",
            "Common.statistics.user_preference_file_creation_time": "Tiempo de creación del archivo de preferencias",
            "Common.HelpMenu.AboutMnemonic": "a",
            "Common.updates.errorWritePermissions": "<html>Esta actualización no puede realizarse.<br>  Usted no tiene permiso para escribir a {0}. <br> Por favor contacte al administrador de systema para ayuda.<br></html>",
            "ColorChooser.hsbBrightnessText": "L",
            "Common.choice.no": "No",
            "Common.About.WebLink": "Visite la Página de PhET",
            "Common.About.OSVersion": "Versión SO:",
            "Common.updates.versionComparison": "<html>Su versión actual de \"{0}\" es {1}. <br> Una versión nueva ({2}) está disponible.</html>",
            "Common.statistics.sim_locale_language": "Lengua",
            "Common.statistics.user_installation_timestamp": "Sello de tiempo de la instalción PhET",
            "Common.statistics.message_version": "Versión de mensaje",
            "Common.ModelSlider.Description": "valor ilegal.",
            "Common.updates.installer.moreMessage": "<html>Mantener la instalación de la pagina web de PhET offline al dia<br>asegura su acceso a las simulaciones más recientes y a<br> materials suplementarios.<br><br>Si usted elige obtener la versión más reciente,<br>un navegador de red se abrirá en la pagina web de PhET, donde puede descargar<br>el instalador de la pagina web de PhET offline.</html>",
            "Common.updates.errorNotAJar": "{0} no es un archivo JAR.",
            "ControlPanel.message.confirmResetAll": "¿Reiniciar todos los ajustes?",
            "Common.HelpMenu.Help": "Ayuda",
            "Games.label.levelControl": "Nivel:",
            "Common.updates.automaticallyCheck": "Buscar actualizaciónes automáticamente",
            "Common.sim.speed": "...velocidad sim...",
            "Common.updates.checkForSimUpdate": "Buscar actualización de simulación...",
            "XMLPersistenceManager.save.confirm.message": "<html>El archivo seleccionado ya existe.<br>¿Desea reemplazarlo por el archivo que está grabando?</html>",
            "FileChooser.newFolderErrorText": "Error al crear nueva carpeta",
            "Common.updates.skipThisUpdate": "Ignore esta versión",
            "Common.About.CreditsButton": "Créditos...",
            "Common.FileMenu.Save.mnemonic": "G",
            "FileChooser.saveDialogTitleText": "Guardar",
            "XMLPersistenceManager.load.title": "Cargar configuración",
            "Common.updates.checkForInstallerUpdate": "Buscar actualización de instalador de la pagina de PhET Offline",
            "timeseries.control.panel.playback": "Volver a ejecutar",
            "Common.updates.progressDialogTitle": "Actualizando",
            "Common.HelpMenu.Title": "Ayuda",
            "FileChooser.fileNameLabelText": "Nombre del archivo:",
            "ColorChooser.rgbNameText": "RVA",
            "Common.softwareAgreement.title": "Acuerdo del uso de software y privacidad",
            "Common.statistics.host_java_version_minor": "Versión de Java (menor)",
            "Common.HelpMenu.TitleMnemonic": "h",
            "Common.About.CreditsDialog.interviews": "Entrevistas",
            "Common.About.Distribution": "Distribución:",
            "Common.statistics.host_java_webstart_version": "Versión de Java Web Start",
            "XMLPersistenceManager.save.error.message": "<html>Error a escribir ell archivo:<br>{0}</html>",
            "Games.label.time": "Tiempo: {0}",
            "FileChooser.openButtonText": "Abrir",
            "Common.statistics.details.description": "<html>La información que mostrada abajo se enviará a PhET caundo la simulación comienze.</html>",
            "ColorChooser.sampleText": "Texto de exemplo",
            "Common.statistics.host_os_version": "Versión del systema operativo",
            "Common.title.confirm": "Confirmar",
            "Games.label.score.max": "Puntaje: {0} de {1}",
            "Common.BasicPhetPanel.LogoToolTip": "Inhabilitar marco completo",
            "Common.statistics.host_java_timezone": "Franja horaria",
            "Common.time.slow": "lento",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.ClockControlPanel.Rewind": "Robovinar",
            "Common.softwareAgreement.accept": "Acceptar y continuar",
            "Common.updates.updateToDate": "Actual",
            "XMLPersistenceManager.save.error.xmlencoder": "La codificación XML falló.",
            "Common.ClockControlPanel.Pause": "Pausa",
            "PhetApplication.StartupDialog.message": "\"{0}\" está comenzando",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Este programa usa el siguiente software de terceros",
            "XMLPersistenceManager.message.notAConfigFile": "Este archivo no contiene una configuración para esta simulación.",
            "Common.preferences.updates": "Actualizaciónes",
            "Games.label.score.max.perfect": "Puntaje: {0} de {1}(!PERFECTO!)",
            "Common.HelpMenu.MegaHelpMnemonic": "m",
            "Common.statistics.enabled": "Permitir el envio de información a PhET",
            "Common.StopwatchPanel.stop": "Parar",
            "Common.HelpPanel.MegaHelp": "Ayuda Mega...",
            "Common.statistics.host_locale_country": "País anfitrión",
            "Common.StopwatchPanel.reset": "Reiniciar",
            "Games.message.confirmNewGame": "<html>No ha terminado este juego.<br>¿Está seguro que quiere empezar uno nuevo?</html>",
            "Common.statistics.sim_minor_version": "Versión de simulación (menor)",
            "Common.updates.tryIt": "Preube la nueava versión antes de actualizar",
            "ColorChooser.rgbBlueText": "Azul",
            "Common.choice.close": "Cerrar",
            "Common.slow.motion": "Lento",
            "Common.ClockControlPanel.Play": "Ejecutar",
            "Common.About.OKButton": "OK",
            "Common.statistics.sim_type": "Typo de simulación",
            "FileChooser.saveButtonText": "Guardar",
            "Common.rewind": "Rebovinar",
            "Common.StopwatchPanel.start": "Comenzar",
            "Common.updates.youHaveCurrent": "Usted tiene la versión más actual ({0}) de {1}.",
            "Common.statistics.sim_sessions_since": "Número de veces que esta simulación ha sido ejecutada desde la ultima conexión a la red",
            "Common.statistics.host_java_vendor": "Vendedor de Java",
            "charts.show-graphs": "Mostrar gráficos:",
            "Common.About.LicenseDialog.Title": "Licencia",
            "Common.statistics.message_type": "Typo de mensaje"
        } );