// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.balanceandtorquestudy;

import java.awt.image.BufferedImage;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Resources (images and translated strings) for "BalanceAndTorque" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator
 */
public class BalanceAndTorqueStudyResources {
    public static final String PROJECT_NAME = "balance-and-torque-study";
    public static final PhetResources RESOURCES = new PhetResources( PROJECT_NAME );

    //Strings
    public static class Strings {
        public static final String ADD_SUPPORTS = RESOURCES.getLocalizedString( "addSupports" );
        public static final String BALANCE_LAB = RESOURCES.getLocalizedString( "balanceLab" );
        public static final String BALANCE_ME = RESOURCES.getLocalizedString( "balanceMe" );
        public static final String BRICKS = RESOURCES.getLocalizedString( "bricks" );
        public static final String CHECK_ANSWER = RESOURCES.getLocalizedString( "checkAnswer" );
        public static final String DISPLAY_CORRECT_ANSWER = RESOURCES.getLocalizedString( "displayCorrectAnswer" );
        public static final String FORCES_FROM_OBJECTS = RESOURCES.getLocalizedString( "forcesFromObjects" );
        public static final String GAME = RESOURCES.getLocalizedString( "game" );
        public static final String INTRO = RESOURCES.getLocalizedString( "intro" );
        public static final String KG = RESOURCES.getLocalizedString( "kg" );
        public static final String LEVEL = RESOURCES.getLocalizedString( "level" );
        public static final String MASS_EQUALS = RESOURCES.getLocalizedString( "massEquals" );
        public static final String MASS_LABEL_A = RESOURCES.getLocalizedString( "massLabelA" );
        public static final String MASS_LABEL_B = RESOURCES.getLocalizedString( "massLabelB" );
        public static final String MASS_LABEL_C = RESOURCES.getLocalizedString( "massLabelC" );
        public static final String MASS_LABEL_D = RESOURCES.getLocalizedString( "massLabelD" );
        public static final String MASS_LABEL_E = RESOURCES.getLocalizedString( "massLabelE" );
        public static final String MASS_LABEL_F = RESOURCES.getLocalizedString( "massLabelF" );
        public static final String MASS_LABEL_G = RESOURCES.getLocalizedString( "massLabelG" );
        public static final String MASS_LABEL_H = RESOURCES.getLocalizedString( "massLabelH" );
        public static final String MASS_LABELS = RESOURCES.getLocalizedString( "massLabels" );
        public static final String METERS = RESOURCES.getLocalizedString( "meters" );
        public static final String MYSTERY_OBJECTS = RESOURCES.getLocalizedString( "mysteryObjects" );
        public static final String NEXT = RESOURCES.getLocalizedString( "next" );
        public static final String PATTERN_0_VALUE_1_UNITS = RESOURCES.getLocalizedString( "pattern0Value1Units" );
        public static final String PEOPLE = RESOURCES.getLocalizedString( "people" );
        public static final String REMOVE_SUPPORTS = RESOURCES.getLocalizedString( "removeSupports" );
        public static final String RULERS = RESOURCES.getLocalizedString( "rulers" );
        public static final String SHOW = RESOURCES.getLocalizedString( "show" );
        public static final String SHOW_RULERS = RESOURCES.getLocalizedString( "showRulers" );
        public static final String TRY_AGAIN = RESOURCES.getLocalizedString( "tryAgain" );
        public static final String UNKNOWN_MASS_LABEL = RESOURCES.getLocalizedString( "unknownMassLabel" );
        public static final String WHAT_IS_THE_MASS = RESOURCES.getLocalizedString( "whatIsTheMass" );
        public static final String WHAT_WILL_HAPPEN = RESOURCES.getLocalizedString( "whatWillHappen" );
    }

    //Images
    public static class Images {
        public static final BufferedImage BARREL = RESOURCES.getImage( "barrel.png" );
        public static final BufferedImage BLUE_BUCKET = RESOURCES.getImage( "blue-bucket.png" );
        public static final BufferedImage BOY_SITTING = RESOURCES.getImage( "boy-sitting.png" );
        public static final BufferedImage BOY_STANDING = RESOURCES.getImage( "boy-standing.png" );
        public static final BufferedImage CINDER_BLOCK = RESOURCES.getImage( "cinder-block.png" );
        public static final BufferedImage FIRE_EXTINGUISHER = RESOURCES.getImage( "fire-extinguisher.png" );
        public static final BufferedImage FIRE_HYDRANT = RESOURCES.getImage( "fire-hydrant.png" );
        public static final BufferedImage FLOWER_POT = RESOURCES.getImage( "flower-pot.png" );
        public static final BufferedImage GIRL_SITTING = RESOURCES.getImage( "girl-sitting.png" );
        public static final BufferedImage GIRL_STANDING = RESOURCES.getImage( "girl-standing.png" );
        public static final BufferedImage MAN_SITTING = RESOURCES.getImage( "man-sitting.png" );
        public static final BufferedImage MAN_STANDING = RESOURCES.getImage( "man-standing.png" );
        public static final BufferedImage METAL_BUCKET = RESOURCES.getImage( "metal-bucket.png" );
        public static final BufferedImage MYSTERY_OBJECT_01 = RESOURCES.getImage( "mystery-object-01.png" );
        public static final BufferedImage MYSTERY_OBJECT_02 = RESOURCES.getImage( "mystery-object-02.png" );
        public static final BufferedImage MYSTERY_OBJECT_03 = RESOURCES.getImage( "mystery-object-03.png" );
        public static final BufferedImage MYSTERY_OBJECT_04 = RESOURCES.getImage( "mystery-object-04.png" );
        public static final BufferedImage MYSTERY_OBJECT_05 = RESOURCES.getImage( "mystery-object-05.png" );
        public static final BufferedImage MYSTERY_OBJECT_06 = RESOURCES.getImage( "mystery-object-06.png" );
        public static final BufferedImage MYSTERY_OBJECT_07 = RESOURCES.getImage( "mystery-object-07.png" );
        public static final BufferedImage MYSTERY_OBJECT_08 = RESOURCES.getImage( "mystery-object-08.png" );
        public static final BufferedImage OLD_TELEVISION = RESOURCES.getImage( "old-television.png" );
        public static final BufferedImage PLANK_BALANCED = RESOURCES.getImage( "plank-balanced.png" );
        public static final BufferedImage PLANK_TIPPED_LEFT = RESOURCES.getImage( "plank-tipped-left.png" );
        public static final BufferedImage PLANK_TIPPED_RIGHT = RESOURCES.getImage( "plank-tipped-right.png" );
        public static final BufferedImage POTTED_PLANT = RESOURCES.getImage( "potted-plant.png" );
        public static final BufferedImage ROCK_1 = RESOURCES.getImage( "rock_1.png" );
        public static final BufferedImage ROCK_4 = RESOURCES.getImage( "rock_4.png" );
        public static final BufferedImage ROCK_6 = RESOURCES.getImage( "rock_6.png" );
        public static final BufferedImage SODA_BOTTLE = RESOURCES.getImage( "soda-bottle.png" );
        public static final BufferedImage TINY_ROCK = RESOURCES.getImage( "tiny-rock.png" );
        public static final BufferedImage TIRE = RESOURCES.getImage( "tire.png" );
        public static final BufferedImage TRASH_CAN = RESOURCES.getImage( "trash-can.png" );
        public static final BufferedImage WOMAN_SITTING = RESOURCES.getImage( "woman-sitting.png" );
        public static final BufferedImage WOMAN_STANDING = RESOURCES.getImage( "woman-standing.png" );
        public static final BufferedImage YELLOW_BUCKET = RESOURCES.getImage( "yellow-bucket.png" );
    }
}