// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.platetectonics;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Resources (images and translated strings) for "PlateTectonics" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator
 */
public class PlateTectonicsResources {
    public static final String PROJECT_NAME = "plate-tectonics";
    public static final PhetResources RESOURCES = new PhetResources( PROJECT_NAME );

    //Strings
    public static class Strings {
        public static final String AUTOMATIC_MODE = RESOURCES.getLocalizedString( "automaticMode" );
        public static final String BOTH_VIEW = RESOURCES.getLocalizedString( "bothView" );
        public static final String COMPOSITION = RESOURCES.getLocalizedString( "composition" );
        public static final String CONTINENTAL_CRUST = RESOURCES.getLocalizedString( "continentalCrust" );
        public static final String COOL = RESOURCES.getLocalizedString( "cool" );
        public static final String CRUST = RESOURCES.getLocalizedString( "crust" );
        public static final String CRUST_TAB = RESOURCES.getLocalizedString( "crustTab" );
        public static final String DENSITY_VIEW = RESOURCES.getLocalizedString( "densityView" );
        public static final String INNER_CORE = RESOURCES.getLocalizedString( "innerCore" );
        public static final String LEGEND = RESOURCES.getLocalizedString( "legend" );
        public static final String LESS_DENSE = RESOURCES.getLocalizedString( "lessDense" );
        public static final String LOWER_MANTLE = RESOURCES.getLocalizedString( "lowerMantle" );
        public static final String MANTLE = RESOURCES.getLocalizedString( "mantle" );
        public static final String MANUAL_MODE = RESOURCES.getLocalizedString( "manualMode" );
        public static final String MILLION_YEARS = RESOURCES.getLocalizedString( "millionYears" );
        public static final String MORE_DENSE = RESOURCES.getLocalizedString( "moreDense" );
        public static final String MORE_IRON = RESOURCES.getLocalizedString( "moreIron" );
        public static final String MORE_SILICA = RESOURCES.getLocalizedString( "moreSilica" );
        public static final String MY_CRUST = RESOURCES.getLocalizedString( "myCrust" );
        public static final String OCEANIC_CRUST = RESOURCES.getLocalizedString( "oceanicCrust" );
        public static final String OLD_OCEANIC_CRUST = RESOURCES.getLocalizedString( "oldOceanicCrust" );
        public static final String OPTIONS = RESOURCES.getLocalizedString( "options" );
        public static final String OUTER_CORE = RESOURCES.getLocalizedString( "outerCore" );
        public static final String PLATE_MOTION_TAB = RESOURCES.getLocalizedString( "plateMotionTab" );
        public static final String RESET_ALL = RESOURCES.getLocalizedString( "resetAll" );
        public static final String REWIND = RESOURCES.getLocalizedString( "rewind" );
        public static final String RULER_UNITS = RESOURCES.getLocalizedString( "rulerUnits" );
        public static final String SENSOR_MULTIPLIER = RESOURCES.getLocalizedString( "sensorMultiplier" );
        public static final String SHOW_LABELS = RESOURCES.getLocalizedString( "showLabels" );
        public static final String SHOW_SEAWATER = RESOURCES.getLocalizedString( "showSeawater" );
        public static final String TEMPERATURE = RESOURCES.getLocalizedString( "temperature" );
        public static final String TEMPERATURE_VIEW = RESOURCES.getLocalizedString( "temperatureView" );
        public static final String THICK = RESOURCES.getLocalizedString( "thick" );
        public static final String THICKNESS = RESOURCES.getLocalizedString( "thickness" );
        public static final String THIN = RESOURCES.getLocalizedString( "thin" );
        public static final String TIME_FAST = RESOURCES.getLocalizedString( "timeFast" );
        public static final String TIME_SLOW = RESOURCES.getLocalizedString( "timeSlow" );
        public static final String TOOLBOX = RESOURCES.getLocalizedString( "toolbox" );
        public static final String WARM = RESOURCES.getLocalizedString( "warm" );
        public static final String YOUNG_OCEANIC_CRUST = RESOURCES.getLocalizedString( "youngOceanicCrust" );
        public static final String ZOOM = RESOURCES.getLocalizedString( "zoom" );
    }

    //Images
    public static class Images {

    }
}