//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_hr.properties
define( {
            "Common.updates.errorMessage": "Greška kod ažururanja.<br>Pokušajte kasnije ili posjetite {0}.",
            "XMLPersistenceManager.save.error.encode": "<html>Greška kod enkodiranja datoteke:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Greška kod dekodiranja datoteke:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "d",
            "Common.softwareAgreement.decline": "Izlaz",
            "Common.statistics.host_os_name": "OS",
            "Common.statistics.user_total_sessions": "Ukupan broj pokretanja svih simulacija",
            "Common.statistics.host_java_version_major": "Java inačica (major)",
            "FileChooser.openDialogTitleText": "Otvori",
            "Common.statistics.host_java_version_maintenance": "Java inačica (podrška)",
            "FileChooser.lookInLabelText": "Pogledaj u:",
            "Common.choice.cancel": "Odustani",
            "Common.updates.seePreferences": "Za promjenu trenutnih postavki odaberite <br>\n Datoteka -> Postavke ",
            "Common.About.CreditsDialog.software-development": "Razvoj",
            "Common.About.JavaVersion": "Java inačica:",
            "ColorChooser.resetText": "Ponovo",
            "wavelength.ir": "IC",
            "Common.About.CreditsDialog.design-team": "Dizajn",
            "Common.statistics.sim_total_sessions": "Ukupni broj pokretanja simulacije",
            "Common.FileMenu.PreferencesMnemonic": "s",
            "wavelength.uv": "UV",
            "XMLPersistenceManager.save.title": "Spremi postavke",
            "XMLPersistenceManager.load.error.contents": "Datoteka je oštećena ili nije prikladna za ovu simulaciju",
            "Common.statistics.details.title": "Info",
            "Common.statistics.sim_dev_version": "Inačica simulacije  (uređaj)",
            "FileChooser.saveInLabelText": "Spremi u:",
            "Common.statistics.sim_name": "Ime simulacije",
            "Save.confirm.message": "<html>Datoteka već postoji.<br>Želite li je zamijeniti datotekom koju spremate?</html>",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "PhET Razvojni Tim",
            "Common.statistics.sim_deployment": "Primjena",
            "Common.FileMenu.Save": "Spremi konfiguraciju...",
            "ColorChooser.hsbSaturationText": "S",
            "FileChooser.acceptAllFileFilterText": "Sve datoteke (*.*)",
            "ColorChooser.hsbNameText": "HSB",
            "Common.ModelSlider.Minimum": "Minimum",
            "Common.FileMenu.Load": "Učitaj konfiguraciju...",
            "Common.FileMenu.Preferences": "Postavke...",
            "Common.updates.downloadingSimJar": "Preuzimam JAR datoteku...",
            "ColorChooser.swatchesRecentText": "Nedavno:",
            "Common.updates.updateAvailable": "Moguća nadogradnja!",
            "Common.statistics.host_locale_language": "Jezik",
            "Common.clear": "Počisti",
            "FileChooser.filesOfTypeLabelText": "Vrsta datoteke:",
            "Common.ErrorDialog.detailsTitle": "Pojedinosti greške",
            "Common.HelpMenu.MegaHelp": "Upute...",
            "Common.ClockControlPanel.Step": "Postupno",
            "Common.statistics.sim_revision": "Inačica Simulacije (revizija)",
            "Common.choice.yes": "Da",
            "Common.FileMenu.Title": "Datoteka",
            "Common.statistics.sim_dev": "Radi li se o razvojnoj inačici?",
            "Common.updates.installer.message": "<html>Vaša PhET Instalacija je od  {0}.<br>Postoji novija verzija od {1}.<br>Želite li nadograditi vašu PhET Instalaciju?</html>",
            "Common.updates.updateNow": "Nadogradi!",
            "Common.record": "Snimi",
            "Common.About.CreditsDialog.Title": "Krediti",
            "Common.updates.error.internetConnection": "<html>Ne mogu se spojiti s {0},<br>provjerite povezanost s Internetom.</html>",
            "Common.time.fast": "brzo",
            "Common.OptionsMenu": "Postavke",
            "XMLPersistenceManager.load.error.message": "<html>Greška kod čitanja iz datoteke:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Maksimum",
            "Common.ClockControlPanel.Restart": "Ponovo",
            "Common.statistics.sim_version_timestamp": "Inačica Simulacije (od dana)",
            "Common.updates.installer.yes": "Da!",
            "Common.phetInstaller": "PhET instalacija",
            "Common.HelpMenu.About": "O programu...",
            "Common.ModelSlider.OutOfRange": "Vrijednost izvan dosega!",
            "ColorChooser.previewText": "Pregled",
            "Common.BasicPhetPanel.Title": "Povratak",
            "Common.HelpPanel.HideHelp": "Sakrij pomoć",
            "Common.statistics.host_os_arch": "Vrsta procesora",
            "Common.preferences.title": "Postavke",
            "ColorChooser.hsbRedText": "C",
            "ColorChooser.hsbBlueText": "P",
            "Common.ModelSlider.YouEntered": "Unijeli ste...",
            "Common.About.BuildDate": "Datum stvaranja:",
            "Common.FileMenu.ExitMnemonic": "z",
            "Common.statistics.sim_project": "Naziv projekta",
            "Common.updates.downloadingBootstrap": "Preuzimam ažuriranje...",
            "Common.title.error": "Greška",
            "Common.FileMenu.Exit": "Izlaz",
            "Common.statistics.sim_major_version": "Inačica simulacije (major)",
            "Common.updates.askMeLater": "Pitaj me kasnije",
            "chart-time-control.go": "Kreni!",
            "Common.HelpMenu.HelpMnemonic": "p",
            "Common.confirm.clear.graphs": "Sigurni ste da želite počistiti grafove?",
            "ColorChooser.swatchesNameText": "Opcije",
            "Common.updates.progressDialogMessage": "Nadograđujem \"{0}\" na inačicu {1}",
            "Common.updates.installer.more": "Više...",
            "XMLPersistenceManager.title.error": "Greška!",
            "ColorChooser.hsbHueText": "H",
            "ControlPanel.button.resetAll": "Na početak",
            "Common.About.AgreementButton": "Ugovor...",
            "Common.FileMenu.Load.mnemonic": "U",
            "Common.ErrorDialog.detailsButton": "Detalji...",
            "Common.updates.errorMissingJar": "<html>Ne mogu završiti ažuriranje.<br>JAR datoteka nije pronađena: {0}.<br>Za pomoć kontaktirajte administratora sustava.<br></html>",
            "Common.preferences.privacy": "Privatnost",
            "Common.HelpMenu.AboutTitle": "O Programu",
            "ColorChooser.rgbRedText": "Crveno",
            "Common.statistics.sim_locale_country": "Zemlja",
            "ColorChooser.hsbGreenText": "Z",
            "ColorChooser.rgbGreenText": "Zeleno",
            "Common.HelpPanel.ShowHelp": "Pomoć!",
            "Common.statistics.sim_distribution_tag": "Inačica simulacije  (distribucija)",
            "Common.statistics.description": "PhET je slobodan softver!<br>\nMinimalna količina  <a href=\"{0}\"> anonimnih informacija</a><br>\nkoju šaljete osigurava bolju podršku našem softveru!",
            "Common.softwareAgreement.message": "Svakim pokretanjem simulacije prikuplja se i šalje minimala<br>količina anonimnih <a href=\"{0}\">informacija</a> prema PhET-u.<br>\nNa primjer: inačica simulacije, verzija OS-a i sl.<br>\nSlanje ovih informacija možete onemogućiti preko izbornika<br>\nDatoteka->Postavke<br>\nOdabirom \"Suglasan! Nastavi!\",<br> prihvaćate  PhET uvjete korištenja softvera <br>uključujući naše uvjete o privatnosti!<br>(Za detelje pogledajte <a href=\"{1}\">ovdje</a>)",
            "Common.choice.ok": "U redu",
            "Common.About.Version": "Inačica:",
            "Common.ErrorDialog.contactPhet": "U slučaju ponavljanja problema pošaljite izvještaj na {0}",
            "Common.OptionsMenu.mnemonic": "P",
            "Common.About.CreditsDialog.lead-design": "Dizajn",
            "Common.statistics.user_preference_file_creation_time": "Vrijeme nastanka datoteke sa zapisom postavki",
            "Common.HelpMenu.AboutMnemonic": "o",
            "Common.updates.errorWritePermissions": "<html>Ova nadogradnja se ne može izvršiti.<br>Nemate dozvolu pisanja u {0}.<br>Za pomoć kontaktirajte  administratora sustava.<br></html>",
            "ColorChooser.hsbBrightnessText": "B",
            "Common.choice.no": "Ne",
            "Common.About.WebLink": "Posjetite WWW stranice PhET-a",
            "Common.About.OSVersion": "Operativni sustav:",
            "Common.updates.versionComparison": "<html>Imte verziju \"{0}\" od {1}.<br> Možete preuzeti noviju ({2}) inačicu.</html>",
            "Common.statistics.sim_locale_language": "Jezik",
            "Common.statistics.user_installation_timestamp": "PhET instalacija (od dana)",
            "Common.statistics.message_version": "Inačica poruke",
            "Common.ModelSlider.Description": "Vrijednost nije dozvoljena!",
            "Common.updates.installer.moreMessage": "<html>Održavaj svoju PhET lokalnu instalaciju ažuriranom<br>i tako osiguraj najnovije PhET simulacije na svom računalu!</html>",
            "ControlPanel.message.confirmResetAll": "Poništi sve postavke?",
            "Common.HelpMenu.Help": "Pomoć",
            "Common.updates.errorNotAJar": "{0} nije JAR datoteka.",
            "Common.updates.automaticallyCheck": "Automatski provjeri ažuriranja",
            "Common.sim.speed": "...brzina simulacije...",
            "Common.updates.checkForSimUpdate": "Provjeri ažuriranja za simulaciju...",
            "XMLPersistenceManager.save.confirm.message": "<html>Datoteka već postoji.<br>Želite li je zamijeniti datotekom koju spremate?</html>",
            "FileChooser.newFolderErrorText": "Ne mogu napraviti novu mapu",
            "Common.updates.skipThisUpdate": "Preskoči ovu verziju",
            "Common.About.CreditsButton": "Krediti...",
            "Common.FileMenu.Save.mnemonic": "S",
            "FileChooser.saveDialogTitleText": "Spremi",
            "XMLPersistenceManager.load.title": "Učitaj konfiguraciju",
            "Common.updates.checkForInstallerUpdate": "Provjeri ažuriranja PhET softvera...",
            "timeseries.control.panel.playback": "Pokreni snimku",
            "Common.updates.progressDialogTitle": "Nadograđujem",
            "Common.HelpMenu.Title": "Pomoć",
            "FileChooser.fileNameLabelText": "Ime datoteke:",
            "ColorChooser.rgbNameText": "RGB",
            "Common.softwareAgreement.title": "Uvjeti korištenja",
            "Common.statistics.host_java_version_minor": "Java inačica (minor)",
            "Common.HelpMenu.TitleMnemonic": "p",
            "Common.About.CreditsDialog.interviews": "Materijali",
            "Common.About.Distribution": "Distribucija:",
            "Common.statistics.host_java_webstart_version": "Java Web Start inačica",
            "XMLPersistenceManager.save.error.message": "<html>Greška kod pisanja u datoteku:<br>{0}</html>",
            "FileChooser.openButtonText": "Otvori",
            "ColorChooser.sampleText": "Primjer obojanog teksta",
            "Common.statistics.details.description": "<html>Sljedeće informacije bit će poslane svaki put kad pokrenete simulaciju:</html>",
            "Common.statistics.host_os_version": "OS inačica",
            "Common.title.confirm": "Potvrdi",
            "Common.BasicPhetPanel.LogoToolTip": "Onemogući puni okvir",
            "Common.statistics.host_java_timezone": "Vremenska Zona",
            "Common.time.slow": "sporo",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.ClockControlPanel.Rewind": "Premotaj",
            "Common.softwareAgreement.accept": "Prihvaćam i želim nastaviti!",
            "Common.updates.updateToDate": "Nema mogućnosti nadogradnje!",
            "Common.ClockControlPanel.Pause": "Zaustavi",
            "PhetApplication.StartupDialog.message": "\"{0}\" se pokreće ...",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Ovaj program koristi i softver drugih\nrazvojnih timova",
            "XMLPersistenceManager.message.notAConfigFile": "Ova datoteka ne sadrži konfiguraciju za ovu simulaciju.",
            "Common.preferences.updates": "Nadogradnja",
            "Common.HelpMenu.MegaHelpMnemonic": "u",
            "Common.statistics.enabled": "Dopusti slanje informacija!",
            "Common.StopwatchPanel.stop": "Zaustavi",
            "Common.HelpPanel.MegaHelp": "Upute...",
            "Common.statistics.host_locale_country": "Zemlja",
            "Common.StopwatchPanel.reset": "Ponovo",
            "Common.playback": "Ponovi",
            "Common.statistics.sim_minor_version": "Inačica simulacije (minor)",
            "Common.updates.tryIt": "Pokušaj s novijom inačicom prije ažuriranja.",
            "ColorChooser.rgbBlueText": "Plavo",
            "Common.choice.close": "Zatvori",
            "Common.ClockControlPanel.Play": "Pokreni",
            "Common.statistics.sim_type": "Vrsta simulacije",
            "FileChooser.saveButtonText": "Spremi",
            "Common.rewind": "Premotaj",
            "Common.StopwatchPanel.start": "Pokreni",
            "Common.updates.youHaveCurrent": "Imate najnoviju verziju ({0}) od {1}.",
            "Common.statistics.sim_sessions_since": "Broj pokretanja simulacije od posljednjeg spajanja s Internetom",
            "Common.statistics.host_java_vendor": "Pakiranje Jave",
            "charts.show-graphs": "Pokaži grafove:",
            "Common.statistics.message_type": "Vrsta poruka"
        } );