// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.energyformsandchanges;

import java.awt.image.BufferedImage;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Resources (images and translated strings) for "EnergyFormsAndChanges" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator
 */
public class EnergyFormsAndChangesResources {
    public static final String PROJECT_NAME = "energy-forms-and-changes";
    public static final PhetResources RESOURCES = new PhetResources( PROJECT_NAME );

    //Strings
    public static class Strings {
        public static final String ENERGY_STORIES = RESOURCES.getLocalizedString( "energyStories" );
        public static final String ENERGY_SYSTEMS = RESOURCES.getLocalizedString( "energySystems" );
        public static final String INTRO = RESOURCES.getLocalizedString( "intro" );
    }

    //Images
    public static class Images {
        public static final BufferedImage BRICK_TEXTURE_FRONT = RESOURCES.getImage( "brick_texture_front.png" );
        public static final BufferedImage BRICK_TEXTURE_RIGHT = RESOURCES.getImage( "brick_texture_right.png" );
        public static final BufferedImage BRICK_TEXTURE_TOP = RESOURCES.getImage( "brick_texture_top.png" );
        public static final BufferedImage CLOUD_1 = RESOURCES.getImage( "cloud_1.png" );
        public static final BufferedImage CONNECTOR = RESOURCES.getImage( "connector.png" );
        public static final BufferedImage ELEMENT_BASE = RESOURCES.getImage( "element_base.png" );
        public static final BufferedImage ENERGY_CHUNKS_WHITE_SEMIBOLD = RESOURCES.getImage( "energy-chunks-white-semibold.png" );
        public static final BufferedImage ENERGY_CHUNKS_WHITE = RESOURCES.getImage( "energy-chunks-white.png" );
        public static final BufferedImage E_ELECTRIC_OUTLINE = RESOURCES.getImage( "E_electric_outline.png" );
        public static final BufferedImage E_ELECTRIC_OUTLINE_BLACK = RESOURCES.getImage( "E_electric_outline_black.png" );
        public static final BufferedImage E_MECH_OUTLINE = RESOURCES.getImage( "E_mech_outline.png" );
        public static final BufferedImage E_MECH_OUTLINE_BLACK = RESOURCES.getImage( "E_mech_outline_black.png" );
        public static final BufferedImage E_THERM_OUTLINE = RESOURCES.getImage( "E_therm_outline.png" );
        public static final BufferedImage E_THERM_OUTLINE_BLACK = RESOURCES.getImage( "E_therm_outline_black.png" );
        public static final BufferedImage FAUCET_ICON = RESOURCES.getImage( "faucet_icon.png" );
        public static final BufferedImage FLUORESCENT = RESOURCES.getImage( "fluorescent.png" );
        public static final BufferedImage FLUORESCENT_ICON = RESOURCES.getImage( "fluorescent_icon.png" );
        public static final BufferedImage FLUORESCENT_ON = RESOURCES.getImage( "fluorescent_on.png" );
        public static final BufferedImage GENERATOR = RESOURCES.getImage( "generator.png" );
        public static final BufferedImage GENERATOR_ICON = RESOURCES.getImage( "generator_icon.png" );
        public static final BufferedImage GENERATOR_WHEEL = RESOURCES.getImage( "generator_wheel.png" );
        public static final BufferedImage GENERATOR_WHEEL_LONG = RESOURCES.getImage( "generator_wheel_long.png" );
        public static final BufferedImage HEATER_ELEMENT = RESOURCES.getImage( "heater_element.png" );
        public static final BufferedImage HEATER_ELEMENT_OFF = RESOURCES.getImage( "heater_element_off.png" );
        public static final BufferedImage INCANDESCENT = RESOURCES.getImage( "incandescent.png" );
        public static final BufferedImage INCANDESCENT_ICON = RESOURCES.getImage( "incandescent_icon.png" );
        public static final BufferedImage INCANDESCENT_ON = RESOURCES.getImage( "incandescent_on.png" );
        public static final BufferedImage SHELF_LONG = RESOURCES.getImage( "shelf_long.png" );
        public static final BufferedImage SOLAR_PANEL = RESOURCES.getImage( "solar_panel.png" );
        public static final BufferedImage SOLAR_PANEL_BASE = RESOURCES.getImage( "solar_panel_base.png" );
        public static final BufferedImage SOLAR_PANEL_ICON = RESOURCES.getImage( "solar_panel_icon.png" );
        public static final BufferedImage SUN_ICON = RESOURCES.getImage( "sun_icon.png" );
        public static final BufferedImage TAB_3_DRAWING = RESOURCES.getImage( "tab-3-drawing.png" );
        public static final BufferedImage TEAPOT = RESOURCES.getImage( "teapot.png" );
        public static final BufferedImage TEAPOT_ICON = RESOURCES.getImage( "teapot_icon.png" );
        public static final BufferedImage TEMP_FAUCET = RESOURCES.getImage( "temp_faucet.png" );
        public static final BufferedImage TEMP_SUN = RESOURCES.getImage( "temp_sun.png" );
        public static final BufferedImage THERMOMETER_MEDIUM_BACK = RESOURCES.getImage( "thermometer_medium_back.png" );
        public static final BufferedImage THERMOMETER_MEDIUM_FRONT = RESOURCES.getImage( "thermometer_medium_front.png" );
        public static final BufferedImage WATER_ICON = RESOURCES.getImage( "water_icon.png" );
        public static final BufferedImage WIRE_BLACK = RESOURCES.getImage( "wire_black.png" );
    }
}