// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.energyformsandchanges;

import java.awt.image.BufferedImage;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Resources (images and translated strings) for "EnergyFormsAndChanges" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator
 */
public class EnergyFormsAndChangesResources {
    public static final String PROJECT_NAME = "energy-forms-and-changes";
    public static final PhetResources RESOURCES = new PhetResources( PROJECT_NAME );

    //Strings
    public static class Strings {
        public static final String BRICK = RESOURCES.getLocalizedString( "brick" );
        public static final String CHEMICAL = RESOURCES.getLocalizedString( "chemical" );
        public static final String CLOUDS = RESOURCES.getLocalizedString( "clouds" );
        public static final String COOL = RESOURCES.getLocalizedString( "cool" );
        public static final String ELECTRICAL = RESOURCES.getLocalizedString( "electrical" );
        public static final String ENERGY_CHUNK_LABEL = RESOURCES.getLocalizedString( "energyChunkLabel" );
        public static final String ENERGY_SYMBOLS = RESOURCES.getLocalizedString( "energySymbols" );
        public static final String ENERGY_SYSTEMS = RESOURCES.getLocalizedString( "energySystems" );
        public static final String FAST_FORWARD = RESOURCES.getLocalizedString( "fastForward" );
        public static final String FEED_ME = RESOURCES.getLocalizedString( "feedMe" );
        public static final String FORMS_OF_ENERGY = RESOURCES.getLocalizedString( "formsOfEnergy" );
        public static final String HEAT = RESOURCES.getLocalizedString( "heat" );
        public static final String INTRO = RESOURCES.getLocalizedString( "intro" );
        public static final String IRON = RESOURCES.getLocalizedString( "iron" );
        public static final String LIGHT = RESOURCES.getLocalizedString( "light" );
        public static final String LOTS = RESOURCES.getLocalizedString( "lots" );
        public static final String MECHANICAL = RESOURCES.getLocalizedString( "mechanical" );
        public static final String NONE = RESOURCES.getLocalizedString( "none" );
        public static final String NORMAL = RESOURCES.getLocalizedString( "normal" );
        public static final String THERMAL = RESOURCES.getLocalizedString( "thermal" );
        public static final String WATER = RESOURCES.getLocalizedString( "water" );
    }

    //Images
    public static class Images {
        public static final BufferedImage BACK_LEG_01 = RESOURCES.getImage( "back_leg_01.png" );
        public static final BufferedImage BACK_LEG_02 = RESOURCES.getImage( "back_leg_02.png" );
        public static final BufferedImage BACK_LEG_03 = RESOURCES.getImage( "back_leg_03.png" );
        public static final BufferedImage BACK_LEG_04 = RESOURCES.getImage( "back_leg_04.png" );
        public static final BufferedImage BACK_LEG_05 = RESOURCES.getImage( "back_leg_05.png" );
        public static final BufferedImage BACK_LEG_06 = RESOURCES.getImage( "back_leg_06.png" );
        public static final BufferedImage BACK_LEG_07 = RESOURCES.getImage( "back_leg_07.png" );
        public static final BufferedImage BACK_LEG_08 = RESOURCES.getImage( "back_leg_08.png" );
        public static final BufferedImage BACK_LEG_09 = RESOURCES.getImage( "back_leg_09.png" );
        public static final BufferedImage BACK_LEG_10 = RESOURCES.getImage( "back_leg_10.png" );
        public static final BufferedImage BACK_LEG_11 = RESOURCES.getImage( "back_leg_11.png" );
        public static final BufferedImage BACK_LEG_12 = RESOURCES.getImage( "back_leg_12.png" );
        public static final BufferedImage BACK_LEG_13 = RESOURCES.getImage( "back_leg_13.png" );
        public static final BufferedImage BACK_LEG_14 = RESOURCES.getImage( "back_leg_14.png" );
        public static final BufferedImage BACK_LEG_15 = RESOURCES.getImage( "back_leg_15.png" );
        public static final BufferedImage BACK_LEG_16 = RESOURCES.getImage( "back_leg_16.png" );
        public static final BufferedImage BACK_LEG_17 = RESOURCES.getImage( "back_leg_17.png" );
        public static final BufferedImage BACK_LEG_18 = RESOURCES.getImage( "back_leg_18.png" );
        public static final BufferedImage BACK_LEG_19 = RESOURCES.getImage( "back_leg_19.png" );
        public static final BufferedImage BACK_LEG_20 = RESOURCES.getImage( "back_leg_20.png" );
        public static final BufferedImage BACK_LEG_21 = RESOURCES.getImage( "back_leg_21.png" );
        public static final BufferedImage BACK_LEG_22 = RESOURCES.getImage( "back_leg_22.png" );
        public static final BufferedImage BACK_LEG_23 = RESOURCES.getImage( "back_leg_23.png" );
        public static final BufferedImage BACK_LEG_24 = RESOURCES.getImage( "back_leg_24.png" );
        public static final BufferedImage BICYCLE_FRAME_3 = RESOURCES.getImage( "bicycle_frame_3.png" );
        public static final BufferedImage BICYCLE_ICON = RESOURCES.getImage( "bicycle_icon.png" );
        public static final BufferedImage BICYCLE_RIDER = RESOURCES.getImage( "bicycle_rider.png" );
        public static final BufferedImage BICYCLE_RIDER_TIRED = RESOURCES.getImage( "bicycle_rider_tired.png" );
        public static final BufferedImage BICYCLE_SPOKES = RESOURCES.getImage( "bicycle_spokes.png" );
        public static final BufferedImage BRICK_TEXTURE_FRONT = RESOURCES.getImage( "brick_texture_front.png" );
        public static final BufferedImage BRICK_TEXTURE_RIGHT = RESOURCES.getImage( "brick_texture_right.png" );
        public static final BufferedImage BRICK_TEXTURE_TOP = RESOURCES.getImage( "brick_texture_top.png" );
        public static final BufferedImage CLOUD_1 = RESOURCES.getImage( "cloud_1.png" );
        public static final BufferedImage CONNECTOR = RESOURCES.getImage( "connector.png" );
        public static final BufferedImage ELEMENT_BASE_BACK = RESOURCES.getImage( "element_base_back.png" );
        public static final BufferedImage ELEMENT_BASE_FRONT = RESOURCES.getImage( "element_base_front.png" );
        public static final BufferedImage E_CHEM_BLANK = RESOURCES.getImage( "E_chem_blank.png" );
        public static final BufferedImage E_DASHED_BLANK = RESOURCES.getImage( "E_dashed_blank.png" );
        public static final BufferedImage E_ELECTRIC_BLANK = RESOURCES.getImage( "E_electric_blank.png" );
        public static final BufferedImage E_LIGHT_BLANK = RESOURCES.getImage( "E_light_blank.png" );
        public static final BufferedImage E_MECH_BLANK = RESOURCES.getImage( "E_mech_blank.png" );
        public static final BufferedImage E_THERM_BLANK = RESOURCES.getImage( "E_therm_blank.png" );
        public static final BufferedImage E_THERM_BLANK_ORANGE = RESOURCES.getImage( "E_therm_blank_orange.png" );
        public static final BufferedImage FAUCET_ICON = RESOURCES.getImage( "faucet_icon.png" );
        public static final BufferedImage FLUORESCENT_BACK_2 = RESOURCES.getImage( "fluorescent_back_2.png" );
        public static final BufferedImage FLUORESCENT_FRONT_2 = RESOURCES.getImage( "fluorescent_front_2.png" );
        public static final BufferedImage FLUORESCENT_ICON = RESOURCES.getImage( "fluorescent_icon.png" );
        public static final BufferedImage FLUORESCENT_ON_BACK_2 = RESOURCES.getImage( "fluorescent_on_back_2.png" );
        public static final BufferedImage FLUORESCENT_ON_FRONT_2 = RESOURCES.getImage( "fluorescent_on_front_2.png" );
        public static final BufferedImage FRONT_LEG_01 = RESOURCES.getImage( "front_leg_01.png" );
        public static final BufferedImage FRONT_LEG_02 = RESOURCES.getImage( "front_leg_02.png" );
        public static final BufferedImage FRONT_LEG_03 = RESOURCES.getImage( "front_leg_03.png" );
        public static final BufferedImage FRONT_LEG_04 = RESOURCES.getImage( "front_leg_04.png" );
        public static final BufferedImage FRONT_LEG_05 = RESOURCES.getImage( "front_leg_05.png" );
        public static final BufferedImage FRONT_LEG_06 = RESOURCES.getImage( "front_leg_06.png" );
        public static final BufferedImage FRONT_LEG_07 = RESOURCES.getImage( "front_leg_07.png" );
        public static final BufferedImage FRONT_LEG_08 = RESOURCES.getImage( "front_leg_08.png" );
        public static final BufferedImage FRONT_LEG_09 = RESOURCES.getImage( "front_leg_09.png" );
        public static final BufferedImage FRONT_LEG_10 = RESOURCES.getImage( "front_leg_10.png" );
        public static final BufferedImage FRONT_LEG_11 = RESOURCES.getImage( "front_leg_11.png" );
        public static final BufferedImage FRONT_LEG_12 = RESOURCES.getImage( "front_leg_12.png" );
        public static final BufferedImage FRONT_LEG_13 = RESOURCES.getImage( "front_leg_13.png" );
        public static final BufferedImage FRONT_LEG_14 = RESOURCES.getImage( "front_leg_14.png" );
        public static final BufferedImage FRONT_LEG_15 = RESOURCES.getImage( "front_leg_15.png" );
        public static final BufferedImage FRONT_LEG_16 = RESOURCES.getImage( "front_leg_16.png" );
        public static final BufferedImage FRONT_LEG_17 = RESOURCES.getImage( "front_leg_17.png" );
        public static final BufferedImage FRONT_LEG_18 = RESOURCES.getImage( "front_leg_18.png" );
        public static final BufferedImage FRONT_LEG_19 = RESOURCES.getImage( "front_leg_19.png" );
        public static final BufferedImage FRONT_LEG_20 = RESOURCES.getImage( "front_leg_20.png" );
        public static final BufferedImage FRONT_LEG_21 = RESOURCES.getImage( "front_leg_21.png" );
        public static final BufferedImage FRONT_LEG_22 = RESOURCES.getImage( "front_leg_22.png" );
        public static final BufferedImage FRONT_LEG_23 = RESOURCES.getImage( "front_leg_23.png" );
        public static final BufferedImage FRONT_LEG_24 = RESOURCES.getImage( "front_leg_24.png" );
        public static final BufferedImage GENERATOR = RESOURCES.getImage( "generator.png" );
        public static final BufferedImage GENERATOR_ICON = RESOURCES.getImage( "generator_icon.png" );
        public static final BufferedImage GENERATOR_WHEEL_HUB_2 = RESOURCES.getImage( "generator_wheel_hub_2.png" );
        public static final BufferedImage GENERATOR_WHEEL_PADDLES_SHORT = RESOURCES.getImage( "generator_wheel_paddles_short.png" );
        public static final BufferedImage GENERATOR_WHEEL_SPOKES = RESOURCES.getImage( "generator_wheel_spokes.png" );
        public static final BufferedImage HEATER_ELEMENT = RESOURCES.getImage( "heater_element.png" );
        public static final BufferedImage HEATER_ELEMENT_DARK = RESOURCES.getImage( "heater_element_dark.png" );
        public static final BufferedImage INCANDESCENT_2 = RESOURCES.getImage( "incandescent_2.png" );
        public static final BufferedImage INCANDESCENT_ICON = RESOURCES.getImage( "incandescent_icon.png" );
        public static final BufferedImage INCANDESCENT_ON_3 = RESOURCES.getImage( "incandescent_on_3.png" );
        public static final BufferedImage SHELF_LONG = RESOURCES.getImage( "shelf_long.png" );
        public static final BufferedImage SOLAR_PANEL = RESOURCES.getImage( "solar_panel.png" );
        public static final BufferedImage SOLAR_PANEL_GEN = RESOURCES.getImage( "solar_panel_gen.png" );
        public static final BufferedImage SOLAR_PANEL_ICON = RESOURCES.getImage( "solar_panel_icon.png" );
        public static final BufferedImage SOLAR_PANEL_POST_2 = RESOURCES.getImage( "solar_panel_post_2.png" );
        public static final BufferedImage SUN_ICON = RESOURCES.getImage( "sun_icon.png" );
        public static final BufferedImage TEAPOT_ICON = RESOURCES.getImage( "teapot_icon.png" );
        public static final BufferedImage TEAPOT_LARGE = RESOURCES.getImage( "teapot_large.png" );
        public static final BufferedImage THERMOMETER_MEDIUM_BACK = RESOURCES.getImage( "thermometer_medium_back.png" );
        public static final BufferedImage THERMOMETER_MEDIUM_FRONT = RESOURCES.getImage( "thermometer_medium_front.png" );
        public static final BufferedImage WATER_ICON = RESOURCES.getImage( "water_icon.png" );
        public static final BufferedImage WIRE_BLACK_62 = RESOURCES.getImage( "wire_black_62.png" );
        public static final BufferedImage WIRE_BLACK_LEFT = RESOURCES.getImage( "wire_black_left.png" );
        public static final BufferedImage WIRE_BLACK_RIGHT = RESOURCES.getImage( "wire_black_right.png" );
    }
}