// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.balanceandtorque;

import java.awt.image.BufferedImage;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Resources (images and translated strings) for "BalanceAndTorque" are loaded
 * eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator
 */
public class BalanceAndTorqueResources {
    public static final String NAME = "balance-and-torque";
    public static final PhetResources RESOURCES = new PhetResources( NAME );

    //Strings
    public static class Strings {

    }

    //Images
    public static class Images {
        public static final BufferedImage ADOLESCENT_SITTING = RESOURCES.getImage( "adolescent-sitting.png" );
        public static final BufferedImage ADOLESCENT_STANDING = RESOURCES.getImage( "adolescent-standing.png" );
        public static final BufferedImage ADULT_MAN_SITTING = RESOURCES.getImage( "adult-man-sitting.png" );
        public static final BufferedImage ADULT_MAN_STANDING = RESOURCES.getImage( "adult-man-standing.png" );
        public static final BufferedImage ADULT_WOMAN_SITTING = RESOURCES.getImage( "adult-woman-sitting.png" );
        public static final BufferedImage ADULT_WOMAN_STANDING = RESOURCES.getImage( "adult-woman-standing.png" );
        public static final BufferedImage COMPACT_ADOLESCENT_SITTING = RESOURCES.getImage( "compact-adolescent-sitting.png" );
        public static final BufferedImage LEVER_INTO_WHEELBARROW = RESOURCES.getImage( "lever-into-wheelbarrow.png" );
        public static final BufferedImage MYSTERY_OBJECT_01 = RESOURCES.getImage( "mystery-object-01.png" );
        public static final BufferedImage MYSTERY_OBJECT_02 = RESOURCES.getImage( "mystery-object-02.png" );
        public static final BufferedImage MYSTERY_OBJECT_03 = RESOURCES.getImage( "mystery-object-03.png" );
        public static final BufferedImage MYSTERY_OBJECT_04 = RESOURCES.getImage( "mystery-object-04.png" );
        public static final BufferedImage MYSTERY_OBJECT_05 = RESOURCES.getImage( "mystery-object-05.png" );
        public static final BufferedImage MYSTERY_OBJECT_06 = RESOURCES.getImage( "mystery-object-06.png" );
        public static final BufferedImage MYSTERY_OBJECT_07 = RESOURCES.getImage( "mystery-object-07.png" );
        public static final BufferedImage MYSTERY_OBJECT_08 = RESOURCES.getImage( "mystery-object-08.png" );
        public static final BufferedImage YOUNG_GIRL_SITTING_01 = RESOURCES.getImage( "young-girl-sitting-01.png" );
        public static final BufferedImage YOUNG_GIRL_STANDING_01 = RESOURCES.getImage( "young-girl-standing-01.png" );
    }
}