// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.balanceandtorque;

import java.awt.image.BufferedImage;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Resources (images and translated strings) for "BalanceAndTorque" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator
 */
public class BalanceAndTorqueResources {
    public static final String NAME = "balance-and-torque";
    public static final PhetResources RESOURCES = new PhetResources( NAME );

    //Strings
    public static class Strings {

    }

    //Images
    public static class Images {
        public static final BufferedImage ADOLESCENT_SITTING = RESOURCES.getImage( "adolescent-sitting.png" );
        public static final BufferedImage ADOLESCENT_STANDING = RESOURCES.getImage( "adolescent-standing.png" );
        public static final BufferedImage ADULT_MAN_STANDING = RESOURCES.getImage( "adult-man-standing.png" );
        public static final BufferedImage COMPACT_ADOLESCENT_SITTING = RESOURCES.getImage( "compact-adolescent-sitting.png" );
        public static final BufferedImage LEVER_INTO_WHEELBARROW = RESOURCES.getImage( "lever-into-wheelbarrow.png" );
    }
}