//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_vi.properties
define( {
            "Games.label.level": "Mức: {0}",
            "Common.updates.errorMessage": "Một lỗi đã xuất hiện trong quá trình cập nhật.<br>Vui lòng thử lại sau hoặc ghé thăm {0}.",
            "XMLPersistenceManager.save.error.encode": "<html>Lỗi mã hóa file:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Lỗi giải mã file:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "f",
            "Common.softwareAgreement.decline": "Thoát",
            "Common.statistics.host_os_name": "Tên hệ điều hành",
            "Common.statistics.user_total_sessions": "Tổng số lần chạy của tất cả các mô phỏng",
            "Common.statistics.host_java_version_major": "Phiên bản Java (chính)",
            "FileChooser.openDialogTitleText": "Mở",
            "Common.statistics.host_java_version_maintenance": "Phiên bản Java (hiện thời)",
            "FileChooser.lookInLabelText": "Tìm trong:",
            "Common.choice.cancel": "Cancel",
            "Common.updates.seePreferences": "Chọn File -> Preferences để thay đổi các tuỳ chọn theo sở thích của bạn.",
            "Common.About.CreditsDialog.software-development": "Phát triển phần mềm",
            "Common.About.JavaVersion": "Phiên bản Java:",
            "ColorChooser.resetText": "Reset",
            "wavelength.ir": "HN",
            "Common.About.CreditsDialog.design-team": "Nhóm thiết kế",
            "Common.statistics.sim_total_sessions": "Tổng số lần chạy của mô phỏng này",
            "Games.title.gameSettings": "Thiết đặt của game",
            "Common.FileMenu.PreferencesMnemonic": "p",
            "wavelength.uv": "TN",
            "XMLPersistenceManager.save.title": "Lưu cấu hình",
            "XMLPersistenceManager.load.error.contents": "File bị hỏng hoặc không được tạo bởi chính mô phỏng này.",
            "Common.statistics.details.title": "Thông tin",
            "Common.statistics.sim_dev_version": "Phiên bản mô phỏng (của nhà phát triển)",
            "FileChooser.saveInLabelText": "Lưu vào:",
            "Common.statistics.sim_name": "Tên mô phỏng",
            "Save.confirm.message": "<html>File bạn chọn đã tồn tại. <br>Bạn có muốn thay thế và ghi đè lên nó không?</html>",
            "Games.label.score": "Điểm: {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "Nhóm phát triển PhET",
            "Games.button.start": "Bắt đầu!",
            "Common.statistics.sim_deployment": "Kiểu triển khai",
            "Common.FileMenu.Save": "Lưu cấu hình...",
            "ColorChooser.hsbSaturationText": "S",
            "Games.radioButton.on": "Bật",
            "FileChooser.acceptAllFileFilterText": "Tất cả File (*.*)",
            "ColorChooser.hsbNameText": "HSB",
            "Common.ModelSlider.Minimum": "Nhỏ nhất",
            "Common.FileMenu.Preferences": "Tuỳ chọn...",
            "Common.FileMenu.Load": "Nạp cấu hình...",
            "Common.updates.downloadingSimJar": "đang download file mô phỏng JAR",
            "Games.radioButton.off": "Tắt",
            "ColorChooser.swatchesRecentText": "Mới đây:",
            "Common.updates.updateAvailable": "Đã có bản cập nhật",
            "Common.statistics.host_locale_language": "Ngôn ngữ bản địa",
            "Common.clear": "Xóa",
            "Games.title.gameOver": "Game over",
            "FileChooser.filesOfTypeLabelText": "Kiểu File:",
            "Common.ErrorDialog.detailsTitle": "Chi tiết lỗi",
            "Common.HelpMenu.MegaHelp": "Trợ giúpchung...",
            "Common.ClockControlPanel.Step": "Step",
            "Common.statistics.sim_revision": "Phiên bản mô phỏng (đã hiệu chỉnh)",
            "Common.choice.yes": "Yes",
            "Common.FileMenu.Title": "File",
            "Common.value_units": "{0} {1}",
            "Common.statistics.sim_dev": "Đây có phải là phiên bản của nhà phát triển?",
            "Common.updates.installer.message": "<html>Bản PhET Offline được cài đặt ngày {0}.<br>Hiện đã có phiên bản mới, ngày {1}.<br><br>Bạn có muốn cài đặt bản PhET Offline mới nhất không?</html>",
            "Common.updates.updateNow": "Cập nhật ngay!",
            "Common.record": "Ghi",
            "Common.About.CreditsDialog.Title": "Nhóm phát triển",
            "Common.updates.error.internetConnection": "<html>Không thể kết nối với {0},<br>Vui lòng kiểm tra đường truyền Internet.</html>",
            "Common.time.fast": "nhanh",
            "XMLPersistenceManager.load.error.message": "<html>Lỗi đọc file:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Lớn nhất",
            "Common.OptionsMenu": "Tuỳ chọn",
            "Common.ClockControlPanel.Restart": "Restart",
            "Common.statistics.sim_version_timestamp": "Phiên bản mô phỏng (thời điểm xác lập)",
            "Common.updates.installer.yes": "Yes!",
            "Common.phetInstaller": "Bản cài đặt PhET Offline",
            "Common.HelpMenu.About": "Thông tin về chương trình...",
            "Common.ModelSlider.OutOfRange": "Trị vượt phạm vi cho phép",
            "ColorChooser.previewText": "Xem trước",
            "Common.BasicPhetPanel.Title": "Quay lại",
            "Common.HelpPanel.HideHelp": "Ẩn trợ giúp",
            "Common.statistics.host_os_arch": "Loại vi xử lí",
            "Common.preferences.title": "Tuỳ chọn",
            "Games.button.newGame": "Game mới",
            "ColorChooser.hsbRedText": "R",
            "ColorChooser.hsbBlueText": "B",
            "Common.ModelSlider.YouEntered": "Bạn đã nhập",
            "Games.label.newBest": "Kỷ lục mới!",
            "Common.About.BuildDate": "Ngày tạo:",
            "Common.FileMenu.ExitMnemonic": "x",
            "Games.label.best": "Cao nhất: {0}",
            "Common.statistics.sim_project": "Tên dự án",
            "Common.updates.downloadingBootstrap": "đang tải và khởi động cập nhật...",
            "Common.title.error": "Lỗi",
            "Common.FileMenu.Exit": "Thoát",
            "Common.statistics.sim_major_version": "Phiên bản mô phỏng (chính)",
            "Common.updates.askMeLater": "Hỏi lại sau",
            "chart-time-control.go": "Go!",
            "Common.HelpMenu.HelpMnemonic": "h",
            "Common.confirm.clear.graphs": "Có chắc là bạn muốn xóa các đồ thị không?",
            "ColorChooser.swatchesNameText": "Bộ sưu tập mẫu",
            "Common.updates.progressDialogMessage": "Đang cập nhật \"{0}\" lên phiên bản{1}",
            "Common.updates.installer.more": "Vui lòng cho tôi biết thêm chi tiết...",
            "XMLPersistenceManager.title.error": "Lỗi",
            "ColorChooser.hsbHueText": "H",
            "ControlPanel.button.resetAll": "Reset tất cả",
            "Common.About.AgreementButton": "Thoả thuận về phần mềm...",
            "Common.FileMenu.Load.mnemonic": "L",
            "Common.ErrorDialog.detailsButton": "Chi tiết...",
            "Common.updates.errorMissingJar": "<html>Không thể thực hiện việc cập nhật.<br>Không định vị được file JAR: {0}.<br>Vui lòng liên hệ với Người quản trị hệ thống để được giúp đỡ.<br></html>",
            "Common.preferences.privacy": "Quyền riêng tư",
            "Common.HelpMenu.AboutTitle": "Thông tin về chương trình",
            "ColorChooser.rgbRedText": "Red",
            "Common.statistics.sim_locale_country": "Quốc gia",
            "ColorChooser.hsbGreenText": "G",
            "ColorChooser.rgbGreenText": "Green",
            "Games.format.time.best": "{0} ({1})",
            "Common.HelpPanel.ShowHelp": "Trợ giúp!",
            "Common.statistics.sim_distribution_tag": "Phiên bản mô phỏng (của nhà phân phối)",
            "Common.statistics.description": "PhET được tài trợ miễn phí, nhưng <br>chúng tôi bắt buộc phải thu thập<br>một lượng tối thiểu <a href=\"{0}\">thông tin ẩn danh</a> để có những báo cáo về<br>số lượng người sử dụng mô phỏng PhET<br> và phục vụ tốt nhu cầu của người sử dụng.",
            "Common.softwareAgreement.message": "Trong tất cả các mô phỏng PhET, chúng tôi thu thập một lượng tối thiểu<br><a href=\"{0}\">thông tin ẩn danh</a> khi mô phỏng khởi động<br>(vd như phiên bản mô phỏng, hệ điều hành).<br>Bạn có thể chặn việc gửi các thông tin này<br>bất kỳ lúc nào bằng cách vào menu File->Preferences.<br><br>Khi click vào \"Đồng ý và Tiếp tục\", bạn đã đồng ý với<br>Bản thoả thuận về phần mềm của PhET, bao gồm chính sách về sự riêng tư cá nhân. (Để biết thêm chi tiết, hãy click <a href=\"{1}\">vào đây</a>).",
            "Common.choice.ok": "OK",
            "Common.About.Version": "Phiên bản:",
            "Common.ErrorDialog.contactPhet": "Nếu vấn đề này vẫn còn, hãy gửi các chi tiết sau đến {0}",
            "Common.About.CreditsDialog.lead-design": "Trưởng nhóm thiết kế",
            "Common.OptionsMenu.mnemonic": "O",
            "Common.statistics.user_preference_file_creation_time": "Thời điểm tạo file lưu các tuỳ chọn",
            "Common.HelpMenu.AboutMnemonic": "a",
            "Common.updates.errorWritePermissions": "<html>Không thể thực hiện việc cập nhật.<br>Bạn không được phép ghi vào {0}.<br>Vui lòng liên hệ với Người quản trị hệ thống  để được giúp đỡ.<br></html>",
            "ColorChooser.hsbBrightnessText": "B",
            "Common.choice.no": "No",
            "Common.About.WebLink": "Ghé thăm trang chủ của PhET",
            "Common.About.OSVersion": "Phiên bản HĐH:",
            "Common.updates.versionComparison": "<html>Bạn đang dùng phiên bản của \"{0}\" là {1}.<br>Đã có phiên bản ({2}) mới hơn.</html>",
            "Common.statistics.sim_locale_language": "Ngôn ngữ",
            "Common.statistics.user_installation_timestamp": "Thời điểm cài đặt PhET",
            "Common.statistics.message_version": "Phiên bản thông báo",
            "Common.ModelSlider.Description": "Giá trị không hợp lệ",
            "Common.updates.installer.moreMessage": "<html>Hãy duy trì việc cập nhật cho phiên bản PhET Offline <br>để bảo đảm rằng bạn có được các mô phỏng và tư liệu<br>mới nhất từ PhET.<br><br>Nếu bạn chọn phiên bản mới nhất, trình duyệt web <br>sẽ mở website của PhET để bạn có thể download<br>bản cài đặt PhET Offline.</html>",
            "ControlPanel.message.confirmResetAll": "Reset mọi thiết lập?",
            "Common.HelpMenu.Help": "Trợ giúp",
            "Common.updates.errorNotAJar": "{0} không phải là file JAR.",
            "Games.label.levelControl": "Mức:",
            "Common.updates.automaticallyCheck": "Tự động kiểm tra cập nhật",
            "Common.sim.speed": "...tốc độ mô phỏng...",
            "Common.updates.checkForSimUpdate": "Kiểm tra cập nhật mô phỏng...",
            "XMLPersistenceManager.save.confirm.message": "<html>File bạn chọn đã tồn tại. <br>Bạn có muốn thay thế và ghi đè lên nó không?</html>",
            "FileChooser.newFolderErrorText": "Lỗi khi tạo Folder mới",
            "Common.updates.skipThisUpdate": "Bỏ qua bản cập nhật này",
            "Common.About.CreditsButton": "Nhóm phát triển...",
            "Common.FileMenu.Save.mnemonic": "S",
            "FileChooser.saveDialogTitleText": "Lưu",
            "XMLPersistenceManager.load.title": "Nạp cấu hình",
            "Common.updates.checkForInstallerUpdate": "Kiểm tra cập nhật bản cài đặt PhET Offline...",
            "timeseries.control.panel.playback": "Chạy lại",
            "Common.updates.progressDialogTitle": "Đang cập nhật",
            "Common.HelpMenu.Title": "Trợ giúp",
            "FileChooser.fileNameLabelText": "Tên File:",
            "ColorChooser.rgbNameText": "RGB",
            "Common.softwareAgreement.title": "Bản thoả thuận về phần mềm",
            "Common.statistics.host_java_version_minor": "Phiên bản Java (phụ)",
            "Common.HelpMenu.TitleMnemonic": "h",
            "Common.About.CreditsDialog.interviews": "Phỏng vấn",
            "Common.About.Distribution": "Phân phối:",
            "Common.statistics.host_java_webstart_version": "Phiên bản Java Web Start",
            "XMLPersistenceManager.save.error.message": "<html>Lỗi ghi file:<br>{0}</html>",
            "Games.label.time": "Thời gian: {0}",
            "FileChooser.openButtonText": "Mở",
            "ColorChooser.sampleText": "Văn bản mẫu",
            "Common.statistics.details.description": "<html>Thông tin hiển thị dưới đây sẽ được gửi cho PhET khi mô phỏng khởi động.</html>",
            "Common.statistics.host_os_version": "Phiên bản hệ điều hành",
            "Common.title.confirm": "Xác nhận",
            "Games.label.score.max": "Điểm: {0} trên {1}",
            "Common.BasicPhetPanel.LogoToolTip": "Tắt Full Frame",
            "Common.statistics.host_java_timezone": "Múi giờ",
            "Common.time.slow": "chậm",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.ClockControlPanel.Rewind": "Rewind",
            "Common.softwareAgreement.accept": "Chấp nhận và Tiếp tục",
            "Common.updates.updateToDate": "Cập nhật",
            "Common.ClockControlPanel.Pause": "Pause",
            "PhetApplication.StartupDialog.message": "\"{0}\" đang khởi động",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Chương trình này sử dụng phần mềm của bên thứ 3 sau",
            "XMLPersistenceManager.message.notAConfigFile": "File không chứa cấu hình của mô phỏng này",
            "Common.preferences.updates": "Cập nhật",
            "Games.label.score.max.perfect": "Điểm: {0} trên {1} (Xuất sắc!)",
            "Common.HelpMenu.MegaHelpMnemonic": "m",
            "Common.statistics.enabled": "Cho phép gửi thông tin đến PhET",
            "Common.StopwatchPanel.stop": "Stop",
            "Common.HelpPanel.MegaHelp": "Trợ giúp chung...",
            "Common.statistics.host_locale_country": "Bản xứ",
            "Common.StopwatchPanel.reset": "Reset",
            "Common.playback": "Chạy lại",
            "Games.message.confirmNewGame": "<html>Bạn chưa hoàn thành game này.<br>Bắt đầu một game mới nhé?</html>",
            "Common.statistics.sim_minor_version": "Phiên bản mô phỏng (phụ)",
            "Common.updates.tryIt": "Xem thử phiên bản mới trước khi cập nhật.",
            "ColorChooser.rgbBlueText": "Blue",
            "Common.choice.close": "Đóng",
            "Common.ClockControlPanel.Play": "Play",
            "Common.statistics.sim_type": "Kiểu mô phỏng",
            "FileChooser.saveButtonText": "Lưu",
            "Common.rewind": "Rewind",
            "Common.StopwatchPanel.start": "Start",
            "Common.updates.youHaveCurrent": "Bạn đang có phiên bản mới nhất ({0}) của {1}.",
            "Common.statistics.sim_sessions_since": "Số lần mô phỏng này đã chạy kể từ lần online mới nhất",
            "Common.statistics.host_java_vendor": "Nhà cung cấp Java",
            "charts.show-graphs": "Hiện đồ thị:",
            "Common.statistics.message_type": "Kiểu thông báo"
        } );