(function(){
function aa(){var a=ba.cookie,b=Math.round((new Date).getTime()/1000),c=h.google_analytics_domain_name,d=typeof c=="undefined"?ca("auto"):ca(c),e=a.indexOf("__utma="+d+".")>-1,f=a.indexOf("__utmb="+d)>-1,g=a.indexOf("__utmc="+d)>-1,i,k={};if(e){i=a.split("__utma="+d+".")[1].split(";")[0].split(".");k.sid=f&&g?i[3]+"":h&&h.gaGlobal&&h.gaGlobal.sid?h.gaGlobal.sid:b+"";k.vid=i[0]+"."+i[1];k.from_cookie=j}else{k.sid=h&&h.gaGlobal&&h.gaGlobal.sid?h.gaGlobal.sid:b+"";k.vid=h&&h.gaGlobal&&h.gaGlobal.vid?
h.gaGlobal.vid:(da()^ea()&2147483647)+"."+b;k.from_cookie=m}k.dh=d;k.hid=h&&h.gaGlobal&&h.gaGlobal.hid?h.gaGlobal.hid:da();h.gaGlobal=k;return k}function da(){return Math.round(Math.random()*2147483647)}
function ea(){var a=ba.cookie?ba.cookie:"",b=h.history.length,c,d,e=[n.appName,n.version,n.language?n.language:n.browserLanguage,n.platform,n.userAgent,n.javaEnabled()?1:0].join("");if(h.screen)e+=h.screen.width+"x"+h.screen.height+h.screen.colorDepth;else if(h.java){d=java.awt.Toolkit.getDefaultToolkit().getScreenSize();e+=d.screen.width+"x"+d.screen.height}e+=a;e+=ba.referrer?ba.referrer:"";c=e.length;while(b>0)e+=b--^c++;return fa(e)}
function fa(a){var b=1,c=0,d,e;if(!(a==undefined||a=="")){b=0;for(d=a.length-1;d>=0;d--){e=a.charCodeAt(d);b=(b<<6&268435455)+e+(e<<14);c=b&266338304;b=c!=0?b^c>>21:b}}return b}function ca(a){if(!a||a==""||a=="none")return 1;if("auto"==a){a=ba.domain;if("www."==a.substring(0,4))a=a.substring(4,a.length)}return fa(a.toLowerCase())}function ga(){}function ha(a){p&&p.Xb(a)}function ia(a){p&&p.Yb(a)}function ja(a){p&&p.Wb(a)}
function s(){this.I=this.Kb();this.pa=m;if(!this.I){this.pa=this.gb();this.pa||ia("Browser does not allow cookies")}}
function ka(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){var b=3,c=1;while(c)try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(b+1));b++}catch(d){c=t}return b.toString()}else if(la("msie")&&!window.opera){var c=t;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){var b=
0;try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6");b=6;c.AllowScriptAccess="always"}catch(d){if(b==6)return b.toString()}try{c=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(d){}}if(c!=t){var b=c.GetVariable("$version").split(" ")[1];return b.replace(/,/g,".")}}return"0"}function ma(a,b){if(b){var c=na(b);if(c){var d=oa("div");d.innerHTML=a;pa(c,d)}}window.console&&typeof window.console.log=="function"&&window.console.log(a)}function qa(a){return a!=t?'"'+a+'"':'""'}
function ra(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function u(a,b){if(a&&b)window.google_ad_url+="&"+a+"="+b}function v(a){var b=window,c=sa[a]||ta[a]||t,d=b[a];u(c,d)}function w(a,b){b&&u(a,ra(b))}function x(a){var b=window,c=sa[a]||ta[a]||t,d=b[a];w(c,d)}function ua(a,b){var c=window,d=sa[a]||ta[a]||t,e=c[a];if(d&&e&&typeof e=="object")e=e[b%e.length];u(d,e)}
function va(a,b){var c=a.screen,d=navigator.javaEnabled(),e=-b.getTimezoneOffset();if(c){u("u_h",c.height);u("u_w",c.width);u("u_ah",c.availHeight);u("u_aw",c.availWidth);u("u_cd",c.colorDepth)}u("u_tz",e);u("u_his",history.length);u("u_java",d);navigator.plugins&&u("u_nplug",navigator.plugins.length);navigator.mimeTypes&&u("u_nmime",navigator.mimeTypes.length)}
function wa(a){if(!a.google_enable_first_party_cookie)return;if(p==t)p=new ga;if(a._GA_googleCookieHelper==t)a._GA_googleCookieHelper=new s;if(!a._google_cookie_fetched){a._google_cookie_fetched=j;a._GA_googleCookieHelper.kb(xa(a.google_ad_client))}}function xa(a){if(a){a=a.toLowerCase();if(a.substring(0,3)!="ca-")a="ca-"+a}return a}function ya(a){if(a){a=a.toLowerCase();if(a.substring(0,9)!="dist-aff-")a="dist-aff-"+a}return a}
function za(a){var b="google_unique_id";if(a[b])++a[b];else a[b]=1;return a[b]}function Aa(){var a=Math.random();if(a<0.0010)return 30143001;else if(a<0.0020)return 30143002;return 0}
function Ba(a,b,c,d){var e=za(a),f=a.google_container_id||d||"google_ad_div"+e;c=c.substring(0,2000);c=c.replace(/%\w?$/,"");var g="script";if((a.google_ad_output=="js"||a.google_ad_output=="json_html")&&(a.google_ad_request_done||a.google_radlink_request_done))b.write("<"+g+' language="JavaScript1.1" src='+qa(c)+"></"+g+">");else if(a.google_ad_output=="html")if(a.google_expandable_iframe||Ca==30143002){var i=Da(f,parseInt(a.google_ad_width,10),parseInt(a.google_ad_height,10),b),k=Ea(e,a,i);a["google_expandable_ad_slot"+
e]=new z(c,k)}else{var l='<iframe name="google_ads_frame" width='+qa(a.google_ad_width)+" height="+qa(a.google_ad_height)+" frameborder="+qa(a.google_ad_frameborder)+" src="+qa(c)+' marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true" scrolling="no"></iframe>';a.google_container_id?Fa(a.google_container_id,b,l):b.write(l)}else a.google_ad_output=="textlink"&&b.write("<"+g+' language="JavaScript1.1" src='+qa(c)+"></"+g+">")}
function Da(a,b,c,d){var e=Ga(a);if(e){e.style.display="block";e.style.height=c+"px";e.style.visibility="visible";e.style.width=b+"px"}else{d.write('<ins id="'+a+'" style="width:'+b+"px;height:"+c+'px;position:relative;margin:0;padding:0;display:block;visibility:visible;border:none"></ins>');e=Ga(a)}return e}
function Ea(a,b,c){var d=Ha().createElement("IFRAME");d.id="google_ads_frame"+a;d.allowTransparency=j;d.frameBorder=b.google_ad_frameborder||0;d.height=b.google_ad_height;d.hspace=0;d.marginHeight=0;d.marginWidth=0;d.name="google_ads_frame";d.scrolling="no";d.style.left=0;d.style.position="absolute";d.style.top=0;d.style.zIndex=999;d.vspace=0;d.width=b.google_ad_width;c.appendChild(d);return d}
function Ia(a){for(var b in sa)a[b]=t;for(var b in ta){if(b=="google_correlator")continue;a[b]=t}a.google_container_id=t}function Ja(a){if(a.google_ad_format)return a.google_ad_format.indexOf("_0ads")>0;return a.google_ad_output!="html"&&a.google_num_radlinks>0}function Ka(a){return a&&a.indexOf("_sdo")!=-1}
function La(a){var b=t,c=window,d=document,e=new Date,f=e.getTime(),g=c.google_ad_format,i=Ma(c);if(c.google_cpa_choice!=b){c.google_ad_url=i+"/cpa/ads?";c.google_ad_url+="client="+escape(xa(c.google_ad_client));c.google_ad_region="_google_cpa_region_";v("google_cpa_choice");if(typeof d.characterSet!="undefined")w("oe",d.characterSet);else typeof d.charset!="undefined"&&w("oe",d.charset)}else if(Ka(g)){c.google_ad_url=i+"/pagead/sdo?";c.google_ad_url+="client="+escape(ya(c.google_ad_client))}else{c.google_ad_url=
i+"/pagead/ads?";c.google_ad_url+="client="+escape(xa(c.google_ad_client))}v("google_ad_host");v("google_ad_host_tier_id");var k=c.google_num_slots_by_client,l=c.google_num_slots_by_channel,o=c.google_prev_ad_formats_by_region,q=c.google_prev_ad_slotnames_by_region;if(c.google_ad_region==b&&c.google_ad_section!=b)c.google_ad_region=c.google_ad_section;var r=c.google_ad_region==b?"":c.google_ad_region;if(Ka(g)){c.google_num_sdo_slots=c.google_num_sdo_slots?c.google_num_sdo_slots+1:1;if(c.google_num_sdo_slots>
4)return m}else if(Ja(c)){c.google_num_0ad_slots=c.google_num_0ad_slots?c.google_num_0ad_slots+1:1;if(c.google_num_0ad_slots>3)return m}else if(c.google_cpa_choice==b){c.google_num_ad_slots=c.google_num_ad_slots?c.google_num_ad_slots+1:1;if(c.google_num_slots_to_rotate){o[r]=b;q[r]=b;if(c.google_num_slot_to_show==b)c.google_num_slot_to_show=f%c.google_num_slots_to_rotate+1;if(c.google_num_slot_to_show!=c.google_num_ad_slots)return m}else if(c.google_num_ad_slots>6&&r=="")return m}u("dt",e.getTime());
v("google_language");c.google_country?v("google_country"):v("google_gl");v("google_region");x("google_city");x("google_hints");v("google_safe");v("google_encoding");v("google_last_modified_time");x("google_alternate_ad_url");v("google_alternate_color");v("google_skip");v("google_targeting");var y=c.google_ad_client;if(k[y])k[y]+=1;else{k[y]=1;k.length+=1}if(o[r])if(!Ka(g)){w("prev_fmts",o[r].toLowerCase());k.length>1&&u("slot",k[y])}q[r]&&w("prev_slotnames",q[r].toLowerCase());if(g&&!c.google_ad_slot){w("format",
g.toLowerCase());Ka(g)||(o[r]=o[r]?o[r]+","+g:g)}if(c.google_ad_slot)q[r]=q[r]?q[r]+","+c.google_ad_slot:c.google_ad_slot;v("google_max_num_ads");u("output",c.google_ad_output);v("google_adtest");v("google_ad_callback");v("google_ad_slot");x("google_correlator");c.google_new_domain_checked==1&&c.google_new_domain_enabled==0&&u("dblk",1);if(c.google_ad_channel){x("google_ad_channel");var M="",rb=c.google_ad_channel.split(/[+, ]/);for(var Ra=0;Ra<rb.length;Ra++){var Sa=rb[Ra];if(l[Sa])M+=Sa+"+";else l[Sa]=
1}w("pv_ch",M)}if(c.google_ad_host_channel){x("google_ad_host_channel");var zc=Na(c.google_ad_host_channel,c.google_viewed_host_channels);w("pv_h_ch",zc)}c.google_enable_first_party_cookie&&w("cookie",c._GA_googleCookieHelper.rb());x("google_page_url");ua("google_color_bg",f);ua("google_color_text",f);ua("google_color_link",f);ua("google_color_url",f);ua("google_color_border",f);ua("google_color_line",f);c.google_reuse_colors?u("reuse_colors",1):u("reuse_colors",0);v("google_kw_type");x("google_kw");
x("google_contents");v("google_num_radlinks");v("google_max_radlink_len");v("google_rl_filtering");v("google_rl_mode");v("google_rt");x("google_rl_dest_url");v("google_num_radlinks_per_unit");v("google_ad_type");v("google_image_size");v("google_ad_region");if(c.google_expandable_iframe===m)c.google_allow_expandable_ads="off";else{Ca=Aa();u("eid",Ca);if(!c.google_expandable_iframe&&Ca!=30143002)c.google_allow_expandable_ads="off"}v("google_allow_expandable_ads");v("google_feedback");x("google_referrer_url");
x("google_page_location");u("frm",c.google_iframing);v("google_bid");v("google_ctr_threshold");v("google_cust_age");v("google_cust_gender");v("google_cust_interests");v("google_cust_id");v("google_cust_job");v("google_cust_u_url");v("google_cust_l");v("google_cust_lh");v("google_cust_ch");v("google_ed");v("google_video_doc_id");v("google_video_product_type");x("google_ui_features");x("google_only_ads_with_video");x("google_disable_video_autoplay");a&&w("ff",Oa(a));if(c.top.location==d.location&&d.body){var sb=
d.body.scrollHeight,tb=d.body.clientHeight;tb&&sb&&w("cc",Math.round(tb*100/sb))}aa();u("ga_vid",c.gaGlobal.vid);u("ga_sid",c.gaGlobal.sid);u("ga_hid",c.gaGlobal.hid);u("ga_fc",c.gaGlobal.from_cookie);x("google_analytics_uacct");v("google_ad_override");v("google_flash_version");va(c,e);return j}
function Na(a,b){var c=a.split("|"),d=-1,e=[];for(var f=0;f<c.length;f++){var g=c[f].split(/[+, ]/);b[f]||(b[f]={});var i="";for(var k=0;k<g.length;k++){var l=g[k];if(b[f][l])i+="+"+l;else b[f][l]=1}i=i.slice(1);e[f]=i;if(i!="")d=f}var o="";if(d>-1){for(var f=0;f<d;f++)o+=e[f]+"|";o+=e[d]}return o}
function Pa(){var a=window,b=document;wa(a);var c;if(Math.random()<0.01){var d="google_temp_span";if(!Ga(d)){b.write("<span id="+d+"></span>");c=Ga(d)}}var e=La(c);c&&Qa(c);if(!e)return;Ba(a,b,a.google_ad_url);Ia(a)}function Ta(){Pa();return j}
function Ua(a,b){var c=b.documentElement;if(a.top.location==b.location)return m;if(a.google_ad_width&&a.google_ad_height){var d=1,e=1;if(a.innerHeight){d=a.innerWidth;e=a.innerHeight}else if(c&&c.clientHeight){d=c.clientWidth;e=c.clientHeight}else if(b.body){d=b.body.clientWidth;e=b.body.clientHeight}if(e>2*a.google_ad_height||d>2*a.google_ad_width)return m}return j}
function Va(a){var b=window,c=t,d=b.onerror;b.onerror=a;if(b.google_ad_frameborder==c)b.google_ad_frameborder=0;if(b.google_ad_output==c)b.google_ad_output="html";if(Ka(b.google_ad_format)){var e=b.google_ad_format.match(/^(\d+)x(\d+)_.*/);if(e){b.google_ad_width=parseInt(e[1],10);b.google_ad_height=parseInt(e[2],10);b.google_ad_output="html"}}if(b.google_ad_format==c&&b.google_ad_output=="html")b.google_ad_format=b.google_ad_width+"x"+b.google_ad_height;Wa(b,document);if(b.google_num_slots_by_channel==
c)b.google_num_slots_by_channel=[];if(b.google_viewed_host_channels==c)b.google_viewed_host_channels=[];if(b.google_num_slots_by_client==c)b.google_num_slots_by_client=[];if(b.google_prev_ad_formats_by_region==c)b.google_prev_ad_formats_by_region=[];if(b.google_prev_ad_slotnames_by_region==c)b.google_prev_ad_slotnames_by_region=[];if(b.google_correlator==c)b.google_correlator=(new Date).getTime();if(b.google_adslot_loaded==c)b.google_adslot_loaded={};if(b.google_adContentsBySlot==c)b.google_adContentsBySlot=
{};if(b.google_flash_version==c)b.google_flash_version=ka();if(b.google_new_domain_checked==c)b.google_new_domain_checked=0;if(b.google_new_domain_enabled==c)b.google_new_domain_enabled=0;b.onerror=d}function la(a){if(a in Xa)return Xa[a];return Xa[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}
function Ya(a){var b={},c=a.split("?"),d=c[c.length-1].split("&");for(var e=0;e<d.length;e++){var f=d[e].split("=");if(f[0])try{b[f[0].toLowerCase()]=f.length>1?window.decodeURIComponent?decodeURIComponent(f[1].replace(/\+/g," ")):unescape(f[1]):""}catch(g){}}return b}function Za(){var a=window,b=Ya(document.URL);if(b.google_ad_override){a.google_ad_override=b.google_ad_override;a.google_adtest="on"}}function $a(a,b){for(var c in b)a["google_"+c]=b[c]}
function ab(a,b){if(!b)return a.location;return a.referrer}function bb(a,b){if(!b&&a.google_referrer_url==t)return"0";else if(b&&a.google_referrer_url==t)return"1";else if(!b&&a.google_referrer_url!=t)return"2";else if(b&&a.google_referrer_url!=t)return"3";return"4"}function cb(a,b,c,d){a.page_url=ab(c,d);a.page_location=t}function db(a,b,c,d){a.page_url=b.google_page_url;a.page_location=ab(c,d)||"EMPTY"}
function eb(a,b){var c={},d=Ua(a,b);c.iframing=bb(a,d);!!a.google_page_url?db(c,a,b,d):cb(c,a,b,d);c.last_modified_time=b.location==c.page_url?Date.parse(b.lastModified)/1000:t;c.referrer_url=d?a.google_referrer_url:a.google_page_url&&a.google_referrer_url?a.google_referrer_url:b.referrer;return c}function fb(a){var b={},c=a.URL.substring(a.URL.lastIndexOf("http"));b.iframing=t;b.page_url=c;b.page_location=a.location;b.last_modified_time=t;b.referrer_url=c;return b}
function Wa(a,b){var c;c=a.google_page_url==t&&gb[b.domain]?fb(b):eb(a,b);$a(a,c)}function Fa(a,b,c){if(a){var d=b.getElementById(a);if(d&&c&&c.length!=""){d.style.visibility="visible";d.innerHTML=c}}}
function hb(a){var b=a.google_page_location||a.google_page_url;if(!b)return m;b=b.toString();if(b.indexOf("http://")==0)b=b.substring(7,b.length);else if(b.indexOf("https://")==0)b=b.substring(8,b.length);var c=b.indexOf("/");if(c==-1)c=b.length;var d=b.substring(0,c),e=d.split("."),f=m;if(e.length>=3)f=e[e.length-3]in ib;if(e.length>=2)f=f||e[e.length-2]in ib;return f}
function jb(a,b,c){if(a.google_new_domain_checked==0){a.google_random_number=Math.random();if(a.google_random_number<c){var d="http://googleads.g.doubleclick.net/pagead/test_domain.js",e="script";b.write("<"+e+' src="'+d+'"></'+e+">");a.google_new_domain_checked=1}}}function Ma(a){var b="http://googleads.g.doubleclick.net",c="http://pagead2.googlesyndication.com";if(!hb(a)&&a.google_new_domain_enabled==1)return b;return c}var m=false,t=null,j=true,ba=document,n=navigator,h=window;var sa={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_region:"region",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",
google_color_url:"color_url",google_contents:"contents",google_country:"gl",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_gl:"gl",google_hints:"hints",
google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_referrer_url:"ref",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_targeting:"targeting",google_ui_features:"ui",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type",google_page_url:"url"},ta={google_ad_format:"format",google_ad_output:"output",google_ad_callback:"callback",google_ad_override:"google_ad_override",google_ad_slot:"slotname",google_analytics_uacct:"ga_wpids",
google_correlator:"correlator",google_cpa_choice:"cpa_choice",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_page_location:"loc",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"};ga.prototype.Xb=function(){};ga.prototype.Yb=function(){};ga.prototype.Wb=function(){};var p=t;s.prototype.fa="__gads=";s.prototype.Q="GoogleAdServingTest=";s.prototype.rb=function(){return this.I};s.prototype.setCookieInfo=function(a){this.C=a._cookies_[0];if(this.C!=t){this.I=this.C._value_;this.Vb()}};s.prototype.lb=function(a){var b=(new Date).valueOf(),c=new Date;c.setTime(b+a);return c};
s.prototype.kb=function(a){if(this.I!=t||!this.pa){ha("Skipping fetch cookie call");return}var b="script",c=document.domain,d="http://partner.googleadservices.com/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo&client="+ra(a)+"&domain="+ra(c);ha("Issuing a fetch cookie call with <a href='"+d+"'>"+d+"</a>");document.write("<"+b+' src="'+d+'"></'+b+">")};
s.prototype.gb=function(){document.cookie=this.Q+"Good";var a=this.Ea(this.Q),b=a=="Good";if(b){var c=this.lb(-1);document.cookie=this.Q+"; expires="+c.toGMTString()}return b};s.prototype.Kb=function(){var a=this.Ea(this.fa);a!=t?ha("Read first party cookie: "+a):ia("No first party cookie found");return a};s.prototype.Ea=function(a){var b=document.cookie,c=b.indexOf(a),d=t;if(c!=-1){var e=c+a.length,f=b.indexOf(";",e);if(f==-1)f=b.length;d=b.substring(e,f)}return d};
s.prototype.Vb=function(){if(this.C==t)ia("Skipping cookie creation: no cookie info");else if(this.I==t)ja("Skipping cookie creation: no cookie value");else{var a=new Date;a.setTime(1000*this.C._expires_);var b=this.C._domain_,c=this.fa+this.I+"; expires="+a.toGMTString()+"; path="+this.C._path_+"; domain=."+b;document.cookie=c;ha("Written cookie: "+c)}};var kb=kb||{},A=this,mb=function(a,b){var c=a.split("."),d=A,e;!(c[0]in d)&&d.execScript&&d.execScript("var "+c[0]);while(c.length&&(e=c.shift()))if(!c.length&&lb(b))d[e]=b;else d=d[e]?d[e]:(d[e]={})},nb=function(a,b){var c=a.split("."),d=b||A;for(var e;e=c.shift();)if(d[e])d=d[e];else return t;return d};
var B=function(a){var b=typeof a;if(b=="object")if(a){if(typeof a.length=="number"&&typeof a.splice!="undefined"&&!ob(a,"length"))return"array";if(typeof a.call!="undefined")return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b};
if(Object.prototype.propertyIsEnumerable)var ob=function(a,b){return Object.prototype.propertyIsEnumerable.call(a,b)};else ob=function(a,b){if(b in a)for(var c in a)if(c==b&&Object.prototype.hasOwnProperty.call(a,b))return j;return m};var lb=function(a){return typeof a!="undefined"};var pb=function(a){var b=B(a);return b=="array"||b=="object"&&typeof a.length=="number"};
var C=function(a){return B(a)=="function"},qb=function(a){var b=B(a);return b=="object"||b=="array"||b=="function"},wb=function(a){if(a.hasOwnProperty&&a.hasOwnProperty(ub)){var b=a[ub];if(b)return b}a[ub]||(a[ub]=++vb);return a[ub]},ub="closure_hashCode_",vb=0,D=function(a,b){var c=a.Zb;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);c&&d.unshift.apply(d,c);c=d}b=a.ac||b;a=a.$b||a;var e,f=b||A;e=c?function(){var g=Array.prototype.slice.call(arguments);g.unshift.apply(g,c);return a.apply(f,
g)}:function(){return a.apply(f,arguments)};e.Zb=c;e.ac=b;e.$b=a;return e},E=Date.now||function(){return(new Date).getTime()},xb=function(a,b){mb(a,b)},F=function(a,b){function c(){}c.prototype=b.prototype;a.q=b.prototype;a.prototype=new c;a.prototype.constructor=a};var yb=function(a,b){this.x=lb(a)?a:0;this.y=lb(b)?b:0};yb.prototype.toString=function(){return"("+this.x+", "+this.y+")"};var zb=function(a,b){this.width=a;this.height=b};zb.prototype.toString=function(){return"("+this.width+" x "+this.height+")"};zb.prototype.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};zb.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};zb.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
zb.prototype.scale=function(a){this.width*=a;this.height*=a;return this};var Ab=function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Gb=function(a,b){if(b)return a.replace(Bb,"&amp;").replace(Cb,"&lt;").replace(Db,"&gt;").replace(Eb,"&quot;");else{if(!Fb.test(a))return a;if(a.indexOf("&")!=-1)a=a.replace(Bb,"&amp;");if(a.indexOf("<")!=-1)a=a.replace(Cb,"&lt;");if(a.indexOf(">")!=-1)a=a.replace(Db,"&gt;");if(a.indexOf('"')!=-1)a=a.replace(Eb,"&quot;");return a}},Bb=/&/g,Cb=/</g,Db=/>/g,Eb=/\"/g,Fb=/[&<>\"]/,Hb=function(a,b){var c=b.length;for(var d=0;d<c;d++){var e=
c==1?b:b.charAt(d);if(a.charAt(0)==e&&a.charAt(a.length-1)==e)return a.substring(1,a.length-1)}return a},Jb=function(a,b){var c=0,d=Ab(String(a)).split("."),e=Ab(String(b)).split("."),f=Math.max(d.length,e.length);for(var g=0;c==0&&g<f;g++){var i=d[g]||"",k=e[g]||"",l=new RegExp("(\\d*)(\\D*)","g"),o=new RegExp("(\\d*)(\\D*)","g");do{var q=l.exec(i)||["","",""],r=o.exec(k)||["","",""];if(q[0].length==0&&r[0].length==0)break;var y=q[1].length==0?0:parseInt(q[1],10),M=r[1].length==0?0:parseInt(r[1],
10);c=Ib(y,M)||Ib(q[2].length==0,r[2].length==0)||Ib(q[2],r[2])}while(c==0)}return c},Ib=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};E();var Kb,Lb,Mb,Nb,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb=function(){var a=m,b=m,c=m,d=m,e=m,f=m,g=m,i=m,k=m,l="";if(A.navigator){var o=A.navigator,q=o.userAgent;a=q.indexOf("Opera")==0;b=!a&&q.indexOf("MSIE")!=-1;c=!a&&q.indexOf("WebKit")!=-1;k=c&&q.indexOf("Mobile")!=-1;d=!a&&!c&&o.product=="Gecko";e=d&&o.vendor=="Camino";var r,y;if(a)r=A.opera.version();else{if(d)y=/rv\:([^\);]+)(\)|;)/;else if(b)y=/MSIE\s+([^\);]+)(\)|;)/;else if(c)y=/WebKit\/(\S+)/;if(y){y.test(q);r=RegExp.$1}}l=o.platform||"";f=l.indexOf("Mac")!=
-1;g=l.indexOf("Win")!=-1;i=l.indexOf("Linux")!=-1}Kb=a;Lb=b;Mb=d;Nb=e;Ob=c;Pb=k;Qb=r;Rb=l;Sb=f;Tb=g;Ub=i};Vb();var Wb=Kb,G=Lb,Xb=Mb,H=Ob,Yb=Pb;var Zb=function(a,b,c){if(a.indexOf)return a.indexOf(b,c);if(Array.indexOf)return Array.indexOf(a,b,c);var d=c==t?0:c<0?Math.max(0,a.length+c):c;for(var e=d;e<a.length;e++)if(e in a&&a[e]===b)return e;return-1},$b=function(a,b,c){if(a.forEach)a.forEach(b,c);else if(Array.forEach)Array.forEach(a,b,c);else{var d=a.length,e=typeof a=="string"?a.split(""):a;for(var f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)}},ac=function(a,b){if(a.contains)return a.contains(b);return Zb(a,b)>-1},bc=function(a,b){var c=Zb(a,
b),d;if(d=c!=-1)Array.prototype.splice.call(a,c,1).length==1;return d};var cc=function(a){if(B(a)=="array")return a.concat();else{var b=[];for(var c=0,d=a.length;c<d;c++)b[c]=a[c];return b}};var dc=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};var ec;var Ha=function(){ec||(ec=new I);return ec},gc=function(a){return a?new I(fc(a)):Ha()};
var na=function(a){return typeof a=="string"?document.getElementById(a):a},Ga=na,ic=function(a,b){dc(b,function(c,d){if(d=="style")a.style.cssText=c;else if(d=="class")a.className=c;else if(d=="for")a.htmlFor=c;else if(d in hc)a.setAttribute(hc[d],c);else a[d]=c})},hc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",rowspan:"rowSpan",valign:"vAlign",height:"height",width:"width",usemap:"useMap",frameborder:"frameBorder"},jc=function(a){var b=a||A||window,c=b.document;if(H&&!(Jb(Qb,
"500")>=0)&&!Yb){if(typeof b.innerHeight=="undefined")b=window;var d=b.innerHeight,e=b.document.documentElement.scrollHeight;if(b==b.top)if(e<d)d-=15;return new zb(b.innerWidth,d)}var f=gc(c),g=f.nb()=="CSS1Compat"&&(!Wb||Wb&&Jb(Qb,"9.50")>=0)?c.documentElement:c.body;return new zb(g.clientWidth,g.clientHeight)},oa=function(){var a=Ha();return a.qa.apply(a,arguments)};var pa=function(a,b){a.appendChild(b)},Qa=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):t};
var kc=H&&Jb(Qb,"521")<=0,lc=function(a,b){if(typeof a.contains!="undefined"&&!kc&&b.nodeType==1)return a==b||a.contains(b);if(typeof a.compareDocumentPosition!="undefined")return a==b||Boolean(a.compareDocumentPosition(b)&16);while(b&&a!=b)b=b.parentNode;return b==a},fc=function(a){return a.nodeType==9?a:a.ownerDocument||a.document},mc=function(a){if(a&&typeof a.length=="number")if(qb(a))return typeof a.item=="function"||typeof a.item=="string";else if(C(a))return typeof a.item=="function";return m},
I=function(a){this.u=a||A.document||document};I.prototype.ob=function(){return this.u};I.prototype.qa=function(a,b){if(G&&b&&b.name)a="<"+a+' name="'+Gb(b.name)+'">';var c=this.createElement(a);b&&ic(c,b);if(arguments.length>2){function d(g){if(g)this.appendChild(c,typeof g=="string"?this.createTextNode(g):g)}for(var e=2;e<arguments.length;e++){var f=arguments[e];pb(f)&&!(qb(f)&&f.nodeType>0)?$b(mc(f)?cc(f):f,d,this):d.call(this,f)}}return c};I.prototype.createElement=function(a){return this.u.createElement(a)};
I.prototype.createTextNode=function(a){return this.u.createTextNode(a)};I.prototype.nb=function(){if(this.u.compatMode)return this.u.compatMode;if(H){var a=this.qa("div",{style:"position:absolute;width:0;height:0;width:1"}),b=a.style.width=="1px"?"BackCompat":"CSS1Compat";return this.u.compatMode=b}return"BackCompat"};
I.prototype.wa=function(){var a=this.u,b,c;if(!H&&a.compatMode=="CSS1Compat"){b=a.documentElement.scrollLeft;c=a.documentElement.scrollTop}else{b=a.body.scrollLeft;c=a.body.scrollTop}return new yb(b,c)};I.prototype.appendChild=pa;I.prototype.removeNode=Qa;I.prototype.contains=lc;var nc,oc=function(a,b){var c=fc(a);if(c.defaultView&&c.defaultView.getComputedStyle){var d=c.defaultView.getComputedStyle(a,"");if(d)return d[b]}return t};
var pc=function(a,b){return oc(a,b)||(a.currentStyle?a.currentStyle[b]:t)||a.style[b]},qc=function(a){var b;b=a?a.nodeType==9?a:fc(a):Ha().ob();if(G&&b.compatMode!="CSS1Compat")return b.body;return b.documentElement},rc=function(a){var b=fc(a),c=Xb&&b.getBoxObjectFor&&pc(a,"position")=="absolute"&&(a.style.top==""||a.style.left=="");if(typeof nc=="undefined")nc=Nb&&!(Jb(Qb,"1.8.0.11")>=0);var d=new yb(0,0),e=qc(b);if(a==e)return d;var f=t,g;if(a.getBoundingClientRect&&!c){g=a.getBoundingClientRect();
var i=gc(b).wa();d.x=g.left+i.x;d.y=g.top+i.y}else if(b.getBoxObjectFor&&!c&&!nc){g=b.getBoxObjectFor(a);var k=b.getBoxObjectFor(e);d.x=g.screenX-k.screenX;d.y=g.screenY-k.screenY}else{f=a;do{d.x+=f.offsetLeft;d.y+=f.offsetTop;if(H&&pc(f,"position")=="fixed"){d.x+=b.body.scrollLeft;d.y+=b.body.scrollTop;break}f=f.offsetParent}while(f&&f!=a);if(Wb||H&&pc(a,"position")=="absolute")d.y-=b.body.offsetTop;f=a.offsetParent;while(f&&f!=b.body){d.x-=f.scrollLeft;if(!Wb||f.tagName!="TR")d.y-=f.scrollTop;f=
f.offsetParent}}if(Xb&&a.getBoundingClientRect){var l=pc(a,"position");if(l=="static"||l=="relative"){d.x=Math.floor(d.x);d.y=Math.floor(d.y)}}return d},sc=function(a){var b=new yb;if(a.nodeType==1)if(a.getBoundingClientRect){var c=a.getBoundingClientRect();b.x=c.left;b.y=c.top}else{var d=gc(a).wa(),e=rc(a);b.x=e.x-d.x;b.y=e.y-d.y}else{b.x=a.clientX;b.y=a.clientY}return b};Xb&&!(Jb(Qb,"1.9")>=0);
var Oa=function(a){var b=fc(a),c="";if(b.createTextRange){var d=b.body.createTextRange();d.moveToElementText(a);c=d.queryCommandValue("FontName")}if(!c){c=pc(a,"fontFamily");if(Wb&&Ub)c=c.replace(/ \[[^\]]*\]/,"")}var e=c.split(",");if(e.length>1)c=e[0];return Hb(c,"\"'")};var J=function(){};J.prototype.va=m;J.prototype.dispose=function(){if(!this.va){this.b();this.va=j}};J.prototype.b=function(){};var tc=function(a){if(/^\s*$/.test(a))return m;var b=/\\["\\\/bfnrtu]/g,c=/"[^"\\\n\r\u2028\u2029\x00-\x1f\x7f-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,d=/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,e=/^[\],:{}\s\u2028\u2029]*$/;return e.test(a.replace(b,"@").replace(c,"]").replace(d,""))},uc=function(a){var b=String(a);if(typeof b.parseJSON=="function")return b.parseJSON();if(tc(a))try{return eval("("+a+")")}catch(c){}throw Error("Invalid JSON string: "+a);},vc=t,xc=function(a){vc||(vc=
new wc);return vc.serialize(a)},wc=function(){};wc.prototype.serialize=function(a){if(a!=t&&typeof a.toJSONString=="function")return a.toJSONString();var b=[];this.ca(a,b);return b.join("")};
wc.prototype.ca=function(a,b){switch(typeof a){case "string":this.Ia(a,b);break;case "number":this.Pb(a,b);break;case "boolean":b.push(a);break;case "undefined":b.push("null");break;case "object":if(a==t){b.push("null");break}if(B(a)=="array"){this.Ob(a,b);break}this.Qb(a,b);break;case "function":break;default:throw Error("Unknown type: "+typeof a);}};var yc={'"':'\\"',"\\":"\\\\","/":"\\/","\u0008":"\\b","\u000c":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\u000b":"\\u000b"};
wc.prototype.Ia=function(a,b){b.push('"',a.replace(/[\\\"\x00-\x1f\x80-\uffff]/g,function(c){if(c in yc)return yc[c];var d=c.charCodeAt(0),e="\\u";if(d<16)e+="000";else if(d<256)e+="00";else if(d<4096)e+="0";return yc[c]=e+d.toString(16)}),'"')};wc.prototype.Pb=function(a,b){b.push(isFinite(a)&&!isNaN(a)?a:"null")};wc.prototype.Ob=function(a,b){var c=a.length;b.push("[");var d="";for(var e=0;e<c;e++){b.push(d);this.ca(a[e],b);d=","}b.push("]")};
wc.prototype.Qb=function(a,b){b.push("{");var c="";for(var d in a){var e=a[d];if(typeof e!="function"){b.push(c);this.Ia(d,b);b.push(":");this.ca(e,b);c=","}}b.push("}")};var Cc=function(a,b){try{var c=Ac(a),d="Message: "+Gb(c.message)+'\nUrl: <a href="view-source:'+c.fileName+'" target="_new">'+c.fileName+"</a>\nLine: "+c.lineNumber+"\n\nBrowser stack:\n"+Gb(c.stack+"-> ")+"[end]\n\nJS stack traversal:\n"+Gb(Bc(b)+"-> ");return d}catch(e){return"Exception trying to expose exception! You win, we lose. "+e}},Ac=function(a){var b=nb("document.location.href");return typeof a=="string"?{message:a,name:"Unknown error",lineNumber:"Not available",fileName:b,stack:"Not available"}:
!a.lineNumber||!a.fileName||!a.stack?{message:a.message,name:a.name,lineNumber:a.lineNumber||a.line||"Not available",fileName:a.fileName||a.sourceURL||b,stack:a.stack||"Not available"}:a},Bc=function(a){return Dc(a||arguments.callee.caller,[])},Dc=function(a,b){var c=[];if(ac(b,a))c.push("[...circular reference...]");else if(a&&b.length<50){c.push(Ec(a)+"(");var d=a.arguments;for(var e=0;e<d.length;e++){e>0&&c.push(", ");var f,g=d[e];switch(typeof g){case "object":f=g?"object":"null";break;case "string":f=
g;break;case "number":f=String(g);break;case "boolean":f=g?"true":"false";break;case "function":f=Ec(g);f=f?f:"[fn]";break;case "undefined":default:f=typeof g;break}if(f.length>40)f=f.substr(0,40)+"...";c.push(f)}b.push(a);c.push(")\n");try{c.push(Dc(a.caller,b))}catch(i){c.push("[exception trying to get caller]\n")}}else a?c.push("[...long stack...]"):c.push("[end]");return c.join("")},Ec=function(a){var b=String(a);if(!Fc[b]){var c=/function ([^\(]+)/.exec(b);if(c){var d=c[1];Fc[b]=d}else Fc[b]=
"[Anonymous]"}return Fc[b]},Fc={};var K=function(a,b,c,d,e){this.nc=typeof e=="number"?e:Gc++;this.oc=d||E();this.p=a;this.gc=b;this.kc=c};K.prototype.ib=t;K.prototype.hb=t;var Gc=0;K.prototype.Rb=function(a){this.ib=a};K.prototype.Sb=function(a){this.hb=a};K.prototype.U=function(){return this.p};K.prototype.da=function(a){this.p=a};K.prototype.xa=function(){return this.gc};var L=function(a){this.Db=a;this.Y=t;this.cc={};this.ya=[]};L.prototype.p=t;var N=function(a,b){this.name=a;this.value=b};N.prototype.toString=function(){return this.name};new N("OFF",Infinity);new N("SHOUT",1200);var Hc=new N("SEVERE",1000),Ic=new N("WARNING",900),Jc=new N("INFO",800),Kc=new N("CONFIG",700),Lc=new N("FINE",500);new N("FINER",400);var Mc=new N("FINEST",300);new N("ALL",0);L.prototype.V=function(){return this.Db};L.prototype.ga=function(a){this.ya.push(a)};L.prototype.pb=function(){return this.Y};
L.prototype.da=function(a){this.p=a};L.prototype.U=function(){return this.p};L.prototype.X=function(a){if(this.p)return a.value>=this.p.value;if(this.Y)return this.Y.X(a);return m};L.prototype.log=function(a,b,c){if(!this.X(a))return;var d=new K(a,String(b),this.Db);if(c){d.Rb(c);d.Sb(Cc(c,arguments.callee.caller))}this.wb(d)};L.prototype.severe=function(a,b){this.log(Hc,a,b)};L.prototype.warning=function(a,b){this.log(Ic,a,b)};L.prototype.info=function(a,b){this.log(Jc,a,b)};
L.prototype.fine=function(a,b){this.log(Lc,a,b)};L.prototype.finest=function(a,b){this.log(Mc,a,b)};L.prototype.wb=function(a){if(!this.X(a.U()))return;var b=this;while(b){b.Sa(a);b=b.pb()}};L.prototype.Sa=function(a){for(var b=0;b<this.ya.length;b++)this.ya[b](a)};L.prototype.Tb=function(a){this.Y=a};L.prototype.Pa=function(a,b){this.cc[a]=b};
var Nc={},Oc=t,Pc=function(){if(!Oc){Oc=new L("");Nc[""]=Oc;Oc.da(Kc)}},Rc=function(a){Pc();return a in Nc?Nc[a]:Qc(a)},Qc=function(a){var b=new L(a),c=a.split("."),d=c[c.length-1];c.length=c.length-1;var e=c.join("."),f=Rc(e);f.Pa(d,b);b.Tb(f);Nc[a]=b;return b};var Sc={"1":"NativeMessagingTransport","2":"FrameElementMethodTransport","3":"IframeRelayTransport","4":"IframePollingTransport","5":"FlashTransport","6":"NixTransport"},O="SETUP_ACK",Tc={},Vc=function(a,b){var c=b||Uc,d=c.length,e="";while(a-- >0)e+=c.charAt(Math.floor(Math.random()*d));return e},Uc="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789",P=Rc("goog.net.xpc");var Q=function(){};F(Q,J);Q.prototype.g=0;Q.prototype.V=function(){return Sc[this.g]||""};var R=function(a){this.a=a;this.N=[];this.fc=D(this.eb,this)};F(R,Q);R.prototype.g=2;R.prototype.n=0;R.prototype.J=1;R.prototype.Z=m;R.prototype.Ub=0;R.prototype.connect=function(){this.aa=window.parent==this.a.f?this.J:this.n;if(this.aa==this.n){this.j=this.a.w;this.j.XPC_toOuter=D(this.za,this)}else this.ja()};
R.prototype.ja=function(){var a=j;try{if(!this.j)this.j=window.frameElement;if(this.j&&this.j.XPC_toOuter){this.Ca=this.j.XPC_toOuter;this.j.XPC_toOuter.XPC_toInner=D(this.za,this);a=m;this.send("tp",O);this.a.m()}}catch(b){P.severe("exception caught while attempting setup: "+b)}if(a){if(!this.Qa)this.Qa=D(this.ja,this);window.setTimeout(this.Qa,100)}};
R.prototype.H=function(a){if(this.aa==this.n&&!this.a.k()&&a==O){this.Ca=this.j.XPC_toOuter.XPC_toInner;this.a.m()}else throw Error("Got unexpected transport message.");};R.prototype.za=function(a,b){if(!this.Z&&this.N.length==0)this.a.o(a,b);else{this.N.push({serviceName:a,payload:b});if(this.N.length==1)this.Ub=window.setTimeout(this.fc,1)}};R.prototype.eb=function(){while(this.N.length){var a=this.N.shift();this.a.o(a.serviceName,a.payload)}};
R.prototype.send=function(a,b){this.Z=j;this.Ca(a,b);this.Z=m};R.prototype.b=function(){R.q.b.call(this);this.Ca=t;this.j=t};var S=function(a){this.a=a;this.O=this.a.c.ppu;this.jc=this.a.c.lpu;this.ba=[]},Wc,Xc,Yc;F(S,Q);S.prototype.g=4;S.prototype.P=0;S.prototype.B=m;S.prototype.connect=function(){this.Za()};S.prototype.Za=function(){P.fine("constructing sender frames.");var a=this.a.name+"_msg";this.zb=this.oa(a);this.Cb=window.frames[a];a=this.a.name+"_ack";this.Ma=this.oa(a);this.Oa=window.frames[a];this.la()};
S.prototype.oa=function(a){var b=Ha().createElement("iframe"),c=b.style;c.position="absolute";c.top="-10px";c.left="10px";c.width="1px";c.height="1px";b.id=b.name=a;b.src=this.O+"#INITIAL";document.body.appendChild(b);return b};
S.prototype.la=function(){this.Va&&window.clearTimeout(this.Va);if(this.Aa("msg")&&this.Aa("ack")){P.fine("foreign frames present");this.Ab=new Zc(this,this.a.f.frames[this.a.name+"_msg"],D(this.Hb,this));this.Na=new Zc(this,this.a.f.frames[this.a.name+"_ack"],D(this.Gb,this));this.na()}else{P.finest("foreign frames not (yet) present");if(!this.Ua)this.Ua=D(this.la,this);this.Va=window.setTimeout(this.Ua,100)}};
S.prototype.Aa=function(a){try{var b=this.a.f.frames[this.a.name+"_"+a];if(!b||b.location.href.indexOf(this.jc)!=0)return m}catch(c){return m}return j};
S.prototype.na=function(){var a=this.a.f.frames;if(a[this.a.name+"_ack"]&&a[this.a.name+"_msg"]){this.Bb=new $c(this.O,this.Cb);this.R=new $c(this.O,this.Oa);P.fine("local frames ready");window.setTimeout(D(function(){this.Bb.send("SETUP");this.mc=j;this.B=j;P.fine("SETUP sent")},this),100)}else{if(!this.Wa)this.Wa=D(this.na,this);window.setTimeout(this.Wa,100);P.fine("local frames not (yet) present")}};
S.prototype.ma=function(){if(this.Ha&&this.Jb){this.a.m();if(this.D){P.fine("delivering queued messages ("+this.D.length+")");for(var a=0,b;a<this.D.length;a++){b=this.D[a];this.a.o(b.service,b.payload)}delete this.D}}else P.finest("checking if connected: ack sent:"+this.Ha+", ack rcvd: "+this.Jb)};
S.prototype.Hb=function(a){P.finest("msg received: "+a);if(a=="SETUP"){if(!this.R)return;this.R.send(O);P.finest("SETUP_ACK sent");this.Ha=j;this.ma()}else if(this.a.k()||this.Ha){var b=a.indexOf("|"),c=a.substring(0,b),d=a.substring(b+1);b=c.indexOf(",");if(b==-1){var e=c;this.R.send("ACK:"+e);this.ta(d)}else{var e=c.substring(0,b);this.R.send("ACK:"+e);var f=c.substring(b+1).split("/");f[0]=parseInt(f[0],10);f[1]=parseInt(f[1],10);if(f[0]==1)this.Da=[];this.Da.push(d);if(f[0]==f[1]){this.ta(this.Da.join(""));
delete this.Da}}}else P.warning("received msg, but channel is not connected")};S.prototype.Gb=function(a){P.finest("ack received: "+a);if(a==O){this.B=m;this.Jb=j;this.ma()}else if(this.a.k()){if(!this.B){P.warning("got unexpected ack");return}var b=parseInt(a.split(":")[1],10);if(b==this.P){this.B=m;this.Ga()}else P.warning("got ack with wrong sequence")}else P.warning("received ack, but channel not connected")};
S.prototype.Ga=function(){if(this.B||!this.ba.length)return;var a=this.ba.shift();++this.P;this.Bb.send(this.P+a);P.finest("msg sent: "+this.P+a);this.B=j};S.prototype.ta=function(a){var b=a.indexOf(":"),c=a.substr(0,b),d=a.substring(b+1);if(this.a.k())this.a.o(c,d);else{(this.D||(this.D=[])).push({service:c,payload:d});P.finest("queued delivery")}};S.prototype.K=3800;
S.prototype.send=function(a,b){var c=a+":"+b;if(!G||b.length<=this.K)this.ba.push("|"+c);else{var d=b.length,e=Math.ceil(d/this.K),f=0,g=1;while(f<d){this.ba.push(","+g+"/"+e+"|"+c.substr(f,this.K));g++;f+=this.K}}this.Ga()};S.prototype.b=function(){S.q.b.call(this);var a=ad;bc(a,this.Ab);bc(a,this.Na);this.Ab=this.Na=t;Qa(this.zb);Qa(this.Ma);this.zb=this.Ma=t;this.Cb=this.Oa=t};
var ad=[],cd=function(){var a=m;try{for(var b=0,c=ad.length;b<c;b++)a=a||ad[b].receive()}catch(d){P.info("receive_() failed: "+d);ad[b].d.a.Eb();if(!ad.length)return}var e=E();if(a)Wc=e;var f=e-Wc<1000?10:100;Xc=window.setTimeout(bd,f)},bd=D(cd,S),dd=function(){P.fine("starting receive-timer");Wc=E();Xc&&window.clearTimeout(Xc);Xc=window.setTimeout(bd,10)},$c=function(a,b){this.O=a;this.Nb=b;this.sa=0};
$c.prototype.send=function(a){this.sa=++this.sa%2;var b=this.O+"#"+this.sa+encodeURIComponent(a);try{if(H)this.Nb.location.href=b;else this.Nb.location.replace(b)}catch(c){P.severe("sending failed",c)}Yc=E()};var Zc=function(a,b,c){this.d=a;this.Ib=b;this.bc=c;this.cb=this.Ib.location.href.split("#")[0]+"#INITIAL";ad.push(this);dd()};Zc.prototype.receive=function(){var a=this.Ib.location.href;if(a!=this.cb){this.cb=a;var b=a.split("#")[1];if(b){b=b.substr(1);this.bc(decodeURIComponent(b))}return j}else return m};var T=function(a,b){J.call(this);this.xb=b;this.v=[];this.ab(a)};F(T,J);T.prototype.S=t;T.prototype.T=t;T.prototype.G=function(a){this.S=a};T.prototype.Ka=function(a){this.T=a};T.prototype.i=function(){if(this.v.length)return this.v.pop();return this.ra()};T.prototype.A=function(a){this.v.length<this.xb?this.v.push(a):this.ua(a)};T.prototype.ab=function(a){if(a>this.xb)throw Error("[goog.structs.SimplePool] Initial cannot be greater than max");for(var b=0;b<a;b++)this.v.push(this.ra())};
T.prototype.ra=function(){return this.S?this.S():{}};T.prototype.ua=function(a){if(this.T)this.T(a);else if(C(a.dispose))a.dispose();else for(var b in a)delete a[b]};T.prototype.b=function(){T.q.b.call(this);var a=this.v;while(a.length)this.ua(a.pop());delete this.v};var ed=function(a,b){this.type=a;this.target=b;this.currentTarget=this.target};F(ed,J);ed.prototype.b=function(){delete this.type;delete this.target;delete this.currentTarget};ed.prototype.F=m;ed.prototype.$=j;ed.prototype.stopPropagation=function(){this.F=j};ed.prototype.preventDefault=function(){this.$=m};var U=function(a,b){a&&this.init(a,b)};F(U,ed);U.prototype.type=t;U.prototype.target=t;U.prototype.relatedTarget=t;U.prototype.offsetX=0;U.prototype.offsetY=0;U.prototype.clientX=0;U.prototype.clientY=0;U.prototype.screenX=0;U.prototype.screenY=0;U.prototype.button=0;U.prototype.keyCode=0;U.prototype.charCode=0;U.prototype.ctrlKey=m;U.prototype.altKey=m;U.prototype.shiftKey=m;U.prototype.metaKey=m;U.prototype.h=t;
U.prototype.init=function(a,b){this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;this.relatedTarget=a.relatedTarget?a.relatedTarget:this.type=="mouseover"?a.fromElement:this.type=="mouseout"?a.toElement:t;this.offsetX=typeof a.layerX=="number"?a.layerX:a.offsetX;this.offsetY=typeof a.layerY=="number"?a.layerY:a.offsetY;this.clientX=typeof a.clientX=="number"?a.clientX:a.pageX;this.clientY=typeof a.clientY=="number"?a.clientY:a.pageY;this.screenX=a.screenX||0;this.screenY=a.screenY||
0;this.button=a.button;this.keyCode=a.keyCode||0;this.charCode=a.charCode||(this.type=="keypress"?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.h=a;delete this.$;delete this.F};U.prototype.stopPropagation=function(){this.F=j;if(this.h.stopPropagation)this.h.stopPropagation();else this.h.cancelBubble=j};
U.prototype.preventDefault=function(){this.$=m;if(this.h.preventDefault)this.h.preventDefault();else{this.h.returnValue=m;try{this.h.keyCode=-1}catch(a){}}};U.prototype.mb=function(){return this.h};U.prototype.b=function(){U.q.b.call(this);this.h=t};var V=function(){},fd=0;V.prototype.W=t;V.prototype.listener=t;V.prototype.proxy=t;V.prototype.src=t;V.prototype.type=t;V.prototype.capture=t;V.prototype.handler=t;V.prototype.key=0;V.prototype.removed=m;V.prototype.ka=m;V.prototype.init=function(a,b,c,d,e,f){if(C(a))this.W=j;else if(a&&a.handleEvent&&C(a.handleEvent))this.W=m;else throw Error("Invalid listener argument");this.listener=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!e;this.handler=f;this.ka=m;this.key=++fd;this.removed=m};
V.prototype.handleEvent=function(a){if(this.W)return this.listener.call(this.handler||this.src,a);return this.listener.handleEvent.call(this.listener,a)};var gd={},W={},hd={},id=new T(0,600);id.G(function(){return{t:0}});id.Ka(function(a){a.t=0});var jd=new T(0,600);jd.G(function(){return[]});jd.Ka(function(a){a.length=0;delete a.M;delete a.Ba});var kd=new T(0,600);kd.G(function(){var a=function(b){return ld.call(a.src,a.key,b)};return a});var md=function(){return new V},nd=new T(0,600);nd.G(md);
var od=function(){return new U},pd=function(){var a=t;if(G){a=new T(0,600);a.G(od)}return a},qd=pd(),rd="on",sd={},td=function(a,b,c,d,e){if(b)if(B(b)=="array"){for(var f=0;f<b.length;f++)td(a,b[f],c,d,e);return t}else{var g=!!d,i=W;b in i||(i[b]=id.i());i=i[b];if(!(g in i)){i[g]=id.i();i.t++}i=i[g];var k=wb(a),l,o;if(i[k]){l=i[k];for(var f=0;f<l.length;f++){o=l[f];if(o.listener==c&&o.handler==e){if(o.removed)break;return l[f].key}}}else{l=i[k]=jd.i();i.t++}var q=kd.i();q.src=a;o=nd.i();o.init(c,
q,a,b,g,e);var r=o.key;q.key=r;l.push(o);gd[r]=o;hd[k]||(hd[k]=jd.i());hd[k].push(o);if(a.addEventListener){if(a==A||!a.ec)a.addEventListener(b,q,g)}else a.attachEvent(ud(b),q);return r}else throw Error("Invalid event type");},vd=function(a,b,c,d,e){if(B(b)=="array"){for(var f=0;f<b.length;f++)vd(a,b[f],c,d,e);return t}var g=!!d,i=wd(a,b,g);if(!i)return m;for(var f=0;f<i.length;f++)if(i[f].listener==c&&i[f].capture==g&&i[f].handler==e)return xd(i[f].key);return m},xd=function(a){if(!gd[a])return m;
var b=gd[a];if(b.removed)return m;var c=b.src,d=b.type,e=b.proxy,f=b.capture;if(c.removeEventListener){if(c==A||!c.ec)c.removeEventListener(d,e,f)}else c.detachEvent&&c.detachEvent(ud(d),e);var g=wb(c),i=W[d][f][g];if(hd[g]){var k=hd[g];bc(k,b);k.length==0&&delete hd[g]}b.removed=j;i.Ba=j;yd(d,f,g,i);delete gd[a];return j},yd=function(a,b,c,d){if(!d.M)if(d.Ba){for(var e=0,f=0;e<d.length;e++){if(d[e].removed){nd.A(d[e]);continue}if(e!=f)d[f]=d[e];f++}d.length=f;d.Ba=m;if(f==0){jd.A(d);delete W[a][b][c];
W[a][b].t--;if(W[a][b].t==0){id.A(W[a][b]);delete W[a][b];W[a].t--}if(W[a].t==0){id.A(W[a]);delete W[a]}}}},wd=function(a,b,c){var d=W;if(b in d){d=d[b];if(c in d){d=d[c];var e=wb(a);if(d[e])return d[e]}}return t},ud=function(a){if(a in sd)return sd[a];return sd[a]=rd+a},Ad=function(a,b,c,d){var e=1,f=W;if(b in f){f=f[b];if(c in f){f=f[c];var g=wb(a);if(f[g]){var i=f[g];if(i.M)i.M++;else i.M=1;try{var k=i.length;for(var l=0;l<k;l++){var o=i[l];if(o&&!o.removed)e&=zd(o,d)!==m}}finally{i.M--;yd(b,c,
g,i)}}}}return Boolean(e)},zd=function(a,b){var c=a.handleEvent(b);a.ka&&xd(a.key);return c},ld=function(a,b){if(!gd[a])return j;var c=gd[a],d=c.type,e=W;if(!(d in e))return j;e=e[d];var f;if(G){var g=b||nb("window.event"),i=j in e;if(i){if(g.keyCode<0||g.returnValue!=undefined)return j;Bd(g)}wb(c.src);var k=qd.i();k.init(g,this);f=j;try{if(i){var l=jd.i();for(var o=k.currentTarget;o;o=o.parentNode)l.push(o);for(var q=l.length-1;!k.F&&q>=0;q--){k.currentTarget=l[q];f&=Ad(l[q],d,j,k)}for(var q=0;!k.F&&
q<l.length;q++){k.currentTarget=l[q];f&=Ad(l[q],d,m,k)}}else f=zd(c,k)}finally{if(l){l.length=0;jd.A(l)}k.dispose();qd.A(k)}return f}var r=new U(b,this);try{f=zd(c,r)}finally{r.dispose()}return f},Bd=function(a){var b=m;if(a.keyCode==0)try{a.keyCode=-1;return}catch(c){b=j}if(b||a.returnValue==undefined)a.returnValue=j};var X=function(a){this.a=a;this.ic=this.a.c.pru;this.Fb=this.a.c.ifrid;H&&Cd()};F(X,Q);if(H){var Dd=[],Ed=0,Cd=function(){Ed||(Ed=window.setTimeout(function(){Fd()},1000))},Fd=function(a){var b=E(),c=a||3000;while(Dd.length&&b-Dd[0].timestamp>=c){var d=Dd.shift().iframeElement;Qa(d);P.finest("iframe removed")}Ed=window.setTimeout(Gd,1000)},Gd=function(){Fd()}}X.prototype.g=3;X.prototype.connect=function(){this.send("tp","SETUP")};
X.prototype.H=function(a){if(a=="SETUP"){this.send("tp",O);this.a.m()}else a==O&&this.a.m()};
X.prototype.send=function(a,b){if(G){var c=document.createElement("div");c.innerHTML='<iframe onload="this.xpcOnload()"></iframe>';var d=c.childNodes[0];d.xpcOnload=Hd}else{var d=document.createElement("iframe");H?Dd.push({timestamp:E(),iframeElement:d}):td(d,"load",Hd)}var e=d.style;e.visibility="hidden";e.width=d.style.height="0px";e.position="absolute";var f=this.ic;f+="#"+this.a.name;if(this.Fb)f+=","+this.Fb;f+="|"+a+":"+encodeURIComponent(b);d.src=f;document.body.appendChild(d);P.finest("msg sent: "+
f)};var Hd=function(){P.finest("iframe-load");Qa(this);this.xpcOnload=t};window.xpcRelay=function(a,b){var c=b.indexOf(":"),d=b.substring(0,c),e=b.substring(c+1);Tc[a].o(d,decodeURIComponent(e))};X.prototype.b=function(){X.q.b.call(this);H&&Fd(0)};var Y=function(a){this.a=a};F(Y,Q);Y.prototype.g=1;var Id=m,Kd=function(){if(!Id){td(C(window.postMessage)?window:document,"message",Jd,m,Y);Id=j}},Jd=function(a){var b=a.mb().data,c=b.indexOf("|"),d=b.indexOf(":");if(c==-1||d==-1)return;var e=b.substring(0,c),f=b.substring(c+1,d),g=b.substring(d+1),i=Tc[e];i?i.o(f,g):P.severe('error delivering msg: no channel named "'+e+'"')};Y.prototype.H=function(a){switch(a){case "SETUP":this.send("tp",O);case O:this.a.m();break}};
Y.prototype.connect=function(){Kd();this.send("tp","SETUP")};Y.prototype.send=function(a,b){var c=this.a.f;if(!c){P.fine("send(): window not ready");return}var d=C(window.postMessage)?c:c.document;this.send=function(e,f){d.postMessage(this.a.name+"|"+e+":"+f,"*")};this.send(a,b)};Y.prototype.b=function(){Y.q.b.call(this);vd(document,"message",this.lc,m,this)};var Z=function(a){this.a=a;this.Ra=a.at||"";this.Mb=a.rat||"";Ld();this[Md]=this.L;this[Nd]=this.$a};F(Z,Q);
var Od="GRPC____NIXVBS_wrapper",Pd="GRPC____NIXVBS_get_wrapper",Md="GRPC____NIXJS_handle_message",Nd="GRPC____NIXJS_create_channel",Qd="GRPC____NIXVBS_container",Ld=function(){if(window.nix_setup_complete)return;var a="Class "+Od+"\n Private m_Transport\nPrivate m_Auth\nPublic Sub SetTransport(transport)\nIf isEmpty(m_Transport) Then\nSet m_Transport = transport\nEnd If\nEnd Sub\nPublic Sub SetAuth(auth)\nIf isEmpty(m_Auth) Then\nm_Auth = auth\nEnd If\nEnd Sub\nPublic Function GetAuthToken()\n GetAuthToken = m_Auth\nEnd Function\nPublic Sub SendMessage(service, payload)\n Call m_Transport."+Md+
"(service, payload)\nEnd Sub\nPublic Sub CreateChannel(channel)\n Call m_Transport."+Nd+"(channel)\nEnd Sub\nPublic Sub "+Qd+"()\n End Sub\nEnd Class\n Function "+Pd+"(transport, auth)\nDim wrap\nSet wrap = New "+Od+"\nwrap.SetTransport transport\nwrap.SetAuth auth\nSet "+Pd+" = wrap\nEnd Function";try{window.execScript(a,"vbscript");window.nix_setup_complete=j}catch(b){P.severe("exception caught while attempting global setup: "+b)}};Z.prototype.g=6;Z.prototype.n=0;Z.prototype.J=1;Z.prototype.z=m;
Z.prototype.l=t;Z.prototype.connect=function(){this.aa=window.parent==this.a.f?this.J:this.n;this.aa==this.n?this.ia():this.ha()};Z.prototype.ia=function(){if(this.z)return;var a=this.a.w;try{a.contentWindow.opener=window[Pd](this,this.Ra);this.z=j}catch(b){P.severe("exception caught while attempting setup: "+b)}this.z||window.setTimeout(D(this.ia,this),100)};
Z.prototype.ha=function(){if(this.z)return;try{var a=window.opener;if(a&&Qd in a){this.l=a;var b=this.l.GetAuthToken();if(b!=this.Mb){P.severe("Invalid auth token from other party");return}this.l.CreateChannel(window[Pd](this,this.Ra));this.z=j;this.a.m()}}catch(c){P.severe("exception caught while attempting setup: "+c);return}this.z||window.setTimeout(D(this.ha,this),100)};
Z.prototype.$a=function(a){if(typeof a!="unknown"||!(Qd in a))P.severe("Invalid NIX channel given to createChannel_");this.l=a;var b=this.l.GetAuthToken();if(b!=this.Mb){P.severe("Invalid auth token from other party");return}this.a.m()};Z.prototype.L=function(a,b){function c(){this.a.o(a,b)}window.setTimeout(D(c,this),1)};Z.prototype.send=function(a,b){typeof this.l!=="unknown"&&P.severe("NIX channel not connected");this.l.SendMessage(a,b)};Z.prototype.b=function(){Z.q.b.call(this);this.l=t};var $=function(a){this.c=a;this.name=this.c.cn||Vc(10);this.Ja={};Tc[this.name]=this;td(window,"unload",Rd);P.info("CrossPageChannel created: "+this.name)};F($,J);$.prototype.d=t;$.prototype.ea=1;$.prototype.k=function(){return this.ea==2};$.prototype.f=t;$.prototype.w=t;$.prototype.La=function(a){this.f=a};
$.prototype.bb=function(){if(this.d)return;if(!this.c.tp)if(C(document.postMessage)||C(window.postMessage))this.c.tp=1;else if(Xb)this.c.tp=2;else if(G&&this.c.pru)this.c.tp=3;else if(G)this.c.tp=6;else if(this.c.lpu&&this.c.ppu)this.c.tp=4;switch(this.c.tp){case 1:this.d=new Y(this);break;case 6:this.d=new Z(this);break;case 2:this.d=new R(this);break;case 3:this.d=new X(this);break;case 4:this.d=new S(this);break}if(this.d)P.info("Transport created: "+this.d.V());else throw Error("CrossPageChannel: No suitable transport found!");
};$.prototype.db=m;$.prototype.Ya=m;$.prototype.connect=function(a){this.dc=a;if(this.db){this.Ya=j;return}if(this.c.ifrid)this.w=na(this.c.ifrid);if(this.w){var b=this.w.contentWindow;b||(b=window.frames[this.c.ifrid]);this.La(b)}if(!this.f)if(window==top)throw Error("CrossPageChannel: Can't connect, peer window-object not set.");else this.La(window.parent);this.bb();this.d.connect()};
$.prototype.close=function(){if(!this.k())return;this.ea=3;this.d.dispose();this.d=t;P.info('Channel "'+this.name+'" closed')};$.prototype.m=function(){if(this.k())return;this.ea=2;P.info('Channel "'+this.name+'" connected');this.dc()};$.prototype.Eb=function(){P.info("Transport Error");this.close()};$.prototype.Lb=function(a,b,c){this.Ja[a]={name:a,callback:b,jsonEncoded:!!c}};
$.prototype.send=function(a,b){if(!this.k()){P.severe("Can't send. Channel not connected.");return}if(this.f.closed){P.severe("Peer has disappeared.");this.close();return}if(qb(b))b=xc(b);this.d.send(a,b)};$.prototype.o=function(a,b){if(!a||a=="tp")this.d.H(b);else if(this.k()){var c=this.Ja[a];if(c){if(c.jsonEncoded)try{b=uc(b)}catch(d){P.info("Error parsing JSON-encoded payload.");return}c.callback(b)}else P.info('CrossPageChannel::deliver_(): No such service: "'+a+'" (payload: '+b+")")}else P.info("CrossPageChannel::deliver_(): Not connected.")};
$.prototype.b=function(){$.q.b.call(this);this.close();this.f=t;this.w=t;delete this.Ja;Tc[this.name]=t};var Rd=function(){for(var a in Tc){var b=Tc[a];b&&b.dispose()}};var Sd=Rc("ExpansionUtil");Sd.ga(function(a){ma("API: "+a.xa(),"console")});var Td=Rc("goog.net.xpc");Td.ga(function(a){ma("XPC: "+a.xa(),"console")});var Ud=function(a){var b=a||document.location.protocol+"//"+document.location.host;return b+"/favicon.ico"};var z=function(a,b){this.s=b.width;this.r=b.height;this.Ta=Vc(10);this.hc=this.qb(a,document);this.e=b;this.e.src=this.yb(document,a);this.vb(this.sb(document))};z.prototype.yb=function(a,b){return b+(b.indexOf("?")==-1?"?":"&")+"w="+this.s+"&h="+this.r+"&xpc="+this.Ta+"&p="+escape(a.location.protocol+"//"+a.location.host)};z.prototype.sb=function(){var a={};a.ifrid=this.e.id;a.pu=this.e.src;a.cn=this.Ta;a.ppu=Ud(this.hc);a.lpu=Ud();return a};
z.prototype.vb=function(a){this.a=new $(a);this.a.Lb("expandable_ad",D(this.L,this));this.a.connect(function(){})};z.prototype.qb=function(a,b){var c=a.indexOf("//"),d=c>0,e=d?a.substring(0,c):b.location.protocol,f=d?a.substring(c+2):b.location.host,g=f.indexOf("/");if(d&&g>0)f=f.substring(0,g);return e+"//"+f};z.prototype.L=function(a){Sd.info("handleMessage("+a+")");var b=a.split("_"),c=b[0];if(c=="expand")this.ub(b);else c=="collapse"?this.tb():Sd.info("ExpandableAdSlot.callback(): unknown message received")};
z.prototype.Fa=function(a){this.a.send("expandable_ad",a)};z.prototype.ub=function(a){var b,c;for(var d in a){var e=a[d].charAt(0);if(e=="w")b=parseInt(a[d].substring(1),10);else if(e=="h")c=parseInt(a[d].substring(1),10)}var f=this.fb(b,c);this.jb(b,c,f);this.Fa("ok_expand_w"+b+"_h"+c+"_d"+f)};z.prototype.tb=function(){this.Xa();this.Fa("ok_collapse_w"+this.s+"_h"+this.r)};
z.prototype.Xa=function(){this.e.style.width=this.s+"px";this.e.style.height=this.r+"px";this.e.style.left="0";this.e.style.top="0";this.e.style.zIndex=999};z.prototype.jb=function(a,b,c){this.e.style.position="absolute";this.e.style.width=a+"px";this.e.style.height=b+"px";this.e.style.zIndex=9999;if(a>this.s&&(c==0||c==3))this.e.style.left="-"+(a-this.s)+"px";if(b>this.r&&(c==1||c==0))this.e.style.top="-"+(b-this.r)+"px"};
z.prototype.fb=function(a,b){var c=sc(this.e),d=jc(window),e=a-this.s,f=b-this.r,g=c.y,i=f>g,k=d.height-(c.y+this.r),l=i||k>=g,o=c.x,q=e>o,r=d.width-(c.x+this.s),y=q||r>=o,M=0;if(l&&y)M=2;else if(l&&!y)M=3;else if(!l&&y)M=1;else if(!l&&!y)M=0;return M};xb("ExpandableAdSlot",z);var Ca=0;var Xa={};var gb={};gb["ad.yieldmanager.com"]=j;window.google_render_ad=Pa;var ib={google:1,googlegroups:1,gmail:1,googlemail:1,orkut:1,googleimages:1,googleprint:1};Za();Va(Ta);jb(window,document,0.0010);var Vd="script";document.write("<"+Vd+"> window.google_render_ad(); </"+Vd+">");
})()
