//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_es_CO.properties
define( {
            "Common.updates.errorMessage": "Se encontró un errror al tratar de actualizar.<br>Puede intentar más tarde o visitar {0}.",
            "XMLPersistenceManager.save.error.encode": "<html>Error codificando el archivo.<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Error decodificando el archivo.<br>{0}</html>",
            "Common.softwareAgreement.decline": "Salir",
            "Common.statistics.host_os_name": "Nombre del sistema operativo:",
            "Common.statistics.user_total_sessions": "Número total de veces que se han ejecutado todas las simulaciones:",
            "Common.statistics.host_java_version_major": "Versión de Java (mayor):",
            "FileChooser.openDialogTitleText": "Abrir",
            "Common.statistics.host_java_version_maintenance": "Versión de Java (mantenimiento):",
            "FileChooser.lookInLabelText": "Mirar en:",
            "Common.choice.cancel": "Cancele",
            "Common.updates.seePreferences": "Vaya a: Archivo ->Preferencias para cambiar sus preferencias.",
            "Common.About.CreditsDialog.software-development": "Desarrollo de Software",
            "Common.About.JavaVersion": "Versión de Java:",
            "ColorChooser.resetText": "Reinicio",
            "wavelength.ir": "IR",
            "Common.About.CreditsDialog.design-team": "Equipo de Diseño",
            "Common.statistics.sim_total_sessions": "Número total de veces que se ha ejecutado ésta simulación:",
            "wavelength.uv": "UV",
            "XMLPersistenceManager.save.title": "Guardar la configuración",
            "XMLPersistenceManager.load.error.contents": "El archivo está corrupto o no fué creado por esta simulación.",
            "Common.statistics.details.title": "Información",
            "Common.statistics.sim_dev_version": "Versión de la simulación (desarrollo):",
            "FileChooser.saveInLabelText": "Guardar en:",
            "Common.statistics.sim_name": "Nombre de la simulación:",
            "Save.confirm.message": "<html>El archivo seleccionado ya existe.<br> ¿Desea re-escribirlo?</html>",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "Equipo de desarrollo de PhET",
            "Common.statistics.sim_deployment": "Tipo de instalación:",
            "Common.FileMenu.Save": "Guardar la configuración",
            "FileChooser.acceptAllFileFilterText": "Todos los archivos (*.*)",
            "Common.ModelSlider.Minimum": "Mínimo",
            "Common.FileMenu.Preferences": "Preferencias",
            "Common.FileMenu.Load": "Cargar la configuración",
            "Common.updates.downloadingSimJar": "bajando archivo JAR de la simulación...",
            "ColorChooser.swatchesRecentText": "Reciente",
            "Common.updates.updateAvailable": "Actualización disponible",
            "Common.statistics.host_locale_language": "Idioma del equipo:",
            "Common.clear": "Borre",
            "FileChooser.filesOfTypeLabelText": "Archivos del tipo:",
            "Common.ErrorDialog.detailsTitle": "Detalles de error",
            "Common.HelpMenu.MegaHelp": "MegaAyuda",
            "Common.ClockControlPanel.Step": "Paso",
            "Common.statistics.sim_revision": "Versión de la simulación (revisión)",
            "Common.choice.yes": "Sí",
            "Common.FileMenu.Title": "Archivo",
            "Common.value_units": "{0} {1}",
            "Common.statistics.sim_dev": "¿Es una versión para desarrolladores?:",
            "Common.updates.installer.message": "<html>Su instalación de PhET Offline está fechada {0}.<br>Hay una actualización disponible, fechada {1}.<br><br>¿Quiere conseguir el último instalador de Phet Offline?</html>",
            "Common.updates.updateNow": "¡Actualizar yá!",
            "Common.record": "Grabar",
            "Common.About.CreditsDialog.Title": "Créditos",
            "Common.updates.error.internetConnection": "<html>No puedo conectarme a {0},<br>por favor revise su conexión a Internet.</html>",
            "Common.time.fast": "rápido",
            "XMLPersistenceManager.load.error.message": "<html>Error leyendo el archivo.<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Máximo",
            "Common.OptionsMenu": "Opciones",
            "Common.ClockControlPanel.Restart": "Reiniciar",
            "Common.statistics.sim_version_timestamp": "Versión de la simulación (sello de tiempo):",
            "Common.updates.installer.yes": "¡Sí!",
            "Common.phetInstaller": "Instalador del sitio PhET offline",
            "Common.HelpMenu.About": "Acerca...",
            "Common.ModelSlider.OutOfRange": "Valor fuera de rango",
            "ColorChooser.previewText": "Vista preliminar",
            "Common.BasicPhetPanel.Title": "Devolver",
            "Common.HelpPanel.HideHelp": "Ocultar ayuda",
            "Common.statistics.host_os_arch": "Tipo de procesador:",
            "Common.preferences.title": "Preferencias",
            "Common.ModelSlider.YouEntered": "Usted escribió",
            "Common.About.BuildDate": "Fecha de construcción",
            "Common.statistics.sim_project": "Nombre del proyecto:",
            "Common.title.message": "Mensaje",
            "Common.updates.downloadingBootstrap": "bajando actualizador de bootstrap...",
            "Common.title.error": "Error",
            "Common.FileMenu.Exit": "Salir",
            "Common.statistics.sim_major_version": "Versión de la simulación (mayor):",
            "Common.updates.askMeLater": "Pregúnteme después",
            "chart-time-control.go": "¡Siga!",
            "Common.confirm.clear.graphs": "¿Está seguro que quiere borrar los gráficos?",
            "Common.updates.progressDialogMessage": "Actualizando \"{0}\" a versión {1}",
            "Common.updates.installer.more": "Dime más...",
            "XMLPersistenceManager.title.error": "Error",
            "ControlPanel.button.resetAll": "Reiniciar todo",
            "Common.About.AgreementButton": "Acuerdo de licencia",
            "Common.ErrorDialog.detailsButton": "Detalles...",
            "Common.updates.errorMissingJar": "<html>Esta actualización no puede realizarse.<br>No se pudo localizar el archivo JAR: {0}.<br>Solicite ayuda a su administrador del sistema.<br></html>",
            "Common.preferences.privacy": "Privacidad",
            "Common.HelpMenu.AboutTitle": "Acerca",
            "Common.statistics.sim_locale_country": "País:",
            "Common.HelpPanel.ShowHelp": "¡Ayuda!",
            "Common.statistics.sim_distribution_tag": "Versión de la simulación (distribución):",
            "Common.statistics.description": "PhET se ofrece gratuitamente gracias a  donantes<br>que nos solicitan recoger una cantidad mínima<br> de <a href=\"{0}\">información</a> anónima para documentar el uso<br> de las simulaciones de PhET y atender mejor<br> las necesidades de nuestros usuarios. ",
            "Common.softwareAgreement.message": "En todas las simulaciones de PhET recogemos una<br> cantidad mínima de <a href=\"{0}\">información</a> anónima cada vez<br> que la simulación arranca (Ej. Versión de la simulación,<br> sistema operativo). Se puede deshabilitar el envío de ésta<br> información en cualquier momento mediante el menú<br> Archivo->Preferencias.<br><br>Marcando \"Acepto y continúe\", usted acepta el acuerdo<br> de licencia de software, incluyendo nuestra política de<br> privacidad, para ésta y toda simulación de PhET que ejecute.<br>\n(Detalles <a href=\"{1}\">aquí</a>).",
            "Common.choice.ok": "OK",
            "Common.About.Version": "Versión",
            "Common.ErrorDialog.contactPhet": "Si este problema persiste, envíe detalles a {0}",
            "Common.About.CreditsDialog.lead-design": "Diseñador Jefe",
            "Common.statistics.user_preference_file_creation_time": "Sello de tiempo de la creación del archivo de preferencias:",
            "Common.updates.errorWritePermissions": "<html>Esta actualización no puede realizarse.<br>Usted no tiene permiso de escritura en {0}.<br>Solicite ayuda a su administrador del sistema.<br></html>",
            "Common.choice.no": "No",
            "Common.About.WebLink": "Visite la página de PhET",
            "Common.About.OSVersion": "Versión del Sist. Operativo:",
            "Common.title.warning": "Advertencia",
            "Common.updates.versionComparison": "<html>La versión actual de \"{0}\" es {1}.<br>Hay una versión ({2}) actualizada. </html>",
            "Common.statistics.sim_locale_language": "Idioma:",
            "Common.statistics.user_installation_timestamp": "Sello de tiempo de la intalación de PhET:",
            "Common.statistics.message_version": "Versión del mensaje:",
            "Common.ModelSlider.Description": "Valor ilegal",
            "Common.updates.installer.moreMessage": "<html>Mantener actualizada su instalación de Phet offline<br>le asegura acceso a las nuevas simulaciones<br>y materiales suplementarios.<br><br>Si decide consegur la última versión, un navegador<br> abrirá el sitio Phet, de donde puede bajar<br>el instalador de PhET Offline.</html>",
            "ControlPanel.message.confirmResetAll": "¿Reiniciar todas las variables?",
            "Common.HelpMenu.Help": "Ayuda",
            "Common.updates.errorNotAJar": "{0} no es un archivo JAR.",
            "Common.updates.automaticallyCheck": "Buscar actualizaciones automáticamente",
            "Common.sim.speed": "...velocidad de la simu...",
            "Common.updates.checkForSimUpdate": "Buscar actualizaciones de la simulacion...",
            "XMLPersistenceManager.save.confirm.message": "<html>El archivo seleccionado ya existe.<br>¿Desea reemplazarlo?</html>",
            "FileChooser.newFolderErrorText": "Error creando nueva carpeta ",
            "Common.updates.skipThisUpdate": "Brínquese esta versión",
            "Common.About.CreditsButton": "Créditos...",
            "FileChooser.saveDialogTitleText": "Guardar",
            "XMLPersistenceManager.load.title": "Cargar la configuración",
            "Common.updates.checkForInstallerUpdate": "Buscar una actualizacion del instalador de Sitio Phet Offline...",
            "Common.updates.progressDialogTitle": "Actualizando",
            "Common.HelpMenu.Title": "Ayuda",
            "FileChooser.fileNameLabelText": "Nombre de archivo:",
            "Common.softwareAgreement.title": "Acuerdo de licencia",
            "Common.statistics.host_java_version_minor": "Versión de Java (menor):",
            "Common.About.CreditsDialog.interviews": "Entrevistas",
            "Common.About.Distribution": "Distribución:",
            "Common.statistics.host_java_webstart_version": "Versión de Java Web Start:",
            "XMLPersistenceManager.save.error.message": "<html>Error escribiendo al archivo.<br>{0}</html>",
            "FileChooser.openButtonText": "Abrir",
            "Common.statistics.details.description": "<html>La información mostrada será enviada a PhET cada vez que la simulación arranque.</html>",
            "ColorChooser.sampleText": "Ejemplo de texto",
            "Common.statistics.host_os_version": "Versión del sistema operativo:",
            "Common.title.confirm": "Confirmar",
            "Common.BasicPhetPanel.LogoToolTip": "Inhabilite el ",
            "Common.statistics.host_java_timezone": "Franja horaria:",
            "Common.time.slow": "lento",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.softwareAgreement.accept": "Acepte y continúe",
            "Common.ClockControlPanel.Rewind": "Devolver",
            "Common.updates.updateToDate": "Al día",
            "Common.ClockControlPanel.Pause": "Pausa",
            "PhetApplication.StartupDialog.message": "\"{0}\" se está iniciando",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Este programa usa los siguientes programas desarrollados por terceros",
            "XMLPersistenceManager.message.notAConfigFile": "Éste archivo no contiene una configuración para ésta simulación.",
            "Common.preferences.updates": "Actualizaciones",
            "Common.statistics.enabled": "Permita el envío de información a PhET",
            "Common.StopwatchPanel.stop": "Pare",
            "Common.HelpPanel.MegaHelp": "MegaAyuda...",
            "Common.statistics.host_locale_country": "País del equipo:",
            "Common.StopwatchPanel.reset": "Reiniciar",
            "Common.playback": "Reproducir",
            "Common.statistics.sim_minor_version": "Versión de la simulación (menor):",
            "Common.updates.tryIt": "Ensaye la versión nueva antes de actualizar.",
            "Common.choice.close": "Cierre",
            "Common.ClockControlPanel.Play": "Reproducir",
            "Common.statistics.sim_type": "Tipo de simulación:",
            "FileChooser.saveButtonText": "Guardar",
            "Common.rewind": "Devolver",
            "Common.updates.youHaveCurrent": "Usted tiene la última actualización ({0}) de {1}",
            "Common.StopwatchPanel.start": "Arranque",
            "Common.statistics.sim_sessions_since": "Número de veces que ésta simulación se ha ejecutado desde la última vez que se conectó:",
            "Common.statistics.host_java_vendor": "Fabricante de Java:",
            "charts.show-graphs": "Mostrar gráficos:",
            "Common.statistics.message_type": "Tipo de mensaje:"
        } );