//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_ca.properties
define( {
            "Common.clear": "Netejar",
            "Common.choice.ok": "OK",
            "Common.WhiteBackground": "Fons blanc",
            "Common.title.confirm": "Confirmar",
            "Common.StopwatchPanel.start": "Començar",
            "PiccoloPhet.VelocitySensorNode.unknown": "?",
            "ColorChooser.sampleText": "Mostra Text Mostra Text",
            "Common.softwareAgreement.decline": "Sortir",
            "Common.StopwatchPanel.stop": "Aturar",
            "Common.time.slow": "lent",
            "Common.FileMenu.Exit": "Exit",
            "Common.HelpMenu.Help": "Ajuda",
            "PiccoloPhet.VelocitySensorNode.speed": "Velocitat",
            "Common.choice.no": "No",
            "Common.choice.close": "Tancar",
            "Common.HelpPanel.HideHelp": "Amagar ajuda",
            "Common.StopwatchPanel.reset": "Restaurar",
            "Common.ClockControlPanel.Restart": "Tornar a començar",
            "Common.HelpMenu.AboutTitle": "Sobre",
            "Common.ModelSlider.Description": "Valor il·legal",
            "Common.ModelSlider.Minimum": "Mínim",
            "Common.FileMenu.Title": "Fitxer",
            "Common.title.warning": "Advertència",
            "Common.softwareAgreement.accept": "Acceptar i Continuar",
            "Common.updates.askMeLater": "Pregunta'm més tard",
            "Common.title.message": "Missatge",
            "ColorChooser.previewText": "Previsualitzar",
            "XMLPersistenceManager.save.title": "Guardar configuració",
            "Common.FileMenu.Save": "Guardar configuració...",
            "Common.FileMenu.Preferences": "Preferències...",
            "ControlPanel.button.resetAll": "Restaurar tot",
            "Common.ModelSlider.Maximum": "Màxim",
            "Common.ClockControlPanel.Play": "Executar",
            "wavelength.ir": "IR",
            "Common.ClockControlPanel.StepBack": "Tornar enrera",
            "Common.ClockControlPanel.Step": "Pas",
            "wavelength.uv": "UV",
            "Common.HelpMenu.About": "Sobre...",
            "Common.choice.yes": "Sí",
            "XMLPersistenceManager.title.error": "Error",
            "Common.choice.cancel": "Cancel·lar",
            "Common.OptionsMenu": "Opcions",
            "Common.time.fast": "ràpid",
            "ColorChooser.resetText": "Restaurar",
            "Common.ClockControlPanel.Pause": "Pausa",
            "Common.ModelSlider.OutOfRange": "Valor fora de rang",
            "chart-time-control.go": "Endavant!",
            "Common.HelpMenu.Title": "Ajuda",
            "Common.title.error": "Error",
            "Common.HelpPanel.ShowHelp": "Ajuda!"
        } );