//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_mk.properties
define( {
            "Common.updates.errorMessage": "Појавена е грешка при преземањето на надградбата<br>Ве молиме пробајте подоцна или посетете ја {0}.",
            "XMLPersistenceManager.save.error.encode": "<html>Грешка при кодирањето:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Грешка при декодирањето:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "д",
            "Common.softwareAgreement.decline": "излез",
            "Common.statistics.host_os_name": "Име на Оперативниот систем:",
            "Common.statistics.user_total_sessions": "Вкупен број на вклучувања на симулацијата:",
            "Common.statistics.host_java_version_major": "Јава верзија (главна)",
            "FileChooser.openDialogTitleText": "Отвори",
            "Common.statistics.host_java_version_maintenance": "Јава верзија (одржување)",
            "FileChooser.lookInLabelText": "Погледни во:",
            "Common.choice.cancel": "Откажи",
            "Common.updates.seePreferences": "Оди на Документ-->Опции за да промените вашите поставувања.",
            "Common.About.CreditsDialog.software-development": "Развој на софтвер",
            "Common.About.JavaVersion": "Јава верзија:",
            "ColorChooser.resetText": "Ресетирај",
            "Common.About.CreditsDialog.design-team": "Развоен тим",
            "Common.statistics.sim_total_sessions": "Вкупен број на вклучувања на симулацијата:",
            "Common.FileMenu.PreferencesMnemonic": "о",
            "XMLPersistenceManager.save.title": "Сними ја конфигурацијата",
            "XMLPersistenceManager.load.error.contents": "Документот е оштетен или не е креиран од оваа симулација",
            "Common.statistics.details.title": "Информации",
            "Common.statistics.sim_dev_version": "Верзија на симулацијата (раз):",
            "FileChooser.saveInLabelText": "Сними во:",
            "Common.statistics.sim_name": "Име на симулацијата:",
            "Save.confirm.message": "<html>Документот кој го избравте веќе постои.<br>Сакате ли да го замените со овој?</html>",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "PhET Развоен тим",
            "Common.statistics.sim_deployment": "Тип на распоредување:",
            "Common.FileMenu.Save": "Сними конфигурација...",
            "ColorChooser.hsbSaturationText": "С",
            "FileChooser.acceptAllFileFilterText": "Сите документи (*.*)",
            "ColorChooser.hsbNameText": "Нијанси",
            "Common.ModelSlider.Minimum": "Минимум",
            "Common.FileMenu.Preferences": "Опции...",
            "Common.FileMenu.Load": "Вчитај конфигурација...",
            "Common.updates.downloadingSimJar": "преземање на JAR симулацијата...",
            "ColorChooser.swatchesRecentText": "Моментално:",
            "Common.updates.updateAvailable": "Постои надградба",
            "Common.statistics.host_locale_language": "Домашен јазик",
            "Common.clear": "Исчисти",
            "FileChooser.filesOfTypeLabelText": "Тип на документ:",
            "Common.ErrorDialog.detailsTitle": "Детали за грешката",
            "Common.HelpMenu.MegaHelp": "Мега момош...",
            "Common.ClockControlPanel.Step": "Чекор",
            "Common.statistics.sim_revision": "Верзија на симулацијата (ревидирана)",
            "Common.choice.yes": "Да",
            "Common.FileMenu.Title": "Документ",
            "Common.statistics.sim_dev": "Дали е ова развојна верзија?:",
            "Common.updates.installer.message": "<html>Вашата  PhET инсталација е со дата {0}.<br>Постои понова верзија со дата {1}.<br><br>Сакате ли да ја преземете последната PhET инсталација?</html>",
            "Common.updates.updateNow": "Надгради сега!",
            "Common.record": "Сними",
            "Common.About.CreditsDialog.Title": "Информации",
            "Common.updates.error.internetConnection": "<html>Неможам да се поврзам {0},<br>проверете ја вашата интернет врска.</html>",
            "Common.time.fast": "брзо",
            "XMLPersistenceManager.load.error.message": "<html>Грешка при читањето:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Максимум",
            "Common.OptionsMenu": "Опции",
            "Common.ClockControlPanel.Restart": "Рестартирај",
            "Common.statistics.sim_version_timestamp": "Верзија на симулацијата (временски маркер)",
            "Common.updates.installer.yes": "Да!",
            "Common.HelpMenu.About": "За програмот...",
            "Common.ModelSlider.OutOfRange": "Вредност надвор од опсегот",
            "ColorChooser.previewText": "Преглед",
            "Common.BasicPhetPanel.Title": "Врати се",
            "Common.HelpPanel.HideHelp": "Скриј помош",
            "Common.statistics.host_os_arch": "Тип на процесор:",
            "Common.preferences.title": "Опции",
            "ColorChooser.hsbRedText": "Ц",
            "ColorChooser.hsbBlueText": "Б",
            "Common.ModelSlider.YouEntered": "Вие влеговте",
            "Common.About.BuildDate": "Датум на изработка:",
            "Common.FileMenu.ExitMnemonic": "и",
            "Common.statistics.sim_project": "Име на проектот:",
            "Common.title.message": "Порака",
            "Common.updates.downloadingBootstrap": "почеток на преземање на надградбата...",
            "Common.title.error": "Грешка",
            "Common.FileMenu.Exit": "Излез",
            "Common.statistics.sim_major_version": "Верзија на симулацијата (главна):",
            "Common.updates.askMeLater": "Прашај ме подоцна",
            "chart-time-control.go": "Почни!",
            "Common.HelpMenu.HelpMnemonic": "п",
            "Common.confirm.clear.graphs": "Дали сигурно сакате да го исбришете графикот?",
            "ColorChooser.swatchesNameText": "Палета на бои",
            "Common.updates.progressDialogMessage": "Надградување на \"{0}\" на верзија {1}",
            "Common.updates.installer.more": "Кажи ми повеќе...",
            "XMLPersistenceManager.title.error": "Грешка",
            "ColorChooser.hsbHueText": "Н",
            "ControlPanel.button.resetAll": "Ресетирај се",
            "Common.About.AgreementButton": "Софтверска согласност...",
            "Common.FileMenu.Load.mnemonic": "в",
            "Common.ErrorDialog.detailsButton": "Детали...",
            "Common.updates.errorMissingJar": "<html>Надградувањето неможе да се направи.<br>Неможе да се најде JAR документот: {0}.<br>Ве молиме контактирајте го вашиот<br>веб администратор за помош.<br></html>",
            "Common.preferences.privacy": "Приватност",
            "Common.HelpMenu.AboutTitle": "За програмот",
            "Common.statistics.sim_locale_country": "Држава:",
            "ColorChooser.hsbGreenText": "З",
            "ColorChooser.rgbGreenText": "Зелено",
            "Common.HelpPanel.ShowHelp": "Помош!",
            "Common.statistics.sim_distribution_tag": "Верзија на симулацијата (дистрибуција):",
            "Common.statistics.description": "<a href='{0}'>PhET</a> е слободно достапен преку грантови кои<br>бараат од нас да ги собереме минималените анонимни<br> информации за да се документира употребата на<br>PhET симулациите за подобрување на услугите на<br>нашите корисници и  ажурирање потребите.",
            "Common.softwareAgreement.message": "Во сите PhET симулации, ние собираме минимална<br>количина на анонимни <a href='{0}'>информации</a> секогаш кога<br>симулацијата стартува (на пр., верзија на симулацијата,<br>оперативен систем).<br>Вие можете да го оневозможте оваа испраќање на информации <br>во секое време преку копчето Документ-->Опции.<br>Со кликнување на \"Согласност и продолжи\", вие ја прифаќате<br>PhET Софтверската согласност, вклучувајќи го договорот за<br>приватност, за оваа и секоја PhET симулација која ја стартувате.<br>(За детали, <a href='{1}'>кликнете овде</a>).",
            "Common.choice.ok": "Добро",
            "Common.About.Version": "Верзија",
            "Common.ErrorDialog.contactPhet": "Ако проблемот останува, испрати ги деталите на {0}",
            "Common.About.CreditsDialog.lead-design": "Водечки развој",
            "Common.OptionsMenu.mnemonic": "о",
            "Common.statistics.user_preference_file_creation_time": "Податоци за времето на создавање:",
            "Common.HelpMenu.AboutMnemonic": "з",
            "Common.updates.errorWritePermissions": "<html>Надградувањето неможе да се направи.<br>Немате дозвола за снимање на {0}.<br>Ве молиме контактирајте го вашиот<br>веб администратор за помош.<br></html>",
            "ColorChooser.hsbBrightnessText": "Б",
            "Common.choice.no": "Не",
            "Common.About.WebLink": "Посети ја PhET вебстраната",
            "Common.About.OSVersion": "Верзија на ОС:",
            "Common.title.warning": "Предупредување",
            "Common.updates.versionComparison": "<html>Вашата верзија на \"{0}\" е {1}.<br>Поновата верзија ({2}) е достапна.</html>",
            "Common.statistics.sim_locale_language": "Јазик:",
            "Common.statistics.user_installation_timestamp": "PhET временски маркер на инсталацијата",
            "Common.statistics.message_version": "Верзија на пораката:",
            "Common.ModelSlider.Description": "Грешка вредност.",
            "Common.updates.installer.moreMessage": "<html>Најновиот PhET Offline Website Installation ви овозможува пристап<br>до најновите PhET симулации и додатни материјали.<br><br>Ако изберете да ја преземете најновата верзија,веб прелистувачот<br>ќе ја отвори PhET вебстраната, каде мозжете да го преземете<br>PhET Offline Website Installer.</html>",
            "ControlPanel.message.confirmResetAll": "Ресетирај ги сите поставувања?",
            "Common.HelpMenu.Help": "Помош",
            "Common.updates.errorNotAJar": "{0} не е JAR документ.",
            "Common.updates.automaticallyCheck": "Автоматски проверувај дали има надградби",
            "Common.sim.speed": "...брзина на симулација...",
            "Common.updates.checkForSimUpdate": "Провери надградба на симулацијата...",
            "XMLPersistenceManager.save.confirm.message": "<html>Документот кој го избравте веќе постои.<br>Сакате ли да го замените со овој?</html>",
            "FileChooser.newFolderErrorText": "Грешка при креирање на нов фолдер",
            "Common.updates.skipThisUpdate": "Скокни ја оваа верзија",
            "Common.About.CreditsButton": "Информации...",
            "Common.FileMenu.Save.mnemonic": "с",
            "FileChooser.saveDialogTitleText": "Сними",
            "XMLPersistenceManager.load.title": "Вчитување на конфигурација",
            "Common.updates.checkForInstallerUpdate": "Провери го PhET Offline Website Installer за надградби...",
            "timeseries.control.panel.playback": "Повторување",
            "Common.updates.progressDialogTitle": "Надградување",
            "Common.HelpMenu.Title": "Помош",
            "FileChooser.fileNameLabelText": "Име на документ:",
            "Common.softwareAgreement.title": "Софтверската согласност",
            "Common.statistics.host_java_version_minor": "Јава верзија (споредна)",
            "Common.HelpMenu.TitleMnemonic": "п",
            "Common.About.CreditsDialog.interviews": "Интервјуа",
            "Common.About.Distribution": "Дистрибуција:",
            "Common.statistics.host_java_webstart_version": "Јава Web Start верзија",
            "XMLPersistenceManager.save.error.message": "<html>Грешка при снимањето:<br>{0}</html>",
            "FileChooser.openButtonText": "Отвори",
            "ColorChooser.sampleText": "Пробен текст Пробен текст",
            "Common.statistics.details.description": "<html>Информацијата прикажана подолу ќе биде испратена до PhET кога  ќе започне симулацијата</html>",
            "Common.statistics.host_os_version": "Верзија на опративниот систем:",
            "Common.title.confirm": "Потврди",
            "Common.BasicPhetPanel.LogoToolTip": "Оневозможи Цела рамка",
            "Common.statistics.host_java_timezone": "Временска зона:",
            "Common.time.slow": "бавно",
            "Common.ClockControlPanel.Rewind": "Врати назад",
            "Common.softwareAgreement.accept": "Прифати и продолжи",
            "Common.updates.updateToDate": "Надградено",
            "Common.ClockControlPanel.Pause": "Пауза",
            "PhetApplication.StartupDialog.message": "\"{0}\" се вклучува",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Овој програм користи софтвер од трети лица.",
            "XMLPersistenceManager.message.notAConfigFile": "Овој документ не содржи конфигурација за оваа симулација.",
            "Common.preferences.updates": "Надградби",
            "Common.HelpMenu.MegaHelpMnemonic": "м",
            "Common.statistics.enabled": "Овозможи испраќање на информации до PhET",
            "Common.StopwatchPanel.stop": "Запри",
            "Common.HelpPanel.MegaHelp": "Мега момош...",
            "Common.statistics.host_locale_country": "Домашна земја:",
            "Common.StopwatchPanel.reset": "Ресетирај",
            "Common.playback": "Повторување",
            "Common.statistics.sim_minor_version": "Верзија на симулацијата (споредна):",
            "Common.updates.tryIt": "Пробај ја новата верзија пред надградбата.",
            "ColorChooser.rgbBlueText": "Сино",
            "Common.choice.close": "Затвори",
            "Common.ClockControlPanel.Play": "Почни",
            "Common.statistics.sim_type": "Вкупен број на вклучувања на симулацијата:",
            "FileChooser.saveButtonText": "Сними",
            "Common.rewind": "Врати назад",
            "Common.StopwatchPanel.start": "Почни",
            "Common.updates.youHaveCurrent": "Вие ја имате најновата верзија ({0}) од {1}.",
            "Common.statistics.sim_sessions_since": "Број на вклучувања на симулацијата од последниот онлајн:",
            "Common.statistics.host_java_vendor": "Јава производител:",
            "charts.show-graphs": "Прикажи графикЧ",
            "Common.statistics.message_type": "Тип на порака:"
        } );