//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_zh_TW.properties
define( {
            "Games.label.level": "難度: {0}",
            "Common.updates.errorMessage": "在嘗試更新時發生錯誤。<br>請等一下再試, 或連線至 {0}。",
            "XMLPersistenceManager.save.error.encode": "<html>錯誤編碼的檔案: <br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>錯誤解碼的檔案:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "f",
            "Common.softwareAgreement.decline": "離開",
            "Common.statistics.host_os_name": "作業系統名稱:",
            "Common.statistics.user_total_sessions": "所有模擬程式執行時間的總和:",
            "Common.statistics.host_java_version_major": "Java 版本 (major):",
            "FileChooser.openDialogTitleText": "開啟",
            "Common.statistics.host_java_version_maintenance": "Java 版本 (maintenance):",
            "FileChooser.lookInLabelText": "參閱:",
            "Common.choice.cancel": "取消",
            "Common.updates.seePreferences": "使用 \"檔案\"->\"偏好\" 更改您的設定",
            "Common.About.CreditsDialog.software-development": "軟體開發",
            "Common.About.JavaVersion": "Java 版本:",
            "ColorChooser.resetText": "重設",
            "wavelength.ir": "紅外線",
            "Common.About.CreditsDialog.design-team": "設計團隊",
            "Common.statistics.sim_total_sessions": "這個模擬執行所用的時間:",
            "Games.title.gameSettings": "遊戲設定",
            "Common.FileMenu.PreferencesMnemonic": "p",
            "wavelength.uv": "紫外線",
            "XMLPersistenceManager.save.title": "儲存設定值",
            "XMLPersistenceManager.load.error.contents": "檔案己損壞或未被模擬程式產生.",
            "Common.statistics.details.title": "資訊",
            "Common.statistics.sim_dev_version": "模擬程式版本 (開發中版):",
            "FileChooser.saveInLabelText": "儲存於:",
            "Common.statistics.sim_name": "模擬程式名:",
            "Save.confirm.message": "<html>您所選擇的檔案己經存在. <br>您要用現在的存檔覆蓋它嗎?</html>",
            "Games.label.score": "得分: {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "PhET 開發團隊",
            "Games.button.start": "開始",
            "Common.statistics.sim_deployment": "開發種類:",
            "Common.FileMenu.Save": "儲存設定...",
            "ColorChooser.hsbSaturationText": "S",
            "Games.radioButton.on": "開啟",
            "FileChooser.acceptAllFileFilterText": "所有檔案 (*.*)",
            "ColorChooser.hsbNameText": "HSB",
            "Common.ModelSlider.Minimum": "極小值",
            "Common.FileMenu.Preferences": "偏好設定...",
            "Common.FileMenu.Load": "讀取設定...",
            "Common.updates.downloadingSimJar": "正在下載模擬程式的 JAR 檔...",
            "Games.radioButton.off": "關閉",
            "ColorChooser.swatchesRecentText": "最近的：",
            "Common.updates.updateAvailable": "有更新版本可用",
            "Common.statistics.host_locale_language": "主要語言:",
            "Common.clear": "清除",
            "Games.title.gameOver": "遊戲結束",
            "FileChooser.filesOfTypeLabelText": "檔案類型:",
            "Common.ErrorDialog.detailsTitle": "錯誤細節",
            "Common.HelpMenu.MegaHelp": "仔細說明...",
            "Common.ClockControlPanel.Step": "前進一格",
            "Common.statistics.sim_revision": "模擬程式版本 (修正版):",
            "Common.choice.yes": "是",
            "Common.FileMenu.Title": "檔案",
            "Common.value_units": "{0} {1}",
            "Common.statistics.sim_dev": "這是開發者使用的版本嗎?",
            "Common.updates.installer.message": "<html>您安裝日期為 {0} PhET 離線安裝程式。.<br>現在有一個日期為 {1} 的更新版本. <br><br>您是否想取得最新的 PhET 離線安裝程式呢?</html>",
            "Common.updates.updateNow": "現在更新!",
            "Common.record": "錄音(影)",
            "Common.About.CreditsDialog.Title": "成員名單",
            "Common.updates.error.internetConnection": "<html>無法連上 {0},<br>請檢查您的網路是否正常.</html>",
            "Common.time.fast": "快",
            "XMLPersistenceManager.load.error.message": "<html>檔案讀取錯誤:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "極大值",
            "Common.OptionsMenu": "選擇",
            "Common.ClockControlPanel.Restart": "重新開始",
            "Common.statistics.sim_version_timestamp": "模擬程式版本 (timestamp):",
            "Common.updates.installer.yes": "確定!",
            "Common.phetInstaller": "PhET 離線安裝程式",
            "Common.HelpMenu.About": "關於...",
            "Common.ModelSlider.OutOfRange": "超出範圍的值",
            "ColorChooser.previewText": "預覽",
            "Common.BasicPhetPanel.Title": "返回",
            "Common.HelpPanel.HideHelp": "隱藏說明",
            "Common.statistics.host_os_arch": "CPU 的種類:",
            "Common.preferences.title": "偏好",
            "Games.button.newGame": "新遊戲",
            "ColorChooser.hsbRedText": "R",
            "ColorChooser.hsbBlueText": "B",
            "Common.ModelSlider.YouEntered": "您曾輸入",
            "Games.label.newBest": "新紀錄!",
            "Common.About.BuildDate": "編譯日期:",
            "Common.FileMenu.ExitMnemonic": "x",
            "Games.label.best": "最好的: {0}",
            "Common.statistics.sim_project": "開發方案名:",
            "Common.title.message": "訊息",
            "Common.updates.downloadingBootstrap": "正在下載更新程式的啟始檔...",
            "Common.title.error": "錯誤",
            "Common.FileMenu.Exit": "離開",
            "Common.statistics.sim_major_version": "模擬程式版本 (主版次):",
            "Common.updates.askMeLater": "下次再問",
            "chart-time-control.go": "衝!",
            "Common.HelpMenu.HelpMnemonic": "h",
            "Common.confirm.clear.graphs": "您真的要清除圖形嗎?",
            "ColorChooser.swatchesNameText": "樣本",
            "Common.updates.progressDialogMessage": "從版本 \"{0}\" 更新至版本 {1}",
            "Common.updates.installer.more": "告訴我多一些訊息...",
            "XMLPersistenceManager.title.error": "錯誤",
            "ColorChooser.hsbHueText": "H",
            "ControlPanel.button.resetAll": "全部重設",
            "Common.About.AgreementButton": "軟體合約...",
            "Common.FileMenu.Load.mnemonic": "L",
            "Common.ErrorDialog.detailsButton": "細節...",
            "Common.updates.errorMissingJar": "<html>無法完成更新的動作。<br>無法連結 JAR 檔所在位址: {0}.<br> 請向您的系統管理者請求協助.<br></html>",
            "Common.preferences.privacy": "隱私",
            "Common.HelpMenu.AboutTitle": "關於",
            "ColorChooser.rgbRedText": "紅",
            "Common.statistics.sim_locale_country": "國家:",
            "ColorChooser.hsbGreenText": "G",
            "ColorChooser.rgbGreenText": "綠",
            "Games.format.time.best": "{0} ({1})",
            "Common.HelpPanel.ShowHelp": "說明!",
            "Common.statistics.sim_distribution_tag": "模擬程式版本 (公開版):",
            "Common.statistics.description": "在贊助經費補助下 PhET 可以自由的取得<br>贊助經費要求收集最少的<br>不記名 <a href=\"{0}\">資訊</a> 用以記錄<br>PhET 模擬程式的使用量<br>及提供使用者所需的較好服務.",
            "Common.softwareAgreement.message": "在所有的 PhET 模擬程式中，開始執行模擬程式時<br>我們收集了最少量的不記名 <a href=\"{0}\"> 資訊</a> <br>(例如, 模擬程式版本, 操作系統)。<br>您可以關閉傳送這些資訊的功能, <br>任何時候都可以從  \"檔案\" -> \"偏好設定\" 去更改設定. <br><br>按下 \"同意及繼續\", 您同意 PhET 的 <br>許可及隱私政策. (更進一步的訊息請見<a href=\"{1}\">here</a>).",
            "Common.choice.ok": "OK",
            "Common.About.Version": "版本:",
            "Common.ErrorDialog.contactPhet": "如果這個問題一直發生, 請把相關資料寄給 {0}",
            "Common.About.CreditsDialog.lead-design": "主要設計者",
            "Common.OptionsMenu.mnemonic": "O",
            "Common.statistics.user_preference_file_creation_time": "產生偏好記錄檔的時間 (timestamp):",
            "Common.HelpMenu.AboutMnemonic": "a",
            "Common.updates.errorWritePermissions": "<html>無法完成更新的動作。<br>您沒有權限寫入 {0}. <br>請向您的系統管理者請求協助.<br></html>",
            "ColorChooser.hsbBrightnessText": "B",
            "Common.choice.no": "否",
            "Common.About.WebLink": "參觀 PhET 的網頁",
            "Common.About.OSVersion": "作業系統版本:",
            "Common.title.warning": "警告",
            "Common.updates.versionComparison": "<html>您的  \"{0}\"  版本是 {1}.<br>有更新的版本 ({2}) 可用.</html>",
            "Common.statistics.sim_locale_language": "語言:",
            "Common.statistics.user_installation_timestamp": "PhET 安裝時間 (timestamp):",
            "Common.statistics.message_version": "訊息版本:",
            "Common.ModelSlider.Description": "不合適的值.",
            "Common.updates.installer.moreMessage": "<html>請保持您的 PhET 離線安裝程式至最新版<br>以保證您可以取得最新的模擬程式<br>和其附屬的文件. <br><br>若您要取得最新版本, 網路溜覽器 <br>將連結至 PhET 網頁, 您可以從那裏下載<br> PhET 離線安裝程式。</html>",
            "ControlPanel.message.confirmResetAll": "重設所有設定嗎?",
            "Common.HelpMenu.Help": "說明",
            "Games.label.levelControl": "難度:",
            "Common.updates.automaticallyCheck": "自動偵測是否有更新版本",
            "Common.sim.speed": "...模擬速度...",
            "Common.updates.checkForSimUpdate": "檢查模擬程式的更新...",
            "XMLPersistenceManager.save.confirm.message": "<html>您所選擇的檔案己經存在.<br>您要用現在的存檔覆蓋它嗎?</html>",
            "FileChooser.newFolderErrorText": "建立資料夾時錯誤",
            "Common.updates.skipThisUpdate": "跳過這個更新版",
            "Common.About.CreditsButton": "成員名單:",
            "Common.FileMenu.Save.mnemonic": "S",
            "FileChooser.saveDialogTitleText": "存檔",
            "XMLPersistenceManager.load.title": "載入設定值",
            "Common.updates.checkForInstallerUpdate": "檢查 PhET 離線安裝程式的更新...",
            "timeseries.control.panel.playback": "撥放",
            "Common.updates.progressDialogTitle": "更新中",
            "Common.HelpMenu.Title": "說明",
            "FileChooser.fileNameLabelText": "檔名:",
            "ColorChooser.rgbNameText": "RGB",
            "Common.softwareAgreement.title": "軟體使用合約",
            "Common.statistics.host_java_version_minor": "Java 版本 (minor):",
            "Common.HelpMenu.TitleMnemonic": "h",
            "Common.About.CreditsDialog.interviews": "面談",
            "Common.About.Distribution": "貢獻者:",
            "Common.statistics.host_java_webstart_version": "Java Web Start 版本:",
            "XMLPersistenceManager.save.error.message": "<html>寫入檔案錯誤:<br>{0}</html>",
            "Games.label.time": "時間: {0}",
            "FileChooser.openButtonText": "開啟",
            "ColorChooser.sampleText": "簡易文字",
            "Common.statistics.details.description": "<html>模擬程式開始執行後, 下列的資訊將被傳送到 PhET.</html>",
            "Common.statistics.host_os_version": "作業系統版本:",
            "Common.title.confirm": "確認",
            "Games.label.score.max": "得分: 共 {1} 分, 得到 {0} 分",
            "Common.BasicPhetPanel.LogoToolTip": "關閉整個視窗框",
            "Common.statistics.host_java_timezone": "時區:",
            "Common.time.slow": "慢",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.ClockControlPanel.Rewind": "倒帶",
            "Common.softwareAgreement.accept": "接受且繼續",
            "Common.updates.updateToDate": "已經是最新的.",
            "Common.ClockControlPanel.Pause": "暫停",
            "PhetApplication.StartupDialog.message": "\"{0}\" 正在開啟中",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "這個程式引用了下列其它的軟體",
            "XMLPersistenceManager.message.notAConfigFile": "這檔案不含組態設定",
            "Common.preferences.updates": "更新",
            "Games.label.score.max.perfect": "得分: 共 {1} 分, 得到 {0} 分 (棒透了!)",
            "Common.HelpMenu.MegaHelpMnemonic": "m",
            "Common.statistics.enabled": "允許傳送資訊到 PhET",
            "Common.StopwatchPanel.stop": "停止",
            "Common.HelpPanel.MegaHelp": "仔細說明...",
            "Common.statistics.host_locale_country": "所在國家:",
            "Common.StopwatchPanel.reset": "重設",
            "Common.playback": "錄放",
            "Games.message.confirmNewGame": "<html>這遊戲還沒結束.<br>您確定要開啟另一個新遊戲?</html>",
            "Common.statistics.sim_minor_version": "模擬程式版本 (次版次):",
            "Common.updates.tryIt": "在更新前試用一下.",
            "ColorChooser.rgbBlueText": "藍",
            "Common.choice.close": "關閉",
            "Common.ClockControlPanel.Play": "播放",
            "Common.statistics.sim_type": "模擬類別:",
            "FileChooser.saveButtonText": "存檔",
            "Common.rewind": "倒帶",
            "Common.StopwatchPanel.start": "開始",
            "Common.updates.youHaveCurrent": "您已經有最新版本 ({0}) of {1}。",
            "Common.statistics.sim_sessions_since": "自從上次登錄後本模擬執行的時間:",
            "Common.statistics.host_java_vendor": "Java 供應商:",
            "charts.show-graphs": "顯示圖形:",
            "Common.statistics.message_type": "訊息種類:"
        } );