//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_sk.properties
define( {
            "Games.label.level": "Úroveň: {0}",
            "Common.updates.errorMessage": "Vznikla chyba pri pokuse o aktualizáciu.<br>Prosím vyskúšajte to znova neskôr, alebo navštívite {0}.",
            "XMLPersistenceManager.save.error.encode": "<html>Chyba kódovania súboru:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Chyba dekódovania súboru:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "s",
            "Common.softwareAgreement.decline": "Koniec",
            "Common.statistics.host_os_name": "Názov operačného systému",
            "Common.statistics.user_total_sessions": "Celkový počet spustení všetkých simulácii.",
            "Common.statistics.host_java_version_major": "Verzia Java (major)",
            "FileChooser.openDialogTitleText": "Otvoriť",
            "Common.WhiteBackground": "Biele pozadie",
            "Common.statistics.host_java_version_maintenance": "Verzia Java (podpora)",
            "FileChooser.lookInLabelText": "Hľadať v:",
            "Common.choice.cancel": "Zrušiť",
            "Common.updates.seePreferences": "Choďte na Súbor->Predvoľby a zmeňte nastavenie predvoľby",
            "Common.About.CreditsDialog.software-development": "Vývoj softvéru",
            "Common.About.JavaVersion": "Java verzia:",
            "ColorChooser.resetText": "Obnoviť",
            "wavelength.ir": "IR",
            "translation.credits": "Augustín Šutta, Bratislava",
            "Common.About.CreditsDialog.design-team": "Dizajnérsky tím",
            "Common.statistics.sim_total_sessions": "Celkový počet spustení simulácie.",
            "Common.FileMenu.PreferencesMnemonic": "p",
            "wavelength.uv": "UV",
            "Games.title.gameSettings": "Nastavenie hry",
            "XMLPersistenceManager.save.title": "Uložiť konfiguráciu",
            "XMLPersistenceManager.load.error.contents": "Súbor je chybný alebo nebol vytvorený touto simuláciou.",
            "Common.statistics.details.title": "Informácie",
            "Common.statistics.sim_dev_version": "Verzia simulácie (dev)",
            "FileChooser.saveInLabelText": "Uložiť do:",
            "Common.statistics.sim_name": "Názov simulácie",
            "Save.confirm.message": "<html>Zvolený súbor už existuje.<br>Chcete ho nahradiť ukladaným súborom?</html>",
            "Games.label.score": "Skóre: {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "PhET vývojový tím",
            "Games.button.start": "Štart!",
            "Common.statistics.sim_deployment": "Typ rozmiestnenia",
            "Common.FileMenu.Save": "Uložiť konfiguráciu...",
            "Common.About.CreditsDialog.licenseDetails": "Podrobnosti licencie",
            "ColorChooser.hsbSaturationText": "S",
            "Games.radioButton.on": "zapnúť",
            "FileChooser.acceptAllFileFilterText": "Všetky súbory (*.*)",
            "ColorChooser.hsbNameText": "HSB",
            "Common.ModelSlider.Minimum": "Minimum",
            "Common.FileMenu.Preferences": "Predvoľby...",
            "Common.FileMenu.Load": "Otvoriť konfiguráciu...",
            "Common.updates.downloadingSimJar": "prevzatie simulácie JAR súbor...",
            "Games.radioButton.off": "vypnúť",
            "ColorChooser.swatchesRecentText": "Posledné: ",
            "Common.updates.updateAvailable": "Aktualizácia je prístupná",
            "Common.statistics.host_locale_language": "Hlavný jazyk",
            "Common.clear": "Zmazať",
            "Games.title.gameOver": "Koniec hry",
            "FileChooser.filesOfTypeLabelText": "Typ súboru:",
            "Common.ErrorDialog.detailsTitle": "Podrobnosti chyby",
            "Common.HelpMenu.MegaHelp": "MegaPomocník...",
            "Common.ClockControlPanel.Step": "Krok",
            "Common.statistics.sim_revision": "Verzia simulácie (skúšobná)",
            "Common.choice.yes": "Áno",
            "Common.FileMenu.Title": "Súbor",
            "Common.statistics.sim_dev": "Je to vývojová verzia?",
            "Common.updates.installer.message": "<html>Vaša PhET offline inštalácia web stránky je z dňa {0}.<br>Je  prístupná novšia verzia, z dňa {1}.<br><br>Chcete nainštalovať najnovšiu PhET offline web stránku?</html>",
            "Common.updates.updateNow": "Aktualizovať teraz!",
            "Common.record": "Záznam",
            "Common.About.CreditsDialog.Title": "Tvorcovia",
            "Common.updates.error.internetConnection": "<html>Nedá sa pripojiť na {0},<br>skontrolujte pripojenie na Internet.</html>",
            "Common.time.fast": "rýchlo",
            "XMLPersistenceManager.load.error.message": "<html>Chyba pri čítani zo súboru:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Maximum",
            "Common.OptionsMenu": "Nastavenia",
            "Common.ClockControlPanel.Restart": "Reštart",
            "Common.statistics.sim_version_timestamp": "Verzia simulácie (čas)",
            "Common.updates.installer.yes": "Áno!",
            "Common.phetInstaller": "PhET offline web stránka",
            "Common.HelpMenu.About": "O programe...",
            "Common.ModelSlider.OutOfRange": "Hodnota mimo rozsah",
            "Common.About.CreditsDialog.TranslationCreditsTitle": "Preložil:",
            "ColorChooser.previewText": "Ukážka",
            "Common.BasicPhetPanel.Title": "Naspäť",
            "Common.HelpPanel.HideHelp": "Skryť pomoc",
            "Common.statistics.host_os_arch": "Typ procesora",
            "Common.preferences.title": "Predvoľby",
            "Games.button.newGame": "Nová hra",
            "ColorChooser.hsbRedText": "Č",
            "ColorChooser.hsbBlueText": "M",
            "Common.ModelSlider.YouEntered": "Potvrdenie",
            "Games.label.newBest": "Váš nový najlepší!",
            "Common.About.BuildDate": "Dátum zostavenia:",
            "Common.FileMenu.ExitMnemonic": "k",
            "Common.statistics.sim_project": "Názov projektu",
            "Games.label.best": "Najlepšie: {0}",
            "Common.title.message": "Správa",
            "Common.updates.downloadingBootstrap": "prevzatie samozavádzacej aktualizácie... ",
            "Common.title.error": "Chyba",
            "Common.FileMenu.Exit": "Koniec",
            "Common.statistics.sim_major_version": "Verzia simulácie (major)",
            "Common.updates.askMeLater": "Spýtať sa neskôr",
            "chart-time-control.go": "Ísť !",
            "Common.HelpMenu.HelpMnemonic": "p",
            "Common.confirm.clear.graphs": "Skutočne chcete zmazať grafy?",
            "ColorChooser.swatchesNameText": "Vzorkovník",
            "Common.updates.progressDialogMessage": "Aktualizácia \"{0}\" na verziu {1}",
            "Common.updates.installer.more": "Viac informácii...",
            "XMLPersistenceManager.title.error": "Chyba",
            "ColorChooser.hsbHueText": "O",
            "ControlPanel.button.resetAll": "Nulovať všetko",
            "Common.About.AgreementButton": "Licenčná zmluva...",
            "Common.FileMenu.Load.mnemonic": "O",
            "Common.ErrorDialog.detailsButton": "Podrobnosti...",
            "Common.updates.errorMissingJar": "<html>Aktualizácia sa nemôže vykonať. <br>Ne je možné vyhľadať JAR súbor: {0}.<br>O pomoc požiadajte svojho systémového administrátora. <br></html> ",
            "Common.preferences.privacy": "Zabezpečenie",
            "Common.HelpMenu.AboutTitle": "O programe",
            "ColorChooser.rgbRedText": "červená",
            "Common.statistics.sim_locale_country": "Krajina",
            "ColorChooser.hsbGreenText": "Z",
            "ColorChooser.rgbGreenText": "zelená",
            "Common.HelpPanel.ShowHelp": "Pomoc!",
            "PiccoloPhet.VelocitySensorNode.speed": "Rýchlosť",
            "Common.statistics.sim_distribution_tag": "Verzia simulácie (distribuovaná)",
            "Common.statistics.description": "PhET  je sprístupnené zadarmo vďaka grantom,<br> ktoré požadujú od nás zbierať minimálne množstvo<br> neosobných <a href=\"{0}\">informácii</a> slúžiacich k preukázaniu<br> využívania PhET simulácii a tiež sú potrebné <br>k zlepšeniu podpory našich užívateľov.   ",
            "Common.softwareAgreement.message": "Vo všetkých PhET simuláciách sa zisťuje pri štarte minimálne<br>množstvo neosobných <a href='{0}'>informácii</a> (napr. verzia simulácie, operačný systém).<br> Kedykoľvek môžete vypnúť posielanie týchto informácii<br> položkou menu Súbor->Predvoľby.<br><br>Kliknutím na „Súhlasiť a pokračovať“ vyjadrujete súhlas s PhET <br>licenčnou zmluvou. (Pre ďalšie podrobnosti <a href='{1}'>kliknite tu</a>).",
            "Common.choice.ok": "OK",
            "Common.About.Version": "Verzia:",
            "Common.ErrorDialog.contactPhet": "Ak problém pretrváva, pošlite podrobnosti na {0}",
            "Common.About.CreditsDialog.lead-design": "Vedúci dizajnu",
            "Common.OptionsMenu.mnemonic": "N",
            "Common.statistics.user_preference_file_creation_time": "Čas vytvorenia súboru Predvoľby",
            "Common.HelpMenu.AboutMnemonic": "o",
            "Common.updates.errorWritePermissions": "<html>Aktualizácia sa nemôže vykonať. <br>Nemáte oprávnenie pre zápis do {0}.<br>O pomoc požiadajte svojho systémového administrátora. <br></html> ",
            "ColorChooser.hsbBrightnessText": "J",
            "Common.choice.no": "Nie",
            "Common.About.WebLink": "Zobraziť domoskú stránku PhET",
            "Common.About.OSVersion": "Verzia OS:",
            "Common.title.warning": "Upozornenie",
            "Common.updates.versionComparison": "<html>Vaša súčasná verzia simulácie \"{0}\" je {1}.<br>Je  prístupná novšia verzia ({2}).</html>",
            "Common.statistics.sim_locale_language": "Jazyk",
            "Common.statistics.user_installation_timestamp": "Čas PhET inštalácie",
            "Common.statistics.message_version": "Verzia správy",
            "Common.ModelSlider.Description": "Chýbná hodnota",
            "Common.updates.installer.moreMessage": "<html>Uloženie dátumu inštalácie vašej PhET offline web stránky vám zaistí <br>prístup k najnovším PhET simuláciám <br>a doplňujúcim materiálom.<br><br>Ak chcete najnovšiu verziu, tak prehliadač otvorí <br>PhET web stránku, kde si môžete prevziať inštalátor <br>PhET offline web stránky. </html>",
            "ControlPanel.message.confirmResetAll": "Nulovať všetky nastavenia?",
            "Common.HelpMenu.Help": "Pomocník",
            "Common.updates.errorNotAJar": "{0} nie je súbor typu JAR.",
            "Games.label.levelControl": "Úroveň:",
            "Common.updates.automaticallyCheck": "Automaticky skontrolovať aktualizáciu",
            "Common.sim.speed": "... rýchlosť simulácie...",
            "Common.updates.checkForSimUpdate": "Skontrolovať aktualizáciu simulácie...",
            "XMLPersistenceManager.save.confirm.message": "<html>Zvolený súbor už existuje.<br>Chcete ho nahradiť ukladaným súborom?</html>",
            "FileChooser.newFolderErrorText": "Chyba pri vytváraní nového priečinka",
            "Common.About.CreditsButton": "Tvorcovia...",
            "Common.updates.skipThisUpdate": "Vynechať aktualizáciu.",
            "Common.FileMenu.Save.mnemonic": "U",
            "FileChooser.saveDialogTitleText": "Uložiť",
            "XMLPersistenceManager.load.title": "Otvoriť konfiguráciu",
            "Common.updates.checkForInstallerUpdate": "Skontrolovať aktualizáciu inštalácie PhET offline web stránky...",
            "timeseries.control.panel.playback": "Zo záznamu",
            "Common.updates.progressDialogTitle": "Aktualizácia",
            "Common.HelpMenu.Title": "Pomocník",
            "ColorChooser.rgbNameText": "RGB",
            "FileChooser.fileNameLabelText": "Názov súboru:",
            "Common.softwareAgreement.title": "Licenčné podmienky ",
            "Common.statistics.host_java_version_minor": "Verzia Java (minor)",
            "Common.HelpMenu.TitleMnemonic": "p",
            "Common.About.CreditsDialog.interviews": "Poradcovia",
            "Common.About.Distribution": "Distribúcia:",
            "Common.statistics.host_java_webstart_version": "Java web štart verzia",
            "XMLPersistenceManager.save.error.message": "<html>Chyba pri zápise do súboru:<br>{0}</html>",
            "Games.label.time": "Čas: {0}",
            "FileChooser.openButtonText": "Otvoriť",
            "ColorChooser.sampleText": "Ukážka textu  Ukážka textu",
            "Common.statistics.details.description": "<html>Informácia zobrazená nižšie bude poslaná PhET po spustení simulácie.</html>",
            "Common.statistics.host_os_version": "Verzia operačného systému",
            "Common.title.confirm": "Potvrdenie",
            "Common.BasicPhetPanel.LogoToolTip": "Vypnúť celoobrazovkový režim",
            "Games.label.score.max": "Skóre: {0} z {1}",
            "Common.statistics.host_java_timezone": "Časové pásmo",
            "Common.time.slow": "pomaly",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.ClockControlPanel.Rewind": "Previnúť",
            "Common.softwareAgreement.accept": "Súhlasiť a pokračovať",
            "Common.updates.updateToDate": "Aktuálne",
            "Common.ClockControlPanel.Pause": "Pauza",
            "PhetApplication.StartupDialog.message": "Simulácia \"{0}\" už začína",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Tento program používa softvér nasledujúcich zmluvných partnerov",
            "XMLPersistenceManager.message.notAConfigFile": "Tento súbor neobsahuje konfiguráciu pre túto simuláciu.",
            "Common.preferences.updates": "Aktualizovať",
            "Games.label.score.max.perfect": "Skóre: {0} z {1} (PERFEKTNÉ!)",
            "Common.HelpMenu.MegaHelpMnemonic": "m",
            "Common.statistics.enabled": "Povoliť odoslanie informácii pre PhET",
            "Common.ClockControlPanel.StepBack": "Krok späť",
            "Common.StopwatchPanel.stop": "Stop",
            "Common.HelpPanel.MegaHelp": "MegaPomocník...",
            "Common.statistics.host_locale_country": "Hlavná krajina",
            "Common.StopwatchPanel.reset": "Nulovať",
            "Common.playback": "Zo záznamu",
            "Common.statistics.sim_minor_version": "Verzia simulácie (minor)",
            "Games.message.confirmNewGame": "<html>Túto hru ste neskončili. <br>Naozaj chcete začať novú hru?</html>",
            "Common.updates.tryIt": "Spustiť novú verziu po jej aktualizácii.",
            "ColorChooser.rgbBlueText": "modrá",
            "Common.choice.close": "Zavrieť",
            "Common.ClockControlPanel.Play": "Spustiť",
            "Common.statistics.sim_type": "Typ simulácie",
            "FileChooser.saveButtonText": "Uložiť",
            "Common.rewind": "Pretočiť",
            "Common.StopwatchPanel.start": "Štart",
            "Common.updates.youHaveCurrent": "Máte najaktuálnejšiu verziu ({0}) simulácie {1}.",
            "Common.statistics.sim_sessions_since": "Počet spustení simulácie od posledného pripojenia.",
            "Common.statistics.host_java_vendor": "Java predajca",
            "charts.show-graphs": "Zobraziť grafy:",
            "Common.statistics.message_type": "Typ správy"
        } );