// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.forcesandmotionbasics;

import java.awt.image.BufferedImage;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Resources (images and translated strings) for "ForcesAndMotionBasics" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator
 */
public class ForcesAndMotionBasicsResources {
    public static final String PROJECT_NAME = "forces-and-motion-basics";
    public static final PhetResources RESOURCES = new PhetResources( PROJECT_NAME );

    //Strings
    public static class Strings {
        public static final String ACCELERATION = RESOURCES.getLocalizedString( "acceleration" );
        public static final String APPLIED_FORCE = RESOURCES.getLocalizedString( "appliedForce" );
        public static final String BLUE_WINS = RESOURCES.getLocalizedString( "blueWins" );
        public static final String FORCE_READOUT__PATTERN = RESOURCES.getLocalizedString( "forceReadout.pattern" );
        public static final String FORCE = RESOURCES.getLocalizedString( "force" );
        public static final String FORCES = RESOURCES.getLocalizedString( "forces" );
        public static final String FRICTION = RESOURCES.getLocalizedString( "friction" );
        public static final String FRICTION_FORCE = RESOURCES.getLocalizedString( "frictionForce" );
        public static final String FRICTION_TITLE = RESOURCES.getLocalizedString( "frictionTitle" );
        public static final String GO = RESOURCES.getLocalizedString( "go" );
        public static final String LEFT_FORCE = RESOURCES.getLocalizedString( "leftForce" );
        public static final String LOTS = RESOURCES.getLocalizedString( "lots" );
        public static final String MASS_DISPLAY__PATTERN = RESOURCES.getLocalizedString( "massDisplay.pattern" );
        public static final String MASSES = RESOURCES.getLocalizedString( "masses" );
        public static final String MOTION = RESOURCES.getLocalizedString( "motion" );
        public static final String NEWTONS = RESOURCES.getLocalizedString( "newtons" );
        public static final String NEWTONS__N = RESOURCES.getLocalizedString( "newtons.n" );
        public static final String NONE = RESOURCES.getLocalizedString( "none" );
        public static final String PAUSE = RESOURCES.getLocalizedString( "pause" );
        public static final String RED_WINS = RESOURCES.getLocalizedString( "redWins" );
        public static final String RETURN = RESOURCES.getLocalizedString( "return" );
        public static final String RIGHT_FORCE = RESOURCES.getLocalizedString( "rightForce" );
        public static final String SOUND = RESOURCES.getLocalizedString( "sound" );
        public static final String SPEED = RESOURCES.getLocalizedString( "speed" );
        public static final String SUM_OF_FORCES = RESOURCES.getLocalizedString( "sumOfForces" );
        public static final String SUM_OF_FORCES_EQUALS_ZERO = RESOURCES.getLocalizedString( "sumOfForcesEqualsZero" );
        public static final String TUG_OF_WAR = RESOURCES.getLocalizedString( "tugOfWar" );
        public static final String VALUES = RESOURCES.getLocalizedString( "values" );
    }

    //Images
    public static class Images {
        public static final BufferedImage BRICK_TILE = RESOURCES.getImage( "brick-tile.png" );
        public static final BufferedImage CART = RESOURCES.getImage( "cart.png" );
        public static final BufferedImage CLOUD1 = RESOURCES.getImage( "cloud1.png" );
        public static final BufferedImage CRATE = RESOURCES.getImage( "crate.png" );
        public static final BufferedImage FRIDGE = RESOURCES.getImage( "fridge.png" );
        public static final BufferedImage GIRL_HOLDING = RESOURCES.getImage( "girl-holding.png" );
        public static final BufferedImage GIRL_SITTING = RESOURCES.getImage( "girl-sitting.png" );
        public static final BufferedImage GIRL_STANDING = RESOURCES.getImage( "girl-standing.png" );
        public static final BufferedImage GO_HOVER = RESOURCES.getImage( "go_hover.png" );
        public static final BufferedImage GO_PRESSED = RESOURCES.getImage( "go_pressed.png" );
        public static final BufferedImage GO_UP = RESOURCES.getImage( "go_up.png" );
        public static final BufferedImage GRASS = RESOURCES.getImage( "grass.png" );
        public static final BufferedImage ICE_OVERLAY = RESOURCES.getImage( "ice_overlay.png" );
        public static final BufferedImage MAN_HOLDING = RESOURCES.getImage( "man-holding.png" );
        public static final BufferedImage MAN_SITTING = RESOURCES.getImage( "man-sitting.png" );
        public static final BufferedImage MAN_STANDING = RESOURCES.getImage( "man-standing.png" );
        public static final BufferedImage MOUNTAINS = RESOURCES.getImage( "mountains.png" );
        public static final BufferedImage MYSTERY_OBJECT_01 = RESOURCES.getImage( "mystery-object-01.png" );
        public static final BufferedImage PULL_FIGURE_BLUE_0 = RESOURCES.getImage( "pull_figure_BLUE_0.png" );
        public static final BufferedImage PULL_FIGURE_BLUE_1 = RESOURCES.getImage( "pull_figure_BLUE_1.png" );
        public static final BufferedImage PULL_FIGURE_BLUE_2 = RESOURCES.getImage( "pull_figure_BLUE_2.png" );
        public static final BufferedImage PULL_FIGURE_BLUE_3 = RESOURCES.getImage( "pull_figure_BLUE_3.png" );
        public static final BufferedImage PULL_FIGURE_LRG_BLUE_0 = RESOURCES.getImage( "pull_figure_lrg_BLUE_0.png" );
        public static final BufferedImage PULL_FIGURE_LRG_BLUE_1 = RESOURCES.getImage( "pull_figure_lrg_BLUE_1.png" );
        public static final BufferedImage PULL_FIGURE_LRG_BLUE_2 = RESOURCES.getImage( "pull_figure_lrg_BLUE_2.png" );
        public static final BufferedImage PULL_FIGURE_LRG_BLUE_3 = RESOURCES.getImage( "pull_figure_lrg_BLUE_3.png" );
        public static final BufferedImage PULL_FIGURE_LRG_RED_0 = RESOURCES.getImage( "pull_figure_lrg_RED_0.png" );
        public static final BufferedImage PULL_FIGURE_LRG_RED_1 = RESOURCES.getImage( "pull_figure_lrg_RED_1.png" );
        public static final BufferedImage PULL_FIGURE_LRG_RED_2 = RESOURCES.getImage( "pull_figure_lrg_RED_2.png" );
        public static final BufferedImage PULL_FIGURE_LRG_RED_3 = RESOURCES.getImage( "pull_figure_lrg_RED_3.png" );
        public static final BufferedImage PULL_FIGURE_RED_0 = RESOURCES.getImage( "pull_figure_RED_0.png" );
        public static final BufferedImage PULL_FIGURE_RED_1 = RESOURCES.getImage( "pull_figure_RED_1.png" );
        public static final BufferedImage PULL_FIGURE_RED_2 = RESOURCES.getImage( "pull_figure_RED_2.png" );
        public static final BufferedImage PULL_FIGURE_RED_3 = RESOURCES.getImage( "pull_figure_RED_3.png" );
        public static final BufferedImage PULL_FIGURE_SMALL_BLUE_0 = RESOURCES.getImage( "pull_figure_small_BLUE_0.png" );
        public static final BufferedImage PULL_FIGURE_SMALL_BLUE_1 = RESOURCES.getImage( "pull_figure_small_BLUE_1.png" );
        public static final BufferedImage PULL_FIGURE_SMALL_BLUE_2 = RESOURCES.getImage( "pull_figure_small_BLUE_2.png" );
        public static final BufferedImage PULL_FIGURE_SMALL_BLUE_3 = RESOURCES.getImage( "pull_figure_small_BLUE_3.png" );
        public static final BufferedImage PULL_FIGURE_SMALL_RED_0 = RESOURCES.getImage( "pull_figure_small_RED_0.png" );
        public static final BufferedImage PULL_FIGURE_SMALL_RED_1 = RESOURCES.getImage( "pull_figure_small_RED_1.png" );
        public static final BufferedImage PULL_FIGURE_SMALL_RED_2 = RESOURCES.getImage( "pull_figure_small_RED_2.png" );
        public static final BufferedImage PULL_FIGURE_SMALL_RED_3 = RESOURCES.getImage( "pull_figure_small_RED_3.png" );
        public static final BufferedImage PUSHER_0 = RESOURCES.getImage( "pusher_0.png" );
        public static final BufferedImage PUSHER_1 = RESOURCES.getImage( "pusher_1.png" );
        public static final BufferedImage PUSHER_10 = RESOURCES.getImage( "pusher_10.png" );
        public static final BufferedImage PUSHER_11 = RESOURCES.getImage( "pusher_11.png" );
        public static final BufferedImage PUSHER_12 = RESOURCES.getImage( "pusher_12.png" );
        public static final BufferedImage PUSHER_13 = RESOURCES.getImage( "pusher_13.png" );
        public static final BufferedImage PUSHER_14 = RESOURCES.getImage( "pusher_14.png" );
        public static final BufferedImage PUSHER_2 = RESOURCES.getImage( "pusher_2.png" );
        public static final BufferedImage PUSHER_3 = RESOURCES.getImage( "pusher_3.png" );
        public static final BufferedImage PUSHER_4 = RESOURCES.getImage( "pusher_4.png" );
        public static final BufferedImage PUSHER_5 = RESOURCES.getImage( "pusher_5.png" );
        public static final BufferedImage PUSHER_6 = RESOURCES.getImage( "pusher_6.png" );
        public static final BufferedImage PUSHER_7 = RESOURCES.getImage( "pusher_7.png" );
        public static final BufferedImage PUSHER_8 = RESOURCES.getImage( "pusher_8.png" );
        public static final BufferedImage PUSHER_9 = RESOURCES.getImage( "pusher_9.png" );
        public static final BufferedImage PUSHER_FALL_DOWN = RESOURCES.getImage( "pusher_fall_down.png" );
        public static final BufferedImage PUSHER_STRAIGHT_ON = RESOURCES.getImage( "pusher_straight_on.png" );
        public static final BufferedImage ROPE = RESOURCES.getImage( "rope.png" );
        public static final BufferedImage SKATEBOARD = RESOURCES.getImage( "skateboard.png" );
        public static final BufferedImage STOP_HOVER = RESOURCES.getImage( "stop_hover.png" );
        public static final BufferedImage STOP_PRESSED = RESOURCES.getImage( "stop_pressed.png" );
        public static final BufferedImage STOP_UP = RESOURCES.getImage( "stop_up.png" );
        public static final BufferedImage TRASH_CAN = RESOURCES.getImage( "trash-can.png" );
    }
}