//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_sl.properties
define( {
            "Games.label.level": "Težavnost: {0}",
            "Common.updates.errorMessage": "Pri poskusu posodobitve je prišlo do napake.<br>Poskusite znova kasneje ali obiščite {0}.",
            "XMLPersistenceManager.save.error.encode": "<html>Napaka pri kodiranju:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Napaka v  dekodiranju:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "d",
            "Common.softwareAgreement.decline": "Izhod",
            "Common.statistics.host_os_name": "Ime operacijskega sistema:",
            "Common.statistics.user_total_sessions": "Število zagonov vseh simulacij:",
            "Common.statistics.host_java_version_major": "Verzija Jave (glavna):",
            "FileChooser.openDialogTitleText": "Odpri",
            "Common.WhiteBackground": "Belo ozadje",
            "Common.statistics.host_java_version_maintenance": "Verzija Jave (maintenance):",
            "FileChooser.lookInLabelText": "Poglej v:",
            "Common.choice.cancel": "Prekliči",
            "Common.updates.seePreferences": "Nastavitve spremenite pod Datoteka->Nastavitve",
            "Common.About.CreditsDialog.software-development": "Razvoj programske opreme",
            "Common.About.JavaVersion": "Verzija Jave:",
            "ColorChooser.resetText": "Ponastavi",
            "wavelength.ir": "IR",
            "translation.credits": "Samo Jamšek",
            "Common.About.CreditsDialog.design-team": "Oblikovalska skupina",
            "Common.statistics.sim_total_sessions": "Število vseh zagonov simulacije:",
            "Common.FileMenu.PreferencesMnemonic": "n",
            "wavelength.uv": "UV",
            "Games.title.gameSettings": "Nastavitve igre",
            "XMLPersistenceManager.save.title": "Shrani nastavitve",
            "XMLPersistenceManager.load.error.contents": "Datoteka je pokvarjena ali pa ni narejena s to simulacijo.",
            "Common.statistics.details.title": "Informacije",
            "Common.statistics.sim_dev_version": "Verzija simulacije (dev):",
            "FileChooser.saveInLabelText": "Shrani v:",
            "Common.statistics.sim_name": "Ime simulacije:",
            "Save.confirm.message": "<html>Izbrana datoteka že obstaja<br>Ali jo želite nadomestiti z datoteko, ki jo pravkar shranjujete?</html>",
            "Games.label.score": "Rezultat: {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "PhET razvojna skupina",
            "Games.button.start": "Start!",
            "Common.statistics.sim_deployment": "Vrsta kompilacije:",
            "Common.FileMenu.Save": "Shrani nastavitve",
            "Common.About.CreditsDialog.licenseDetails": "Podrobnosti o licenci",
            "ColorChooser.hsbSaturationText": "S",
            "Games.radioButton.on": "vključeno",
            "FileChooser.acceptAllFileFilterText": "Vse datoteke (*.*)",
            "ColorChooser.hsbNameText": "HSB",
            "Common.ModelSlider.Minimum": "Minimum",
            "Common.FileMenu.Preferences": "Nastavitve...",
            "Common.FileMenu.Load": "Naloži konfiguracijo",
            "Common.updates.downloadingSimJar": "prenašanje datoteke JAR s simulacijo...",
            "Games.radioButton.off": "izključeno",
            "ColorChooser.swatchesRecentText": "Zadnje:",
            "Common.updates.updateAvailable": "Posodobitev je na voljo",
            "Common.statistics.host_locale_language": "Jezik:",
            "Common.clear": "Izbriši",
            "Games.title.gameOver": "Konec igre",
            "FileChooser.filesOfTypeLabelText": "Vrste datotek:",
            "Common.ErrorDialog.detailsTitle": "Podrobnosti o napaki",
            "Common.HelpMenu.MegaHelp": "MegaPomoč",
            "Common.ClockControlPanel.Step": "Korak",
            "Common.statistics.sim_revision": "Verzija simulacije (revizija):",
            "Common.choice.yes": "Da",
            "Common.FileMenu.Title": "Datoteka",
            "Common.value_units": "{0} {1}",
            "Common.statistics.sim_dev": "Je to razvojna verzija?",
            "Common.updates.installer.message": "<html>Uporabljate PhET offline namestitveni program z datumom {0}.<br>Na voljo je novejša verzija z datumom {1}.<br><br>Ali želite prenesti najnovejšo različico PhET offline namestitvenega sistema?</html>",
            "Common.updates.updateNow": "Posodobi zdaj!",
            "Common.record": "Snemaj",
            "Common.About.CreditsDialog.Title": "Zasluge",
            "Common.updates.error.internetConnection": "<html>Ni povezave z {0},<br>preverite internetno povezavo.</html>",
            "Common.time.fast": "hitro",
            "XMLPersistenceManager.load.error.message": "<html>Napaka branja datoteke:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Maksimum",
            "Common.OptionsMenu": "Možnosti",
            "Common.ClockControlPanel.Restart": "Ponovni zagon",
            "Common.statistics.sim_version_timestamp": "Verzija simulacije (časovni žig):",
            "Common.updates.installer.yes": "Da!",
            "Common.phetInstaller": "PhET offline namestitveni sistema",
            "Common.HelpMenu.About": "Vizitka...",
            "Common.ModelSlider.OutOfRange": "Vrednost izven obsega",
            "Common.About.CreditsDialog.TranslationCreditsTitle": "Prevod",
            "ColorChooser.previewText": "Predogled",
            "Common.BasicPhetPanel.Title": "Nazaj",
            "Common.HelpPanel.HideHelp": "Skrij pomoč",
            "Common.statistics.host_os_arch": "Vrsta procesorja:",
            "Common.preferences.title": "Nastavitve",
            "Games.button.newGame": "Nova igra",
            "ColorChooser.hsbRedText": "R",
            "ColorChooser.hsbBlueText": "B",
            "Common.ModelSlider.YouEntered": "Vnesli ste",
            "Games.label.newBest": "Nov najboljši rezultat!",
            "Common.About.BuildDate": "Datum gradnje:",
            "Common.FileMenu.ExitMnemonic": "x",
            "Common.statistics.sim_project": "Ime projekta:",
            "Games.label.best": "Najboljši rezultati: {0}",
            "Common.title.message": "Sporočilo",
            "Common.updates.downloadingBootstrap": "prenašanje programa za posodobitev",
            "Common.title.error": "Napaka",
            "Common.FileMenu.Exit": "Izhod",
            "Common.statistics.sim_major_version": "Verzija simulacije (major):",
            "Common.updates.askMeLater": "Vprašaj me pozneje",
            "chart-time-control.go": "Poženi!",
            "Common.HelpMenu.HelpMnemonic": "p",
            "Common.confirm.clear.graphs": "Ali želite izbrisati grafe?",
            "ColorChooser.swatchesNameText": "Gradniki",
            "Common.updates.progressDialogMessage": "Posodabljanje \"{0}\" na verzijo {1}",
            "Common.updates.installer.more": "Več o ...",
            "XMLPersistenceManager.title.error": "Napaka",
            "ColorChooser.hsbHueText": "H",
            "ControlPanel.button.resetAll": "Ponastavi",
            "Common.About.AgreementButton": "Licenčna pogodba...",
            "Common.FileMenu.Load.mnemonic": "L",
            "Common.ErrorDialog.detailsButton": "Podrobnosti...",
            "Common.updates.errorMissingJar": "<html>Posodobitve ni mogoče izvesti.<br>Ni datoteke JAR: {0}.<br>Obrnite se na vašega sistemskega administratorja.<br></html>",
            "Common.preferences.privacy": "Zasebnost",
            "Common.HelpMenu.AboutTitle": "Vizitka",
            "ColorChooser.rgbRedText": "Rdeča",
            "Common.statistics.sim_locale_country": "Država:",
            "ColorChooser.hsbGreenText": "G",
            "ColorChooser.rgbGreenText": "Zelena",
            "Games.format.time.best": "{0} ({1})",
            "Common.HelpPanel.ShowHelp": "Pomoč!",
            "Common.statistics.sim_distribution_tag": "Verzija simulacije (distribucija):",
            "Common.statistics.description": "Brezplačno dostopnost so omogočila denarna<br>stredstva, za pridobitev katerih je potrebno<br>zbiranje minimalnih anonimnih <a href=\"{0}\">informacij</a>,<br>s katerimi beležimo uporabo PhET simulacij<br>in zadostimo željam uporabnikov po posodobitvah.",
            "Common.softwareAgreement.message": "Pri vsaki uporabi PhET simulacije zbiramo le minimalno<br>količino anonimnih <a href=\"{0}\">informacij</a>  (npr., verzija simulacije,<br>operacijski sistem). Pošiljanje informacij lahko kadarkoli<br>onemogočite preko ukaza Datoteka->Nastavitve.<br><br>S klikom na \"Se strinjam in želim nadaljevati\" sprejemate<br>PhET's licenčno pogodbo, vključno z izjavo o<br>varovanju zasebnosti, ki velja za katerokoli PhET simulacijo.<br>(Več <a href=\"{1}\">podrobnosti</a>).",
            "Common.choice.ok": "OK",
            "Common.About.Version": "Verzija:",
            "Common.ErrorDialog.contactPhet": "Če se težave nadaljujejo, pošljite spodnje podorbnosti na {0}",
            "Common.About.CreditsDialog.lead-design": "Glavni dizajn",
            "Common.OptionsMenu.mnemonic": "M",
            "Common.statistics.user_preference_file_creation_time": "Čas izdelave datotek nastavitev:",
            "Common.HelpMenu.AboutMnemonic": "v",
            "Common.updates.errorWritePermissions": "<html>Posodobitve ni mogoče izvesti.<br>Nimate dovoljenja za pisanje na {0}.<br>Obrnite se na vašega sistemskega administratorja.<br></html>",
            "ColorChooser.hsbBrightnessText": "B",
            "Common.choice.no": "Ne",
            "Common.About.WebLink": "Obiščite strani PhET",
            "Common.About.OSVersion": "Verzija OS",
            "Common.title.warning": "Opozorilo",
            "Common.updates.versionComparison": "<html>Vaša trenutna verzija \"{0}\" je {1}.<br>Na voljo je novejša verzija ({2}).</html>",
            "Common.statistics.sim_locale_language": "Jezik:",
            "Common.statistics.user_installation_timestamp": "PhET namestitveni časovni žig:",
            "Common.statistics.message_version": "Verzija sporočila:",
            "Common.ModelSlider.Description": "Nepravilna vrednost.",
            "Common.updates.installer.moreMessage": "<html>Z rednim posodabljanjem Offline Website Installer-ja, si zagotovite<br>dostop do najnovejših PhET simulacij in dodatnega gradiva.<br><br>Če izberete prenos najnovejše različice, se bo v brskalniku odprla<br>stran PhET, s katere si prenesete PhET offline namestitveni sistem.</html>",
            "ControlPanel.message.confirmResetAll": "Ponastavi vse nastavitve?",
            "Common.HelpMenu.Help": "Pomoč",
            "Common.updates.errorNotAJar": "{0} ni JAR datoteka.",
            "Games.label.levelControl": "Težavnost:",
            "Common.updates.automaticallyCheck": "Samodejno preverjaj za posodobitvami",
            "Common.sim.speed": "...hitrost simulacije...",
            "Common.updates.checkForSimUpdate": "Preveri posodobitve simulacije...",
            "XMLPersistenceManager.save.confirm.message": "<html>Datoteka že obstaja.<br>Ali jo želite prepisati?</html>",
            "FileChooser.newFolderErrorText": "Napaka pri ustvarjanju nove mape",
            "Common.About.CreditsButton": "Zasluge...",
            "Common.updates.skipThisUpdate": "Preskoči to verzijo",
            "Common.FileMenu.Save.mnemonic": "S",
            "FileChooser.saveDialogTitleText": "Shrani",
            "XMLPersistenceManager.load.title": "Naloži nastavitve",
            "Common.updates.checkForInstallerUpdate": "Preveri za PhET offline namestitveni sistem...",
            "timeseries.control.panel.playback": "Predvajanje",
            "Common.updates.progressDialogTitle": "Posodabljanje",
            "Common.HelpMenu.Title": "Pomoč",
            "ColorChooser.rgbNameText": "RGB",
            "FileChooser.fileNameLabelText": "Ime datoteke:",
            "Common.softwareAgreement.title": "Licenca programske opreme",
            "Common.statistics.host_java_version_minor": "Verzija Jave (manjša):",
            "Common.HelpMenu.TitleMnemonic": "p",
            "Common.About.CreditsDialog.interviews": "Intervjuji",
            "Common.About.Distribution": "Distribucija:",
            "Common.statistics.host_java_webstart_version": "Verzija Java Web Start",
            "XMLPersistenceManager.save.error.message": "<html>Napaka pri shranjevanju:<br>{0}</html>",
            "Games.label.time": "Čas: {0}",
            "FileChooser.openButtonText": "Odpri",
            "ColorChooser.sampleText": "Vzorčno besedilo Vzorčno besedilo",
            "Common.statistics.details.description": "<html>Spodaj prikazani podatki bodo poslani na PhET vsakič ob zagonu simulacije.</html>",
            "Common.statistics.host_os_version": "Verzija operacijskega sistema:",
            "Common.title.confirm": "Potrdi",
            "Common.BasicPhetPanel.LogoToolTip": "Onemogoči celozaslonski okvir",
            "Games.label.score.max": "Rezultat: {0} od {1}",
            "Common.statistics.host_java_timezone": "Časovni pas:",
            "Common.time.slow": "počasi",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.ClockControlPanel.Rewind": "Nazaj",
            "Common.softwareAgreement.accept": "Sprejmi in nadaljuj",
            "message.valueOutOfRange": "Vrednost mora biti med {0} in {1}.",
            "Common.updates.updateToDate": "Posodobljeno",
            "Common.ClockControlPanel.Pause": "Pavza",
            "PhetApplication.StartupDialog.message": "\"{0}\" se nalaga",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Program uporablja naslednjo programsko opremo",
            "XMLPersistenceManager.message.notAConfigFile": "Datoteka ne vsebuje konfiguracije za simulacijo.",
            "Common.preferences.updates": "Posodobitve",
            "Games.label.score.max.perfect": "Rezultat: {0} od {1} (ODLIČNO!)",
            "Common.HelpMenu.MegaHelpMnemonic": "m",
            "Common.statistics.enabled": "Dovoli pošiljanje podatkov na PhET",
            "Common.ClockControlPanel.StepBack": "Korak nazaj",
            "Common.StopwatchPanel.stop": "Stop",
            "Common.HelpPanel.MegaHelp": "MegaPomoč...",
            "Common.statistics.host_locale_country": "Država:",
            "Common.StopwatchPanel.reset": "Ponastavitev",
            "Common.playback": "Predvajanje",
            "Common.statistics.sim_minor_version": "Verzija simulacije (minor):",
            "Games.message.confirmNewGame": "<html>Igre še ni konec.<br>Ali želite začeti novo igro?</html>",
            "Common.updates.tryIt": "Pred posodobitvijo preizkusite novo verzijo",
            "ColorChooser.rgbBlueText": "Modra",
            "Common.choice.close": "Zapri",
            "Common.ClockControlPanel.Play": "Predvajaj",
            "Common.statistics.sim_type": "Vrsta simulacije:",
            "FileChooser.saveButtonText": "Shrani",
            "Common.rewind": "Nazaj",
            "Common.StopwatchPanel.start": "Start",
            "Common.updates.youHaveCurrent": "Uporabljate najnovejšo verzijo ({0}) od {1}.",
            "Common.statistics.sim_sessions_since": "Število zagonov simulacije od zadnjega online dostopa:",
            "Common.statistics.host_java_vendor": "Java prodajalec:",
            "charts.show-graphs": "Prikaži grafe:",
            "Common.statistics.message_type": "Vrsta sporočila:"
        } );