// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.geneexpressionbasics;

import java.awt.image.BufferedImage;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Resources (images and translated strings) for "GeneExpressionBasics" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator$8
 * See #2967
 */
public class GeneExpressionBasicsResources {
    public static final String NAME = "gene-expression-basics";
    public static final PhetResources RESOURCES = new PhetResources( NAME );

    //Strings

    //Images
    public static final BufferedImage GRAY_ARROW = RESOURCES.getImage( "gray-arrow.png" );
}