//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_tk.properties
define( {
            "Games.label.level": "Dereje: {0}",
            "Common.updates.errorMessage": "Täzelenjek bolanda ýalňyşlyk ýüze çykdy.<br>Soňrak ýenede synanşyň, ýa-da şu ýere baryp görüň {0}.",
            "XMLPersistenceManager.save.error.encode": "<html>Faýly kodlamada ýalňyşlyk döredi:<br>{0}</html>?",
            "XMLPersistenceManager.load.error.decode": "<html>Faýl dekodlama edilende ýalňyşlyk ýüze çykdy:<br>{0}</html>",
            "Common.softwareAgreement.decline": "Çyk",
            "Common.statistics.host_os_name": "Operasion sistemanyň ady:",
            "Common.statistics.user_total_sessions": "Ähli simulýasiýalarynyň jemi näçe gezek işledilendikleriň sany:",
            "Common.statistics.host_java_version_major": "Java werisýasy (esasy):",
            "FileChooser.openDialogTitleText": "Aç",
            "Common.WhiteBackground": "Ak fon",
            "Common.statistics.host_java_version_maintenance": "Java werisýasy (bejeriş):",
            "FileChooser.lookInLabelText": "Serediň:",
            "Common.choice.cancel": "Goýbolsun et",
            "Common.updates.seePreferences": "Git Faýl->Go to File->Saýlanylan häsiýetler we ol ýerden özüňize gerekli sazlamalary ediň.",
            "Common.About.CreditsDialog.software-development": "Programmanyň taýýarlanylyşy",
            "Common.About.JavaVersion": "Java wersiýasy",
            "ColorChooser.resetText": "Yza gaýt",
            "wavelength.ir": "infragyzyl",
            "translation.credits": "PICT Turkmenistan",
            "Common.About.CreditsDialog.design-team": "Taýýarlap-düzen topar",
            "Common.statistics.sim_total_sessions": "Ähli simulýasiýalarynyň jemi näçe gezek işledilendikleriň sany:",
            "wavelength.uv": "ultramenewşe",
            "Games.title.gameSettings": "Oýunyň sazlamalary",
            "XMLPersistenceManager.save.title": "Konfigurasiýany ýatda sakla",
            "XMLPersistenceManager.load.error.contents": "Faýl ýa-da zaýa ýa-da ol bu simulýasiýa bilen döredilmändir.",
            "Common.statistics.details.title": "Maglumat",
            "Common.statistics.sim_dev_version": "Simulýasiýanyň wersiýasy (gyşarma):",
            "FileChooser.saveInLabelText": "Ýatda sakla şu ýerde:",
            "Common.statistics.sim_name": "Simulýasiýanyň ady:",
            "Save.confirm.message": "<html>Saýlan faýlyň eýýäm bar.<br>Ony şu ýatda saklajak faýly bilen çalşmaga isleýäňmi?</html>",
            "Games.label.score": "Bahaňyz: {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "PhET düzen adamlar",
            "Games.button.start": "Start",
            "Common.statistics.sim_deployment": "Ýerlemekligiň görnüşi",
            "Common.FileMenu.Save": "Konfigurasiýany ýada salmak...",
            "Common.About.CreditsDialog.licenseDetails": "Lisenziýa barada maglumat",
            "Games.radioButton.on": "açyk",
            "FileChooser.acceptAllFileFilterText": "Ähli faýllar (*.*)",
            "Common.ModelSlider.Minimum": "Minimum",
            "Common.FileMenu.Preferences": "Saýlanylan häsiýetler...",
            "Common.FileMenu.Load": "Konfigurasiýany ýükle",
            "Common.updates.downloadingSimJar": "Simulýasiýa JAR faýly...",
            "Games.radioButton.off": "ýapyk",
            "Jme.copyThisToTheClipboard": "Şuny kopiýa edip ýatda sakla",
            "ColorChooser.swatchesRecentText": "Söňky:",
            "Common.updates.updateAvailable": "Täzelenme bar",
            "Common.statistics.host_locale_language": "Ýerli dil:",
            "Common.clear": "Arassala",
            "Games.title.gameOver": "Oýun gutardy",
            "FileChooser.filesOfTypeLabelText": "Faýl tipi:",
            "Common.ErrorDialog.detailsTitle": "Ýalňyşlyk barada maglumat",
            "Common.HelpMenu.MegaHelp": "Mega kömek...",
            "Common.ClockControlPanel.Step": "Öňe bir ädim geçmek",
            "Common.statistics.sim_revision": "Simulýasiýanyň wersiýasy (üýtgedilen):",
            "Common.choice.yes": "Hawa",
            "Common.FileMenu.Title": "Faýl",
            "Common.statistics.sim_dev": "Bu düzüjiniň wersiýasy my?",
            "Common.updates.installer.message": "<html>PhET programmaňyzyň senesi {0}.<br>Has täze wersiýanyň senesi {1}.<br><br>Iň soňky PhET programmany almak isleýäňizmi?</html>",
            "Common.updates.updateNow": "Şu wagt täzele!",
            "Common.record": "Ýazmak",
            "Common.About.CreditsDialog.Title": "Awtorlar",
            "Common.updates.error.internetConnection": "<html>Birikdirip bolank {0},<br>Internet baglanşygy barlap görüň.</html>",
            "Common.time.fast": "çalt",
            "XMLPersistenceManager.load.error.message": "<html>Faýl açylanda ýalňyşlyk ýüze çykdy:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Maksimum",
            "Common.OptionsMenu": "Saýlamalar",
            "Common.ClockControlPanel.Restart": "Täzeden açmak",
            "Common.statistics.sim_version_timestamp": "Simulýasiýanyň wersiýasy (wagt belligi):",
            "Common.updates.installer.yes": "Hawa!",
            "Common.phetInstaller": "PhET özbaşdak web-saýt programma",
            "Jme.thisSimulationWasUnableToStart": "Simulýasiýany başlap bolmady.",
            "Common.HelpMenu.About": "Bu barada maglumat...",
            "Common.ModelSlider.OutOfRange": "Çäkden daşary çykýan baha",
            "Common.About.CreditsDialog.TranslationCreditsTitle": "Terjime eden",
            "ColorChooser.previewText": "Öňünden seredip görme",
            "Common.BasicPhetPanel.Title": "Yza dolanmak",
            "Common.HelpPanel.HideHelp": "Kömegi gizlemek",
            "Common.statistics.host_os_arch": "Prosessor tipi:",
            "Common.preferences.title": "Saýlanylan häsiýetler",
            "Games.button.newGame": "Täze oýun:",
            "Common.ModelSlider.YouEntered": "Siz girizdiňiz",
            "Games.label.newBest": "Siziň üçin indi täze iň gowy netije!",
            "Common.About.BuildDate": "Ýasalan wagty:",
            "Common.statistics.sim_project": "Proýektiň ady:",
            "Games.label.best": "Siziň üçin iň gowy netije:{0}",
            "Common.title.message": "Habar",
            "Common.updates.downloadingBootstrap": "Täzeleýan programma alnyp ýüklenýär...",
            "Common.title.error": "Ýalňyşlyk",
            "Common.FileMenu.Exit": "Çyk",
            "Common.statistics.sim_major_version": "Simulýasiýanyň wersiýasy (esasy):",
            "Common.updates.askMeLater": "Menden bu soragy soňrak sora",
            "chart-time-control.go": "Git!",
            "Common.confirm.clear.graphs": "Grafikleri çyndan hem aarassalamak isleýäňizmi?",
            "ColorChooser.swatchesNameText": "Nusgalar",
            "Common.updates.progressDialogMessage": "Täzelenýär wersiýa \"{0}\" şu wersiýa {1}",
            "Common.updates.installer.more": "Maňa has giňişleýin gürrüň ber...",
            "XMLPersistenceManager.title.error": "Ýalňyşlyk",
            "ControlPanel.button.resetAll": "Hemmesini yza gaýtar",
            "Common.About.AgreementButton": "Programma boýunça ylalaşyk...",
            "Common.ErrorDialog.detailsButton": "Goşmaça maglumat...",
            "Common.updates.errorMissingJar": "<html>Täzeläp bolanok.<br>Gerekli JARfaýl tapylmandyr: {0}.<br>Öz sistema administratoryňyza kömek üçin ýüzleniň.<br></html>",
            "Common.preferences.privacy": "Şahsy maglumatlar",
            "Common.HelpMenu.AboutTitle": "Bu barada maglumat",
            "ColorChooser.rgbRedText": "Gyzyl",
            "Common.statistics.sim_locale_country": "Ýurt:",
            "ColorChooser.rgbGreenText": "Ýaşyl",
            "Common.HelpPanel.ShowHelp": "Kömek et!",
            "PiccoloPhet.VelocitySensorNode.speed": "Tizlik",
            "Common.statistics.sim_distribution_tag": "Simulýasiýanyň wersiýasy (ýaýratma):",
            "Common.statistics.description": "PhET bu mugt berilýän programmadyr, ol grantlar hasabyna edilýär we onuň üçin bizden iň az möçberde <br>anonim <a href=\"{0}\">maglumat</a> ýygnalmagy talap edilýär, şeýlelikde PhET ulanylyşy hasaba alnyp <br> ulanyjylaryň täze isleglerini kanagatlandyrmaga ýardam edilýär.",
            "Common.softwareAgreement.message": "Ähli PhET simulýasiýalarynda, biz ýygnaýarys iň az möçberde anonim <a href=\"{0}\">maglumat</a>her gezek simulýasiýa başlanda <br> (meselem, wersiýa, operasion sistema barada).<br> Siz islendik pursatda bu maglumatlaryň iberilmegini Faýl-Saýlanan häsiýetler knopka arkaly kesip bilýäňiz.<br><br>\"Ylalaş we dowam et\"knopkany basyp,siz PhET<br>Programmasynyň ylalaşygy boýunça biziň Şahsy maglumatlara barada syýasadymyza hem ylalaşýaňyz şu we hemme başga PhET simulýasiýalary ulananyňyzda.<br>(goşmaça maglumat üçin basyň <a href=\"{1}\">şu ýere</a>).",
            "Common.choice.ok": "Bolýar",
            "Common.About.Version": "Wersiýa:",
            "Common.ErrorDialog.contactPhet": "Bu problem dowam etse, şu aşakdaky maglumatlary iberiň {0}",
            "Common.About.CreditsDialog.lead-design": "Baş dizaýn",
            "Jme.moreInformation": "<html><body>Wideokartaňyzy täzeläp şu problemany çözüp bolmagy mümkin.<br/>Has jikme-jik maglumat almak üçin, baryň {0},<br/> ýa-da şulary kopiýa edip email arkaly iberiň {1}.<br/></body></html>",
            "Common.statistics.user_preference_file_creation_time": "Islenen häsiýetleriň faýlynyň döredilmegiň wagt belligi",
            "Common.updates.errorWritePermissions": "<html>Buny täzeläp bolmady.<br>Bäri ýazmaga hakyňyz ýok {0}.<br>Öz sistema administratoryňyza kömek üçin ýüzleniň.<br></html>",
            "Common.choice.no": "Ýok",
            "Common.About.WebLink": "PhET web-sahypasyny gör",
            "Common.About.OSVersion": "Operasion sistemanyň wersiýasy",
            "Common.title.warning": "Duýduryş",
            "Common.updates.versionComparison": "<html>Şu wagtky wersiýaňyz \"{0}\" - {1}.<br>Has täze wersiýa ({2})bar.</html>",
            "Common.statistics.sim_locale_language": "Dil:",
            "Common.statistics.user_installation_timestamp": "PhET dikeltmegiň wagt belligi:",
            "Common.statistics.message_version": "Habaryň wersiýasy:",
            "Common.ModelSlider.Description": "Rugsat edilmeýän baha.",
            "Common.updates.installer.moreMessage": "<html>PhET özbaşdak web-saýt programmany täzeläp dursaňyz iň <br>soňky simulýasiýalar <br>we goşmaça materiallar eliňizde bolar.<br><br>Iň täze wersiýany almak isleseňiz <br>PhET web-saýty açylar, şol ýerden<br>tsoňky PhET programmany alyp bilersiňiz.</html>",
            "ControlPanel.message.confirmResetAll": "Ähli sazlamalary täzeden dikeltmeli?",
            "Common.HelpMenu.Help": "Kömek",
            "Common.updates.errorNotAJar": "{0}bu JAR faýl däl.",
            "Games.label.levelControl": "Dereje:",
            "Common.updates.automaticallyCheck": "Täzelenmeleri awtomatik barla",
            "Common.sim.speed": "Simulýasiýa tizligi",
            "Common.updates.checkForSimUpdate": "Simulýasiýanyň täzelenmelerini barla...",
            "XMLPersistenceManager.save.confirm.message": "<html>Saýlan faýlyňyz eýýäm bar.<br>Ony şu ýatda saklajak faýly bilen çalşmaga isleýäňmi?</html>",
            "FileChooser.newFolderErrorText": "Täze papka açmaklyk bilen ýalňyşlyk ýüze çykdy",
            "Common.updates.skipThisUpdate": "Bu wersiýadan böküp geç",
            "Common.About.CreditsButton": "Awtorlar...",
            "FileChooser.saveDialogTitleText": "Ýatda sakla",
            "Common.TeacherMenu": "Mugallym",
            "XMLPersistenceManager.load.title": "Konfigurasiýany ýükle",
            "Common.updates.checkForInstallerUpdate": "PhET täzelenmeleri barlap gör...",
            "timeseries.control.panel.playback": "Oýnat",
            "Common.updates.progressDialogTitle": "Täzelenip dur...",
            "Common.HelpMenu.Title": "Kömek",
            "FileChooser.fileNameLabelText": "Faýl ady:",
            "Common.softwareAgreement.title": "Programma boýunça ylalaşyk",
            "Common.statistics.host_java_version_minor": "Java werisýasy (goşmaça):",
            "Common.About.CreditsDialog.interviews": "Söhbetdeşlikler",
            "Common.About.Distribution": "Ýaýratma:",
            "Common.statistics.host_java_webstart_version": "Java Web Start werisýasy:",
            "XMLPersistenceManager.save.error.message": "<html>Faýl ýazmaklyk bilen ýalňyşlyk döredi:<br>{0}</html>",
            "Games.label.time": "Wagt:{0}",
            "FileChooser.openButtonText": "Aç",
            "ColorChooser.sampleText": "Nusgalyk tekst Nusgalyk tekst",
            "Common.statistics.details.description": "<html>Aşakdaky magllumat PhET üçin iberiler her simulýasiýa başlanda.</html>",
            "Common.statistics.host_os_version": "Operasion sistemanyň wersiýasy:",
            "Common.title.confirm": "Tassykla",
            "Common.BasicPhetPanel.LogoToolTip": "Ramkany doly aýyr",
            "Games.label.score.max": "Bahaňyz: {0} out of {1}",
            "Common.statistics.host_java_timezone": "Wagt zonasy",
            "Common.time.slow": "haýal",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.ClockControlPanel.Rewind": "Sarap geçirmek",
            "Common.softwareAgreement.accept": "Ylalaş we dowam et",
            "message.valueOutOfRange": "Bahalar bolmaly şu aralykda - {0} we {1}.",
            "Common.updates.updateToDate": "Täze",
            "Common.ClockControlPanel.Pause": "Arakesme etmek",
            "PhetApplication.StartupDialog.message": "\"{0}\" açylýar",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Bu programma şeýle keseki programmalary ulanýar:",
            "XMLPersistenceManager.message.notAConfigFile": "Bu faýlyň şu simulýasiýa üçin konfigurasiýasy ýok",
            "Common.preferences.updates": "Täzelenme",
            "Games.label.score.max.perfect": "Bahaňyz: {0} out of {1}",
            "Common.statistics.enabled": "PhET ýçin maglumat ibermäge rugsat ber",
            "Common.ClockControlPanel.StepBack": "Yza bir ädim geçmek",
            "Common.HelpPanel.MegaHelp": "Mega kömek",
            "Common.statistics.host_locale_country": "Ýurt:",
            "Common.StopwatchPanel.reset": "Yza gaýt",
            "Common.playback": "Oýnatmak",
            "Common.statistics.sim_minor_version": "Simulýasiýanyň wersiýasy (goşmaça):",
            "Games.message.confirmNewGame": "<html>Bu oýuny entek gutarmadyň.<br>Çyndan hem täze oýuny başlamak isleýäňmi?</html>",
            "Common.updates.tryIt": "Täzelemkden öň by täze wersiýany deňäp gör.",
            "ColorChooser.rgbBlueText": "Gök",
            "Common.choice.close": "Ýap",
            "Common.ClockControlPanel.Play": "Oýnatmak",
            "Common.statistics.sim_type": "Simulýasiýanyň tipi:",
            "FileChooser.saveButtonText": "Ýatda sakla",
            "Common.rewind": "Saramak",
            "Common.updates.youHaveCurrent": "Sizde iň soňky wersiýa bar ({0}) - {1}.",
            "Common.statistics.sim_sessions_since": "Bu simulýasiýanyň soňky näçe gezek online işledilendigiň sany:",
            "Common.statistics.host_java_vendor": "Java üpjün ediji:",
            "charts.show-graphs": "Grafikleri görkez:",
            "Common.statistics.message_type": "Habaryň görnüşi:"
        } );