// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.chemicalreactions;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Resources (images and translated strings) for "ChemicalReactions" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator
 */
public class ChemicalReactionsResources {
    public static final String PROJECT_NAME = "chemical-reactions";
    public static final PhetResources RESOURCES = new PhetResources( PROJECT_NAME );

    //Strings
    public static class Strings {
        public static final String TITLE__CHEMICAL_REACTIONS = RESOURCES.getLocalizedString( "title.chemicalReactions" );
    }

    //Images
    public static class Images {

    }
}