//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_fi.properties
define( {
            "Games.label.level": "Taso: {0}",
            "Common.updates.errorMessage": "Päivityksessä tapahtui virhe.<br>Yritä uudelleen myöhemmin tai käy: {0}.",
            "XMLPersistenceManager.save.error.encode": "<html>Virhe tulkattaessa tiedostoa:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Virhe tulkattaessa tiedostoa:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "t",
            "Common.softwareAgreement.decline": "Poistu",
            "Common.statistics.host_os_name": "Käyttöjärjestelmä",
            "Common.statistics.user_total_sessions": "Kaikkien simulaatioiden suorituskertojen kokonaismäärä",
            "Common.statistics.host_java_version_major": "Javaversio (major)",
            "FileChooser.openDialogTitleText": "Avaa",
            "Common.WhiteBackground": "Valkoinen tausta",
            "Common.statistics.host_java_version_maintenance": "Javaversio (maintenance)",
            "FileChooser.lookInLabelText": "Tarkastele:",
            "Common.choice.cancel": "Peruuta",
            "Common.updates.seePreferences": "Klikkaa Tiedosto ->Omat säädöt mukauttaaksesi ohjelmaa",
            "Common.About.CreditsDialog.software-development": "Ohjelmistokehitys",
            "Common.About.JavaVersion": "Javaversio:",
            "ColorChooser.resetText": "Alusta",
            "wavelength.ir": "InfraP",
            "Common.WhiteBackground.mnemonic": "v",
            "Common.About.CreditsDialog.design-team": "Suunnittelutiimi",
            "Common.statistics.sim_total_sessions": "Simulaation suorituskertojen kokonaismäärä",
            "Common.FileMenu.PreferencesMnemonic": "O",
            "wavelength.uv": "UltraV",
            "Games.title.gameSettings": "Peliasetukset",
            "XMLPersistenceManager.save.title": "Tallenna alustustiedot",
            "XMLPersistenceManager.load.error.contents": "Tiedosto on viottunut tai sitä ei ole luotu tällä simulaatiolla.",
            "Common.statistics.details.title": "Tietoja",
            "Common.statistics.sim_dev_version": "Simulaation versio (kehit.)",
            "FileChooser.saveInLabelText": "Tallenna nimellä:",
            "Common.statistics.sim_name": "Simulaation nimi",
            "Save.confirm.message": "<html>Tiedosto on jo olemassa.<br>Haluatko korvata se tällä tiedostolla?</html>",
            "Games.label.score": "Pisteet: {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "PhET kehittäjätiimi",
            "Games.button.start": "Aloita",
            "Common.statistics.sim_deployment": "Päivittäminen (depl.)",
            "Common.FileMenu.Save": "Tallenna alustustiedot...",
            "Common.About.CreditsDialog.licenseDetails": "Käyttöoikeustiedot",
            "ColorChooser.hsbSaturationText": "Kylläisyys",
            "Games.radioButton.on": "päälle",
            "FileChooser.acceptAllFileFilterText": "Kaikki tiedostot (*.*)",
            "ColorChooser.hsbNameText": "Värimalli HSB",
            "Common.ModelSlider.Minimum": "Minimiarvo",
            "Common.FileMenu.Preferences": "Asetukset...",
            "Common.FileMenu.Load": "Avaa alustustiedot...",
            "Common.updates.downloadingSimJar": "ladataan simulaation JAR-tiedostoa...",
            "Games.radioButton.off": "pois",
            "ColorChooser.swatchesRecentText": "Edellinen:",
            "Common.updates.updateAvailable": "Päivitys saatavissa",
            "Common.statistics.host_locale_language": "Kieli",
            "Common.clear": "Tyhjennä",
            "Games.title.gameOver": "Peli päättyi",
            "FileChooser.filesOfTypeLabelText": "Tiedostojen tyyppi:",
            "Common.ErrorDialog.detailsTitle": "Virhetiedot",
            "Common.HelpMenu.MegaHelp": "Opastus...",
            "Common.ClockControlPanel.Step": "Askel",
            "Common.statistics.sim_revision": "Simulaation versio (korjattu)",
            "Common.choice.yes": "Kyllä",
            "PiccoloPhet.VelocitySensorNode.unknown": "?",
            "Common.FileMenu.Title": "Tiedosto",
            "Common.value_units": "{0} {1}",
            "Common.statistics.sim_dev": "Onko tämä kehittäjän versio?",
            "Common.updates.installer.message": "<html>Sinun PhET:n nettiasentajasi päiväys on {0}.<br>Uudempi versio {1} on nyt saatavilla.<br><br>Haluatko ladata uusimman nettiasentajan?</html>",
            "Common.updates.updateNow": "Päivitä nyt!",
            "Common.record": "Tallenna",
            "Common.About.CreditsDialog.Title": "Kehittäjät",
            "Common.updates.error.internetConnection": "<html>Ei saada yhteys kohteeseen {0}.<br>Tarkista yhteytesi Internetiin.</html>",
            "Common.time.fast": "nopea",
            "XMLPersistenceManager.load.error.message": "<html>Virhe luettaessa tiedostoa:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Maksimiarvo",
            "Common.OptionsMenu": "Asetukset",
            "Common.ClockControlPanel.Restart": "Jatka",
            "Common.statistics.sim_version_timestamp": "Simulaation versio (aikaleima)",
            "Common.updates.installer.yes": "Kyllä!",
            "Common.phetInstaller": "PhET:n nettiasentaja",
            "Common.HelpMenu.About": "Tietoja...",
            "Common.ModelSlider.OutOfRange": "Arvo ei ole sallituissa rajoissa",
            "Common.About.CreditsDialog.TranslationCreditsTitle": "Kielikäännöksen tekijä:",
            "ColorChooser.previewText": "Esikatsele",
            "Common.BasicPhetPanel.Title": "Takaisin",
            "Common.HelpPanel.HideHelp": "Piilota ohje",
            "Common.statistics.host_os_arch": "Prosessorin tyyppi",
            "Common.preferences.title": "Omat säädöt",
            "Games.button.newGame": "Uusi peli",
            "ColorChooser.hsbRedText": "Punainen",
            "ColorChooser.hsbBlueText": "Sininen",
            "Common.ModelSlider.YouEntered": "Kirjoitit",
            "Games.label.newBest": "Uusi ennätys!",
            "Common.About.BuildDate": "Käännetty:",
            "Common.FileMenu.ExitMnemonic": "P",
            "Common.statistics.sim_project": "Projektin nimi",
            "Games.label.best": "Paras tulos: {0}",
            "Common.title.message": "Viesti",
            "Common.updates.downloadingBootstrap": "ladataan päivitysohjelmaa...",
            "Common.title.error": "Virhe",
            "Common.FileMenu.Exit": "Poistu",
            "Common.statistics.sim_major_version": "Simulaation versio (major)",
            "Common.updates.askMeLater": "Kysy myöhemmin",
            "chart-time-control.go": "Nyt!",
            "Common.HelpMenu.HelpMnemonic": "o",
            "Common.confirm.clear.graphs": "Haluatko varmasti tyhjentää kuvaajat?",
            "ColorChooser.swatchesNameText": "Värikartta",
            "Common.updates.progressDialogMessage": "Päivittää \"{0}\" versioksi {1}",
            "Common.updates.installer.more": "Kerro lisää...",
            "XMLPersistenceManager.title.error": "Virhe",
            "ColorChooser.hsbHueText": "Värisävy",
            "ControlPanel.button.resetAll": "Alusta kaikki",
            "Common.About.AgreementButton": "Käyttöehdot...",
            "Common.FileMenu.Load.mnemonic": "A",
            "Common.ErrorDialog.detailsButton": "Lisätietoa...",
            "Common.updates.errorMissingJar": "<html>Päivitys ei onnistu, koska ei pystytä<br>määrittämään kansiota JAR-tiedostolle: {0}.<br>Ota yhteys järjestelmävalvojaan.<br></html>",
            "Common.preferences.privacy": "Yksityisyys",
            "Common.HelpMenu.AboutTitle": "Tietoja",
            "ColorChooser.rgbRedText": "Punainen",
            "Common.statistics.sim_locale_country": "Maa",
            "ColorChooser.hsbGreenText": "Vihreä",
            "ColorChooser.rgbGreenText": "Vihreä",
            "Games.format.time.best": "{0} ({1})",
            "Common.HelpPanel.ShowHelp": "Ohje",
            "PiccoloPhet.VelocitySensorNode.speed": "Nopeus",
            "Common.statistics.sim_distribution_tag": "Simulaation versio (jakelu)",
            "Common.statistics.description": "PhET tarjotaan käytettäväksi ilmaiseksi<br>ehdolla, että voidaan kerätä anonyymiä <br><a href=\"{0}\">tietoa</a> simulaatioiden<br>käyttömääristä ja siten huomioida paremmin käyttäjien <br>tarpeita.",
            "Common.softwareAgreement.message": "Kaikissa PhET:n simulaatioissa keräämme <br>hieman anonyymiä <a href=\"{0}\">tietoa</a> jokaisen käynnistyksen yhteydessä <br>(mm. simulaation ja käyttöjärjestelmän versio). Voit estää<br> tiedon lähettämisen valikosta Tiedosto -> Omat säädöt. <br><br>Klikkaamalla \"Hyväksy ja Jatka\", hyväksyt PhET:n käyttöehdot, <br>mukaan lukien yksityisyys käytäntömme, tälle ja kaikille<br> seuraaville PhET:n simulaatioiden käyttökerroille. (Lisätietoa löydät <a href=\"{1}\">täältä</a>).",
            "Common.choice.ok": "Hyväksy",
            "Common.About.Version": "Versio:",
            "Common.ErrorDialog.contactPhet": "Jos ongelma jatkuu, lähetä alla olevat tiedot tukeen: {0}",
            "Common.About.CreditsDialog.lead-design": "Pääsuunnittelija",
            "Common.OptionsMenu.mnemonic": "A",
            "Common.statistics.user_preference_file_creation_time": "Omat säädöt- tiedoston luontiaika",
            "Common.HelpMenu.AboutMnemonic": "T",
            "Common.updates.errorWritePermissions": "<html>Päivitys ei onnistu. Onko<br>sinulla riittävät oikeudet kansioon {0}.<br>Ota yhteys järjestelmävalvojaan.<br></html>",
            "ColorChooser.hsbBrightnessText": "Kirkkaus",
            "Common.choice.no": "Ei",
            "Common.About.WebLink": "Käy PhET:n kotisivulla",
            "Common.About.OSVersion": "Käyttöjärjestelmäversio:",
            "Common.title.warning": "Varoitus",
            "Common.updates.versionComparison": "<html>Nykyinen versiosi ohjelmasta \"{0}\" on {1}.<br>Uudempi versio ({2}) on saatavissa.</html>",
            "Common.statistics.sim_locale_language": "Kieli",
            "Common.statistics.user_installation_timestamp": "PhET:n asennuksen aikaleima",
            "Common.statistics.message_version": "Viestin versio",
            "Common.ModelSlider.Description": "Sopimaton arvo.",
            "Common.updates.installer.moreMessage": "<html>Pitämällä PhET:n nettiasentajan ajan tasalla <br>varmistaa sen, että sinulla on pääsy viimeisimpiin PhET-simulaatioihin <br>ja niitä tukeviin materiaaleihin.<br><br>Jos haluat uusimman version, verkkoselain <br>avaa PhET:n kotisivun, josta voit ladata<br>nettiasentajan koneellesi.</html>",
            "Common.HelpMenu.Help": "Ohje",
            "Common.updates.errorNotAJar": "{0} ei ole JAR-tiedosto.",
            "ControlPanel.message.confirmResetAll": "Haluatko alustaa kaikki asetukset?",
            "Games.label.levelControl": "Taso:",
            "Common.updates.automaticallyCheck": "Tarkista päivitykset automaattisesti",
            "Common.sim.speed": "Simulaationopeus",
            "Common.updates.checkForSimUpdate": "Tarkista, onko simulaatioon päivitystä...",
            "XMLPersistenceManager.save.confirm.message": "<html>Tiedosto on jo olemassa.<br>Haluatko korvata se tällä tiedostolla?</html>",
            "FileChooser.newFolderErrorText": "Virhe luotaessa uusi kansio",
            "Common.About.CreditsButton": "Kehittäjät...",
            "Common.updates.skipThisUpdate": "Jätä tämä versio väliin",
            "Common.FileMenu.Save.mnemonic": "T",
            "Common.TeacherMenu": "Opettaja",
            "FileChooser.saveDialogTitleText": "Tallenna",
            "XMLPersistenceManager.load.title": "Avaa alustustiedot",
            "Common.updates.checkForInstallerUpdate": "Tarkista, onko PhET:n nettiasentajaan päivitystä...",
            "timeseries.control.panel.playback": "Toista nauhoitus",
            "Common.updates.progressDialogTitle": "Päivitys",
            "Common.HelpMenu.Title": "Ohje",
            "Common.TeacherMenu.mnemonic": "O",
            "ColorChooser.rgbNameText": "Värimalli RGB",
            "FileChooser.fileNameLabelText": "Tiedoston nimi:",
            "Common.softwareAgreement.title": "Käyttöehdot",
            "Common.statistics.host_java_version_minor": "Javaversio (minor)",
            "Common.HelpMenu.TitleMnemonic": "o",
            "Common.About.CreditsDialog.interviews": "Haastattelut",
            "Common.About.Distribution": "Jakelu:",
            "Common.statistics.host_java_webstart_version": "Javan Web Start versio",
            "XMLPersistenceManager.save.error.message": "<html>Virhe kirjoitettaessa tiedostoon:<br>{0}</html>",
            "Games.label.time": "Aika: {0}",
            "FileChooser.openButtonText": "Avaa",
            "ColorChooser.sampleText": "Esimerkkiteksti Esimerkkiteksti",
            "Common.statistics.details.description": "<html>Alla näkyvät tiedot lähetetään PhET:iin aina simulaation käynnistämisen yhteydessä.</html>",
            "Common.statistics.host_os_version": "Käyttöjärjestelmän versio",
            "Common.title.confirm": "Vahvista",
            "Common.BasicPhetPanel.LogoToolTip": "Rajoita ikkunaa",
            "Games.label.score.max": "Pisteet: {0} / {1}",
            "Common.statistics.host_java_timezone": "Aikavyöhyke",
            "Common.time.slow": "hidas",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.ClockControlPanel.Rewind": "Kelaa",
            "Common.softwareAgreement.accept": "Hyväksy ja jatka",
            "message.valueOutOfRange": "Arvon tulee olla väliltä {0} ja {1}.",
            "Common.updates.updateToDate": "Päivitykseen",
            "Common.ClockControlPanel.Pause": "Pysäytä",
            "PhetApplication.StartupDialog.message": "\"{0}\" käynnistyy",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Ohjelman käyttämät kolmannen osapuolen ohjelmat",
            "XMLPersistenceManager.message.notAConfigFile": "Tässä tiedostossa ei ole alustustietoja tälle simulaatiolle.",
            "Common.preferences.updates": "Päivitykset",
            "Games.label.score.max.perfect": "Pisteet: {0} / {1} (Huipputulos!)",
            "Common.HelpMenu.MegaHelpMnemonic": "p",
            "Common.statistics.enabled": "Salli tietojen lähettäminen PhET:lle",
            "Common.ClockControlPanel.StepBack": "Askel taakse",
            "Common.StopwatchPanel.stop": "Pysäytä",
            "Common.HelpPanel.MegaHelp": "Opastus...",
            "Common.statistics.host_locale_country": "Maa",
            "Common.StopwatchPanel.reset": "Alusta",
            "Common.playback": "Toista nauhoitus",
            "Common.statistics.sim_minor_version": "Simulaation versio (minor)",
            "Games.message.confirmNewGame": "<html>Peli on kesken.<br>Haluatko varmasti aloittaa uuden pelin?</html>",
            "Common.updates.tryIt": "Kokeile uusinta versiota ennen päivitystä.",
            "ColorChooser.rgbBlueText": "Sininen",
            "Common.choice.close": "Sulje",
            "Common.ClockControlPanel.Play": "Käynnistä",
            "Common.statistics.sim_type": "Simulaation tyyppi",
            "FileChooser.saveButtonText": "Tallenna",
            "Common.rewind": "Kelaa",
            "Common.StopwatchPanel.start": "Käynnistä",
            "Common.updates.youHaveCurrent": "Sinulla on viimeisin versio ({0}) päivityksestä {1}.",
            "Common.statistics.sim_sessions_since": "Simulaation suorituskertojen määrä sitten edellisen verkkoyhteyden",
            "Common.statistics.host_java_vendor": "Javan myyjä",
            "charts.show-graphs": "Näytä kuvaajat:",
            "Common.statistics.message_type": "Viestin tyyppi"
        } );