//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_sv.properties
define( {
            "Common.updates.errorMessage": "Ett fel uppstod vid uppdateringen.<br> Var vänlig, försök senare eller besök{0}.",
            "XMLPersistenceManager.save.error.encode": "<html>Fel vid kodning av fil:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Fel vid avkodning av fil:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "f",
            "Common.softwareAgreement.decline": "Avsluta",
            "FileChooser.openDialogTitleText": "Öppna",
            "FileChooser.lookInLabelText": "Titta i:",
            "Common.choice.cancel": "Avbryt",
            "Common.updates.seePreferences": "Gå till Fil-> Inställningar för att ändar dina inställningar.",
            "Common.About.CreditsDialog.software-development": "Mjukvaru utveckling",
            "Common.About.JavaVersion": "Java version:",
            "ColorChooser.resetText": "Återställ",
            "wavelength.ir": "IR",
            "Common.FileMenu.PreferencesMnemonic": "p",
            "wavelength.uv": "UV",
            "XMLPersistenceManager.save.title": "Spara konfiguration",
            "XMLPersistenceManager.load.error.contents": "Filen är trasig eller skapades inte av denna simulering.",
            "Common.statistics.details.title": "Information",
            "FileChooser.saveInLabelText": "Spara i:",
            "Save.confirm.message": "<html>Filen du valde finns redan.<br>Vill du ersätta den med filen du önskar spara?</html>",
            "Common.FileMenu.Save": "Spara inställningar",
            "ColorChooser.hsbSaturationText": "S",
            "FileChooser.acceptAllFileFilterText": "Alla filer (*.*)",
            "ColorChooser.hsbNameText": "HSB",
            "Common.ModelSlider.Minimum": "Minimum",
            "Common.FileMenu.Preferences": "Förval...",
            "Common.FileMenu.Load": "Ladda konfiguration",
            "ColorChooser.swatchesRecentText": "Senaste:",
            "Common.updates.updateAvailable": "Uppdatering tillgänglig",
            "Common.clear": "Rensa",
            "FileChooser.filesOfTypeLabelText": "Filtyp:",
            "Common.ErrorDialog.detailsTitle": "Felinformation",
            "Common.HelpMenu.MegaHelp": "MegaHjälp",
            "Common.ClockControlPanel.Step": "Steg",
            "Common.choice.yes": "Ja",
            "Common.FileMenu.Title": "Fil",
            "Common.value_units": "{0} {1}",
            "Common.updates.installer.message": "<html> Din PhET Offline webbplats Installation är gammal {0}. <br> En nyare version finns tillgänglig, daterad {1}. <br> Vill du få den senaste Phet Offline Webbsida Installer installerad? </html>",
            "Common.updates.updateNow": "Uppdatera nu!",
            "Common.record": "Spela in",
            "Common.updates.error.internetConnection": "<html>Kan inte ansluta till {0},<br>kontrollera din internetuppkoppling.</html> ",
            "Common.time.fast": "snabb",
            "XMLPersistenceManager.load.error.message": "<html>Fel vid läsning av fil:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Maximum",
            "Common.OptionsMenu": "Alternativ",
            "Common.ClockControlPanel.Restart": "Omstart",
            "Common.updates.installer.yes": "Ja!",
            "Common.phetInstaller": "PhET Offline Website Installer",
            "Common.HelpMenu.About": "Om...",
            "Common.ModelSlider.OutOfRange": "Värde utanför intervallet",
            "ColorChooser.previewText": "Förhandsvisning",
            "Common.BasicPhetPanel.Title": "Välj",
            "Common.HelpPanel.HideHelp": "Göm Hjälp",
            "Common.preferences.title": "Inställningar",
            "ColorChooser.hsbRedText": "R",
            "ColorChooser.hsbBlueText": "B",
            "Common.ModelSlider.YouEntered": "Du skrev",
            "Common.FileMenu.ExitMnemonic": "x",
            "Common.title.message": "Meddelande",
            "Common.title.error": "Fel",
            "Common.FileMenu.Exit": "Avsluta",
            "Common.updates.askMeLater": "Fråga mig senare",
            "chart-time-control.go": "Kör!",
            "Common.HelpMenu.HelpMnemonic": "h",
            "Common.confirm.clear.graphs": "Är du säker på att du vill rensa graferna?",
            "ColorChooser.swatchesNameText": "Blandare",
            "Common.updates.progressDialogMessage": "Uppdatera \"{0}\" till version {1}",
            "Common.updates.installer.more": "Berätta mer...",
            "XMLPersistenceManager.title.error": "Fel",
            "ColorChooser.hsbHueText": "H",
            "ControlPanel.button.resetAll": "Återställ allt",
            "Common.About.AgreementButton": "Mjukvaruavtal...",
            "Common.FileMenu.Load.mnemonic": "L",
            "Common.ErrorDialog.detailsButton": "Detaljer...",
            "Common.updates.errorMissingJar": "<html>Uppdateringen kan inte utföras. <br>Hittar inte JAR-filen: {0}. <br> Kontakta din systemadministratör om hjälp. <br></html>",
            "Common.preferences.privacy": "Privacy",
            "Common.HelpMenu.AboutTitle": "Om",
            "ColorChooser.rgbRedText": "Röd",
            "ColorChooser.hsbGreenText": "G",
            "ColorChooser.rgbGreenText": "Grön",
            "Common.HelpPanel.ShowHelp": "Hjälp!",
            "Common.statistics.description": "PhET görs fritt tillgänglig genom bidrag som <br> kräver att vi samlar in en minimal mängd av <br> anonym <a href=\"{0}\"> information </a> för att dokumentera <br>nyttjandegraden av PhET-simuleringar <br> och för att bättre serva våra användares behov.",
            "Common.softwareAgreement.message": "I alla PhET-simuleringar samlar vi en minimal mängd <br> av anonym  <a href=\"{0}\">information</a> varje gång simuleringen startar <br> (t.ex. simuleringsversion, operativsystem). <Br > Du kan inaktivera sändning av denna information <br> via Arkiv-> Inställningar menyalternativet. <br> Genom att klicka på \"Godkänn och fortsätt\" godkänner du PhET' s <br> programvaruavtal , inklusive vår policy <br> för denna samt i alla PhET-simuleringar du kör. <br> (För detaljer, klicka<a href=\"{1}\"> här </a>).",
            "Common.choice.ok": "OK",
            "Common.About.Version": "Version:",
            "Common.ErrorDialog.contactPhet": "Om problemet kvarstår, skicka informationen nedan till {0}",
            "Common.OptionsMenu.mnemonic": "O",
            "Common.HelpMenu.AboutMnemonic": "a",
            "Common.updates.errorWritePermissions": "<html>Uppdateringen kan inte utföras. <br> Du har inte behörighet att skriva till {0}. <br> Kontakta din systemadministratör om hjälp. <br> </html>",
            "ColorChooser.hsbBrightnessText": "B",
            "Common.choice.no": "Nej",
            "Common.About.WebLink": "Besök PhET webbsida",
            "Common.About.OSVersion": "OS version:",
            "Common.title.warning": "Varning",
            "Common.updates.versionComparison": "<html>Din nuvarande version av\"{0}\" är {1}. <br>En nyare version ({2}) är tillgänglig.</html>",
            "Common.ModelSlider.Description": "Otillåtet värde.",
            "Common.updates.installer.moreMessage": "<html>Genom att hålla PhET Offline webbplats Installation up-to-date <br> ser till att du har tillgång till den nyaste PhET-simuleringarna <br> och kompletterande material. <br><br> Om du väljer att få den nyaste versionen, kommer webbläsaren <br> att öppna  PhET webbplats där du kan ladda ner <br> den PhET Offline Webbsite Installer. </html>",
            "ControlPanel.message.confirmResetAll": "Återställ alla inställningar?",
            "Common.HelpMenu.Help": "Hjälp",
            "Common.updates.errorNotAJar": "{0} är inte en JAR-fil.",
            "Common.updates.automaticallyCheck": "Sök automatiskt efter uppdateringar",
            "Common.sim.speed": "...sim hastighet...",
            "Common.updates.checkForSimUpdate": "Sök efter uppdatering av simulering",
            "XMLPersistenceManager.save.confirm.message": "<html>Filen du valt finns redan.<br>Vill du ersätta den med filen du önskar spara?</html>",
            "FileChooser.newFolderErrorText": "Fel vid skapande av ny mapp",
            "Common.updates.skipThisUpdate": "Hoppa över denna version",
            "Common.FileMenu.Save.mnemonic": "S",
            "FileChooser.saveDialogTitleText": "Spara",
            "XMLPersistenceManager.load.title": "Ladda konfiguration",
            "Common.updates.checkForInstallerUpdate": "Sök efter PhET Offline Website Installer uppdatering",
            "timeseries.control.panel.playback": "Playback",
            "Common.updates.progressDialogTitle": "Uppdaterar",
            "Common.HelpMenu.Title": "Hjälp",
            "FileChooser.fileNameLabelText": "Filnamn:",
            "ColorChooser.rgbNameText": "RGB",
            "Common.softwareAgreement.title": "Mjukvaruavtal",
            "Common.HelpMenu.TitleMnemonic": "h",
            "Common.About.Distribution": "Distrubution:",
            "XMLPersistenceManager.save.error.message": "<html>Fel vid skrivning till fil:<br>{0}</html>",
            "FileChooser.openButtonText": "Öppna",
            "Common.statistics.details.description": "<html>Informationen nedan kommer att sändas till PhET varje gång simuleringen startar.</html>",
            "ColorChooser.sampleText": "Exempeltext Exempeltext",
            "Common.title.confirm": "Bekräfta",
            "Common.BasicPhetPanel.LogoToolTip": "Inaktivera Helskärm",
            "Common.statistics.host_java_timezone": "Tidszon:",
            "Common.time.slow": "långsam",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.softwareAgreement.accept": "Acceptera och fortsätt",
            "Common.ClockControlPanel.Rewind": "Återgå",
            "Common.updates.updateToDate": "Up To Date",
            "Common.ClockControlPanel.Pause": "Paus",
            "PhetApplication.StartupDialog.message": "\"{0}\" startas",
            "XMLPersistenceManager.message.notAConfigFile": "Filen innehåller inte någon konfiguration för denna simulering.",
            "Common.preferences.updates": "Uppdateringar",
            "Common.HelpMenu.MegaHelpMnemonic": "m",
            "Common.statistics.enabled": "Tillåt sändning av information till PhET",
            "Common.StopwatchPanel.stop": "Stopp",
            "Common.HelpPanel.MegaHelp": "MegaHjälp",
            "Common.StopwatchPanel.reset": "Återställ",
            "Common.playback": "Playback",
            "Common.updates.tryIt": "Pröva den nya versionen innan du uppdaterar.",
            "ColorChooser.rgbBlueText": "Blå",
            "Common.choice.close": "Stäng",
            "Common.ClockControlPanel.Play": "Spela",
            "FileChooser.saveButtonText": "Spara",
            "Common.rewind": "Återgå",
            "Common.updates.youHaveCurrent": "Du har den nyaste versionen ({0}) of {1}.",
            "Common.StopwatchPanel.start": "Start",
            "charts.show-graphs": "Visa grafer:"
        } );