//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_pt_BR.properties
define( {
            "Games.label.level": "Nível: {0}",
            "Common.updates.errorMessage": "Um erro ocorreu na tentativa de atualização.<br>Por favor, tente novamente mais tarde, ou visite {0}.",
            "XMLPersistenceManager.save.error.encode": "<html>Erro ao codificar arquivo:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Erro ao decodificar arquivo:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "f",
            "Common.softwareAgreement.decline": "Sair",
            "Common.statistics.host_os_name": "Nome do sistema oparecional:",
            "Common.statistics.user_total_sessions": "Número total de vezes que todas as simulações foram rodadas:",
            "Common.statistics.host_java_version_major": "Versão do Java (major):",
            "FileChooser.openDialogTitleText": "Abrir",
            "Common.statistics.host_java_version_maintenance": "Versão do Java (manutenção):",
            "FileChooser.lookInLabelText": "Procurar em:",
            "Common.choice.cancel": "Cancelar",
            "Common.updates.seePreferences": "Vá para Arquivo->Preferências para alterar suas preferências.",
            "Common.About.CreditsDialog.software-development": "Desenvolvimento de Software",
            "Common.About.JavaVersion": "Java Versão:",
            "ColorChooser.resetText": "Reiniciar",
            "wavelength.ir": "IV",
            "Common.About.CreditsDialog.design-team": "Equipe de Design",
            "Common.statistics.sim_total_sessions": "Número total de vezes que a simulação foi rodada:",
            "wavelength.uv": "UV",
            "Games.title.gameSettings": "Configurações do jogo",
            "XMLPersistenceManager.save.title": "Salvar as configurações",
            "XMLPersistenceManager.load.error.contents": "O arquivo está corrompido ou não foi criado por esta simulação.",
            "Common.statistics.details.title": "Informações",
            "Common.statistics.sim_dev_version": "Versão da simulação (desenvolvedores):",
            "FileChooser.saveInLabelText": "Salvar em:",
            "Common.statistics.sim_name": "Nome da simulação:",
            "Save.confirm.message": "<html>O nome do arquivo que você escolheu já existe.<br>Deseja substituir pelo arquivo que você está salvando?</html>",
            "Games.label.score": "Pontos: {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "Equipe de Desenvolvimento PhET",
            "Games.button.start": "Iniciar!",
            "Common.statistics.sim_deployment": "Tipo de execução:",
            "Common.FileMenu.Save": "Salvar configurações...",
            "Games.radioButton.on": "liga",
            "FileChooser.acceptAllFileFilterText": "Todos os arquivos (*.*)",
            "Common.ModelSlider.Minimum": "Mínimo",
            "Common.FileMenu.Preferences": "Preferências",
            "Common.FileMenu.Load": "Carregar configurações...",
            "Common.updates.downloadingSimJar": "Baixando o arquivo JAR da simulação",
            "Games.radioButton.off": "deslig.",
            "ColorChooser.swatchesRecentText": "Recente:",
            "Common.updates.updateAvailable": "Atualização Disponível",
            "Common.statistics.host_locale_language": "Idioma local:",
            "Common.clear": "Limpar",
            "Games.title.gameOver": "Fim de jogo",
            "FileChooser.filesOfTypeLabelText": "Arquivos do tipo:",
            "Common.ErrorDialog.detailsTitle": "Detalhes do erro",
            "Common.HelpMenu.MegaHelp": "Grande Ajuda...",
            "Common.ClockControlPanel.Step": "Passo a passo",
            "Common.statistics.sim_revision": "Versão da simulação (revisão):",
            "Common.choice.yes": "Sim",
            "Common.FileMenu.Title": "Arquivo",
            "Common.statistics.sim_dev": "Esta é uma versão para desenvolvedores?:",
            "Common.updates.installer.message": "<html>Sua Instalação do Website Offline PhET é de {0}.<br>Uma nova versão está disponível, de {1}.<br><br>Você gostaria de obter o mais recente  Instalador do Website Offline PhET?</html>",
            "Common.updates.updateNow": "Atualizar Agora!",
            "Common.record": "Gravar",
            "Common.About.CreditsDialog.Title": "Créditos",
            "Common.updates.error.internetConnection": "<html>Impossível conectar-se a {0},<br>por favor, verifique sua conexão à internet.</html>",
            "Common.time.fast": "rápido",
            "XMLPersistenceManager.load.error.message": "<html>Erro ao ler do arquivo:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Máximo",
            "Common.OptionsMenu": "Opções",
            "Common.ClockControlPanel.Restart": "Reiniciar",
            "Common.statistics.sim_version_timestamp": "Versão da simulação (data e hora):",
            "Common.updates.installer.yes": "Sim!",
            "Common.phetInstaller": "Instalador do Website Offline PhET",
            "Common.HelpMenu.About": "Sobre...",
            "Common.ModelSlider.OutOfRange": "Valor fora da escala",
            "ColorChooser.previewText": "Visualizar",
            "Common.BasicPhetPanel.Title": "Retornar",
            "Common.HelpPanel.HideHelp": "Ocultar Ajuda",
            "Common.statistics.host_os_arch": "Tipo de processador:",
            "Common.preferences.title": "Preferências",
            "Games.button.newGame": "Novo Jogo",
            "Common.ModelSlider.YouEntered": "Você entrou",
            "Games.label.newBest": "Novo Recorde!",
            "Common.About.BuildDate": "Data de construção:",
            "Common.statistics.sim_project": "Nome do projeto:",
            "Games.label.best": "melhor: {0}",
            "Common.title.message": "Mensagem",
            "Common.updates.downloadingBootstrap": "Baixando o inicializador da atualização...",
            "Common.title.error": "Erro",
            "Common.FileMenu.Exit": "Sair",
            "Common.statistics.sim_major_version": "Versão da simulação (major):",
            "Common.updates.askMeLater": "Pergunte-me mais tarde",
            "chart-time-control.go": "Ir!",
            "Common.HelpMenu.HelpMnemonic": "h",
            "Common.confirm.clear.graphs": "Tem certeza de que deseja limpar os gráficos?",
            "Common.updates.progressDialogMessage": "Atualizando \"{0}\" para a versão {1}",
            "Common.updates.installer.more": "Conte-me mais...",
            "XMLPersistenceManager.title.error": "Erro",
            "ControlPanel.button.resetAll": "Reiniciar tudo?",
            "Common.About.AgreementButton": "Termo de Licença de Software",
            "Common.ErrorDialog.detailsButton": "Detalhes...",
            "Common.updates.errorMissingJar": "<html>Esta atualização não pode ser realizada.<br>Impossível encontrar arquivo JAR: {0}.<br>Por favor, contate o administrador do sistema para obter ajuda.<br></html>",
            "Common.preferences.privacy": "Privacidade",
            "Common.HelpMenu.AboutTitle": "Sobre",
            "ColorChooser.rgbRedText": "Vermelho",
            "Common.statistics.sim_locale_country": "País:",
            "ColorChooser.rgbGreenText": "Verde",
            "Games.format.time.best": "{0} ({1})",
            "Common.HelpPanel.ShowHelp": "Ajuda!",
            "PiccoloPhet.VelocitySensorNode.speed": "Velocidade",
            "Common.statistics.sim_distribution_tag": "Versão da simulação (distribuição):",
            "Common.statistics.description": "PhET é gratuitamente disponível por concessões<br> que requerem que coletemos uma mínima <br>quantidade de informações<a href=\"{0}\"> anônimas que</a> ajudem a documentar a quantidade <br>de uso das simulações do PhET e a melhor<br> servir às necessidades dos usuários.",
            "Common.softwareAgreement.message": "Em todas as simulações do PhET, coletamos uma quantidade mínima<br>de informação <a href=\"{0}\">anônima</a> sempre que a simulação é iniciada<br>(e.g., versão da simulação, sistema operacional).<br>Você pode desabilitar o envio de tais informações<br>a qualquer momento através de Arquivo->Preferências (item do menu).<br><br>Clicando em \"Concordar e Continuar\", você concordará com o<br>Termo de Licença de Software, incluindo nossas políticas de provacidade,<br>para esta e todas as simulações do PhET que você executar.<br>(Para detalhes, clique <a href=\"{1}\">aqui</a>).",
            "Common.choice.ok": "OK",
            "Common.About.Version": "Versão:",
            "Common.ErrorDialog.contactPhet": "Se este problema persistir, envie os detalhes abaixo para {0}",
            "Common.About.CreditsDialog.lead-design": "Design Principal",
            "Common.statistics.user_preference_file_creation_time": "Data e hora da criação do arquivo Preferências:",
            "Common.HelpMenu.AboutMnemonic": "a",
            "Common.updates.errorWritePermissions": "<html>Esta atualização não pode ser realizada.<br>Você não tem permissão para modidicar {0}.<br>Por favor, contate o administrador do sistema para obter ajuda.<br></html>",
            "Common.choice.no": "Não",
            "Common.About.WebLink": "Visite a Homepage do PhET",
            "Common.About.OSVersion": "Versão do Sistema Operacional",
            "Common.title.warning": "Aviso",
            "Common.updates.versionComparison": "<html>Sua versão atual de \"{0}\" é {1}.<br>Uma nova versão ({2}) está disponível.</html>",
            "Common.statistics.sim_locale_language": "Idioma:",
            "Common.statistics.user_installation_timestamp": "Data e hora da instalação do PhET:",
            "Common.statistics.message_version": "Versão da mensagem:",
            "Common.ModelSlider.Description": "Valor Ilegal.",
            "Common.updates.installer.moreMessage": "<html>Manter sua instalação do Website Offline PhET atualizada<br>assegura que você tenha acesso às mais novas simulações do PhET<br>e a materiais complementares.<br><br>Se você decidir obter a mais nova versão, um navegador<br>abrirá na página do PhET, onde você poderá baixar<br>o Instalador do Website Offline PhET.</html>",
            "ControlPanel.message.confirmResetAll": "Reiniciar todas as configurações?",
            "Common.HelpMenu.Help": "Ajuda",
            "Common.updates.errorNotAJar": "{0} não é um arquivo JAR.",
            "Games.label.levelControl": "Nível:",
            "Common.updates.automaticallyCheck": "Procurar atualizações automaticamente",
            "Common.sim.speed": "...velocidade da simulação...",
            "Common.updates.checkForSimUpdate": "Procurar atualizações da simulação...",
            "XMLPersistenceManager.save.confirm.message": "<html>O nome do arquivo que você escolheu já existe.<br>Você quer substituir pelo arquivo que você está salvando?</html>",
            "FileChooser.newFolderErrorText": "Erro ao criar nova pasta",
            "Common.updates.skipThisUpdate": "Pular esta versão.",
            "Common.About.CreditsButton": "Créditos...",
            "FileChooser.saveDialogTitleText": "Salvar",
            "XMLPersistenceManager.load.title": "Carregar as configurações",
            "Common.updates.checkForInstallerUpdate": "Procurar atualizações do Instalador do Website Offline PhET...",
            "timeseries.control.panel.playback": "Reproduzir",
            "Common.updates.progressDialogTitle": "Atualizando",
            "Common.HelpMenu.Title": "Ajuda",
            "FileChooser.fileNameLabelText": "Nome do arquivo:",
            "ColorChooser.rgbNameText": "RGB",
            "Common.softwareAgreement.title": "Termo de Licença de Software",
            "Common.statistics.host_java_version_minor": "Versão do Java (minor):",
            "Common.HelpMenu.TitleMnemonic": "h",
            "Common.About.CreditsDialog.interviews": "Entrevistas",
            "Common.About.Distribution": "Distribuição",
            "Common.statistics.host_java_webstart_version": "Versão do Java Web Start:",
            "XMLPersistenceManager.save.error.message": "<html>Erro ao gravar no arquivo:<br>{0}</html>",
            "Games.label.time": "Tempo: {0}",
            "FileChooser.openButtonText": "Abrir",
            "ColorChooser.sampleText": "Amostra de Texto",
            "Common.statistics.details.description": "<html>As informações mostradas abaixo serão enviadas ao PhET sempre que uma simulação for iniciada.</html>",
            "Common.statistics.host_os_version": "Versão do sistema operacional:",
            "Common.title.confirm": "Confirmar",
            "Common.BasicPhetPanel.LogoToolTip": "Desativar tela cheia",
            "Games.label.score.max": "Pontos: {0} de {1}",
            "Common.statistics.host_java_timezone": "Fuso Horário",
            "Common.time.slow": "lento",
            "Common.ClockControlPanel.Rewind": "Rebobinar",
            "Common.softwareAgreement.accept": "Aceitar e Continuar",
            "Common.updates.updateToDate": "Atualizado",
            "Common.ClockControlPanel.Pause": "Pausa",
            "PhetApplication.StartupDialog.message": "\"{0}\" está sendo iniciado",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Este programa usa o seguinte software de terceiros:",
            "XMLPersistenceManager.message.notAConfigFile": "Este arquivo não contém uma configuração para esta simulação.",
            "Common.preferences.updates": "Atualizações",
            "Games.label.score.max.perfect": "Pontos: {0} de {1} (PERFEITO!)",
            "Common.HelpMenu.MegaHelpMnemonic": "m",
            "Common.statistics.enabled": "Permitir o envio de informações ao PhET",
            "Common.StopwatchPanel.stop": "Parar",
            "Common.HelpPanel.MegaHelp": "Grande Ajuda...",
            "Common.statistics.host_locale_country": "País de origem:",
            "Common.StopwatchPanel.reset": "Recomeçar",
            "Common.playback": "Reproduzir",
            "Common.statistics.sim_minor_version": "Versão da simulação (minor):",
            "Games.message.confirmNewGame": "<html>Você não terminou esse jogo.<br>Tem certeza que quer começar um jogo novo?</html>",
            "Common.updates.tryIt": "Experimente a nova versão antes de atualizar.",
            "ColorChooser.rgbBlueText": "Azul",
            "Common.choice.close": "Fechar",
            "Common.ClockControlPanel.Play": "Iniciar",
            "Common.statistics.sim_type": "Tipo da simulação:",
            "FileChooser.saveButtonText": "Salvar",
            "Common.rewind": "Rebobinar",
            "Common.StopwatchPanel.start": "Iniciar",
            "Common.updates.youHaveCurrent": "Você tem a versão mais recente ({0}) de {1}.",
            "Common.statistics.sim_sessions_since": "Número de vezes que a simulação foi executada desde a última conexão:",
            "Common.statistics.host_java_vendor": "Distribuidor do Java:",
            "charts.show-graphs": "Mostrar gráficos:",
            "Common.statistics.message_type": "Tipo da mensagem:"
        } );