//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_tr.properties
define( {
            "Common.updates.errorMessage": "güncelleme yapmaya  çalışırken bir hata ile karşılaşıldı.<br>Lütfen daha sonra tekrar deneyin yada ziyaret edin {0}.",
            "XMLPersistenceManager.save.error.encode": "<html>Şifreleme hatası dosya:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Şifre çözülürken hata oldu dosya:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "f",
            "Common.softwareAgreement.decline": "Çıkış",
            "Common.statistics.host_os_name": "İşletim sistemi ismi",
            "Common.statistics.user_total_sessions": "şimdiye kadar  bütün simülasyonların toplam çalıştırılma sayısı",
            "Common.statistics.host_java_version_major": "Java Versiyon (major)",
            "FileChooser.openDialogTitleText": "Aç",
            "Common.statistics.host_java_version_maintenance": "Java Versiyonu (Bakım)",
            "FileChooser.lookInLabelText": "Şuraya bak:",
            "Common.choice.cancel": "İptal",
            "Common.updates.seePreferences": "Bu dosyaya git -> Tercihlerinizi değiştirmek için tercihler.",
            "Common.About.CreditsDialog.software-development": "Yazılım Geliştirici",
            "Common.About.JavaVersion": "Java Versiyonu:",
            "ColorChooser.resetText": "Sıfırla",
            "wavelength.ir": "IR",
            "Common.About.CreditsDialog.design-team": "Tasarım Ekibi",
            "Common.statistics.sim_total_sessions": "Şimdiye kadar bu simülasyonun toplam çalıştırılma sayısı",
            "Common.FileMenu.PreferencesMnemonic": "p",
            "wavelength.uv": "UV",
            "XMLPersistenceManager.save.title": "Ayarları kaydet",
            "XMLPersistenceManager.load.error.contents": "Dosya bozulmuş yada bu simülasyon tarafından oluşturmamış.",
            "Common.statistics.details.title": "Bilgi",
            "Common.statistics.sim_dev_version": "Simülasyon versiyonu (dev)",
            "FileChooser.saveInLabelText": "Buraya kaydet:",
            "Common.statistics.sim_name": "Simülasyon ismi",
            "Save.confirm.message": "<html>The file you selected already exists.<br>Do you want to replace it with the file you are saving?</html>",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "Phet Geliştirici Ekibi",
            "Common.statistics.sim_deployment": "Dağıtım tipi",
            "ColorChooser.hsbSaturationText": "S",
            "FileChooser.acceptAllFileFilterText": "Bütün dosyalar(*.*)",
            "ColorChooser.hsbNameText": "HSB",
            "Common.ModelSlider.Minimum": "Minumum",
            "Common.FileMenu.Preferences": "Tercihler",
            "Common.updates.downloadingSimJar": "Simülasyonun JAR dosyası yükleniyor...",
            "ColorChooser.swatchesRecentText": "Yenilenmiş:",
            "Common.updates.updateAvailable": "İndirlilebilir güncelleme ",
            "Common.statistics.host_locale_language": "Sunucu dili",
            "Common.clear": "Temizle",
            "FileChooser.filesOfTypeLabelText": "Dosyanın tipi:",
            "Common.ErrorDialog.detailsTitle": "Hata Ayrıntıları",
            "Common.HelpMenu.MegaHelp": "BüyükYardım...",
            "Common.ClockControlPanel.Step": "Adım",
            "Common.statistics.sim_revision": "Simülasyon versiyonu (düzeltilmiş)",
            "Common.choice.yes": "Evet",
            "Common.FileMenu.Title": "Dosya",
            "Common.statistics.sim_dev": "Geliştirici veryisonu bu mu ?",
            "Common.updates.installer.message": "<html>Sizin çevrimdışı Phet Websitesi yükeleme tarihli  {0}.<br>Daha yeni bir versiyon indirlilebilir {1}.<br><br>En yeni çevrimdışı  Phet Websitesi yükleyicisini indirmek istiyor musunuz ?</html>",
            "Common.updates.updateNow": "Şimdi güncelle!",
            "Common.About.CreditsDialog.Title": "Hazırlayanlar",
            "Common.time.fast": "Hızlı",
            "Common.OptionsMenu": "Ayarlar",
            "XMLPersistenceManager.load.error.message": "<html>Dosyadan okurken hata oldu:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Maksimum",
            "Common.ClockControlPanel.Restart": "Tekrar Oynat",
            "Common.statistics.sim_version_timestamp": "Simülasyon versiyonu (tarih bilgisi)",
            "Common.updates.installer.yes": "Evet !",
            "Common.phetInstaller": "Phet Çevrimdışı Websitesi Yükleyicisi",
            "Common.HelpMenu.About": "Hakkında...",
            "Common.ModelSlider.OutOfRange": "Alabilecek değer dışı",
            "ColorChooser.previewText": "Önizleme",
            "Common.BasicPhetPanel.Title": "Başa Dön",
            "Common.HelpPanel.HideHelp": "Yardımı Gizle",
            "Common.statistics.host_os_arch": "İşlemci tipi",
            "Common.preferences.title": "Tercihler",
            "ColorChooser.hsbRedText": "R",
            "ColorChooser.hsbBlueText": "B",
            "Common.ModelSlider.YouEntered": "Sen girdin",
            "Common.About.BuildDate": "Yapım Tarihi",
            "Common.FileMenu.ExitMnemonic": "x",
            "Common.statistics.sim_project": "Proje ismi",
            "Common.title.error": "Hata",
            "Common.FileMenu.Exit": "Çıkış",
            "Common.statistics.sim_major_version": "Simülasyon versiyonu (major)",
            "Common.updates.askMeLater": "Sonra sor",
            "chart-time-control.go": "İlerle!",
            "Common.HelpMenu.HelpMnemonic": "h",
            "Common.confirm.clear.graphs": "Grafiği temizlemek istediğine emin misin ?",
            "ColorChooser.swatchesNameText": "Numune",
            "Common.updates.progressDialogMessage": "Güncelleniyor \"{0}\" versiyona  {1}",
            "Common.updates.installer.more": "Daha fazlası...",
            "XMLPersistenceManager.title.error": "Hata",
            "ColorChooser.hsbHueText": "H",
            "ControlPanel.button.resetAll": "Tümünü sıfırla",
            "Common.About.AgreementButton": "Yazılım Sözleşmesi...",
            "Common.ErrorDialog.detailsButton": "Ayrıntılar",
            "Common.updates.errorMissingJar": "<html>Bu güncelleme yapılamadı.<br>JAR dosyasının yeri saptanamadı: {0}.<br>Yardım için sistem yöneticinize başvurun.<br></html>",
            "Common.preferences.privacy": "Gzililik",
            "Common.HelpMenu.AboutTitle": "Hakkında",
            "ColorChooser.rgbRedText": "Kırmızı",
            "Common.statistics.sim_locale_country": "Ülke",
            "ColorChooser.hsbGreenText": "G",
            "ColorChooser.rgbGreenText": "Yeşil",
            "Common.HelpPanel.ShowHelp": "Yardım!",
            "Common.statistics.sim_distribution_tag": "Simülasyon versiyonu (dağıtım)",
            "Common.statistics.description": "Phet bağış yolu ile ulaşılabilir ücretsiz hale getirilmiştir.<br>Phet simülasyonlarının kullanımını dökümante etmeye<br>yardımcı olmak ve kullanıcılarımızın güncelleme<br>ihtiyaçlarına daha iyi hizmet etmek için minumum <br>miktarda <a href=\"{0}\">bilgi</a> toplamamız gerekiyor.",
            "Common.softwareAgreement.message": "Tüm Phet simülasyonlarının her çalıştırılışında bazı anonim<br>bilgileri genel olarak alıyoruz <a href='{0}'>bilgi</a> (örneğin simülasyon versiyonunu, <br>işletim sistemi gibi). Bu bilgileri göndemeyi iptal etmek<br>isterseniz Dosya->Tercihler butonuna basarak bunu<br>hizmet dışı bırakabilirsiniz.<br><br>\"Kabul ve Devam\" a tıklayarak Phet yazılım sözleşmesini onaylayabilirsiniz.<br>(Ayrıntılar için, <a href='{1}'>buraya tıklayın</a>).",
            "Common.choice.ok": "Tamam",
            "Common.About.Version": "Versiyon:",
            "Common.ErrorDialog.contactPhet": "Eğer sorun tekrarlarsa, ayrıntıları aşagıdaki {0} gönder",
            "Common.About.CreditsDialog.lead-design": "Tasarım Lideri",
            "Common.statistics.user_preference_file_creation_time": "Tercihler dosyası oluşturma zamanı",
            "Common.HelpMenu.AboutMnemonic": "a",
            "Common.updates.errorWritePermissions": "<html>Bu güncelleme yapılamadı.<br>Bunu yapmak için izniniz yok{0}.<br>Yardım için sistem yöneticinize başvurun.<br></html>",
            "ColorChooser.hsbBrightnessText": "B",
            "Common.choice.no": "Hayır",
            "Common.About.WebLink": "Phet Anasayfasını",
            "Common.About.OSVersion": "İşletim Sistemi Versiyonu:",
            "Common.updates.versionComparison": "<html>şimdiki versiyonunuz \"{0}\"of  {1}.<br>Daha yeni bir versiyonu yükeleyebilirsiniz ({2}) .</html>",
            "Common.statistics.sim_locale_language": "Dil",
            "Common.statistics.user_installation_timestamp": "Phet yükleme tarih bilgisi",
            "Common.statistics.message_version": "Mesaj versiyonu",
            "Common.ModelSlider.Description": "Geçersiz değer.",
            "Common.updates.installer.moreMessage": "<html>PhET Çevrimdışı Websitesi Kurulum güncellemeleri size <br>yeni PhET simülasyonları <br>ve ilave materyallere  erişmenize olanak sağlar.<br><br>Eğer yeni versiyonu istiyorsanız, Phet websitesine yönlendirileceksiniz<br> ve çevrimdışı Phet websitesi yükleyicisini indirebileceksiniz..</html>",
            "ControlPanel.message.confirmResetAll": "Tüm Ayarları sıfırlamak istermisin ?",
            "Common.HelpMenu.Help": "Yardım",
            "Common.updates.errorNotAJar": "{0} bu JAR dosyası değil.",
            "Common.updates.automaticallyCheck": "Güncellemeleri otomatik kontrol et",
            "Common.sim.speed": "... sim hızı",
            "Common.updates.checkForSimUpdate": "Simülasyon güncellemesini kontrol et",
            "XMLPersistenceManager.save.confirm.message": "<html>Zaten bu dosyayı seçtiniz.<br>Bu dosya ile değiştirmek ister misiniz?</html>",
            "FileChooser.newFolderErrorText": "Yeni klasör oluştururken hata oldu",
            "Common.updates.skipThisUpdate": "Bu güncellemeyi atla.",
            "Common.About.CreditsButton": "Hazırlayanlar...",
            "FileChooser.saveDialogTitleText": "Kaydet",
            "XMLPersistenceManager.load.title": "Ayarları yükle",
            "Common.updates.checkForInstallerUpdate": "Çevrimdışı Phet websitesi yükleyicisi güncellemesini kontrol et...",
            "timeseries.control.panel.playback": "Gerioynat",
            "Common.updates.progressDialogTitle": "Güncelleniyor",
            "Common.HelpMenu.Title": "Yardım",
            "FileChooser.fileNameLabelText": "Dsoya adı:",
            "ColorChooser.rgbNameText": "KYM",
            "Common.softwareAgreement.title": "Yazılım Sözleşmesi...",
            "Common.statistics.host_java_version_minor": "Java Versiyon (minor)",
            "Common.HelpMenu.TitleMnemonic": "h",
            "Common.About.CreditsDialog.interviews": "Görüşme",
            "Common.About.Distribution": "Dağıtım:",
            "Common.statistics.host_java_webstart_version": "Java Web Başlatıcısı Versiyonu",
            "XMLPersistenceManager.save.error.message": "<html>Dosyaya yazarken hata oldu:<br>{0}</html>",
            "FileChooser.openButtonText": "Aç",
            "Common.statistics.details.description": "<html>Aşağıda gösterilen bilgiler simülasyon başladığında Phet 'e gönderilecek.</html>",
            "ColorChooser.sampleText": "Örnek Metin",
            "Common.statistics.host_os_version": "İşletim sistemi versiyonu",
            "Common.title.confirm": "Doğrula",
            "Common.BasicPhetPanel.LogoToolTip": "Yapıyı Geçersiz Kıl",
            "Common.statistics.host_java_timezone": "Zamandilimi",
            "Common.time.slow": "Yavaş",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.ClockControlPanel.Rewind": "Geri Al",
            "Common.softwareAgreement.accept": "Devam etmek istiyorum",
            "Common.updates.updateToDate": "güncel",
            "Common.ClockControlPanel.Pause": "Durdur",
            "PhetApplication.StartupDialog.message": "\"{0}\" başlıyor",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Bu program üçüncü taraf yazılımı kullanıyor.",
            "Common.preferences.updates": "Güncellemeler",
            "Common.HelpMenu.MegaHelpMnemonic": "m",
            "Common.statistics.enabled": "Phet 'e bilgi göndermeye izin ver",
            "Common.StopwatchPanel.stop": "Durdur",
            "Common.HelpPanel.MegaHelp": "BüyükYardım...",
            "Common.statistics.host_locale_country": "Sunucu ülke",
            "Common.StopwatchPanel.reset": "Sıfırla",
            "Common.statistics.sim_minor_version": "Simülasyon versiyonu (minor)",
            "Common.updates.tryIt": "Güncelleme yapamadan önce yeni versiyonu dene.",
            "ColorChooser.rgbBlueText": "Mavi",
            "Common.choice.close": "Kapat",
            "Common.ClockControlPanel.Play": "Oynat",
            "Common.statistics.sim_type": "Simülasyon tipi",
            "FileChooser.saveButtonText": "Kaydet",
            "Common.rewind": "Başa al",
            "Common.StopwatchPanel.start": "Başlat",
            "Common.updates.youHaveCurrent": "En güncel versiyona sahipsiniz {0} of {1} ",
            "Common.statistics.sim_sessions_since": "son çevrimiçi olduktan sonra şimdiye kadar bu simülasyonun toplam çalıştırılma sayısı",
            "Common.statistics.host_java_vendor": "Java Satıcısı",
            "charts.show-graphs": "Grafiği göster:",
            "Common.statistics.message_type": "Mesaj tipi"
        } );