//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_ka.properties
define( {
            "ColorChooser.rgbBlueText": "ლურჯი",
            "Common.time.fast": "სწრაფად",
            "Common.About.Distribution": "განაწილება:",
            "FileChooser.acceptAllFileFilterText": "ყველა ფაილი (*.*)",
            "Common.updates.youHaveCurrent": "შენ გაქვს ({0})-დან ყველაზე მიმდინარე ვერსია {1}.",
            "Common.updates.installer.yes": "დიახ!",
            "Common.HelpMenu.AboutTitle": "შესახებ",
            "Common.updates.versionComparison": "<html>შენი  ვერსია \"{0}\"-დან არის {1}.<br>ვერსია ({2}) ხელმისაწვდომია.</html>",
            "Common.statistics.sim_type": "სიმულაციის ტიპი",
            "charts.show-graphs": "მიჩვენე გრაფიკი:",
            "Common.updates.updateAvailable": "განახლება შესაძლებელია",
            "Common.updates.progressDialogMessage": "განახლება \"{0}\"-დან {1} ვერსიამდე",
            "Common.statistics.user_total_sessions": "ყველა სიმულაციის გაშვების ჯამური რიცხვი",
            "Common.confirm.clear.graphs": "ნამდვილად გსურს გრაფიკის გასუფთავება?",
            "Common.updates.seePreferences": "შედი File->Preferences რომ შეცვალო შენი პარამეტრები.",
            "XMLPersistenceManager.save.error.encode": "<html>ფაილ.კოდირ.შეცდ:<br>{0}</html>",
            "Common.OptionsMenu": "დამატებები",
            "Common.updates.updateNow": "განაახლე ახლა!",
            "Common.About.CreditsDialog.design-team": "შემქმნელები",
            "Common.About.CreditsButton": "მადლობები...",
            "Save.confirm.message": "<html>შენი არჩეული ფაილი უკვე არსებობს.<br>გსურს შეცვალო ის ფაილით, რომელსაც ინახავ?</html>",
            "Common.HelpPanel.HideHelp": "დამალე დახმარება",
            "Common.updates.downloadingBootstrap": "განახლების პროგრამის ჩამოტვირთვა...",
            "Common.statistics.sim_name": "სიმულაციის სახელი",
            "Common.About.CreditsDialog.software-development": "პროგრამის დამუშავება",
            "FileChooser.openDialogTitleText": "გახსენი",
            "XMLPersistenceManager.save.title": "შეინახე კონფიგურაცია",
            "FileChooser.lookInLabelText": "ნახე -ში:",
            "Common.ClockControlPanel.Rewind": "თავში გადასვლა",
            "Common.choice.no": "არა",
            "XMLPersistenceManager.title.error": "შეცდომა",
            "Common.updates.installer.more": "მითხარი მეტი...",
            "Common.updates.installer.message": "<html>შენი PhET Offline Website Installation-ის თარიღია {0}.<br>არის განახლებული ვერსია, თარიღით \n{1}.<br><br>გსურს უახლესი PhET Offline Website Installation?</html>",
            "FileChooser.saveButtonText": "შეინახე",
            "XMLPersistenceManager.save.error.message": "<html>ფაილში ჩაწერ.შეცდ:<br>{0}</html>",
            "Common.updates.updateToDate": "უახლესი",
            "XMLPersistenceManager.load.error.contents": "ფაილი დაზიანებულია ან არ არის შექმნილი ამ სიმულაციით.",
            "Common.updates.installer.moreMessage": "<html>თუ  განაახლებ PhET Offline Website Installation-ს<br>ნახავ PhET-ის \nუახლეს სიმულაციებს და თანმდევ მასალებს.<br><br>თუ აირჩევ უახლესი ვერსიის მიღებას, ვებ \nბროუზერი<br>გახსნის PhET-ის ვებგვერდს და  ჩამოტვირთავ<br>PhET Offline Website Installation-ს.</html>",
            "Common.choice.close": "დახურვა",
            "timeseries.control.panel.playback": "გაშვება",
            "Common.rewind": "თავში გადასვლა",
            "chart-time-control.go": "მიდი!",
            "XMLPersistenceManager.message.notAConfigFile": "ეს ფაილი არ შეიცავს ამ სიმულაციის კონფიგურაციას.",
            "ColorChooser.sampleText": "მაგალითის ტექსტი მაგალითის ტექსტი",
            "Common.statistics.user_installation_timestamp": "PhET-ის ინსტალაციის მოდიფიკაცია",
            "Common.updates.errorNotAJar": "{0} არ არის JAR ფაილი.",
            "Common.title.error": "შეცდომა",
            "Common.About.AgreementButton": "პროგრამაზე შეთანხმება...",
            "Common.updates.errorWritePermissions": "<html>განახლება ვერ დასრულდება.<br>შენ არ გაქვს უფლება ჩაწერო {0}.<br>დასახმარებლად მიმართე სისტემურ ადმინისტრატორს.<br></html> ",
            "Common.ModelSlider.Maximum": "მაქსიმუმი",
            "Common.FileMenu.Load": "ჩატვირთე კონფიგურაცია",
            "Common.ClockControlPanel.Play": "დაკვრა",
            "ColorChooser.previewText": "გადახედვა",
            "Common.ModelSlider.YouEntered": "შეხვედი",
            "Common.statistics.sim_revision": "სიმულაციის ვერსია",
            "XMLPersistenceManager.save.confirm.message": "<html>შენი არჩეული ფაილი უკვე არსებობს.<br>გსურს შეცვალო ის ფაილით, რომელსაც ინახავ?</html>",
            "wavelength.ir": "ინფრაწითელი",
            "Common.softwareAgreement.accept": "მიიღე და გააგრძელე",
            "Common.choice.cancel": "გაუქმება",
            "wavelength.uv": "ულტრაიისფერი",
            "Common.ClockControlPanel.Pause": "პაუზა",
            "Common.HelpMenu.Help": "დახმარება",
            "Common.statistics.user_preference_file_creation_time": "პარამეტრების ფაილის შექმნის მოდიფიკაცია",
            "Common.statistics.sim_version_timestamp": "სიმულაციის ვერსია (მოდიფიკაცია)",
            "XMLPersistenceManager.load.title": "ჩატვირთე კონფიგურაცია",
            "ColorChooser.resetText": "აღდგენა",
            "Common.ModelSlider.Minimum": "მინიმუმი",
            "Common.ModelSlider.OutOfRange": "სიდიდე საზღვრებს გარეთააა",
            "Common.FileMenu.Exit": "გამოსვლა",
            "Common.sim.speed": "...სიმულაციის სიჩქარე...",
            "ControlPanel.message.confirmResetAll": "აღვადგინო ყველა პარამეტრები?",
            "Common.statistics.enabled": "ინფორმაციის გაგზავნა PhET-ში ნებადართულია",
            "Common.About.BuildDate": "დამზადების თარიღი:",
            "Common.playback": "გაშვება",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "ეს პროგრამა იყენებს მესამე მხარის პროგრამებს",
            "Common.About.CreditsDialog.interviews": "ინტერვიუები",
            "FileChooser.filesOfTypeLabelText": "ტიპის ფაილები:",
            "Common.StopwatchPanel.start": "დასაწყისი",
            "Common.updates.errorMissingJar": "<html>განახლება ვერ დასრულდება.<br>ვერ ვპოულობ JAR ფაილს: {0}.<br>დასახმარებლად მიმართე სისტემურ ადმინისტრატორს.<br></html>",
            "ControlPanel.button.resetAll": "აღადგინე ყველა",
            "Common.preferences.privacy": "პირადულობა",
            "FileChooser.newFolderErrorText": "ახალი საქაღალდის გახსნის შეცდომა",
            "Common.updates.skipThisUpdate": "გამოტოვე ეს ვერსია",
            "Common.FileMenu.Save": "შეინახე კონფიგურაცია",
            "Common.updates.downloadingSimJar": "სიმულაციის JAR ფაილის ჩამოტვირთვა...",
            "Common.ClockControlPanel.Step": "ბიჯი",
            "Common.HelpMenu.Title": "დახმარება",
            "Common.statistics.host_java_timezone": "დროითი ზონა",
            "Common.HelpMenu.About": "შესახებ...",
            "FileChooser.fileNameLabelText": "ფაილის სახელი:",
            "Common.clear": "გასუფთავება",
            "Common.statistics.details.description": "<html>ქვემოთ მოყვანილი ინფორმაცია გაეგზავნება PhET-ს ამ სიმულაციის ყოველ გაშვებაზე.</html>",
            "Common.time.slow": "ნელა",
            "Common.About.CreditsDialog.Title": "მადლობები",
            "PhetApplication.StartupDialog.message": "\"{0}\" გაშვებულია",
            "Common.ErrorDialog.detailsButton": "დაწვრილებით...",
            "FileChooser.openButtonText": "გახსენი",
            "Common.ErrorDialog.detailsTitle": "შეცდომა დაწვრილებით",
            "FileChooser.saveInLabelText": "შეინახე -ში:",
            "Common.StopwatchPanel.stop": "შეჩერება",
            "Common.statistics.sim_sessions_since": "რამდენჯერ არის გაშვებული ეს სიმულაცია უკანასკნელი განთავსებიდან",
            "Common.BasicPhetPanel.Title": "დაბრუნება",
            "Common.ModelSlider.Description": "არასწორი სიდიდე.",
            "FileChooser.saveDialogTitleText": "შეინახე",
            "Common.updates.checkForSimUpdate": "შეამოწმე სიმულაციის განახლება...",
            "Common.updates.errorMessage": "განახლებისას წავაწყდი შეცდომას.<br>სცადე მოგვიანებით, ან ესტუმრე {0}.",
            "Common.statistics.sim_project": "პროექტის სახელი",
            "Common.updates.checkForInstallerUpdate": "PhET Offline Website Installer-ის \nგანახლების შემოწმება...",
            "Common.ClockControlPanel.Restart": "გადატვირთვა",
            "Common.ErrorDialog.contactPhet": "თუ ეს პრობლემა არსებობს, გააგზავნე აღწერა {0}-თან",
            "Common.updates.error.internetConnection": "<html>ვერ ვუკავშირდები {0},<br>შეამოწმე შენი ინტერნეტ შეერთება.</html>",
            "Common.choice.yes": "დიახ",
            "ColorChooser.rgbGreenText": "მწვანე",
            "Common.BasicPhetPanel.LogoToolTip": "მთელი ჩარჩო გამორთულია",
            "Common.updates.askMeLater": "მკითხე მოგვიანებით",
            "Common.preferences.updates": "განახლება",
            "Common.statistics.details.title": "ინფორმაცია",
            "Common.StopwatchPanel.reset": "აღადგინე",
            "Common.HelpPanel.ShowHelp": "დამეხმარე!",
            "ColorChooser.rgbRedText": "წითელი",
            "Common.updates.tryIt": "განახლებამდე სცადე ახალი ვერსია.",
            "XMLPersistenceManager.load.error.message": "<html>ფაილიდან კითხ.შეცდ:<br>{0}</html>",
            "Common.record": "ჩაწერა",
            "Common.softwareAgreement.decline": "გამოსვლა",
            "XMLPersistenceManager.load.error.decode": "<html>ფაილ.დეკოდ.შეცდ:<br>{0}</html>",
            "Common.title.confirm": "დადასტურება",
            "ColorChooser.swatchesNameText": "ნიმუშები",
            "ColorChooser.swatchesRecentText": "ბოლო დოკუმენტები:",
            "Common.statistics.sim_total_sessions": "სიმულაციის გაშვების ჯამური რიცხვი",
            "Common.updates.automaticallyCheck": "ავტომატურად შეამოწმე განახლებები"
        } );