// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.moleculeshapes;

import java.awt.image.BufferedImage;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Resources (images and translated strings) for "MoleculeShapes" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator
 */
public class MoleculeShapesResources {
    public static final String NAME = "molecule-shapes";
    public static final PhetResources RESOURCES = new PhetResources( NAME );

    //Strings
    public static class Strings {
        public static final String GEOMETRY__DIATOMIC = RESOURCES.getLocalizedString( "geometry.diatomic" );
        public static final String GEOMETRY__EMPTY = RESOURCES.getLocalizedString( "geometry.empty" );
        public static final String GEOMETRY__LINEAR = RESOURCES.getLocalizedString( "geometry.linear" );
        public static final String GEOMETRY__OCTAHEDRAL = RESOURCES.getLocalizedString( "geometry.octahedral" );
        public static final String GEOMETRY__TETRAHEDRAL = RESOURCES.getLocalizedString( "geometry.tetrahedral" );
        public static final String GEOMETRY__TRIGONAL_BIPYRAMIDAL = RESOURCES.getLocalizedString( "geometry.trigonalBipyramidal" );
        public static final String GEOMETRY__TRIGONAL_PLANAR = RESOURCES.getLocalizedString( "geometry.trigonalPlanar" );
        public static final String MOLECULE__SHAPES__TITLE = RESOURCES.getLocalizedString( "molecule-shapes.title" );
        public static final String SHAPE__BENT = RESOURCES.getLocalizedString( "shape.bent" );
        public static final String SHAPE__DIATOMIC = RESOURCES.getLocalizedString( "shape.diatomic" );
        public static final String SHAPE__EMPTY = RESOURCES.getLocalizedString( "shape.empty" );
        public static final String SHAPE__LINEAR = RESOURCES.getLocalizedString( "shape.linear" );
        public static final String SHAPE__OCTAHEDRAL = RESOURCES.getLocalizedString( "shape.octahedral" );
        public static final String SHAPE__SEESAW = RESOURCES.getLocalizedString( "shape.seesaw" );
        public static final String SHAPE__SQUARE_PLANAR = RESOURCES.getLocalizedString( "shape.squarePlanar" );
        public static final String SHAPE__SQUARE_PYRAMIDAL = RESOURCES.getLocalizedString( "shape.squarePyramidal" );
        public static final String SHAPE__T_SHAPED = RESOURCES.getLocalizedString( "shape.tShaped" );
        public static final String SHAPE__TETRAHEDRAL = RESOURCES.getLocalizedString( "shape.tetrahedral" );
        public static final String SHAPE__TRIGONAL_BIPYRAMIDAL = RESOURCES.getLocalizedString( "shape.trigonalBipyramidal" );
        public static final String SHAPE__TRIGONAL_PLANAR = RESOURCES.getLocalizedString( "shape.trigonalPlanar" );
        public static final String SHAPE__TRIGONAL_PYRAMIDAL = RESOURCES.getLocalizedString( "shape.trigonalPyramidal" );
    }

    //Images
    public static class Images {
        public static final BufferedImage DOUBLE_BOND_SMALL = RESOURCES.getImage( "double-bond-small.png" );
        public static final BufferedImage LONE_PAIR_SMALL = RESOURCES.getImage( "lone-pair-small.png" );
        public static final BufferedImage SINGLE_BOND_SMALL = RESOURCES.getImage( "single-bond-small.png" );
        public static final BufferedImage TRIPLE_BOND_SMALL = RESOURCES.getImage( "triple-bond-small.png" );
    }
}