//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_hu.properties
define( {
            "Games.label.level": "Szint: {0}",
            "Common.updates.errorMessage": "Frissítés közben hiba történt. Próbálkozzon <br>később vagy látogasson ide: {0}.",
            "XMLPersistenceManager.save.error.encode": "<html>Kódolási hiba:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Dekódolási hiba:<br>{0}</html>",
            "Common.softwareAgreement.decline": "Kilépés",
            "Common.statistics.host_os_name": "Operációs rendszer neve:",
            "Common.statistics.user_total_sessions": "Az összes szimuláció összes futtatásainak száma:",
            "Common.statistics.host_java_version_major": "Java-verzió (fő):",
            "FileChooser.openDialogTitleText": "Megnyit",
            "Common.WhiteBackground": "Fehér háttér",
            "Common.statistics.host_java_version_maintenance": "Java-verzió (javítás):",
            "FileChooser.lookInLabelText": "Itt keress:",
            "Common.choice.cancel": "Mégsem",
            "Common.updates.seePreferences": "A beállítások megváltoztatása  a Fájl->Beállítások menüpontban",
            "Common.About.CreditsDialog.software-development": "Szoftverfejlesztés",
            "Common.About.JavaVersion": "Java-verzió:",
            "ColorChooser.resetText": "Visszaállítás",
            "translation.credits": "<html><a href=\"http://nagysandor.eu/\">Nagy Sándor</a><br>ELTE, <a href=\"http://www.chem.elte.hu/pr/\">Kémiai Intézet</a>, Budapest</html>",
            "Common.About.CreditsDialog.design-team": "Dizájn Csoport",
            "Common.statistics.sim_total_sessions": "A szimuláció összes futtatásainak száma:",
            "Games.title.gameSettings": "Játékbeállítások",
            "XMLPersistenceManager.save.title": "Konfiguráció mentése",
            "XMLPersistenceManager.load.error.contents": "A fájl sérült, vagy nem ez a szimuláció hozta létre.",
            "Common.statistics.details.title": "Információ",
            "Common.statistics.sim_dev_version": "Szimulációverzió (fejl):",
            "FileChooser.saveInLabelText": "Mentés ide:",
            "Common.statistics.sim_name": "Szimuláció neve:",
            "Save.confirm.message": "<html>A kiválasztott nevű fájl már létezik.<br>Akarja, hogy lecserélődjön a mentett fájlra?</html>",
            "Games.label.score": "Pontszám: {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "PhET Fejlesztő Csoport",
            "Games.button.start": "Mehet!",
            "Common.statistics.sim_deployment": "Felhasználás típusa:",
            "Common.FileMenu.Save": "Konfiguráció mentése...",
            "Common.About.CreditsDialog.licenseDetails": "A licenc részletei",
            "Games.radioButton.on": "be",
            "FileChooser.acceptAllFileFilterText": "Minden fájl (*.*)",
            "Common.FileMenu.Preferences": "Beállítások...",
            "Common.FileMenu.Load": "Konfiguráció betöltése...",
            "Common.updates.downloadingSimJar": "szimulációs JAR fájl letöltése...",
            "Games.radioButton.off": "ki",
            "Jme.copyThisToTheClipboard": "Másolja ezt a vágólapra!",
            "ColorChooser.swatchesRecentText": "Jelenlegi:",
            "Common.updates.updateAvailable": "Létezik frissítés",
            "Common.statistics.host_locale_language": "Szerver nyelve:",
            "Common.clear": "Töröl",
            "Games.title.gameOver": "Játék vége",
            "FileChooser.filesOfTypeLabelText": "Fájltípus:",
            "Common.ErrorDialog.detailsTitle": "A hiba részletezése",
            "Common.HelpMenu.MegaHelp": "SÚGÓ",
            "Common.ClockControlPanel.Step": "Léptet",
            "Common.statistics.sim_revision": "Szimulációverzió (javítás):",
            "Common.choice.yes": "Igen",
            "Common.FileMenu.Title": "Fájl",
            "Common.statistics.sim_dev": "Fejlesztői verzió?:",
            "Common.updates.installer.message": "<html>Az offlájn PhET- webhely telepítési dátuma {0}.<br>Újabb verzió létezik, melynek dátuma  {1}.<br><br>Óhajtja a frissebb offlájn PhET- webhely telepítését?</html>",
            "Common.updates.updateNow": "Frissíts!",
            "Common.record": "Felvétel",
            "Common.About.CreditsDialog.Title": "Hivatkozás",
            "Common.updates.error.internetConnection": "<html>Ez a hely  {0}<br> nem érhető el. Ellenőrizze  a hálózatot.</html>",
            "Common.time.fast": "gyors",
            "XMLPersistenceManager.load.error.message": "<html>Olvasási hiba:<br>{0}</html>",
            "Common.OptionsMenu": "Opciók",
            "Common.ClockControlPanel.Restart": "Újraindít",
            "Common.statistics.sim_version_timestamp": "Szimulációverzió (időbélyegző):",
            "Common.updates.installer.yes": "Igen!",
            "Common.phetInstaller": "Offlájn PhET  Webhelytelepítő",
            "Jme.thisSimulationWasUnableToStart": "A szimuláció nem tudott elindulni.",
            "Common.HelpMenu.About": "Névjegy...",
            "Common.ModelSlider.OutOfRange": "Túl kis/nagy érték",
            "Common.About.CreditsDialog.TranslationCreditsTitle": "Magyarítás:",
            "ColorChooser.previewText": "Eőnézet",
            "Common.BasicPhetPanel.Title": "Vissza",
            "Common.HelpPanel.HideHelp": "Súgó elrejtése",
            "Common.statistics.host_os_arch": "Processzortípus:",
            "Common.preferences.title": "Beállítások",
            "Games.button.newGame": "Új játék",
            "Common.ModelSlider.YouEntered": "Belépett",
            "Games.label.newBest": "REKORD!",
            "Common.About.BuildDate": "Verzió (build) dátuma",
            "Common.statistics.sim_project": "Projekt neve:",
            "Games.label.best": "Legjobb: {0}",
            "Common.title.message": "Üzenet",
            "Common.updates.downloadingBootstrap": "frissítő letöltése...",
            "Common.title.error": "Hiba",
            "Common.FileMenu.Exit": "Kilépés",
            "Common.statistics.sim_major_version": "Szimulációverzió (major):",
            "Common.updates.askMeLater": "Kérdezz máskor",
            "chart-time-control.go": "Mehet!",
            "Common.confirm.clear.graphs": "Biztosan törölni akarja a grafikonokat?",
            "ColorChooser.swatchesNameText": "Színtár",
            "Common.updates.progressDialogMessage": " \"{0}\" frissítése. Új verzió: {1}",
            "Common.updates.installer.more": "Bővebb információt kérek...",
            "XMLPersistenceManager.title.error": "Hiba",
            "ControlPanel.button.resetAll": "Mindent visszaállít",
            "Common.About.AgreementButton": "Felhasználási feltételek...",
            "Common.ErrorDialog.detailsButton": "Részletezés...",
            "Common.updates.errorMissingJar": "<html>A frissítést nem lehetett végrehajtani.<br>A JAR fájl: {0} nem található.<br>Kérjen segítséget  rendszergazdájától.<br></html>",
            "Common.preferences.privacy": "Adatvédelem",
            "Common.HelpMenu.AboutTitle": "Névjegy",
            "ColorChooser.rgbRedText": "Vörös",
            "Common.statistics.sim_locale_country": "Ország:",
            "ColorChooser.rgbGreenText": "Zöld",
            "Common.HelpPanel.ShowHelp": "Súgó!",
            "PiccoloPhet.VelocitySensorNode.speed": "Sebesség",
            "Common.statistics.sim_distribution_tag": "Szimulációverzió (terjesztett):",
            "Common.statistics.description": "A PhET ingyenes használatát finanszírozó <br> pályázatok  minimális mennnyiségű <br>névtelen <a href=\"{0}\">információ</a> begyűjtését követelik meg,<br> hogy dokumentálhassuk a PhET-szimulációk <br> használatát, és  javíthassuk szolgáltatásainkat.",
            "Common.softwareAgreement.message": "A PhET-szimulációk minimális mennyiségű<br>névtelen <a href=\"{0}\">információt</a> gyűjtenek a szimuláció <br>indításakor (pl.  szimulációverzió, operációs rendszer).<br>Az információküldés bármikor letiltható<br>a  Fájl->Beállítások menüpontban.<br><br>Az  \"Elfogadás és folytatás\" pontra kattintva, elfogadja a <br>PhET Felhasználási feltételeit, beleértve az adatvédelmi <br>nyilatkozatot, nemcsak a jelen, hanem a többi  PhET-<br>szimulációra  vonatkozóan  is, melyet futtat. (Részletek <a href=\"{1}\">itt</a>).",
            "Common.About.Version": "Verzió:",
            "Common.ErrorDialog.contactPhet": "Ha a probléma ismétlődik, küldje az alábbi részleteket ide: {0}",
            "Common.About.CreditsDialog.lead-design": "Dizájnirányítás",
            "Jme.moreInformation": "<html><body>A videokártya meghajtójának frissítése segíthet a problémán.<br/>További információért látogasson ide {0}, vagy másolja bele<br/>a következőt egy emailbe, majd küldje el ide {1}.<br/></body></html>",
            "Common.statistics.user_preference_file_creation_time": "Beállítások fájlgenerálás időbélyegzője:",
            "Sponsor.sponsoredBy": "A szim támogatója",
            "Common.updates.errorWritePermissions": "<html>A frissítést nem lehetett végrehajtani.<br>Nincs írási engedélye ide: {0}.<br>Kérjen segítséget  rendszergazdájától.<br></html>",
            "Common.choice.no": "Nem",
            "Common.About.WebLink": "Látogassa meg a PhET honlapját",
            "Common.About.OSVersion": "OR verzió:",
            "Common.title.warning": "Figyelmeztetés",
            "Common.updates.versionComparison": "<html> \"{0}\" jelenlegi verziója {1}.<br>Újabb verzió ({2}) is létezik.</html>",
            "Common.statistics.sim_locale_language": "Nyelv:",
            "Common.statistics.user_installation_timestamp": "PhET-telepítés időbélyegzője:",
            "Common.statistics.message_version": "Üzenetverzió:",
            "Common.ModelSlider.Description": "Helytelen érték.",
            "Common.updates.installer.moreMessage": "<html>Az offlájn PhET- webhely  frissítése lehetővé teszi, <br>hogy elérje a legújabb PhET-szimulációkat<br>és a kiegészítő anyagokat.<br><br>Ha a frissítés mellett dönt, egy új böngészőablak <br>nyílik meg a PhET-webhellyel, ahonnan letöltheti<br>az offlájn PhET- webhely telepítőjét.</html>",
            "ControlPanel.message.confirmResetAll": "Minden beállítást visszaállít?",
            "Common.HelpMenu.Help": "Súgó",
            "Common.updates.errorNotAJar": "{0} nem  JAR fájl.",
            "Games.label.levelControl": "Szint:",
            "Common.updates.automaticallyCheck": "Frissítések automatikus ellenőrzése",
            "Common.sim.speed": "...szimulációsebesség...",
            "Common.updates.checkForSimUpdate": "Szimulációfrissítés ellenőrzése...",
            "XMLPersistenceManager.save.confirm.message": "<html>A kiválasztott nevű fájl már létezik.<br>Akarja, hogy lecserélődjön a mentett fájlra?</html>",
            "FileChooser.newFolderErrorText": "Hiba az új könyvtár létrehozása közben ",
            "Common.updates.skipThisUpdate": "Kihagyom ezt a verziót",
            "Common.About.CreditsButton": "Hivatkozás...",
            "FileChooser.saveDialogTitleText": "Elment",
            "Common.TeacherMenu": "Tanár",
            "XMLPersistenceManager.load.title": "Konfiguráció betöltése",
            "Common.updates.checkForInstallerUpdate": "Offlájn PhET- webhely telepítő frissítésének ellenőrzése...",
            "timeseries.control.panel.playback": "Visszajátszás",
            "Sponsor.sponsorMenuItem": "Támogató...",
            "Common.updates.progressDialogTitle": "Frissítés",
            "Common.HelpMenu.Title": "Súgó",
            "FileChooser.fileNameLabelText": "Fájlnév:",
            "Common.softwareAgreement.title": "Felhasználási feltételek",
            "Common.statistics.host_java_version_minor": "Java-verzió (al):",
            "Common.About.CreditsDialog.interviews": "Konzultáció",
            "Common.About.Distribution": "Forgalmazás:",
            "Common.statistics.host_java_webstart_version": "Java Web Start-verzió:",
            "XMLPersistenceManager.save.error.message": "<html>Írási hiba:<br>{0}</html>",
            "Games.label.time": "Idő: {0}",
            "FileChooser.openButtonText": "Megnyit",
            "ColorChooser.sampleText": "Szövegminta Szövegminta",
            "Common.statistics.details.description": "<html>Az alábbi információ mindannyiszor  elküldésre kerül, amikor a PhET -szimuláció elindul.</html>",
            "Common.statistics.host_os_version": "Operációs rendszer verziója:",
            "Common.title.confirm": "Megerősítés",
            "Common.BasicPhetPanel.LogoToolTip": "Teljes nézet letiltása",
            "Games.label.score.max": "Pontszám: {0} (max.: {1})",
            "Common.statistics.host_java_timezone": "Időzóna:",
            "Common.time.slow": "lassú",
            "Common.ClockControlPanel.Rewind": "Elejére",
            "Common.softwareAgreement.accept": "Elfogadás és folytatás",
            "message.valueOutOfRange": "Az értéknek {0} és {1} közé kell esnie.",
            "Common.updates.updateToDate": "Naprakész",
            "Common.ClockControlPanel.Pause": "Pillanat állj",
            "PhetApplication.StartupDialog.message": "\"{0}\" indítás alatt",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "A program a következő idegen szoftvereket használja",
            "XMLPersistenceManager.message.notAConfigFile": "Ez a fájl nem tartalmaz konfigurációt ehhez a szimulációhoz.",
            "Common.preferences.updates": "Frissítések",
            "Games.label.score.max.perfect": "Pontszám: {0} (max.: {1}) TÖKÉLETES!",
            "Common.statistics.enabled": "Információküldés engedélyezése a PhET-hez",
            "Common.ClockControlPanel.StepBack": "Visszaléptet",
            "Common.HelpPanel.MegaHelp": "SÚGÓ...",
            "Common.statistics.host_locale_country": "Szerver országa:",
            "Common.StopwatchPanel.reset": "Visszaállít",
            "Common.playback": "Visszajátszás",
            "Common.statistics.sim_minor_version": "Szimulációverzió (minor):",
            "Games.message.confirmNewGame": "<html>Még nem fejezted be a játékot!<br>Biztos, hogy újat akarsz kezdeni?</html>",
            "Common.updates.tryIt": "Próbálja ki az új verziót frissítés előtt!",
            "ColorChooser.rgbBlueText": "Kék",
            "Common.choice.close": "Bezár",
            "Common.ClockControlPanel.Play": "Lejátszás",
            "Common.statistics.sim_type": "Szimuláció típusa:",
            "FileChooser.saveButtonText": "Elment",
            "Common.rewind": "Elejére",
            "Common.updates.youHaveCurrent": "Önnek {1} legfrissebb verziója ({0}) van meg.",
            "Common.statistics.sim_sessions_since": "A szimuláció futtatásainak száma az utolsó onlájn kapcsolat óta:",
            "Common.statistics.host_java_vendor": "Java-forgalmazó:",
            "charts.show-graphs": "Grafikonok mutatása:",
            "Common.statistics.message_type": "Üzenettípus:"
        } );