// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.forcesandmotionbasics;

import java.awt.image.BufferedImage;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Resources (images and translated strings) for "ForcesAndMotionBasics" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator
 */
public class ForcesAndMotionBasicsResources {
    public static final String PROJECT_NAME = "forces-and-motion-basics";
    public static final PhetResources RESOURCES = new PhetResources( PROJECT_NAME );

    //Strings
    public static class Strings {

    }

    //Images
    public static class Images {
        public static final BufferedImage BRICK_TILE = RESOURCES.getImage( "brick-tile.png" );
        public static final BufferedImage CLOUD1 = RESOURCES.getImage( "cloud1.png" );
        public static final BufferedImage DRAKOONSONNE = RESOURCES.getImage( "DrakoonSonne.png" );
        public static final BufferedImage GROUND_TEXTURE = RESOURCES.getImage( "ground-texture.png" );
        public static final BufferedImage MYSTERY_BOX = RESOURCES.getImage( "mystery-box.png" );
    }
}