// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.forcesandmotionbasics;

import java.awt.image.BufferedImage;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Resources (images and translated strings) for "ForcesAndMotionBasics" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator
 */
public class ForcesAndMotionBasicsResources {
    public static final String PROJECT_NAME = "forces-and-motion-basics";
    public static final PhetResources RESOURCES = new PhetResources( PROJECT_NAME );

    //Strings
    public static class Strings {

    }

    //Images
    public static class Images {
        public static final BufferedImage BRICK_TILE = RESOURCES.getImage( "brick-tile.png" );
        public static final BufferedImage CART = RESOURCES.getImage( "cart.png" );
        public static final BufferedImage CLOUD1 = RESOURCES.getImage( "cloud1.png" );
        public static final BufferedImage DRAKOONSONNE = RESOURCES.getImage( "DrakoonSonne.png" );
        public static final BufferedImage GO_BUTTON = RESOURCES.getImage( "go_button.png" );
        public static final BufferedImage GO_HOVER = RESOURCES.getImage( "go_hover.png" );
        public static final BufferedImage GO_PRESSED = RESOURCES.getImage( "go_pressed.png" );
        public static final BufferedImage GO_UP = RESOURCES.getImage( "go_up.png" );
        public static final BufferedImage GRASS = RESOURCES.getImage( "grass.png" );
        public static final BufferedImage GROUND_TEXTURE = RESOURCES.getImage( "ground-texture.png" );
        public static final BufferedImage MYSTERY_BOX = RESOURCES.getImage( "mystery-box.png" );
        public static final BufferedImage PULL_FIGURE_BLUE_0 = RESOURCES.getImage( "pull_figure_BLUE_0.png" );
        public static final BufferedImage PULL_FIGURE_BLUE_1 = RESOURCES.getImage( "pull_figure_BLUE_1.png" );
        public static final BufferedImage PULL_FIGURE_BLUE_2 = RESOURCES.getImage( "pull_figure_BLUE_2.png" );
        public static final BufferedImage PULL_FIGURE_BLUE_3 = RESOURCES.getImage( "pull_figure_BLUE_3.png" );
        public static final BufferedImage PULL_FIGURE_LRG_BLUE_0 = RESOURCES.getImage( "pull_figure_lrg_BLUE_0.png" );
        public static final BufferedImage PULL_FIGURE_LRG_BLUE_1 = RESOURCES.getImage( "pull_figure_lrg_BLUE_1.png" );
        public static final BufferedImage PULL_FIGURE_LRG_BLUE_2 = RESOURCES.getImage( "pull_figure_lrg_BLUE_2.png" );
        public static final BufferedImage PULL_FIGURE_LRG_BLUE_3 = RESOURCES.getImage( "pull_figure_lrg_BLUE_3.png" );
        public static final BufferedImage PULL_FIGURE_LRG_RED_0 = RESOURCES.getImage( "pull_figure_lrg_RED_0.png" );
        public static final BufferedImage PULL_FIGURE_LRG_RED_1 = RESOURCES.getImage( "pull_figure_lrg_RED_1.png" );
        public static final BufferedImage PULL_FIGURE_LRG_RED_2 = RESOURCES.getImage( "pull_figure_lrg_RED_2.png" );
        public static final BufferedImage PULL_FIGURE_LRG_RED_3 = RESOURCES.getImage( "pull_figure_lrg_RED_3.png" );
        public static final BufferedImage PULL_FIGURE_RED_0 = RESOURCES.getImage( "pull_figure_RED_0.png" );
        public static final BufferedImage PULL_FIGURE_RED_1 = RESOURCES.getImage( "pull_figure_RED_1.png" );
        public static final BufferedImage PULL_FIGURE_RED_2 = RESOURCES.getImage( "pull_figure_RED_2.png" );
        public static final BufferedImage PULL_FIGURE_RED_3 = RESOURCES.getImage( "pull_figure_RED_3.png" );
        public static final BufferedImage PULL_FIGURE_SMALL_BLUE_0 = RESOURCES.getImage( "pull_figure_small_BLUE_0.png" );
        public static final BufferedImage PULL_FIGURE_SMALL_BLUE_1 = RESOURCES.getImage( "pull_figure_small_BLUE_1.png" );
        public static final BufferedImage PULL_FIGURE_SMALL_BLUE_2 = RESOURCES.getImage( "pull_figure_small_BLUE_2.png" );
        public static final BufferedImage PULL_FIGURE_SMALL_BLUE_3 = RESOURCES.getImage( "pull_figure_small_BLUE_3.png" );
        public static final BufferedImage PULL_FIGURE_SMALL_RED_0 = RESOURCES.getImage( "pull_figure_small_RED_0.png" );
        public static final BufferedImage PULL_FIGURE_SMALL_RED_1 = RESOURCES.getImage( "pull_figure_small_RED_1.png" );
        public static final BufferedImage PULL_FIGURE_SMALL_RED_2 = RESOURCES.getImage( "pull_figure_small_RED_2.png" );
        public static final BufferedImage PULL_FIGURE_SMALL_RED_3 = RESOURCES.getImage( "pull_figure_small_RED_3.png" );
        public static final BufferedImage ROPE = RESOURCES.getImage( "rope.png" );
        public static final BufferedImage STOP_BUTTON = RESOURCES.getImage( "stop_button.png" );
        public static final BufferedImage STOP_HOVER = RESOURCES.getImage( "stop_hover.png" );
        public static final BufferedImage STOP_PRESSED = RESOURCES.getImage( "stop_pressed.png" );
        public static final BufferedImage STOP_UP = RESOURCES.getImage( "stop_up.png" );
    }
}