//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_et.properties
define( {
            "XMLPersistenceManager.load.error.contents": "Fail on vigane või ei ole salvestatud selle simulatsiooniga.",
            "Common.FileMenu.TitleMnemonic": "f",
            "XMLPersistenceManager.save.error.message": "<html>Viga faili kirjutamisel:<br>{0}</html>",
            "Common.choice.ok": "OK",
            "Common.title.confirm": "Kinnita",
            "Common.StopwatchPanel.start": "Start",
            "Common.ModelSlider.YouEntered": "Sa sisestasid",
            "Common.StopwatchPanel.stop": "Stop",
            "XMLPersistenceManager.save.confirm.message": "<html>Faili nimi mille valisid on juba olemas.<br>Kas sa tahad selle üle salvestada?</html>",
            "Common.About.JavaVersion": "Java Versioon:",
            "XMLPersistenceManager.load.error.message": "<html>Viga faili lugemisel:<br>{0}</html>",
            "Common.HelpMenu.VersionLabel": "Versioon",
            "Common.About.CreditsDialog.Title": "Tiitrid",
            "Common.FileMenu.Exit": "Välju",
            "Common.HelpMenu.JavaVersion": "Java Versioon",
            "Common.HelpMenu.Help": "Abi",
            "Common.HelpMenu.AboutMnemonic": "a",
            "Common.HelpMenu.TitleMnemonic": "h",
            "XMLPersistenceManager.save.error.encode": "<html>Viga faili kodeerimisel:<br>{0}</html>",
            "Common.About.LicenseButton": "Litsents...",
            "Common.choice.no": "Ei",
            "Common.HelpPanel.HideHelp": "Peida Abi!",
            "Common.HelpPanel.MegaHelp": "Megaabi...",
            "Common.About.OKButton": "OK",
            "Common.HelpMenu.By": "",
            "Common.StopwatchPanel.reset": "Tühista",
            "Common.ClockTimeReadout.RunningTime": "Jooksev aeg",
            "Common.About.LicenseDialog.Title": "Litsents",
            "Common.ClockControlPanel.Restart": "Taaskäivita",
            "Common.HelpMenu.AboutTitle": "Mis on",
            "XMLPersistenceManager.load.title": "Lae seadistused",
            "Common.About.WebLink": "Visit the PhET Homepage",
            "Common.HelpMenu.HelpMnemonic": "h",
            "Common.ModelSlider.Description": "Sobimatu väärtus.",
            "Common.ModelSlider.Minimum": "Miinimum",
            "XMLPersistenceManager.save.error.xmlencoder": "XML kodeerimine ebaõnnestus.",
            "Common.FileMenu.Title": "Fail",
            "Common.About.CreditsButton": "Tiitrid...",
            "Common.HelpMenu.MegaHelp": "MegaAbi...",
            "XMLPersistenceManager.load.error.decode": "<html>Viga faili lahti kodeerimisel:<br>{0}</html>",
            "XMLPersistenceManager.save.title": "Salevesta seadistus",
            "ControlPanel.button.resetAll": "Tühista kõik",
            "Common.ModelSlider.Maximum": "Maksimum",
            "Common.ClockControlPanel.Play": "Mängi",
            "Save.confirm.message": "<html>Faili nimi mille valisid on juba olemas.<br>Kas sa tahad selle üle salvestada?</html>",
            "Common.BasicPhetPanel.Title": "Tagasi",
            "Common.ClockControlPanel.Step": "Samm edasi",
            "Common.About.Version": "Versioon:",
            "ControlPanel.message.confirmResetAll": "Taasta kõik algseadistused?",
            "Common.choice.yes": "Jah",
            "Common.HelpMenu.About": "Mis on...",
            "XMLPersistenceManager.title.error": "Viga",
            "Common.choice.cancel": "Tühista",
            "Common.BasicPhetPanel.LogoToolTip": "Tühista täis raam",
            "Common.FileMenu.ExitMnemonic": "x",
            "Common.ClockControlPanel.Pause": "Paus",
            "PhetApplication.StartupDialog.message": "\"{0}\" käivitub",
            "Common.ModelSlider.OutOfRange": "Väärtus väljaspool ulatust",
            "Common.HelpMenu.Title": "Abi",
            "Common.HelpPanel.ShowHelp": "Abi!",
            "Common.HelpMenu.MegaHelpMnemonic": "m"
        } );