//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_el.properties
define( {
            "Games.label.level": "Επίπεδο: {0}",
            "Common.updates.errorMessage": "Εντοπίστηκε ένα σφάλμα κατά την προσπάθεια ενημέρωσης. <br>Παρακαλώ προσπαθήστε αργότερα, ή επισκεφθείτε {0}.",
            "XMLPersistenceManager.save.error.encode": "<html>Σφάλμα κωδικοποίησης στο αρχείο:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Σφάλμα αποκωδικοποίησης στο αρχείο:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "f",
            "Common.softwareAgreement.decline": "Έξοδος",
            "Common.statistics.host_os_name": "Όνομα λειτουργικού συστήματος",
            "Common.statistics.user_total_sessions": "Συνολικός αριθμός εκτελέσεων όλων των προσομοιώσεων",
            "Common.statistics.host_java_version_major": "Έκδοση Java (μεγαλύτερη)",
            "FileChooser.openDialogTitleText": "Άνοιγμα",
            "Common.WhiteBackground": "Λευκό παρασκήνιο",
            "Common.statistics.host_java_version_maintenance": "Έκδοση Java (συντήρηση)",
            "FileChooser.lookInLabelText": "Αναζήτηση σε:",
            "Common.choice.cancel": "Ακύρωση",
            "Common.updates.seePreferences": "Μετάβαση στο αρχείο->Προτιμήσεις για να κάνετε αλλαγές.",
            "Common.About.CreditsDialog.software-development": "Ανάπτυξη λογισμικού",
            "Common.About.JavaVersion": "Έκδοση Java:",
            "ColorChooser.resetText": "Επαναφορά",
            "wavelength.ir": "IR",
            "translation.credits": "Yannis Kaskamanidis",
            "Common.WhiteBackground.mnemonic": "λ",
            "Common.About.CreditsDialog.design-team": "Ομάδα σχεδίασης",
            "Common.statistics.sim_total_sessions": "Συνολικός αριθμός εκτελέσεων αυτής της προσομοίωσης",
            "Common.FileMenu.PreferencesMnemonic": "p",
            "wavelength.uv": "UV",
            "Games.title.gameSettings": "Ρυθμίσεις παιχνιδιού",
            "XMLPersistenceManager.save.title": "Αποθήκευση Διαμόρφωσης",
            "XMLPersistenceManager.load.error.contents": "Το αρχείο είναι χαλασμένο ή δεν δημιουργήθηκε από αυτή την προσομοίωση.",
            "Common.statistics.details.title": "Πληροφορίες",
            "Common.statistics.sim_dev_version": "Έκδοση προσομοίωσης (ανάπτυξη)",
            "FileChooser.saveInLabelText": "Αποθήκευση σε:",
            "Common.statistics.sim_name": "Όνομα προσομοίωσης",
            "Save.confirm.message": "<html>Το αρχείο που επιλέξατε υπάρχει ήδη.<br>Να γίνει αντικατάσταση με το αρχείο που αποθηκεύετε;</html>",
            "Games.label.score": "Βαθμολογία: {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "Ομάδα ανάπτυξης του PhET",
            "Games.button.start": "Έναρξη!",
            "Common.statistics.sim_deployment": "Είδος ανάπτυξης",
            "Common.FileMenu.Save": "Αποθήκευση ρυθμίσεων...",
            "Common.About.CreditsDialog.licenseDetails": "Λεπτομέρειες αδειοδότησης",
            "ColorChooser.hsbSaturationText": "S",
            "Games.radioButton.on": "κλειστό",
            "FileChooser.acceptAllFileFilterText": "Όλα τα αρχεία (*.*)",
            "ColorChooser.hsbNameText": "HSB",
            "Common.ModelSlider.Minimum": "Ελάχιστο",
            "Common.FileMenu.Preferences": "Προτιμήσεις...",
            "Common.FileMenu.Load": "Φόρτωση ρυθμίσεων...",
            "Common.updates.downloadingSimJar": "Java αρχείο λήψης προσομοίωσης...",
            "Games.radioButton.off": "ανοιχτό",
            "Jme.copyThisToTheClipboard": "Αντιγραφή αυτού στο πρόχειρο",
            "ColorChooser.swatchesRecentText": "Πρόσφατο:",
            "Common.updates.updateAvailable": "Διαθέσιμη ενημέρωση",
            "Common.statistics.host_locale_language": "Γλώσσα υπολογιστή",
            "Common.clear": "Καθαρισμός",
            "Games.title.gameOver": "Τέλος παιχνιδιού",
            "FileChooser.filesOfTypeLabelText": "Αρχεία είδους:",
            "Common.ErrorDialog.detailsTitle": "Λεπτομέρειες σφάλματος",
            "Common.HelpMenu.MegaHelp": "Μεγα-βοήθεια...",
            "Common.ClockControlPanel.Step": "Βήμα",
            "Common.statistics.sim_revision": "Έκδοση προσομοίωσης (αναθεωρημένη)",
            "Common.choice.yes": "Ναι",
            "PiccoloPhet.VelocitySensorNode.unknown": ";",
            "Common.FileMenu.Title": "Αρχείο",
            "Common.value_units": "{0} {1}",
            "Common.statistics.sim_dev": "Είναι μια έκδοση ανάπτυξης;",
            "Common.updates.installer.message": "<html> Η εκτός σύνδεσης εγκατάσταση του PhET είναι απαρχαιωμένη {0}.<br> Μια νεώτερη έκδοση είναι διαθέσιμη, με ημερομηνία {1}.<br><br>Θέλετε να λάβετε την τελευταία έκδοση εκτός σύνδεσης εγκατάσταση του PhET;</html>",
            "Common.updates.updateNow": "Ενημέρωση τώρα!",
            "Common.record": "Εγγραφή",
            "Common.About.CreditsDialog.Title": "Εύσημα",
            "Common.updates.error.internetConnection": "<html>Αδυναμία σύνδεσης στο {0},<br>παρακαλώ ελέγξτε τη σύνδεσήσ σας.</html>",
            "Common.time.fast": "γρήγορα",
            "XMLPersistenceManager.load.error.message": "<html>Σφάλμα ανάγνωσης από το αρχείο:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Μέγιστο",
            "Common.OptionsMenu": "Επιλογές",
            "Common.ClockControlPanel.Restart": "Επανέναρξη",
            "Common.statistics.sim_version_timestamp": "Έκδοση προσομοίωσης (χρονική ένδειξη)",
            "Common.updates.installer.yes": "Ναι!",
            "Common.phetInstaller": "Εκτός σύνδεσης εγκαταστάσης του PhET",
            "Jme.thisSimulationWasUnableToStart": "Δεν είναι δυνατή η εκκίνηση αυτής της προσομοίωσης.",
            "Common.HelpMenu.About": "Σχετικά με...",
            "Common.ModelSlider.OutOfRange": "Τιμή εκτός κλίμακας",
            "Common.About.CreditsDialog.TranslationCreditsTitle": "Μεταφράστηκε από τον",
            "ColorChooser.previewText": "Προεπισκόπηση",
            "Common.BasicPhetPanel.Title": "Επιστροφή",
            "Common.HelpPanel.HideHelp": "Απόκρυψη bοήθειας",
            "Common.statistics.host_os_arch": "Είδος επεξεργαστή",
            "Common.preferences.title": "Προτιμήσεις",
            "Games.button.newGame": "Νέο παιχνίδι",
            "ColorChooser.hsbRedText": "R",
            "ColorChooser.hsbBlueText": "B",
            "Common.ModelSlider.YouEntered": "Πληκτρολογήσατε",
            "Games.label.newBest": "ΝΕΟ ΚΑΛΥΤΕΡΟ:",
            "Common.About.BuildDate": "Ημερομηνία δημιουργίας:",
            "Common.FileMenu.ExitMnemonic": "x",
            "Common.statistics.sim_project": "Όνομα έργου",
            "Games.label.best": "Καλύτερο: {0}",
            "Common.title.message": "Μήνυμ",
            "Common.updates.downloadingBootstrap": "σύνολο εντολών για τη λήψη της ενημέρωσης...",
            "Common.title.error": "Σφάλμα",
            "Common.FileMenu.Exit": "Έξοδος",
            "Common.statistics.sim_major_version": "Έκδοση προσομοίωσης (μεγαλύτερη)",
            "Common.updates.askMeLater": "Ρώτα με αργότερα",
            "chart-time-control.go": "Πάμε!",
            "Common.HelpMenu.HelpMnemonic": "Β",
            "Common.confirm.clear.graphs": "Είστε βέβαιος ότι θέλετε να καθαρίσετε τα γραφήματα;",
            "ColorChooser.swatchesNameText": "Δείγματα",
            "Common.updates.progressDialogMessage": "Ενημέρωση \"{0}\" στην έκδοση {1}",
            "Common.updates.installer.more": "Πες μου περισσότερα...</html>",
            "XMLPersistenceManager.title.error": "Σφάλμα",
            "ColorChooser.hsbHueText": "H",
            "ControlPanel.button.resetAll": "Επαναφορά Όλων",
            "Common.About.AgreementButton": "Άδεια χρήσης λογισμικού...",
            "Common.FileMenu.Load.mnemonic": "L",
            "Common.ErrorDialog.detailsButton": "Λεπτομέρειες...",
            "Common.updates.errorMissingJar": "<html>Αυτή η ενημέρωση δεν μπορεί να ολοκληρωθεί.<br>Δεν είναι δυνατός ο εντοπισμός του αρχείου JAR: {0}.<br>Παρακαλώ επικοινωνήστε με τον διαχειριστή του συστήματος για να ζητήσετε βοήθεια.<br></html>",
            "Common.preferences.privacy": "Απόρρητο",
            "Common.HelpMenu.AboutTitle": "Σχετικά με",
            "ColorChooser.rgbRedText": "Κόκκινο",
            "Common.statistics.sim_locale_country": "Χώρα",
            "ColorChooser.hsbGreenText": "G",
            "ColorChooser.rgbGreenText": "Πράσινο",
            "Games.format.time.best": "{0} ({1})",
            "Common.HelpPanel.ShowHelp": "Βοήθεια!",
            "PiccoloPhet.VelocitySensorNode.speed": "Ταχύτητα",
            "Common.statistics.sim_distribution_tag": "Έκδοση προσομοίωσης (διανομή)",
            "Common.statistics.description": "Το PhET είναι ελεύθερα διαθέσιμο μέσω επιχορηγήσεων οι οποίες <br>απαιτούν από εμάς τη συλλογή μερικών <br>ανώνυμων <a href=\"{0}\">πληροφοριών</a> προκειμένου να βοηθηθούμε στην τεκμηρίωση της χρήσης των προσομοιώσεων του PhET<br> και να ικανοποιούμε καλύτερα τις ανάγκες των χρηστών.",
            "Common.softwareAgreement.message": "Σε όλες τις προσομοιώσεις του PhET, συλλέγουμε μερικές ανώνυμες <a href='{0}'>πληροφορίες</a> κάθε φορά που ξεκινά μια προσομοίωση (π.χ. έκδοση προσομοίωσης, λειτουργικό σύστημα). Μπορείτε να απενεργοποιήσετε την αποστολή αυτών των πληροφοριών ανά πάσα στιγμή μέσα από το μενού Προτιμήσεις. Κάνοντας κλικ στο \"Αποδοχή και συνέχεια\" συμφωνείτε με την Άδεια χρήσης του PhET, που περιλαμβάνει την πολιτική απορρήτου γι' αυτήν και για κάθε προσομοίωση του PhET που εκτελείτε στον υπολογιστή σας. (Για λεπτομέρειες  <a href='{1}'>κάντε κλικ εδώ</a>).",
            "Common.choice.ok": "Εντάξει",
            "Common.About.Version": "Έκδοση:",
            "Common.ErrorDialog.contactPhet": "Εάν αυτό το πρόβλημα παραμένει, στείλτε τις παρακάτω λεπτομέρειες στο {0}",
            "Common.About.CreditsDialog.lead-design": "Καθοδήγηση σχεδιασμού",
            "Common.OptionsMenu.mnemonic": "O",
            "Jme.moreInformation": "<html><body>Αναβάθμιση του προγράμματος οδήγησης της κάρτας γραφικών, ενδεχομένως να λύσει αυτό το πρόβλημα.<br/>Για περισσότερες πληροφορίες, επισκεφθείτε {0},<br/> ή αντιγράψτε και επικολλήστε το ακόλουθο σε ένα μήνυμα email προς {1}.<br/></body></html>",
            "Common.statistics.user_preference_file_creation_time": "Χρονική ένδειξη δημιουργίας αρχείου Προτιμήσεων",
            "Common.HelpMenu.AboutMnemonic": "a",
            "Common.updates.errorWritePermissions": "<html>Αυτή η ενημέρωση δεν μπορεί να ολοκληρωθεί.<br>Δεν έχετε δικαιώματα εγγραφής στο {0}.<br>>Παρακαλώ επικοινωνήστε με τον διαχειριστή του συστήματος για να ζητήσετε βοήθεια.<br></html>",
            "ColorChooser.hsbBrightnessText": "B",
            "Common.choice.no": "Όχι",
            "Common.About.WebLink": "Επισκεφθείτε την Ιστοσελίδα του Phet",
            "Common.About.OSVersion": "Έκδοση λειτουργικού συστήματος:",
            "Common.title.warning": "Προειδοποίηση",
            "Common.updates.versionComparison": "<html>Η τρέχουσα έκδοσή σας του \"{0}\" είναι {1}.<br>Μια νεότερη έκδοση ({2}) είναι διαθέσιμη.</html>",
            "Common.statistics.sim_locale_language": "Γλώσσα",
            "Common.statistics.user_installation_timestamp": "Χρονική ένδειξη εγκατάστασης του PhET",
            "Common.statistics.message_version": "Έκδοση μηνύματος",
            "Common.ModelSlider.Description": "μη αποδεκτή τιμή.",
            "Common.updates.installer.moreMessage": "<html>Διατηρώντας την εκτός σύνδεσης εγκατάσταση του PhET ενημερωμένη<br>εξασφαλίζετε ότι θα έχετε πρόσβαση στις νεότερες προσομοιώσεις<br>και το συμπληρωματικό υλικό του PhET.<br><br>Εάν επιλέξετε να λάβετε την τελευταία ενημέρωση, ένας περιηγητής ιστού <br>θα ανοίξει την ιστοσελίδα του PhET, όπου μπορείτε να κάνετε λήψη<br>του εκτός σύνδεσης εγκαταστάτη του PhET.</html>",
            "Common.HelpMenu.Help": "Βοήθεια",
            "Common.updates.errorNotAJar": "{0} δεν είναι ένα αρχείο JAR.",
            "ControlPanel.message.confirmResetAll": "Επαναφορά όλων των ρυθμίσεων;",
            "Games.label.levelControl": "Επίπεδο:",
            "Common.updates.automaticallyCheck": "Αυτόματος έλεγχος για ενημερώσεις",
            "Common.sim.speed": "... ταχύτητα προσομοίωσης...",
            "Common.updates.checkForSimUpdate": "Έλεγχος για ενημέρωση της προσομοίωσης...",
            "XMLPersistenceManager.save.confirm.message": "<html>Το αρχείο που επιλέξατε υπάρχει ήδη.<br>Να γίνει αντικατάσταση με το αρχείο που αποθηκεύετε;</html>",
            "FileChooser.newFolderErrorText": "Σφάλμα δημιουργίας νέου φακέλου",
            "Common.About.CreditsButton": "Εύσημα...",
            "Common.updates.skipThisUpdate": "Παράκαμψη αυτής της έκδοσης",
            "Common.FileMenu.Save.mnemonic": "S",
            "Common.TeacherMenu": "Δάσκαλος",
            "FileChooser.saveDialogTitleText": "Αποθήκευση",
            "XMLPersistenceManager.load.title": "Φόρτωση Διαμόρφωσης",
            "Common.updates.checkForInstallerUpdate": "Έλεγχος για ενημερώσεις της εκτός σύνδεσης εγκατάστασης του PhET...",
            "timeseries.control.panel.playback": "Αναπαραγωγή",
            "Common.updates.progressDialogTitle": "Ενημέρωση",
            "Common.HelpMenu.Title": "Βοήθεια",
            "Common.TeacherMenu.mnemonic": "Δ",
            "ColorChooser.rgbNameText": "RGB",
            "FileChooser.fileNameLabelText": "Όνομα αρχέιου:",
            "Common.softwareAgreement.title": "Άδεια χρήσης λογισμικού",
            "Common.statistics.host_java_version_minor": "Έκδοση Java (μικρότερη)",
            "Common.HelpMenu.TitleMnemonic": "Β",
            "Common.About.CreditsDialog.interviews": "Συνεντεύξεις",
            "Common.About.Distribution": "Διανομή:",
            "Common.statistics.host_java_webstart_version": "Έκδοση Java εκκίνησης από το Web",
            "XMLPersistenceManager.save.error.message": "<html>Σφάλμα εγγραφής στο αρχείο:<br>{0}</html>",
            "Games.label.time": "Χρόνος: {0}",
            "FileChooser.openButtonText": "Άνοιγμα",
            "ColorChooser.sampleText": "Δείγμα κειμένου Δείγμα κειμένου",
            "Common.statistics.details.description": "<html>Οι πληροφορίες που εμφανίζονται παρακάτω θα αποστέλλονται στο PhEt κάθε φορά που ξεκινά η προσομοίωση.</html>",
            "Common.statistics.host_os_version": "Έκδοση λειτουργικού συστήματος",
            "Common.title.confirm": "Επιβεβαίωση",
            "Common.BasicPhetPanel.LogoToolTip": "Απενεργοποίηση πλήρους πλαισίου",
            "Games.label.score.max": "Βαθμολογία: {0} από {1}",
            "Common.statistics.host_java_timezone": "Ζώνη ώρας",
            "Common.time.slow": "αργά",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.ClockControlPanel.Rewind": "Πίσω",
            "Common.softwareAgreement.accept": "Αποδοχή και συνέχεια",
            "message.valueOutOfRange": "Η τιμή πρέπει να είναι μεταξύ {0} και {1}.",
            "Common.updates.updateToDate": "Ενημερωμένο",
            "Common.ClockControlPanel.Pause": "Παύση",
            "PhetApplication.StartupDialog.message": "Εκκίνηση του \"{0}\" ",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Αυτό το πρόγραμμα χρησιμοποιεί λογισμικό από τρίτους",
            "XMLPersistenceManager.message.notAConfigFile": "Αυτό το αρχείο δεν περιέχει ρύθμιση γι' αυτή την προσομοίωση.",
            "Common.preferences.updates": "Ενημερώσεις",
            "Games.label.score.max.perfect": "Βαθμολογία: {0} από {1} (ΕΞΑΙΡΕΤΙΚΗ!)",
            "Common.HelpMenu.MegaHelpMnemonic": "M",
            "Common.statistics.enabled": "Επιτρέπεται να αποστέλλονται οι πληροφορίες στο PhET.",
            "Common.ClockControlPanel.StepBack": "Βήμα πίσω",
            "Common.StopwatchPanel.stop": "Διακοπή",
            "Common.HelpPanel.MegaHelp": "Μεγα-βοήθεια...",
            "Common.statistics.host_locale_country": "Χώρα υπολογιστή",
            "Common.StopwatchPanel.reset": "Επαναφορά",
            "Common.playback": "Αναπαραγωγή",
            "Common.statistics.sim_minor_version": "Έκδοση προσομοίωσης (μικρότερη)",
            "Games.message.confirmNewGame": "<html>Δεν έχετε τελειώσει αυτό το παιχνίδι.<br>Είστε σίγουρος ότι θέλετε να ξεκινήσετε ένα νέο παιχνίδι;</html>",
            "Common.updates.tryIt": "Δοκιμάστε τη νέα έκδοση πριν την ενημέρωση.",
            "ColorChooser.rgbBlueText": "Μπλε",
            "Common.choice.close": "Κλείσιμο",
            "Common.ClockControlPanel.Play": "Αναπαραγωγή",
            "Common.statistics.sim_type": "Είδος προσομοίωσης",
            "FileChooser.saveButtonText": "Αποθήκευση",
            "Common.rewind": "Πίσω",
            "Common.StopwatchPanel.start": "Έναρξη",
            "Common.updates.youHaveCurrent": "Έχετε την πιο πρόσφατη έκδοση ({0}) από {1}.",
            "Common.statistics.sim_sessions_since": "Αριθμός εκτελέσεων της προσομοίωσης από την τελευταία φορά που ήσασταν online.",
            "Common.statistics.host_java_vendor": "Προμηθευτής Java",
            "charts.show-graphs": "Εμφάνιση γραφημάτων:",
            "Common.statistics.message_type": "Είδος μηνύματος"
        } );