//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_it.properties
define( {
            "Games.label.level": "Livello: {0}",
            "Common.updates.errorMessage": "C'è  stato un errore durante l'aggiornamento. <br> Ti prego di provare più tardi o visitare {0}",
            "XMLPersistenceManager.save.error.encode": "<html>Errore di codifica per il file:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Errore di codifica del file:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "f",
            "Common.softwareAgreement.decline": "Esci",
            "Common.statistics.host_os_name": "Nome del Sistema Operativo:",
            "Common.statistics.user_total_sessions": "Numero totale di tutte le simulazioni eseguite",
            "Common.statistics.host_java_version_major": "Versione Java (maggiore):",
            "FileChooser.openDialogTitleText": "Apri",
            "Common.WhiteBackground": "Sfondo bianco",
            "Common.statistics.host_java_version_maintenance": "Versione Java (mantenimento):",
            "FileChooser.lookInLabelText": "Guarda in:",
            "Common.choice.cancel": "Elimina",
            "Common.updates.seePreferences": "Vai a  \"File->Preferenze\" per cambiare le tue scelte",
            "Common.About.CreditsDialog.software-development": "Sviluppatori del software",
            "Common.About.JavaVersion": "Versione Java:",
            "ColorChooser.resetText": "Azzera",
            "translation.credits": "<html>Vito Garganese<br>vito.garganese@alice.it<br></html>",
            "Common.WhiteBackground.mnemonic": "b",
            "Common.About.CreditsDialog.design-team": "team progettisti",
            "Common.statistics.sim_total_sessions": "Numero totale delle esecuzioni della simulazione",
            "Games.title.gameSettings": "Impostazioni del gioco",
            "XMLPersistenceManager.save.title": "Salva la configurazione",
            "XMLPersistenceManager.load.error.contents": "Il file è corrotto o non è stato creato da questa simulazione.",
            "Common.statistics.details.title": "Informazioni",
            "Common.statistics.sim_dev_version": "Versione della simulazione (dev):",
            "FileChooser.saveInLabelText": "Salva in:",
            "Common.statistics.sim_name": "Nome della simulazione:",
            "Save.confirm.message": "<html>Il file selezionato esiste già.<br>Vuoi sostituirlo con il nuovo file?</html>",
            "Games.label.score": "Punteggio: {0} ",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "Team di sviluppo PhET",
            "Games.button.start": "Via",
            "Common.statistics.sim_deployment": "Tipo di distribuzione:",
            "Common.FileMenu.Save": "Salva configurazione...",
            "Common.About.CreditsDialog.licenseDetails": "Dettagli della licenza",
            "Games.radioButton.on": "I",
            "FileChooser.acceptAllFileFilterText": "Tutti i file (*.*)",
            "Common.ModelSlider.Minimum": "Minimo",
            "Common.FileMenu.Preferences": "Preferenze",
            "Common.FileMenu.Load": "Carica configurazione...",
            "Common.updates.downloadingSimJar": "Sto scaricando il file JAR della simulazione",
            "Games.radioButton.off": "O",
            "Jme.copyThisToTheClipboard": "Copia negli appunti",
            "ColorChooser.swatchesRecentText": "Recente:",
            "Common.updates.updateAvailable": "Aggiornamento disponibile",
            "Common.statistics.host_locale_language": "Lingua locale:",
            "Common.clear": "Annulla",
            "Games.title.gameOver": "Gioco terminato",
            "FileChooser.filesOfTypeLabelText": "Tipo dei file:",
            "Common.ErrorDialog.detailsTitle": "Dettagli dell'errore",
            "Common.HelpMenu.MegaHelp": "Grande aiuto...",
            "Common.ClockControlPanel.Step": "Avanti di un passo",
            "Common.statistics.sim_revision": "Versione della simulazione (revisione):",
            "Common.choice.yes": "Sì",
            "Common.FileMenu.Title": "File",
            "Common.statistics.sim_dev": "Questa è una versione di sviluppo?",
            "Common.updates.installer.message": "<html>La tua verione di PhET residente è in data {0}.<br>E' disponibile la nuova versione del {1}.<br><br>Vuoi installare la versione aggiornata?</html>",
            "Common.updates.updateNow": "Aggiorna adesso!",
            "Common.record": "Registra",
            "Common.About.CreditsDialog.Title": "Autori",
            "Common.updates.error.internetConnection": "<html>Non riesco a connettermi a  {0},<br>ti prego di controllare la tua connessione Internet.</html>",
            "Common.time.fast": "accelera",
            "XMLPersistenceManager.load.error.message": "<html>Errore di lettura del file:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Massimo",
            "Common.OptionsMenu": "Opzioni",
            "Common.ClockControlPanel.Restart": "Riavvia",
            "Common.statistics.sim_version_timestamp": "Versione della simulazione (timestamp)",
            "Common.updates.installer.yes": "Si!",
            "Common.phetInstaller": "Installazione residente di PhET",
            "Jme.thisSimulationWasUnableToStart": "Questa simulazione non parte",
            "Common.HelpMenu.About": "Informazioni...",
            "Common.ModelSlider.OutOfRange": "Valore fuori dai limiti",
            "Common.About.CreditsDialog.TranslationCreditsTitle": "tradotto da",
            "ColorChooser.previewText": "Anteprima",
            "Common.BasicPhetPanel.Title": "Invia",
            "Common.HelpPanel.HideHelp": "Nascondi aiuto",
            "Common.statistics.host_os_arch": "Tipo di processore:",
            "Common.preferences.title": "Preferenze",
            "Games.button.newGame": "Nuovo gioco",
            "Common.ModelSlider.YouEntered": "Hai inserito",
            "Games.label.newBest": "Sei il migliore!",
            "Common.About.BuildDate": "data della versione:",
            "Common.FileMenu.ExitMnemonic": "x",
            "Common.statistics.sim_project": "Nome del Progetto:",
            "Games.label.best": "Il tuo miglior punteggio: {0}",
            "Common.title.message": "Messaggio",
            "Common.updates.downloadingBootstrap": "Sto scaricando l'aggiornamento dell'avvio",
            "Common.title.error": "Errore",
            "Common.FileMenu.Exit": "Esci",
            "Common.statistics.sim_major_version": "Versione della simulazione (maggiore):",
            "Common.updates.askMeLater": "chiedimi dopo",
            "chart-time-control.go": "Vai!",
            "Common.HelpMenu.HelpMnemonic": "h",
            "Common.confirm.clear.graphs": "Sei sicuro di voler pulire il grafico?",
            "ColorChooser.swatchesNameText": "Campioni",
            "Common.updates.progressDialogMessage": "Aggiornamento \"{0}\" alla versione  {1}",
            "Common.updates.installer.more": "Dimmi di più..",
            "XMLPersistenceManager.title.error": "Errore",
            "ControlPanel.button.resetAll": "Ripristina tutto",
            "Common.About.AgreementButton": "Condizioni d'uso del software...",
            "Common.FileMenu.Load.mnemonic": "C",
            "Common.ErrorDialog.detailsButton": "Dettagli..",
            "Common.updates.errorMissingJar": "<html> Non posso eseguire l'aggiornamento. <br> Non posso allocare il file JAR: {0}. <br>Per favore, contatta il tuo Amministratore di sistema. <br> </html>",
            "Common.preferences.privacy": "Riservatezza",
            "Common.HelpMenu.AboutTitle": "Informazioni",
            "ColorChooser.rgbRedText": "Rosso",
            "Common.statistics.sim_locale_country": "Paese:",
            "ColorChooser.hsbGreenText": "V",
            "ColorChooser.rgbGreenText": "Verde",
            "Common.HelpPanel.ShowHelp": "Aiuto!",
            "PiccoloPhet.VelocitySensorNode.speed": "Velocità",
            "Common.statistics.sim_distribution_tag": "Versione della simulazione (distribuzione)",
            "Common.statistics.description": "PhET è reso liberamente disponibile da sovvenzionatori<br> che ci chiedono di raccogliere una piccola quantità di <a href=\"{0}\">informazioni</a> anonime<br> per consentire la documentazione della quantità d'uso delle simulazioni PhET <br>e per migliorare il servizio verso gli utenti finali",
            "Common.softwareAgreement.message": "In tutte le simulazioni Phet, raccogliamo una minima quantità di <a href=\"{0}\">informazioni</a> anonime  <br>ogni volta che la simulazione ha inizio  <br> (ad esempio, la versione della simulazione, il sistema operativo). <br > È possibile disabilitare l'invio delle informazioni in qualsiasi momento  <br>tramite il menu  File->Preferenze. <br> Facendo clic su \"Accetta e continua\", l'utente accetta le condizioni di contratto del software di PhET <br> compresa la nostra politica sulla privacy, per questa e per ogni simulazione che si esegue. <br> (Per maggiori dettagli, fare clic <a href=\"{1}\"> qui </a>).\n",
            "Common.choice.ok": "OK",
            "Common.About.Version": "Versione:",
            "Common.ErrorDialog.contactPhet": "Se il problema persiste  invia i dettagli a {0}",
            "Common.About.CreditsDialog.lead-design": "Capo progettista",
            "Common.OptionsMenu.mnemonic": "O",
            "Jme.moreInformation": "<html><body>Aggiornare la tua scheda video può risolvere il problema.<br/>Per ulteriori informazioni visita  {0},<br/>o copia e incolla il testo inviandolo all' indirizzo mail  {1}.<br/></body></html>",
            "Common.statistics.user_preference_file_creation_time": "Creazione del file di preferenze timestamp:",
            "Sponsor.sponsoredBy": "Sponsorizzato da",
            "Common.HelpMenu.AboutMnemonic": "a",
            "Common.updates.errorWritePermissions": "<html>Questo aggiornamento non può essese eseguito.<br>Non hai il permesso di memorizzazione per  {0}.<br>Per favore, contatta il tuo  Amministratore di sistema. <br> </html>",
            "Common.choice.no": "No",
            "Common.About.WebLink": "Visita la Homepage di PhET ",
            "Common.About.OSVersion": "Versione del sistema operativo",
            "Common.title.warning": "Attenzione",
            "Common.updates.versionComparison": "<html>La tua versione corrente di \"{0}\" è {1}.<br>E' disponibile ({2}) una nuova versione.</html>",
            "Common.statistics.sim_locale_language": "Lingua:",
            "Common.statistics.user_installation_timestamp": "Installazione timestamp di PhET",
            "Common.statistics.message_version": "Versione del messsaggio:",
            "Common.ModelSlider.Description": "Valore non ammesso.",
            "Common.updates.installer.moreMessage": "<html>Mantenendo la tua versione di PhET aggiornata<br>ti assicuri l'accesso alle simulazioni più recenti<br>ed a materiali aggiuntivi.<br><br>Se scegli di ottenere la versione aggiornata, il tuo browser <br>aprirà il sito PhET dove poter scaricare<br>l'istallatore dell'ultima versione residente di PhET.</html>",
            "ControlPanel.message.confirmResetAll": "Vuoi ripristinare tutte le scelte?",
            "Common.HelpMenu.Help": "Aiuto",
            "Common.updates.errorNotAJar": "{0} non è un file JAR.",
            "Games.label.levelControl": "Livello:",
            "Common.updates.automaticallyCheck": "Controllo automatico per l'aggiornamento",
            "Common.sim.speed": "..velocità della simulazione..",
            "Common.updates.checkForSimUpdate": "Controllo dell'aggiornamento della simulazione",
            "XMLPersistenceManager.save.confirm.message": "<html>Il file selezionato esiste già.<br>Vuoi sostituirlo con il nuovo file?</html>",
            "FileChooser.newFolderErrorText": "Errore nella creazione della nuova cartella",
            "Common.About.CreditsButton": "Autori...",
            "Common.updates.skipThisUpdate": "Salta questa versione",
            "Common.FileMenu.Save.mnemonic": "S",
            "Common.TeacherMenu": "Insegnante",
            "FileChooser.saveDialogTitleText": "Salva",
            "XMLPersistenceManager.load.title": "Carica configurazione",
            "Common.updates.checkForInstallerUpdate": "Controllo dell'aggiorrnamento dell'installazione residente di PhET ",
            "timeseries.control.panel.playback": "Riproduci",
            "Common.updates.progressDialogTitle": "Aggiornamento",
            "Common.HelpMenu.Title": "Aiuto",
            "Common.TeacherMenu.mnemonic": "I",
            "FileChooser.fileNameLabelText": "Nome del file:",
            "Common.softwareAgreement.title": "Condizioni d'uso del software",
            "Common.statistics.host_java_version_minor": "Versione Java (minore):",
            "Common.HelpMenu.TitleMnemonic": "h",
            "Common.About.CreditsDialog.interviews": "interviste",
            "Common.About.Distribution": "Distribuzione",
            "Common.statistics.host_java_webstart_version": "Versione Java per  avvio Web:",
            "XMLPersistenceManager.save.error.message": "<html>Errore di scrittura nel file:<br>{0}</html>",
            "Games.label.time": "tempo: {0}",
            "FileChooser.openButtonText": "Apri",
            "ColorChooser.sampleText": "Testo campione Testo Campione",
            "Common.statistics.details.description": "<html> Le informazioni riportate sotto sono inviate a PhET ogni volta che la simulazione parte. </html>",
            "Common.statistics.host_os_version": "Versione del Sistema Operativo:",
            "Common.title.confirm": "Conferma",
            "Common.BasicPhetPanel.LogoToolTip": "Disabilita tutto schermo",
            "Games.label.score.max": "Punteggio: {0} su {1}",
            "Common.statistics.host_java_timezone": "fuso orario:",
            "Common.time.slow": "rallenta",
            "Common.ClockControlPanel.Rewind": "Indietro",
            "Common.softwareAgreement.accept": "Accetta e continua",
            "message.valueOutOfRange": "Il valore deve essere compreso tra {0} e {1}",
            "Common.updates.updateToDate": "Fino ad oggi",
            "Common.ClockControlPanel.Pause": "Pausa",
            "PhetApplication.StartupDialog.message": "\"{0}\" sta partendo",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Questo programma utilizza i seguenti software di terze parti",
            "XMLPersistenceManager.message.notAConfigFile": "Questo file non contiene una configurazione per questa simulazione.",
            "Common.preferences.updates": "Aggiorna",
            "Games.label.score.max.perfect": "Punteggio: {0} su {1} (esatto!)",
            "Common.HelpMenu.MegaHelpMnemonic": "m",
            "Common.statistics.enabled": "Permetti di inviare informazioni a PhET",
            "Common.ClockControlPanel.StepBack": "Indietro di un passo",
            "Common.StopwatchPanel.stop": "Stop",
            "Common.HelpPanel.MegaHelp": "Grande aiuto...",
            "Common.statistics.host_locale_country": "Paese ospite:",
            "Common.StopwatchPanel.reset": "Ripristina",
            "Common.playback": "Riproduci",
            "Common.statistics.sim_minor_version": "Versione della simulazione (minore)",
            "Games.message.confirmNewGame": "<html>Non hai finito il gioco.<br>Sei sicuro di voler ricominciare?</html>",
            "Common.updates.tryIt": "Cerca la nuova versione prima di fare l'aggiornamento.",
            "ColorChooser.rgbBlueText": "Blu",
            "Common.choice.close": "Chiudi",
            "Common.ClockControlPanel.Play": "Play",
            "Common.statistics.sim_type": "Tipo di simulazione:",
            "FileChooser.saveButtonText": "Salva",
            "Common.rewind": "Indietro",
            "Common.StopwatchPanel.start": "Via",
            "Common.updates.youHaveCurrent": "Hai la versione più recente ({0}) of {1}.",
            "Common.statistics.sim_sessions_since": "Numero delle volte che la simulazione è stata eseguita dall'ultima connessione",
            "Common.statistics.host_java_vendor": "Concessionario Java:",
            "charts.show-graphs": "Mostra i grafici:",
            "Common.statistics.message_type": "Tipo di messaggio:",
            "Sponsor.sinceDate": "(dal {0})"
        } );