// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.sugarandsaltsolutions;

import java.awt.image.BufferedImage;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Translated strings for "SugarAndSaltSolutions" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator$8
 * See #2967
 */
public class SugarAndSaltSolutionsResources {
    public static final String NAME = "sugar-and-salt-solutions";
    public static final PhetResources RESOURCES = new PhetResources( NAME );

    //Strings
    public static final String SALT = RESOURCES.getLocalizedString( "salt" );

    //Images
    public static final BufferedImage FAUCET = RESOURCES.getImage( "faucet.png" );
    public static final BufferedImage SALT_1 = RESOURCES.getImage( "salt_1.png" );
    public static final BufferedImage SALT_EMPTY = RESOURCES.getImage( "salt_empty.png" );
    public static final BufferedImage SUCROSE = RESOURCES.getImage( "sucrose.png" );
    public static final BufferedImage SUGAR_CLOSED = RESOURCES.getImage( "sugar_closed.png" );
    public static final BufferedImage SUGAR_EMPTY_CLOSED = RESOURCES.getImage( "sugar_empty_closed.png" );
    public static final BufferedImage SUGAR_EMPTY_OPEN = RESOURCES.getImage( "sugar_empty_open.png" );
    public static final BufferedImage SUGAR_OPEN = RESOURCES.getImage( "sugar_open.png" );
}