//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_nl.properties
define( {
            "Games.label.level": "Niveau: {0}",
            "Common.updates.errorMessage": "Een fout tijdens updaten.<br>Probeer later nog eens, of bezoek {0}.",
            "XMLPersistenceManager.save.error.encode": "<html>Bestand coderingsfout:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Bestand decodeerfout:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "B",
            "Common.softwareAgreement.decline": "Annuleer",
            "Common.statistics.host_os_name": "Besturingssysteem naam",
            "Common.statistics.user_total_sessions": "Totaal aantal keren dat alle simulaties gedraait zijn",
            "Common.statistics.host_java_version_major": "Java versie (hoofdversie)",
            "FileChooser.openDialogTitleText": "Open",
            "Common.WhiteBackground": "Witte achtergrond",
            "Common.statistics.host_java_version_maintenance": "Java versie (onderhoud)",
            "FileChooser.lookInLabelText": "Kijk In:",
            "Common.choice.cancel": "Annuleer",
            "Common.updates.seePreferences": "Ga naar Bestand->Voorkeuren om uw voorkeuren te weizigen.",
            "Common.About.CreditsDialog.software-development": "Software-ontwikkeling",
            "Common.About.JavaVersion": "Java Versie:",
            "ColorChooser.resetText": "Herstel",
            "wavelength.ir": "IR",
            "Common.WhiteBackground.mnemonic": "w",
            "Common.About.CreditsDialog.design-team": "Ontwerpteam",
            "Common.statistics.sim_total_sessions": "Totaal aantal keren dat deze simulatie gedraait is",
            "Common.FileMenu.PreferencesMnemonic": "V",
            "wavelength.uv": "UV",
            "Games.title.gameSettings": "Spelinstellingen",
            "XMLPersistenceManager.save.title": "Configuratie opslaan",
            "XMLPersistenceManager.load.error.contents": "Het bestand is beschadigd, of is niet gemaakt door deze simulatie.",
            "Common.statistics.details.title": "Informatie",
            "Common.statistics.sim_dev_version": "Simulatie versie (ontw.)",
            "FileChooser.saveInLabelText": "Opslaan In:",
            "Common.statistics.sim_name": "Simulatie naam",
            "Save.confirm.message": "<html>Dit bestand bestaat al.<br>Wilt u het vervangen door het bestand dat u nu opslaat?</html>",
            "Games.label.score": "Score: {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "PhET Ontwikkelingsteam",
            "Games.button.start": "Start!",
            "Common.statistics.sim_deployment": "Methode van distributie",
            "Common.FileMenu.Save": "Configuratie opslaan...",
            "Common.About.CreditsDialog.licenseDetails": "Licentie Details",
            "ColorChooser.hsbSaturationText": "V",
            "Games.radioButton.on": "aan",
            "FileChooser.acceptAllFileFilterText": "Alle bestanden (*.*)",
            "ColorChooser.hsbNameText": "Kleurruimte",
            "Common.ModelSlider.Minimum": "Minimum",
            "Common.FileMenu.Preferences": "Voorkeuren...",
            "Common.FileMenu.Load": "Laad configuratie",
            "Common.updates.downloadingSimJar": "Bezig met downloaden simulatie JAR-bestand...",
            "Games.radioButton.off": "uit",
            "Jme.copyThisToTheClipboard": "Kopieer dit naar het klembord",
            "ColorChooser.swatchesRecentText": "Recent:",
            "Common.updates.updateAvailable": "Update Beschikbaar",
            "Common.statistics.host_locale_language": "Host taal",
            "Common.clear": "Schoonmaken",
            "Games.title.gameOver": "Einde spel",
            "FileChooser.filesOfTypeLabelText": "Bestanden van Type:",
            "Common.ErrorDialog.detailsTitle": "Fout details",
            "Common.HelpMenu.MegaHelp": "Uitgebreide documentatie",
            "Common.ClockControlPanel.Step": "Stap",
            "Common.statistics.sim_revision": "Simulatie versie (herziening)",
            "Common.choice.yes": "Ja",
            "PiccoloPhet.VelocitySensorNode.unknown": "?",
            "Common.FileMenu.Title": "Bestand",
            "Common.value_units": "{0} {1}",
            "Common.statistics.sim_dev": "Is dit een ontwikkelaarsversie?",
            "Common.updates.installer.message": "<html>Uw PhET Offline Website Installatie is verouderd {0}.<br>Een nieuwere versie d.d. {1} is beschikbaar.<br><br>Wilt u het recentste PhET Offline Website Installatieprogramma?</html>",
            "Common.updates.updateNow": "Nu Updaten!",
            "Common.record": "Opnemen",
            "Common.About.CreditsDialog.Title": "Met dank aan",
            "Common.updates.error.internetConnection": "<html>Kan geen verbinding maken met {0},<br>controleer uw internetverbinding.</html>",
            "Common.time.fast": "snel",
            "XMLPersistenceManager.load.error.message": "<html>Bestand leesfout:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Maximum",
            "Common.OptionsMenu": "Opties",
            "Common.ClockControlPanel.Restart": "Herstart",
            "Common.statistics.sim_version_timestamp": "Simulaite versie (datum/tijd)",
            "Common.updates.installer.yes": "Ja!",
            "Common.phetInstaller": "PhET Offline website installatieprogramma",
            "Jme.thisSimulationWasUnableToStart": "Deze simulatie kon niet gestart worden",
            "Common.HelpMenu.About": "Over...",
            "Common.ModelSlider.OutOfRange": "Waarde buiten bereik",
            "Common.About.CreditsDialog.TranslationCreditsTitle": "Vertaald door",
            "ColorChooser.previewText": "Voorbeeld",
            "Common.BasicPhetPanel.Title": "Terug",
            "Common.HelpPanel.HideHelp": "Verberg Help",
            "Common.statistics.host_os_arch": "Processor  type",
            "Common.preferences.title": "Voorkeuren",
            "Games.button.newGame": "Opnieuw",
            "ColorChooser.hsbRedText": "R",
            "ColorChooser.hsbBlueText": "B",
            "Common.ModelSlider.YouEntered": "U voerde in",
            "Games.label.newBest": "JE BENT DE BESTE!",
            "Common.About.BuildDate": "Bouwdatum:",
            "Common.FileMenu.ExitMnemonic": "A",
            "Common.statistics.sim_project": "Projectnaam",
            "Games.label.best": "Beste: {0}",
            "Common.title.message": "Bericht",
            "Common.updates.downloadingBootstrap": "Bezig met downloaden opstartprogramma updater",
            "Common.title.error": "Fout",
            "Common.FileMenu.Exit": "Afsluiten",
            "Common.statistics.sim_major_version": "Simulatie versie (hoofdversie)",
            "Common.updates.askMeLater": "Vraag mij later",
            "chart-time-control.go": "Start!",
            "Common.HelpMenu.HelpMnemonic": "H",
            "Common.confirm.clear.graphs": "Weet u zeker dat u de grafieken wilt schoonmaken?",
            "ColorChooser.swatchesNameText": "Kleurstalen",
            "Common.updates.progressDialogMessage": "Bezig met updaten \"{0}\" naar versie {1}",
            "Common.updates.installer.more": "Vertel me meer...",
            "XMLPersistenceManager.title.error": "Fout",
            "ColorChooser.hsbHueText": "T",
            "ControlPanel.button.resetAll": "Alles Resetten",
            "Common.About.AgreementButton": "Software Overeenkomst...",
            "Common.FileMenu.Load.mnemonic": "L",
            "Common.ErrorDialog.detailsButton": "Details...",
            "Common.updates.errorMissingJar": "<html>Deze update kan niet worden uitgevoerd.<br>Kan JAR-bestand: {0} niet vinden.<br> Neem contact op met uw systeembeheerder.<br></html>",
            "Common.preferences.privacy": "Privacy",
            "Common.HelpMenu.AboutTitle": "Over",
            "ColorChooser.rgbRedText": "Rood",
            "Common.statistics.sim_locale_country": "Land",
            "ColorChooser.hsbGreenText": "G",
            "ColorChooser.rgbGreenText": "Groen",
            "Games.format.time.best": "{0} ({1})",
            "Common.HelpPanel.ShowHelp": "Help!",
            "PiccoloPhet.VelocitySensorNode.speed": "Snelheid",
            "Common.statistics.sim_distribution_tag": "Simulatie versie (distributie)",
            "Common.statistics.description": "PhET is vrij beschikbaar dankzij giften die<br>ons verplichten een minimale hoeveelheid<br>anonieme <a href=\"{0}\">informatie</a> te verzamelen om de<br>gebruiksfrequentie van de PhET simulaties<br>vast te stellen, en om onze gebruikers<br>beter te bedienen.",
            "Common.softwareAgreement.message": "In alle PhET simulaties verzamelen we een geringe<br>hoeveelheid van anonieme <a href=\"{0}\"> informatie</a> elke keer als de<br>simulatie start (bijv. simulatieversie, besturingssysteem).<br>U kunt het verzenden van deze informatie te allen tijde<br>uitschakelen via het Bestand->Voorkeuren menu-item.<br><br>Door te klikken op \"Akkoord en Doorgaan\", gaat u akkoord<br>met PhET´s Software-Overeenkomst, inclusief ons<br>privacybeleid, voor deze en iedere andere PhET simulatie<br>die u gebruikt. (voor meer details, klik <a href=\"{1}\">hier</a>).",
            "Common.choice.ok": "OK",
            "Common.About.Version": "Versie:",
            "Common.ErrorDialog.contactPhet": "Als dit probleem zich blijft voordoen, zend dan onderstaande details naar {0}",
            "Common.About.CreditsDialog.lead-design": "Hoofdontwerp",
            "Common.OptionsMenu.mnemonic": "O",
            "Jme.moreInformation": "<html><body>Upgraden van uw videokaart-drivers <br/> zou het probleem kunnen oplossen.<br/>Voor nadere informatie, bezoek {0},<br/> of kopieer-plak het volgende in een e-mail naar {1}.<br/></body></html>",
            "Common.statistics.user_preference_file_creation_time": "Voorkeurenbestand gemaakt op:",
            "Sponsor.sponsoredBy": "Gesponsord door",
            "Common.HelpMenu.AboutMnemonic": "r",
            "Common.updates.errorWritePermissions": "<html>Deze update kan niet uitgevoerd worden.<br>U heeft geen schrijfrechten op {0}.<br> Neem contact op met uw systeembeheerder.<br></html>",
            "ColorChooser.hsbBrightnessText": "H",
            "Common.choice.no": "Nee",
            "Common.About.WebLink": "Bezoek de PhET Homepagina",
            "Common.About.OSVersion": "Besturingssysteem Versie:",
            "Common.title.warning": "Waarschuwing",
            "Common.updates.versionComparison": "<html>Uw huidige versie van \"{0}\" is {1}.<br>Nieuwere versie({2}) is beschikbaar.</html>",
            "Common.statistics.sim_locale_language": "Taal",
            "Common.statistics.user_installation_timestamp": "Tijdsmoment van PhET installatie",
            "Common.wavelengthControl.nm": "nm",
            "Common.statistics.message_version": "Bericht versie",
            "Common.ModelSlider.Description": "Ongeldige waarde",
            "Common.updates.installer.moreMessage": "<html>Door uw PhET Offline Installatie bij de tijd te houden<br>verzekert u zich van toegang tot de nieuwste PhET simulaties<br>en aanvullend materiaal.<br><br>Als u voor de recentste versie kiest, zal uw browser<br>de PhET website openen, waar u het<br>PhET website installatieprogramma kunt downloaden.</html>",
            "Common.HelpMenu.Help": "Help",
            "Common.updates.errorNotAJar": "{0} is geen JAR-bestand.",
            "ControlPanel.message.confirmResetAll": "Alle instellingen resetten?",
            "Games.label.levelControl": "Niveau:",
            "Common.updates.automaticallyCheck": "Automatisch updates zoeken",
            "Common.sim.speed": "...simulatie snelheid...",
            "Common.updates.checkForSimUpdate": "Zoek naar update voor simulatie...",
            "XMLPersistenceManager.save.confirm.message": "<html>Dit bestand bestaat al.<br>Wilt u het vervangen door het bestand dat u nu opslaat?</html>",
            "Common.wavelengthControl.IR": "IR",
            "FileChooser.newFolderErrorText": "Fout bij aanmaken nieuwe map",
            "Common.About.CreditsButton": "Met dank aan...",
            "Common.updates.skipThisUpdate": "Sla deze versie over",
            "Common.FileMenu.Save.mnemonic": "O",
            "Common.TeacherMenu": "Docent",
            "FileChooser.saveDialogTitleText": "Opslaan",
            "XMLPersistenceManager.load.title": "Laad configuratie",
            "Common.wavelengthControl.UV": "UV",
            "Common.updates.checkForInstallerUpdate": "Zoek naar update voor PhET offline website installatieprogramma",
            "timeseries.control.panel.playback": "Replay",
            "Sponsor.sponsorMenuItem": "Sponsor...",
            "Common.updates.progressDialogTitle": "Bezig met updaten",
            "Common.HelpMenu.Title": "Help",
            "Common.TeacherMenu.mnemonic": "T",
            "ColorChooser.rgbNameText": "RGB",
            "FileChooser.fileNameLabelText": "Bestandsnaam:",
            "Common.softwareAgreement.title": "Software Overeenkomst",
            "Common.statistics.host_java_version_minor": "Java versie (onderversie)",
            "Common.HelpMenu.TitleMnemonic": "H",
            "Common.About.CreditsDialog.interviews": "Interviews",
            "Common.About.Distribution": "Distributie:",
            "Common.statistics.host_java_webstart_version": "Java Web Start versie",
            "XMLPersistenceManager.save.error.message": "<html>Bestand schrijffout:<br>{0}</html>",
            "Games.label.time": "Tijd: {0}",
            "FileChooser.openButtonText": "Open",
            "ColorChooser.sampleText": "Voorbeeld Tekst Voorbeeld Tekst",
            "Common.statistics.details.description": "<html>De hieronder getoonde informatie wordt naar PhET gezonden bij elke start van de simulatie.</html>",
            "Common.statistics.host_os_version": "Besturingssysteem versie",
            "Common.title.confirm": "Bevestig",
            "Common.BasicPhetPanel.LogoToolTip": "Volledig Scherm UItschakelen",
            "Games.label.score.max": "Score: {0} van {1}",
            "Common.statistics.host_java_timezone": "Tijdzone",
            "Common.time.slow": "langzaam",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.ClockControlPanel.Rewind": "Terugspoelen",
            "Common.softwareAgreement.accept": "Akkord en Doorgaan",
            "message.valueOutOfRange": "Waarde moet liggen tussen {0} en {1}",
            "Common.updates.updateToDate": "Update Bijgewerkt",
            "Common.ClockControlPanel.Pause": "Pauze",
            "PhetApplication.StartupDialog.message": "\"{0}\" is bezig met starten",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Dit programma gebruikt de volgende  software van derden",
            "XMLPersistenceManager.message.notAConfigFile": "Dit bestand bevat geen configuratie voor deze simulatie.",
            "Common.preferences.updates": "Updates",
            "Games.label.score.max.perfect": "Score: {0} van {1} (PERFECT!)",
            "Common.HelpMenu.MegaHelpMnemonic": "M",
            "Common.statistics.enabled": "Toestaan verzinding van informatie naar PhET",
            "Common.ClockControlPanel.StepBack": "Stap terug",
            "Common.StopwatchPanel.stop": "Stop",
            "Common.HelpPanel.MegaHelp": "Uitgebreide documentatie",
            "Common.statistics.host_locale_country": "Host land",
            "Common.StopwatchPanel.reset": "Herstel",
            "Common.playback": "Opnieuw bekijken",
            "Common.statistics.sim_minor_version": "Simulaite versie (onderversie)",
            "Games.message.confirmNewGame": "<html>Je hebt deze ronde nog niet afgemaakt.<br>Toch een nieuwe ronde starten?</html>",
            "Common.updates.tryIt": "Probeer de nieuwe versie voordat u update",
            "ColorChooser.rgbBlueText": "Blauw",
            "Common.choice.close": "Sluiten",
            "Common.ClockControlPanel.Play": "Start",
            "Common.statistics.sim_type": "Simulatie type",
            "FileChooser.saveButtonText": "Opslaan",
            "Common.rewind": "Terugspoelen",
            "Common.StopwatchPanel.start": "Start",
            "Common.updates.youHaveCurrent": "U heeft de meest recente versie ({0}) van {1}.",
            "Common.statistics.sim_sessions_since": "Aantal keren dat deze simulatie gedraait is sinds laatste bezoek",
            "Common.statistics.host_java_vendor": "Java verkoper",
            "charts.show-graphs": "Laat grafieken zien:",
            "Common.statistics.message_type": "Bericht type",
            "Sponsor.sinceDate": "(sinds {0})"
        } );