/* Copyright 2005, University of Colorado */

/*
 * CVS Info -
 * Filename : $Source$
 * Branch : $Name$
 * Modified by : $Author$
 * Revision : $Revision$
 * Date modified : $Date$
 */

package edu.colorado.phet.shaper.control;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import edu.colorado.phet.shaper.module.BaseModule;


/**
 * ShaperControlPanel
 *
 * @author Chris Malley (cmalley@pixelzoom.com)
 * @version $Revision$
 */
public class ShaperControlPanel extends BaseControlPanel {

    //----------------------------------------------------------------------------
    // Class data
    //----------------------------------------------------------------------------
    
    //----------------------------------------------------------------------------
    // Instance data
    //----------------------------------------------------------------------------
    
    // Things to be controlled
    
    // UI components
    
    //----------------------------------------------------------------------------
    // Constructors
    //----------------------------------------------------------------------------
    
    /**
     * Sole constructor.
     * 
     * @param module
     */
    public ShaperControlPanel( BaseModule module ) {
        super( module );
        
        // Add the Reset button after adding other controls
        addResetButton();
    }
    
    public void cleanup() {
    }
    
    //----------------------------------------------------------------------------
    // BaseControlPanel implementation
    //----------------------------------------------------------------------------

    public void reset() {
    }
    
    //----------------------------------------------------------------------------
    // Inner classes
    //----------------------------------------------------------------------------

    /**
     * EventListener is a nested class that is private to this control panel.
     * It handles dispatching of all events generated by the controls.
     */
    private class EventListener implements ActionListener {

        public EventListener() {}

        public void actionPerformed( ActionEvent event ) {
        }
    }
    
    //----------------------------------------------------------------------------
    // Event handlers
    //----------------------------------------------------------------------------
}
