# we actually don't need other things under org.jmol.shape, so leave this as-is
-keep class org.jmol.adapter.readers.xml.XmlCmlReader
-keep class org.jmol.shape.Balls
-keep class org.jmol.shape.BallsRenderer
-keep class org.jmol.shape.Sticks
-keep class org.jmol.shape.SticksRenderer
-keep class org.jmol.shape.Frank
-keep class org.jmol.shape.FrankRenderer
-keep class org.jmol.shape.Uccage
-keep class org.jmol.shape.UccageRenderer
-keep class org.jmol.shape.Bbcage
-keep class org.jmol.shape.BbcageRenderer
-keep class org.jmol.shape.Measures
-keep class org.jmol.shape.MeasuresRenderer