//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_cs.properties
define( {
            "Games.label.level": "Kolo: {0}",
            "Common.updates.errorMessage": "Vznikla chyba při pokusu o aktualizaci.<br>Prosím zkuste aktualizaci později nebo navštivte {0}.",
            "XMLPersistenceManager.save.error.encode": "<html>Chyba při kódování souboru:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Chyba při dekódování souboru:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "s",
            "Common.softwareAgreement.decline": "Konec",
            "Common.statistics.host_os_name": "Název operačního systému:",
            "Common.statistics.user_total_sessions": "Celkový počet všech spuštěných simulací:",
            "Common.statistics.host_java_version_major": "Java verze (major):",
            "FileChooser.openDialogTitleText": "Otevřít",
            "Common.WhiteBackground": "Bílé pozadí",
            "Common.statistics.host_java_version_maintenance": "Java verze (podpora):",
            "FileChooser.lookInLabelText": "Hledat v:",
            "Common.choice.cancel": "Zrušit",
            "Common.updates.seePreferences": "Jděte na Soubor->Předvolby a zmeňte nastavení předvoleb.",
            "Common.About.CreditsDialog.software-development": "Vývoj softwaru",
            "Common.About.JavaVersion": "Verze Java:",
            "ColorChooser.resetText": "Reset",
            "wavelength.ir": "IR",
            "translation.credits": "Robert Seifert (seifrob@seznam.cz)",
            "Common.About.CreditsDialog.design-team": "Vývojový tým",
            "Common.statistics.sim_total_sessions": "Celkový počet spuštěných simulací:",
            "Common.FileMenu.PreferencesMnemonic": "m",
            "wavelength.uv": "UV",
            "Games.title.gameSettings": "Nastavení hry",
            "XMLPersistenceManager.save.title": "Uložit nastavení",
            "XMLPersistenceManager.load.error.contents": "Soubor je poškozen, anebo nebyl vytvořen touto simulací.",
            "Common.statistics.details.title": "Informace",
            "Common.statistics.sim_dev_version": "Verze simulace (dev):",
            "FileChooser.saveInLabelText": "Uložit do:",
            "Common.statistics.sim_name": "Název simulace:",
            "Save.confirm.message": "<html>Zvolený soubor již existuje.<br>Chcete ho přepsat novým souborem?</html>",
            "Games.label.score": "Skóre: {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "PhET vývojový tým",
            "Games.button.start": "Start!",
            "Common.statistics.sim_deployment": "Typ nasazení:",
            "Common.FileMenu.Save": "Uložit nastavení...",
            "Common.About.CreditsDialog.licenseDetails": "Podrobnosti k licenci",
            "ColorChooser.hsbSaturationText": "S",
            "Games.radioButton.on": "zapnuto",
            "FileChooser.acceptAllFileFilterText": "Všechny soubory (*.*)",
            "ColorChooser.hsbNameText": "HSB",
            "Common.ModelSlider.Minimum": "Minimum",
            "Common.FileMenu.Preferences": "Možnosti...",
            "Common.FileMenu.Load": "Načíst nastavení...",
            "Common.updates.downloadingSimJar": "stahování simulace JAR souboru...",
            "Games.radioButton.off": "vypnuto",
            "ColorChooser.swatchesRecentText": "Nedávný: ",
            "Common.updates.updateAvailable": "Aktualizace je dostupná",
            "Common.statistics.host_locale_language": "Jazyk:",
            "Common.clear": "Vymazat",
            "Games.title.gameOver": "Konec hry",
            "FileChooser.filesOfTypeLabelText": "Typ souboru:",
            "Common.ErrorDialog.detailsTitle": "Podrobnosti o chybě",
            "Common.HelpMenu.MegaHelp": "Megapomoc...",
            "Common.ClockControlPanel.Step": "Krok",
            "Common.statistics.sim_revision": "Verze simulace (revision):",
            "Common.choice.yes": "Ano",
            "PiccoloPhet.VelocitySensorNode.unknown": "?",
            "Common.FileMenu.Title": "Soubor",
            "Common.value_units": "{0} {1}",
            "Common.statistics.sim_dev": "Je toto vývojová verze?:",
            "Common.updates.installer.message": "<html>Váš PhET Offline Website Installer je ze dne {0}.<br>Je  dostupná novější verze ze dne {1}.<br><br>Chcete nainstalovat nejnovější PhET Offline Website Installer?</html>",
            "Common.updates.updateNow": "Aktualizovat teď!",
            "Common.record": "Nahrávat",
            "Common.About.CreditsDialog.Title": "Poděkování",
            "Common.updates.error.internetConnection": "<html>Nelze se připojit k {0},<br> zkontrolujte připojení k internetu.</html>",
            "Common.time.fast": "rychle",
            "XMLPersistenceManager.load.error.message": "<html>Chyba pri čtení ze souboru:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Maximum",
            "Common.OptionsMenu": "Volby",
            "Common.ClockControlPanel.Restart": "Znovu",
            "Common.statistics.sim_version_timestamp": "Verze simulace (čas):",
            "Common.updates.installer.yes": "Ano!",
            "Common.phetInstaller": "PhET - offline instalátor",
            "Common.HelpMenu.About": "O programu...",
            "Common.ModelSlider.OutOfRange": "Hodnota mimo rozsah",
            "Common.About.CreditsDialog.TranslationCreditsTitle": "Překlad: ",
            "ColorChooser.previewText": "Náhled",
            "Common.BasicPhetPanel.Title": "Zpět",
            "Common.HelpPanel.HideHelp": "Skrýt pomoc",
            "Common.statistics.host_os_arch": "Typ procesoru:",
            "Common.preferences.title": "Předvolby",
            "Games.button.newGame": "Nová hra",
            "ColorChooser.hsbRedText": "R",
            "ColorChooser.hsbBlueText": "B",
            "Common.ModelSlider.YouEntered": "Zadali jste",
            "Games.label.newBest": "Nový rekord!",
            "Common.About.BuildDate": "Datum vytvoření:",
            "Common.FileMenu.ExitMnemonic": "k",
            "Common.statistics.sim_project": "Název projektu:",
            "Games.label.best": "Nejlepší: {0}",
            "Common.title.message": "Zpráva",
            "Common.updates.downloadingBootstrap": "stahování aktualizačního zavaděče... ",
            "Common.title.error": "Chyba",
            "Common.FileMenu.Exit": "Konec",
            "Common.statistics.sim_major_version": "Verze simulace (major):",
            "Common.updates.askMeLater": "Zeptat se později",
            "chart-time-control.go": "Jeď !",
            "Common.HelpMenu.HelpMnemonic": "v",
            "Common.confirm.clear.graphs": "Skutečně chcete vymazat grafy?",
            "ColorChooser.swatchesNameText": "Vzorníky",
            "Common.updates.progressDialogMessage": "Aktualizace \"{0}\" na verzi {1}",
            "Common.updates.installer.more": "Více informací...",
            "XMLPersistenceManager.title.error": "Chyba",
            "ColorChooser.hsbHueText": "H",
            "ControlPanel.button.resetAll": "Resetovat vše",
            "Common.About.AgreementButton": "Licenční podmínky...",
            "Common.FileMenu.Load.mnemonic": "N",
            "Common.ErrorDialog.detailsButton": "Podrobnosti...",
            "Common.updates.errorMissingJar": "<html>Aktualizace se nezdařila. <br>Nelze nalést JAR soubor: {0}.<br>Požádejte o pomoc svého systémového administrátora. <br></html> ",
            "Common.preferences.privacy": "Soukromí",
            "Common.HelpMenu.AboutTitle": "O programu",
            "ColorChooser.rgbRedText": "Červená",
            "Common.statistics.sim_locale_country": "Země:",
            "ColorChooser.hsbGreenText": "G",
            "ColorChooser.rgbGreenText": "Zelená",
            "Games.format.time.best": "{0} ({1})",
            "Common.HelpPanel.ShowHelp": "Pomoc!",
            "PiccoloPhet.VelocitySensorNode.speed": "Rychlost",
            "Common.statistics.sim_distribution_tag": "Verze simulace (distribuovaná):",
            "Common.statistics.description": "PhET je volně k dispozici díky grantům,<br> které po nás požadují shromáždit několik <br> anonymních <a href=\"{0}\">informací</a> sloužících k prokázání<br> využívání PhET simulací, které jsou potřebné <br>k zlepšení podpory našim uživatelům.",
            "Common.softwareAgreement.message": "Všechny PhET simulace během startu shromažďují malé <br> množství anonymních <a href='{0}'>informací</a> (např. verze simulace, <br>verze operačního systému apod.). Odesílání těchto informací<br> můžete kdykoliv zakázat položkou v menu Soubor->Předvolby.<br><br>Kliknutím na „Souhlasit a pokračovať“ vyjadřujete souhlas s PhET <br>licenční smluvou. (Pro další podrobnosti klikněte <a href='{1}'>zde</a>).",
            "Common.choice.ok": "OK",
            "Common.About.Version": "Verze:",
            "Common.ErrorDialog.contactPhet": "Pokud problém přetrvává, zašlete podrobnosti na {0}",
            "Common.About.CreditsDialog.lead-design": "Vedoucí vývoje",
            "Common.OptionsMenu.mnemonic": "v",
            "Common.statistics.user_preference_file_creation_time": "Čas vytvoření souboru Předvolby:",
            "Common.HelpMenu.AboutMnemonic": "o",
            "Common.updates.errorWritePermissions": "<html>Aktualizace se nezdařila. <br>Nemáte oprávnění pro zápis do {0}.<br>Požádajte o pomoc svého systémového administrátora. <br></html> ",
            "ColorChooser.hsbBrightnessText": "B",
            "Common.choice.no": "Ne",
            "Common.About.WebLink": "Navštívit domovskou stránku PhET",
            "Common.About.OSVersion": "Verze OS:",
            "Common.title.warning": "Varování",
            "Common.updates.versionComparison": "<html>Vaše současná verze \"{0}\" je {1}.<br>Je dostupná novější verze ({2}).</html>",
            "Common.statistics.sim_locale_language": "Jazyk:",
            "Common.statistics.user_installation_timestamp": "Čas PhET instalace:",
            "Common.statistics.message_version": "Verze zprávy:",
            "Common.ModelSlider.Description": "Nepovolená hodnota.",
            "Common.updates.installer.moreMessage": "<html>Udržování aktuální verze PhET Offline Website Installeru,<br> vám zajistí  přístup k nejnovějším PhET simulacím a doplňkovým<br> materiálům. <br><br> Rozhodnete-li se získat nejnovější verzi, tak vám prohlížeč otevře <br>webové stránky PhET, odkud si můžete stáhnout PhET<br> Offline Website Installer.</html>",
            "Common.HelpMenu.Help": "Nápověda",
            "Common.updates.errorNotAJar": "{0} není JAR soubor.",
            "ControlPanel.message.confirmResetAll": "Resetovat všechna nastavení?",
            "Games.label.levelControl": "Kolo:",
            "Common.updates.automaticallyCheck": "Automaticky zkontrolovat aktualizaci",
            "Common.sim.speed": "Rychlost simulace",
            "Common.updates.checkForSimUpdate": "Zkontrolovat aktualizaci simulace...",
            "XMLPersistenceManager.save.confirm.message": "<html>Zvolený soubor již existuje.<br>Chcete ho přepsat novým souborem?</html>",
            "FileChooser.newFolderErrorText": "Chyba při vytváření nové složky",
            "Common.About.CreditsButton": "Poděkování...",
            "Common.updates.skipThisUpdate": "Přeskočit tuto verzi",
            "Common.FileMenu.Save.mnemonic": "u",
            "Common.TeacherMenu": "Učitel",
            "FileChooser.saveDialogTitleText": "Uložit",
            "XMLPersistenceManager.load.title": "Načíst nastavení",
            "Common.updates.checkForInstallerUpdate": "Zkontrolovat aktualizaci PhET Offline Website Installer...",
            "timeseries.control.panel.playback": "Přehrát",
            "Common.updates.progressDialogTitle": "Aktualizace",
            "Common.HelpMenu.Title": "Nápověda",
            "ColorChooser.rgbNameText": "RGB",
            "FileChooser.fileNameLabelText": "Název souboru:",
            "Common.softwareAgreement.title": "Licenční podmínky",
            "Common.statistics.host_java_version_minor": "Java verze (minor):",
            "Common.HelpMenu.TitleMnemonic": "v",
            "Common.About.CreditsDialog.interviews": "Rozhovory",
            "Common.About.Distribution": "Distribuce:",
            "Common.statistics.host_java_webstart_version": "Java Web Start verze:",
            "XMLPersistenceManager.save.error.message": "<html>Chyba při zápisu do souboru:<br>{0}</html>",
            "Games.label.time": "Čas: {0}",
            "FileChooser.openButtonText": "Otevřít",
            "ColorChooser.sampleText": "Ukázka textu Ukázka textu",
            "Common.statistics.details.description": "<html>Po spuštění simulace bude níže zobrazená informace poslána do PhET.</html>",
            "Common.statistics.host_os_version": "Verze operačního systému:",
            "Common.title.confirm": "Potvrdit",
            "Common.BasicPhetPanel.LogoToolTip": "Zakázat celoobrazovkový režim",
            "Games.label.score.max": "Skóre: {0} z {1}",
            "Common.statistics.host_java_timezone": "Časové pásmo:",
            "Common.time.slow": "pomalu",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.ClockControlPanel.Rewind": "Přetočit",
            "Common.softwareAgreement.accept": "Souhlasit a pokračovat",
            "message.valueOutOfRange": "Hodnota mussí být mezi {0} a {1}",
            "Common.updates.updateToDate": "Aktuální",
            "Common.ClockControlPanel.Pause": "Pauza",
            "PhetApplication.StartupDialog.message": "Spouští se \"{0}\"",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Tento program používá software nasledujících třetích stran",
            "XMLPersistenceManager.message.notAConfigFile": "Tento soubor neobsahuje konfiguraci pro tuto simulaci.",
            "Common.preferences.updates": "Aktualizace",
            "Games.label.score.max.perfect": "Skóre: {0} z {1} (BEZ CHYB!",
            "Common.HelpMenu.MegaHelpMnemonic": "p",
            "Common.statistics.enabled": "Povolit odesílání informací fo PhET",
            "Common.ClockControlPanel.StepBack": "Krok zpět",
            "Common.StopwatchPanel.stop": "Stop",
            "Common.HelpPanel.MegaHelp": "Megapomoc...",
            "Common.statistics.host_locale_country": "Země:",
            "Common.StopwatchPanel.reset": "Reset",
            "Common.playback": "Přehrávat",
            "Common.statistics.sim_minor_version": "Verze simulace (minor):",
            "Games.message.confirmNewGame": "<html>Nedokončili jste tuto hru.<br>Chcete opravdu začít novou  hru?</html>",
            "Common.updates.tryIt": "Před aktualizaci vyzkoušet tuto novou vezi.",
            "ColorChooser.rgbBlueText": "Modrá",
            "Common.choice.close": "Zavřít",
            "Common.ClockControlPanel.Play": "Spustit",
            "Common.statistics.sim_type": "Typ simulace:",
            "FileChooser.saveButtonText": "Uložit",
            "Common.rewind": "Přetočit",
            "Common.StopwatchPanel.start": "Start",
            "Common.updates.youHaveCurrent": "Máte nejnovější verzi ({0}) {1}.",
            "Common.statistics.sim_sessions_since": "Počet spuštěných simulací od posledního připojení:",
            "Common.statistics.host_java_vendor": "Výrobce Java stroje:",
            "charts.show-graphs": "Zobrazit grafy:",
            "Common.statistics.message_type": "Typ zprávy:"
        } );