//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_zh_CN.properties
define( {
            "Games.label.level": "等级: {0}",
            "Common.updates.errorMessage": "当更新时产生了一个错误.<br>一会再试或者浏览{0}.",
            "XMLPersistenceManager.save.error.encode": "<html>文件编码错误:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>文件解码错误:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "f",
            "Common.softwareAgreement.decline": "退出",
            "Common.statistics.host_os_name": "操作系统名字",
            "Common.statistics.user_total_sessions": "所有模拟程序被运行的次数",
            "Common.statistics.host_java_version_major": "Java 主要版本",
            "FileChooser.openDialogTitleText": "打开",
            "Common.WhiteBackground": "白色背景",
            "Common.statistics.host_java_version_maintenance": "Java修订版",
            "FileChooser.lookInLabelText": "文件内部标识",
            "Common.choice.cancel": "取消",
            "Common.updates.seePreferences": "到文件的参数选择中设定你的参量",
            "Common.About.CreditsDialog.software-development": "软件开发",
            "Common.About.JavaVersion": "java 版本",
            "ColorChooser.resetText": "重置",
            "wavelength.ir": "IR",
            "translation.credits": "张大红（天津铁厂第二中学）",
            "Common.About.CreditsDialog.design-team": "设计团队",
            "Common.statistics.sim_total_sessions": "模拟程序总共被运行的次数",
            "Common.FileMenu.PreferencesMnemonic": "p",
            "wavelength.uv": "UV",
            "Games.title.gameSettings": "游戏设置",
            "XMLPersistenceManager.save.title": "保存配置",
            "XMLPersistenceManager.load.error.contents": "文件数据出错或者不能被这个模拟(计算机仿真)创设",
            "Common.statistics.details.title": "信息",
            "Common.statistics.sim_dev_version": "模拟程序版本(dev)",
            "FileChooser.saveInLabelText": "保存到",
            "Common.statistics.sim_name": "模拟程序名字",
            "Save.confirm.message": "<html>你选择的文件已经存在.<br>你要覆盖原有的文件么?</html>",
            "Games.label.score": "得分: {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "phET开发团队",
            "Games.button.start": "开始",
            "Common.statistics.sim_deployment": "开发类型",
            "Common.FileMenu.Save": "保存设置",
            "Common.About.CreditsDialog.licenseDetails": "许可信息",
            "ColorChooser.hsbSaturationText": "饱和度",
            "Games.radioButton.on": "开",
            "FileChooser.acceptAllFileFilterText": "所有文件(*.*)",
            "ColorChooser.hsbNameText": "HSB",
            "Common.ModelSlider.Minimum": "最小值",
            "Common.FileMenu.Preferences": "参数设置",
            "Common.FileMenu.Load": "装载配置",
            "Common.updates.downloadingSimJar": "下载模拟(计算机仿真)jar文件",
            "Games.radioButton.off": "关闭",
            "ColorChooser.swatchesRecentText": "最近",
            "Common.updates.updateAvailable": "更新版本可用",
            "Common.statistics.host_locale_language": "主要语言",
            "Common.clear": "清除",
            "Games.title.gameOver": "游戏结束",
            "FileChooser.filesOfTypeLabelText": "文件类型",
            "Common.ErrorDialog.detailsTitle": "错误细节",
            "Common.HelpMenu.MegaHelp": "更多帮助",
            "Common.ClockControlPanel.Step": "下一步",
            "Common.statistics.sim_revision": "模拟程序修订版本",
            "Common.choice.yes": "是",
            "Common.FileMenu.Title": "文件",
            "Common.value_units": "{0} {1}",
            "Common.statistics.sim_dev": "这是一个开发的版本么?",
            "Common.updates.installer.message": "<html>你的 PhET离线浏览安装程序最新日期是 {0}.<br>最新的程序日期是{1}.<br><br>你想获取最新的安装程序么</html>",
            "Common.updates.updateNow": "现在更新",
            "Common.record": "记录",
            "Common.About.CreditsDialog.Title": "工作人员",
            "Common.updates.error.internetConnection": "<html>不能连接 {0},<br>请检查你的计算机网络连接.</html>",
            "Common.time.fast": "快",
            "XMLPersistenceManager.load.error.message": "<html>文件读入错误:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "最大值",
            "Common.OptionsMenu": "参数",
            "Common.ClockControlPanel.Restart": "重新开始",
            "Common.statistics.sim_version_timestamp": "模拟程序终结版本",
            "Common.updates.installer.yes": "是!",
            "Common.phetInstaller": "PhET 离线浏览安装",
            "Common.HelpMenu.About": "关于",
            "Common.ModelSlider.OutOfRange": "参量范围",
            "Common.About.CreditsDialog.TranslationCreditsTitle": "翻译人：",
            "ColorChooser.previewText": "预览",
            "Common.BasicPhetPanel.Title": "返回",
            "Common.HelpPanel.HideHelp": "隐藏帮助",
            "Common.statistics.host_os_arch": "处理器类型",
            "Common.preferences.title": "参数选择",
            "Games.button.newGame": "新游戏",
            "ColorChooser.hsbRedText": "红色",
            "ColorChooser.hsbBlueText": "蓝色",
            "Common.ModelSlider.YouEntered": "你的输入",
            "Games.label.newBest": "你最新最好成绩!",
            "Common.About.BuildDate": "制作时间",
            "Common.FileMenu.ExitMnemonic": "x",
            "Common.statistics.sim_project": "项目名字",
            "Games.label.best": "你最好的: {0}",
            "Common.title.message": "信息",
            "Common.updates.downloadingBootstrap": "下载更新的引导装入程序",
            "Common.title.error": "错误",
            "Common.FileMenu.Exit": "退出",
            "Common.statistics.sim_major_version": "模拟程序主要版本",
            "Common.updates.askMeLater": "以后咨询我",
            "chart-time-control.go": "开始",
            "Common.HelpMenu.HelpMnemonic": "h",
            "Common.confirm.clear.graphs": "你是否真的要清除图线",
            "ColorChooser.swatchesNameText": "色票",
            "Common.updates.progressDialogMessage": "更新 \"{0}\"到版本 {1}",
            "Common.updates.installer.more": "告诉我们更多",
            "XMLPersistenceManager.title.error": "错误",
            "ColorChooser.hsbHueText": "色调",
            "ControlPanel.button.resetAll": "重置所有",
            "Common.About.AgreementButton": "软件协议",
            "Common.FileMenu.Load.mnemonic": "L",
            "Common.ErrorDialog.detailsButton": "细节",
            "Common.updates.errorMissingJar": "<html>这次更新不能完成.<br>不能装载 本地JAR 文件: {0}.<br>请与系统管理员联系寻求帮助.<br></html>",
            "Common.preferences.privacy": "隐私",
            "Common.HelpMenu.AboutTitle": "关于",
            "ColorChooser.rgbRedText": "红色",
            "Common.statistics.sim_locale_country": "国家",
            "ColorChooser.hsbGreenText": "绿色",
            "ColorChooser.rgbGreenText": "绿色",
            "Games.format.time.best": "{0} ({1})",
            "Common.HelpPanel.ShowHelp": "帮助!",
            "Common.statistics.sim_distribution_tag": "模拟程序版本（开发中心）",
            "Common.choice.ok": "确定",
            "Common.About.Version": "版本",
            "Common.ErrorDialog.contactPhet": "如果问题没有解决请发送详细信息到{0}",
            "Common.About.CreditsDialog.lead-design": "主设计",
            "Common.OptionsMenu.mnemonic": "O",
            "Common.statistics.user_preference_file_creation_time": "参数设置文件制作截止时间",
            "Common.HelpMenu.AboutMnemonic": "a",
            "Common.updates.errorWritePermissions": "<html>这次更新不能完成.<br>你没有向 {0}里写入的权限.<br>请与系统管理员联系寻求帮助.<br></html>",
            "ColorChooser.hsbBrightnessText": "亮度",
            "Common.choice.no": "否",
            "Common.About.WebLink": "浏览phET 主页",
            "Common.About.OSVersion": "OS版本",
            "Common.title.warning": "警告",
            "Common.updates.versionComparison": "<html>你现在的版本 \"{0}\"是{1}.<br>新的可用版本是 ({2}).</html>",
            "Common.statistics.sim_locale_language": "语言",
            "Common.statistics.user_installation_timestamp": "phET安装终结版",
            "Common.statistics.message_version": "信息版本",
            "Common.ModelSlider.Description": "非法参量",
            "ControlPanel.message.confirmResetAll": "重置所有设置",
            "Common.HelpMenu.Help": "帮助",
            "Common.updates.errorNotAJar": "{0}不是jar文件",
            "Games.label.levelControl": "等级:",
            "Common.updates.automaticallyCheck": "自动检测更新",
            "Common.sim.speed": "一般速度",
            "Common.updates.checkForSimUpdate": "检测模拟（计算机仿真）更新",
            "XMLPersistenceManager.save.confirm.message": "<html>你选择的文件已经存在.<br>你要覆盖原有的文件么?</html>",
            "FileChooser.newFolderErrorText": "新建文件夹时出错",
            "Common.About.CreditsButton": "工作人员",
            "Common.updates.skipThisUpdate": "跳过这个版本",
            "Common.FileMenu.Save.mnemonic": "S",
            "FileChooser.saveDialogTitleText": "保存",
            "XMLPersistenceManager.load.title": "装入配置",
            "Common.updates.checkForInstallerUpdate": "检测phET离线浏览安装版本更新",
            "timeseries.control.panel.playback": "回放",
            "Common.updates.progressDialogTitle": "更新",
            "Common.HelpMenu.Title": "帮助",
            "ColorChooser.rgbNameText": "RGB",
            "FileChooser.fileNameLabelText": "文件名字",
            "Common.softwareAgreement.title": "软件协议",
            "Common.statistics.host_java_version_minor": "Java 辅助版本",
            "Common.HelpMenu.TitleMnemonic": "h",
            "Common.About.CreditsDialog.interviews": "交流（面谈）",
            "Common.About.Distribution": "软件开发中心",
            "Common.statistics.host_java_webstart_version": "java网络版",
            "XMLPersistenceManager.save.error.message": "<html>文件写入错误:<br>{0}</html>",
            "Games.label.time": "时间: {0}",
            "FileChooser.openButtonText": "打开",
            "ColorChooser.sampleText": "事范文本",
            "Common.statistics.details.description": "<html>每次程序运行时下面的信息将被发送到phET</html>",
            "Common.statistics.host_os_version": "操作系统版本",
            "Common.title.confirm": "确认",
            "Common.BasicPhetPanel.LogoToolTip": "禁止满桢",
            "Games.label.score.max": "得分: {0} 超出 {1}",
            "Common.statistics.host_java_timezone": "截止时间",
            "Common.time.slow": "慢",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.ClockControlPanel.Rewind": "回退",
            "Common.softwareAgreement.accept": "接受并继续",
            "message.valueOutOfRange": "参数必须在 {0} 和 {1}.之间",
            "Common.updates.updateToDate": "时时更新",
            "Common.ClockControlPanel.Pause": "暂停",
            "PhetApplication.StartupDialog.message": "\"{0}\" 正在装载",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "这个程序使用以下第三方软件",
            "XMLPersistenceManager.message.notAConfigFile": "这个文件没有此模拟程序的参数",
            "Common.preferences.updates": "更新",
            "Games.label.score.max.perfect": "得分: {0} 超出 {1} (非常棒!)",
            "Common.HelpMenu.MegaHelpMnemonic": "m",
            "Common.statistics.enabled": "准许把信息发送到PhET",
            "Common.ClockControlPanel.StepBack": "返回",
            "Common.StopwatchPanel.stop": "停止",
            "Common.HelpPanel.MegaHelp": "更多帮助",
            "Common.statistics.host_locale_country": "承办国家",
            "Common.StopwatchPanel.reset": "重置",
            "Common.playback": "回放",
            "Common.statistics.sim_minor_version": "模拟程序辅助版本",
            "Games.message.confirmNewGame": "<html>你还没有结束游戏<br>你确信要开始新的游戏么?</html>",
            "Common.updates.tryIt": "在更新前试用新的版本",
            "ColorChooser.rgbBlueText": "蓝色",
            "Common.choice.close": "关闭",
            "Common.ClockControlPanel.Play": "播放",
            "Common.statistics.sim_type": "模拟程序类型",
            "FileChooser.saveButtonText": "保存",
            "Common.rewind": "回退",
            "Common.StopwatchPanel.start": "开始",
            "Common.updates.youHaveCurrent": "你的最新版本({0}) 时{1}",
            "Common.statistics.sim_sessions_since": "模拟程序从上线到现在被运行的次数",
            "Common.statistics.host_java_vendor": "java厂商",
            "charts.show-graphs": "显示图线",
            "Common.statistics.message_type": "信息类型"
        } );