// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.fluidpressureandflow;

import java.awt.image.BufferedImage;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Resources (images and translated strings) for "FluidPressureAndFlow" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator
 */
public class FluidPressureAndFlowResources {
    public static final String PROJECT_NAME = "fluid-pressure-and-flow";
    public static final PhetResources RESOURCES = new PhetResources( PROJECT_NAME );

    //Strings
    public static class Strings {
        public static final String AREA = RESOURCES.getLocalizedString( "area" );
        public static final String AREA_UNITS_ENGLISH = RESOURCES.getLocalizedString( "areaUnitsEnglish" );
        public static final String AREA_UNITS_METRIC = RESOURCES.getLocalizedString( "areaUnitsMetric" );
        public static final String ATM = RESOURCES.getLocalizedString( "atm" );
        public static final String ATMOSPHERES = RESOURCES.getLocalizedString( "atmospheres" );
        public static final String DENSITY_UNITS_ENGLISH = RESOURCES.getLocalizedString( "densityUnitsEnglish" );
        public static final String DENSITY_UNITS_METRIC = RESOURCES.getLocalizedString( "densityUnitsMetric" );
        public static final String DOTS = RESOURCES.getLocalizedString( "dots" );
        public static final String ENGLISH = RESOURCES.getLocalizedString( "english" );
        public static final String FILL = RESOURCES.getLocalizedString( "fill" );
        public static final String FLOW = RESOURCES.getLocalizedString( "flow" );
        public static final String FLOW_RATE = RESOURCES.getLocalizedString( "flowRate" );
        public static final String FLUID_DENSITY = RESOURCES.getLocalizedString( "fluidDensity" );
        public static final String FLUX = RESOURCES.getLocalizedString( "flux" );
        public static final String FLUX_METER = RESOURCES.getLocalizedString( "fluxMeter" );
        public static final String FLUX_UNITS_ENGLISH = RESOURCES.getLocalizedString( "fluxUnitsEnglish" );
        public static final String FLUX_UNITS_METRIC = RESOURCES.getLocalizedString( "fluxUnitsMetric" );
        public static final String FRICTION = RESOURCES.getLocalizedString( "friction" );
        public static final String FT = RESOURCES.getLocalizedString( "ft" );
        public static final String FT_PER_S = RESOURCES.getLocalizedString( "ftPerS" );
        public static final String GASOLINE = RESOURCES.getLocalizedString( "gasoline" );
        public static final String GRID = RESOURCES.getLocalizedString( "grid" );
        public static final String HONEY = RESOURCES.getLocalizedString( "honey" );
        public static final String HOSE = RESOURCES.getLocalizedString( "hose" );
        public static final String M = RESOURCES.getLocalizedString( "m" );
        public static final String M_PER_S = RESOURCES.getLocalizedString( "mPerS" );
        public static final String MANUAL = RESOURCES.getLocalizedString( "manual" );
        public static final String MATCH_LEAKAGE = RESOURCES.getLocalizedString( "matchLeakage" );
        public static final String MEASURING_TAPE = RESOURCES.getLocalizedString( "measuringTape" );
        public static final String METRIC = RESOURCES.getLocalizedString( "metric" );
        public static final String PA = RESOURCES.getLocalizedString( "pa" );
        public static final String PRESSURE = RESOURCES.getLocalizedString( "pressure" );
        public static final String PSI = RESOURCES.getLocalizedString( "psi" );
        public static final String QUESTION_MARK = RESOURCES.getLocalizedString( "questionMark" );
        public static final String RATE_UNITS_ENGLISH = RESOURCES.getLocalizedString( "rateUnitsEnglish" );
        public static final String RATE_UNITS_METRIC = RESOURCES.getLocalizedString( "rateUnitsMetric" );
        public static final String RESET = RESOURCES.getLocalizedString( "reset" );
        public static final String RULER = RESOURCES.getLocalizedString( "ruler" );
        public static final String UNITS = RESOURCES.getLocalizedString( "units" );
        public static final String UNKNOWN_VELOCITY = RESOURCES.getLocalizedString( "unknownVelocity" );
        public static final String VALUE_WITH_UNITS_PATTERN = RESOURCES.getLocalizedString( "valueWithUnitsPattern" );
        public static final String WATER = RESOURCES.getLocalizedString( "water" );
        public static final String WATER_TOWER = RESOURCES.getLocalizedString( "waterTower" );
    }

    //Images
    public static class Images {
        public static final BufferedImage DRAIN_FAUCET_ATTACHED = RESOURCES.getImage( "drain-faucet-attached.png" );
        public static final BufferedImage HANDLE = RESOURCES.getImage( "handle.png" );
        public static final BufferedImage KNOB = RESOURCES.getImage( "knob.png" );
        public static final BufferedImage NOZZLE = RESOURCES.getImage( "nozzle.png" );
        public static final BufferedImage PANEL = RESOURCES.getImage( "panel.png" );
        public static final BufferedImage PIPE_LEFT_BACK = RESOURCES.getImage( "pipe-left-back.png" );
        public static final BufferedImage PIPE_LEFT_FRONT = RESOURCES.getImage( "pipe-left-front.png" );
        public static final BufferedImage PIPE_MIDDLE = RESOURCES.getImage( "pipe-middle.png" );
        public static final BufferedImage PIPE_RIGHT = RESOURCES.getImage( "pipe-right.png" );
        public static final BufferedImage PIPE_HANDLE_1 = RESOURCES.getImage( "pipe_handle_1.png" );
        public static final BufferedImage POTTED_PLANT = RESOURCES.getImage( "potted-plant.png" );
    }
}