// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.fluidpressureandflow;

import java.awt.image.BufferedImage;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Resources (images and translated strings) for "FluidPressureAndFlow" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator
 */
public class FluidPressureAndFlowResources {
    public static final String NAME = "fluid-pressure-and-flow";
    public static final PhetResources RESOURCES = new PhetResources( NAME );

    //Strings
    public static class Strings {
        public static final String ATM = RESOURCES.getLocalizedString( "atm" );
        public static final String ATMOSPHERES = RESOURCES.getLocalizedString( "atmospheres" );
        public static final String ENGLISH = RESOURCES.getLocalizedString( "english" );
        public static final String FEET = RESOURCES.getLocalizedString( "feet" );
        public static final String FEET_FT = RESOURCES.getLocalizedString( "feetFt" );
        public static final String FLOW = RESOURCES.getLocalizedString( "flow" );
        public static final String FLUID_DENSITY = RESOURCES.getLocalizedString( "fluidDensity" );
        public static final String FT = RESOURCES.getLocalizedString( "ft" );
        public static final String FT_PER_S = RESOURCES.getLocalizedString( "ftPerS" );
        public static final String GASOLINE = RESOURCES.getLocalizedString( "gasoline" );
        public static final String HONEY = RESOURCES.getLocalizedString( "honey" );
        public static final String HOSE = RESOURCES.getLocalizedString( "hose" );
        public static final String KG_PER_M_3 = RESOURCES.getLocalizedString( "kgPerM3" );
        public static final String LB_PER_FT_3 = RESOURCES.getLocalizedString( "lbPerFt3" );
        public static final String LOTS = RESOURCES.getLocalizedString( "lots" );
        public static final String M = RESOURCES.getLocalizedString( "m" );
        public static final String M_PER_S = RESOURCES.getLocalizedString( "mPerS" );
        public static final String MANUAL = RESOURCES.getLocalizedString( "manual" );
        public static final String MATCH_LEAKAGE = RESOURCES.getLocalizedString( "matchLeakage" );
        public static final String MEASURING_TAPE = RESOURCES.getLocalizedString( "measuringTape" );
        public static final String METERS = RESOURCES.getLocalizedString( "meters" );
        public static final String METERS_M = RESOURCES.getLocalizedString( "metersM" );
        public static final String METERS_PER_SECOND = RESOURCES.getLocalizedString( "metersPerSecond" );
        public static final String METRIC = RESOURCES.getLocalizedString( "metric" );
        public static final String NONE = RESOURCES.getLocalizedString( "none" );
        public static final String PA = RESOURCES.getLocalizedString( "pa" );
        public static final String PASCALS = RESOURCES.getLocalizedString( "pascals" );
        public static final String PASCALS_PA = RESOURCES.getLocalizedString( "pascalsPa" );
        public static final String POUNDS_PER_SQUARE_INCH = RESOURCES.getLocalizedString( "poundsPerSquareInch" );
        public static final String POUNDS_PER_SQUARE_INCH_PSI = RESOURCES.getLocalizedString( "poundsPerSquareInchPsi" );
        public static final String PRESSURE = RESOURCES.getLocalizedString( "pressure" );
        public static final String PRESSURE_ATM = RESOURCES.getLocalizedString( "pressureAtm" );
        public static final String PSI = RESOURCES.getLocalizedString( "psi" );
        public static final String QUESTION_MARK = RESOURCES.getLocalizedString( "questionMark" );
        public static final String RESET = RESOURCES.getLocalizedString( "reset" );
        public static final String RULER = RESOURCES.getLocalizedString( "ruler" );
        public static final String SENSOR_PATTERN = RESOURCES.getLocalizedString( "sensorPattern" );
        public static final String UNITS = RESOURCES.getLocalizedString( "units" );
        public static final String WATER = RESOURCES.getLocalizedString( "water" );
        public static final String WATER_TOWER = RESOURCES.getLocalizedString( "waterTower" );
    }

    //Images
    public static class Images {
        public static final BufferedImage BUTTON_PRESSED = RESOURCES.getImage( "button_pressed.png" );
        public static final BufferedImage BUTTON_UNPRESSED = RESOURCES.getImage( "button_unpressed.png" );
        public static final BufferedImage FAUCET = RESOURCES.getImage( "faucet.png" );
        public static final BufferedImage HANDLE = RESOURCES.getImage( "handle.png" );
        public static final BufferedImage HANDLE_1 = RESOURCES.getImage( "handle_1.png" );
        public static final BufferedImage HANDLE_T = RESOURCES.getImage( "handle_T.png" );
        public static final BufferedImage PANEL = RESOURCES.getImage( "panel.png" );
        public static final BufferedImage PIPE_LEFT_BACK = RESOURCES.getImage( "pipe-left-back.png" );
        public static final BufferedImage PIPE_LEFT_FRONT = RESOURCES.getImage( "pipe-left-front.png" );
        public static final BufferedImage PIPE_MIDDLE = RESOURCES.getImage( "pipe-middle.png" );
        public static final BufferedImage PIPE_RIGHT = RESOURCES.getImage( "pipe-right.png" );
        public static final BufferedImage PRESSURE_METER_CENTER = RESOURCES.getImage( "pressure_meter_center.png" );
        public static final BufferedImage PRESSURE_METER_LEFT = RESOURCES.getImage( "pressure_meter_left.png" );
        public static final BufferedImage PRESSURE_METER_RIGHT = RESOURCES.getImage( "pressure_meter_right.png" );
        public static final BufferedImage SQUEEZER_BACKGROUND = RESOURCES.getImage( "squeezer_background.png" );
    }
}