//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_ru.properties
define( {
            "Common.updates.errorMessage": "Произошла ошибка в процессе обновления.<br>Попробуйте ещё раз позднее, или посетите {0}.",
            "XMLPersistenceManager.save.error.encode": "<html>ошибка кодирования файла:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Ошибка декодирования файла:<br>{0}</html>",
            "Common.softwareAgreement.decline": "Выход",
            "Common.statistics.host_os_name": "Название операционной системы",
            "Common.statistics.user_total_sessions": "Общее число всех запусков всех демонстраций",
            "Common.statistics.host_java_version_major": "Версия Java (старшая цифра)",
            "FileChooser.openDialogTitleText": "Открыть",
            "Common.statistics.host_java_version_maintenance": "Версия Java (поддерживающий релиз)",
            "FileChooser.lookInLabelText": "Искать в:",
            "Common.choice.cancel": "Отмена",
            "Common.updates.seePreferences": "Изменить предпочтения можно в меню Файл->Предпочтения.",
            "Common.About.CreditsDialog.software-development": "Разработка ПО",
            "Common.About.JavaVersion": "Версия Java:",
            "ColorChooser.resetText": "Сброс",
            "wavelength.ir": "ИК",
            "Common.About.CreditsDialog.design-team": "Команда дизайнеров",
            "Common.statistics.sim_total_sessions": "Общее число запусков демонстрации",
            "wavelength.uv": "УФ",
            "XMLPersistenceManager.save.title": "Сохранить конфигурацию",
            "XMLPersistenceManager.load.error.contents": "Файл испорчен или создан не этой демонстрацией.",
            "Common.statistics.details.title": "Информация",
            "Common.statistics.sim_dev_version": "Версия демонстрации (для разраб.)",
            "FileChooser.saveInLabelText": "Сохранить в:",
            "Common.statistics.sim_name": "Название демонстрации",
            "Save.confirm.message": "<html>Выбранный вами файл уже существует.<br>Хотите заменить его сохраняемым файлом?</html>",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "Команда разработчиков PhET",
            "Common.statistics.sim_deployment": "Тип установки",
            "Common.FileMenu.Save": "Сохранить конфигурацию...",
            "ColorChooser.hsbSaturationText": "S",
            "FileChooser.acceptAllFileFilterText": "Все файлы (*.*)",
            "ColorChooser.hsbNameText": "HSB",
            "Common.ModelSlider.Minimum": "Минимум",
            "Common.FileMenu.Preferences": "Предпочтения...",
            "Common.FileMenu.Load": "Загрузить конфигурацию...",
            "Common.updates.downloadingSimJar": "загружается файл JAR демонстрации...",
            "ColorChooser.swatchesRecentText": "Недавние:",
            "Common.updates.updateAvailable": "Доступно обновление",
            "Common.statistics.host_locale_language": "Язык хоста",
            "Common.clear": "Очистить",
            "FileChooser.filesOfTypeLabelText": "Файлы типа: ",
            "Common.ErrorDialog.detailsTitle": "Дополнительная информация об ошибке",
            "Common.HelpMenu.MegaHelp": "МегаСправка...",
            "Common.ClockControlPanel.Step": "Шаг",
            "Common.statistics.sim_revision": "Версия демонстрации (ревизия)",
            "Common.choice.yes": "Да",
            "Common.FileMenu.Title": "Файл",
            "Common.value_units": "{0} {1}",
            "Common.statistics.sim_dev": "Версия для разработчиков?",
            "Common.updates.installer.message": "<html>Версия установленного оффлайнового сайта PhET датирована {0}.<br>Доступна новая версия, датированная {1}.<br><br>Хотите ли вы загрузить последнюю версию<br> установщика оффлайнового сайта PhET?</html>",
            "Common.updates.updateNow": "Обновить сейчас!",
            "Common.record": "Запись",
            "Common.About.CreditsDialog.Title": "Благодарности",
            "Common.updates.error.internetConnection": "<html>Не удаётся соединиться с {0},<br> проверьте ваше соединение с сетью.</html>",
            "Common.time.fast": "быстрее",
            "XMLPersistenceManager.load.error.message": "<html>Ошибка чтения из файла:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Максимум",
            "Common.OptionsMenu": "Опции",
            "Common.ClockControlPanel.Restart": "Перезапуск",
            "Common.statistics.sim_version_timestamp": "Версия демонстрации (время создания)",
            "Common.updates.installer.yes": "Да!",
            "Common.phetInstaller": "Установка оффлайнового сайта PhET",
            "Common.HelpMenu.About": "О программе...",
            "Common.ModelSlider.OutOfRange": "Значение не попадает в допустимый диапазон",
            "ColorChooser.previewText": "Предпросмотр",
            "Common.BasicPhetPanel.Title": "Возврат",
            "Common.HelpPanel.HideHelp": "Скрыть справку",
            "Common.statistics.host_os_arch": "Тип процессора",
            "Common.preferences.title": "Предпочтения",
            "ColorChooser.hsbRedText": "R",
            "ColorChooser.hsbBlueText": "B",
            "Common.ModelSlider.YouEntered": "Вы ввели",
            "Common.About.BuildDate": "Дата сборки:",
            "Common.statistics.sim_project": "Имя проекта",
            "Common.updates.downloadingBootstrap": "загружается программа обновления...",
            "Common.title.error": "Ошибка",
            "Common.FileMenu.Exit": "Выход",
            "Common.statistics.sim_major_version": "Версия демонстрации (старшая цифра)",
            "Common.updates.askMeLater": "Спросить позже",
            "chart-time-control.go": "Поехали!",
            "Common.confirm.clear.graphs": "Вы уверены, что хотите очистить графики?",
            "ColorChooser.swatchesNameText": "Образцы",
            "Common.updates.progressDialogMessage": "Обновляется \"{0}\" до версии {1}",
            "Common.updates.installer.more": "Подробнее...",
            "XMLPersistenceManager.title.error": "Ошибка",
            "ColorChooser.hsbHueText": "H",
            "ControlPanel.button.resetAll": "Сбросить всё",
            "Common.About.AgreementButton": "Соглашение о использовании...",
            "Common.ErrorDialog.detailsButton": "Подробности...",
            "Common.updates.errorMissingJar": "<html>Это обновление не может быть выполнено.<br>Не удалось обнаружить файл JAR: {0}.<br>Свяжитесь с вашим системным администратором.<br></html>",
            "Common.preferences.privacy": "Конфиденциальность",
            "Common.HelpMenu.AboutTitle": "О программе",
            "ColorChooser.rgbRedText": "Красный",
            "Common.statistics.sim_locale_country": "Страна",
            "ColorChooser.hsbGreenText": "G",
            "ColorChooser.rgbGreenText": "Зелёный",
            "Common.HelpPanel.ShowHelp": "На помощь!",
            "Common.statistics.sim_distribution_tag": "Версия демонстрации (распространяемая)",
            "Common.statistics.description": "PhET сделано свободно доступным на средства грантов,<br>которые требуют от нас сбора минимального количества<br> анонимной <a href=\"{0}\">информации</a> чтобы задокументировать<br>объём использования демонстраций PhET<br>и чтобы лучше удовлетворять потребности пользователей.",
            "Common.softwareAgreement.message": "Во всех демонстрациях PhET мы собираем минимальное количество <br>анонимной <a href=\"{0}\">информации</a> при каждом запуске демонстрации<br>(например, версию демонстрации, операционную систему).<br>Можно отключить отправку этой информации<br>в любое время с помощью меню Файл->Предпочтения<br><br>Нажатием \"Принять и продолжить\" вы принимаете<br>соглашение об использовании PhET,<br> включая нашу политику конфиденциальности, <br>для текущей и любой другой демонстрации, запущенной вами.<br> (Дополнительная информация доступна <a href=\"{1}\">здесь</a>).",
            "Common.About.Version": "Версия:",
            "Common.ErrorDialog.contactPhet": "Если эта проблема останется, отошлите подробноную информацию {0}",
            "Common.About.CreditsDialog.lead-design": "Ведущий дизайнер",
            "Common.statistics.user_preference_file_creation_time": "Время создания файла предпочтений",
            "Common.updates.errorWritePermissions": "<html>Это обновление не может быть выполнено.<br>Недостаточно прав для записи в {0}.<br>Свяжитесь с вашим системным администратором.<br></html>",
            "ColorChooser.hsbBrightnessText": "B",
            "Common.choice.no": "Нет",
            "Common.About.WebLink": "Посетите домашнюю страницу PhET",
            "Common.About.OSVersion": "Версия ОС:",
            "Common.updates.versionComparison": "<html>Текущая версия \"{0}\" {1}.<br>Доступна новая версия ({2}) .</html>",
            "Common.statistics.sim_locale_language": "Язык",
            "Common.statistics.user_installation_timestamp": "Время создания установки PhET",
            "Common.statistics.message_version": "Версия сообщения",
            "Common.ModelSlider.Description": "Недопустимое значение.",
            "Common.updates.installer.moreMessage": "<html>Своевременно обновляя установку оффлайнового сайта PhET<br>вы получаете последнии версии демонстраций<br>и дополнительных материалов.<br><br>Если выбрать загрузку новой версии, браузер<br>откроет сайт PhET, где можно загрузить <br>PhET Offline Website Installer.</html>",
            "ControlPanel.message.confirmResetAll": "Сбросить все настройки?",
            "Common.HelpMenu.Help": "Справка",
            "Common.updates.errorNotAJar": "{0} не является файлом JAR.",
            "Common.updates.automaticallyCheck": "Автоматически проверять обновления",
            "Common.sim.speed": "...скорость демонстрации...",
            "Common.updates.checkForSimUpdate": "Проверить обновления демонстрации...",
            "XMLPersistenceManager.save.confirm.message": "<html>Выбранный вами файл уже существует.<br>Хотите заменить его сохраняемым файлом?</html>",
            "FileChooser.newFolderErrorText": "Ошибка создания нового каталога",
            "Common.updates.skipThisUpdate": "Пропустить эту версию",
            "Common.About.CreditsButton": "Благодарности...",
            "FileChooser.saveDialogTitleText": "Сохранить",
            "XMLPersistenceManager.load.title": "Загрузить конфигурацию",
            "Common.updates.checkForInstallerUpdate": "Проверить доступность обновления программы установки оффлайнового сайта PhET",
            "timeseries.control.panel.playback": "Воспроизведение",
            "Common.updates.progressDialogTitle": "Обновляется",
            "Common.HelpMenu.Title": "Справка",
            "FileChooser.fileNameLabelText": "Имя файла:",
            "ColorChooser.rgbNameText": "RGB",
            "Common.softwareAgreement.title": "Соглашение об использовании",
            "Common.statistics.host_java_version_minor": "Версия Java (младшая цифра)",
            "Common.About.CreditsDialog.interviews": "Интервью",
            "Common.About.Distribution": "Дистрибутив:",
            "Common.statistics.host_java_webstart_version": "Версия Java Web Start",
            "XMLPersistenceManager.save.error.message": "<html>Ошибка записи в файл:<br>{0}</html>",
            "FileChooser.openButtonText": "Открыть",
            "Common.statistics.details.description": "<html>Указанная ниже информация будет отсылаться в PhET при каждом запуске демонстрации.</html>",
            "ColorChooser.sampleText": "Образец текста Образец текста",
            "Common.statistics.host_os_version": "Версия операционной системы",
            "Common.title.confirm": "Подтвердить",
            "Common.BasicPhetPanel.LogoToolTip": "Отключить ",
            "Common.statistics.host_java_timezone": "Часовой пояс",
            "Common.time.slow": "медленнее",
            "FileChooser.newFolderErrorSeparator": ": ",
            "Common.ClockControlPanel.Rewind": "Перемотать",
            "Common.softwareAgreement.accept": "Принять и продолжить",
            "Common.updates.updateToDate": "Версия самая новая",
            "Common.ClockControlPanel.Pause": "Пауза",
            "PhetApplication.StartupDialog.message": "\"{0}\" запускается",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Эта программа использует следующее стороннее ПО",
            "XMLPersistenceManager.message.notAConfigFile": "Этот файл не содержит конфигурации для этой демонстрации.",
            "Common.preferences.updates": "Обновления",
            "Common.statistics.enabled": "Разрешить отправку информации PhET",
            "Common.StopwatchPanel.stop": "Стоп",
            "Common.HelpPanel.MegaHelp": "МегаСправка...",
            "Common.statistics.host_locale_country": "Страна хоста",
            "Common.StopwatchPanel.reset": "Сброс",
            "Common.playback": "Воспроизведение",
            "Common.statistics.sim_minor_version": "Версия демонстрации (младшая цифра)",
            "Common.updates.tryIt": "Попробовать новую версию перед обновлением.",
            "ColorChooser.rgbBlueText": "Синий",
            "Common.choice.close": "Закрыть",
            "Common.ClockControlPanel.Play": "Запуск",
            "Common.statistics.sim_type": "Тип демонстрации",
            "FileChooser.saveButtonText": "Сохранить",
            "Common.rewind": "Перемотка",
            "Common.StopwatchPanel.start": "Пуск",
            "Common.updates.youHaveCurrent": "Установлена последняя версия ({0})  {1}.",
            "Common.statistics.sim_sessions_since": "Число запусков демонстрации с последнего выхода в интернет",
            "Common.statistics.host_java_vendor": "Поставщик Java",
            "charts.show-graphs": "Показать графики:",
            "Common.statistics.message_type": "Тип сообщения"
        } );