//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_sr.properties
define( {
            "Games.label.level": "Ниво: {0}",
            "Common.updates.errorMessage": "Дошло је до грешке при покушају ажурирања. <br>Молим покушајте касније, или посетите{0}.",
            "XMLPersistenceManager.save.error.encode": "<html>Грешка при кодирању датотеке:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Грешка при декодирању датотеке:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "д",
            "Common.softwareAgreement.decline": "Изађи",
            "Common.statistics.host_os_name": "Назив оперативног система",
            "Common.statistics.user_total_sessions": "Укупан број покретања свих симулација",
            "Common.statistics.host_java_version_major": "Јава верзија (главна)",
            "FileChooser.openDialogTitleText": "Отвори",
            "Common.WhiteBackground": "Бела позадина",
            "Common.statistics.host_java_version_maintenance": "Јава верзија (одржавање)",
            "FileChooser.lookInLabelText": "Погледај у:",
            "Common.choice.cancel": "Одустани",
            "Common.updates.seePreferences": "Идите на Датотека->Подешавања ради измене подешавања.",
            "Common.About.CreditsDialog.software-development": "Развој софтвера",
            "Common.About.JavaVersion": "Јава верзија:",
            "ColorChooser.resetText": "Ресетуј",
            "wavelength.ir": "ИЦ (IR)",
            "translation.credits": "Превео Владан Ал. Младеновић. Примедбе добродошле на  vladan.al.m@gmail.com",
            "Common.About.CreditsDialog.design-team": "Пројектни тим",
            "Common.statistics.sim_total_sessions": "Укупан број колико је пута покренута симулација",
            "Common.FileMenu.PreferencesMnemonic": "п",
            "wavelength.uv": "УЉ (UV)",
            "Games.title.gameSettings": "Подешавања игре",
            "XMLPersistenceManager.save.title": "Сними конфигурацију",
            "XMLPersistenceManager.load.error.contents": "Датотека је оштећена или није креирана овом симулацијом.",
            "Common.statistics.details.title": "Информације",
            "Common.statistics.sim_dev_version": "Верзија симулације (развој)",
            "FileChooser.saveInLabelText": "Сними у:",
            "Common.statistics.sim_name": "Назив симулације",
            "Save.confirm.message": "<html>Датотека коју сте изабрали већ постоји.<br>Желите ли да је замените датотеком коју снимате?</html>",
            "Games.label.score": "Резултат: {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "PhET Развојни тим",
            "Games.button.start": "Старт!",
            "Common.statistics.sim_deployment": "Врста развоја",
            "Common.FileMenu.Save": "Сачувај конфигурацију...",
            "Common.About.CreditsDialog.licenseDetails": "Детаљи лиценце",
            "ColorChooser.hsbSaturationText": "Засићеност",
            "Games.radioButton.on": "укљ.",
            "FileChooser.acceptAllFileFilterText": "Све датотеке (*.*)",
            "ColorChooser.hsbNameText": "Ниј.Зас.Осв. (HSB)",
            "Common.ModelSlider.Minimum": "Минимум",
            "Common.FileMenu.Preferences": "Подешавања...",
            "Common.FileMenu.Load": "Учитај конфигурацију...",
            "Common.updates.downloadingSimJar": "преузимање JAR датотеке симулације...",
            "Games.radioButton.off": "искљ.",
            "Jme.copyThisToTheClipboard": "Копирајте ово у клипборд",
            "ColorChooser.swatchesRecentText": "Недавно:",
            "Common.updates.updateAvailable": "Доступна нова верзија",
            "Common.statistics.host_locale_language": "Језик",
            "Common.clear": "Обриши",
            "Games.title.gameOver": "Крај игре",
            "FileChooser.filesOfTypeLabelText": "Тип датотеке:",
            "Common.ErrorDialog.detailsTitle": "Детаљи грешке",
            "Common.HelpMenu.MegaHelp": "Велика помоћ...",
            "Common.ClockControlPanel.Step": "Корак",
            "Common.statistics.sim_revision": "Верзија симулације (преправљено)",
            "Common.choice.yes": "Да",
            "Common.FileMenu.Title": "Датотека",
            "Common.statistics.sim_dev": "Да ли је ово унапређена  верзија?",
            "Common.updates.installer.message": "<html>Датум вашег независне (офлајн) PhET инсталације је {0}.<br>Доступна је новија верзија датирана {1}.<br><br>Желите ли да преузмете најновији независни PhET вебсајт инсталер?</html>",
            "Common.updates.updateNow": "Ажурирај сада",
            "Common.record": "Сними",
            "Common.About.CreditsDialog.Title": "Заслуге",
            "Common.updates.error.internetConnection": "<html>Не могу да се повежем на {0},<br>молим проверите Интернет конекцију.</html>",
            "Common.time.fast": "брзо",
            "XMLPersistenceManager.load.error.message": "<html>Грешка при читању датотеке:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Максимум",
            "Common.OptionsMenu": "Опције",
            "Common.ClockControlPanel.Restart": "Изнова",
            "Common.statistics.sim_version_timestamp": "Верзија симулације (датум)",
            "Common.updates.installer.yes": "Да!",
            "Common.phetInstaller": "Независни ( офлајн) инсталер PhET вебсајта",
            "Jme.thisSimulationWasUnableToStart": "Симулација није могла бити покренута.",
            "Common.HelpMenu.About": "О програму...",
            "Common.ModelSlider.OutOfRange": "Вредност изван опсега",
            "Common.About.CreditsDialog.TranslationCreditsTitle": "Превео:",
            "ColorChooser.previewText": "Приказ",
            "Common.BasicPhetPanel.Title": "Повратак",
            "Common.HelpPanel.HideHelp": "Сакриј помоћ",
            "Common.statistics.host_os_arch": "Тип процесора",
            "Common.preferences.title": "Подешавања",
            "Games.button.newGame": "Нова игра",
            "ColorChooser.hsbRedText": "Црвено",
            "ColorChooser.hsbBlueText": "Плаво",
            "Common.ModelSlider.YouEntered": "Унели сте",
            "Games.label.newBest": "НОВИ РЕКОРД!",
            "Common.About.BuildDate": "Датум израде:",
            "Common.FileMenu.ExitMnemonic": "и",
            "Common.statistics.sim_project": "Назив пројекта",
            "Games.label.best": "Најбољи: {0}",
            "Common.title.message": "Порука",
            "Common.updates.downloadingBootstrap": "преузимање почетног програма ажурирања...",
            "Common.title.error": "Грешка",
            "Common.FileMenu.Exit": "Излаз",
            "Common.statistics.sim_major_version": "Верзија симулације (главна)",
            "Common.updates.askMeLater": "Питај ме касније",
            "chart-time-control.go": "Крени!",
            "Common.HelpMenu.HelpMnemonic": "п",
            "Common.confirm.clear.graphs": "Да ли сте сигурни да желите да обришете графиконе?",
            "ColorChooser.swatchesNameText": "Узорци боја",
            "Common.updates.progressDialogMessage": "Ажурира се \"{0}\" на верзију {1}",
            "Common.updates.installer.more": "Кажи ми више о томе...",
            "XMLPersistenceManager.title.error": "Грешка",
            "ColorChooser.hsbHueText": "Нијанса",
            "ControlPanel.button.resetAll": "Ресетуј све",
            "Common.About.AgreementButton": "Уговор о софтверу...",
            "Common.FileMenu.Load.mnemonic": "У",
            "Common.ErrorDialog.detailsButton": "Детаљи...",
            "Common.updates.errorMissingJar": "<html>Ово ажурирање се не може извести.<br>Не могу да пронађем JAR датотеку: {0}.<br>Молим контактирајте вашег систем администратора ради помоћи.<br></html>",
            "Common.preferences.privacy": "Приватност",
            "Common.HelpMenu.AboutTitle": "О програму...",
            "ColorChooser.rgbRedText": "Црвена",
            "Common.statistics.sim_locale_country": "Земља",
            "ColorChooser.hsbGreenText": "Зелено",
            "ColorChooser.rgbGreenText": "Зелена",
            "Common.HelpPanel.ShowHelp": "Помоћ!",
            "PiccoloPhet.VelocitySensorNode.speed": "Брзина",
            "Common.statistics.sim_distribution_tag": "Верзија симулације (дистрибуција)",
            "Common.statistics.description": "PhET је доступан свима, одобрењем, којим се<br>од нас захтева да прикупимо минималну количину<br>анонимних <a href=\"{0}\">информација</a> којима се доказује<br>обим коришћења PhET симулација<br>и боље излази у сусрет потребама корисника.",
            "Common.softwareAgreement.message": "Код свих PhET simulacija, прикупљамо минималну количину <br>анонимних<a href=\"{0}\">информација</a> при сваком покретању симулације<br>(нпр. верзију симулације, оперативни систем).<br>Можете онемогућити слање ових информација<br>у било ком тренутку преко ставке менија Датотека->Подешавања.<br><br>Притиском на \"Прихватам, настави\", прихватате PhEТ-ов<br>Уговор о софтверу, укључујући нашу политику о приватности,<br>за ову и сваку PhET симулацију коју покренете.<br>(За детаље, кликните <a href=\"{1}\">овде</a>).",
            "Common.choice.ok": "У реду",
            "Common.About.Version": "Верзија:",
            "Common.ErrorDialog.contactPhet": "Ако се овај проблем понови, о детаљима обавестите {0}",
            "Common.About.CreditsDialog.lead-design": "Водећи пројектант",
            "Common.OptionsMenu.mnemonic": "О",
            "Jme.moreInformation": "<html><body>Надоградите драјвере за вашу графичку картицу. Можда то реш проблем.<br/>За више информација посетите {0},<br/> или ископирајте следећи текст и пошаљите мејлом на {1}.<br/></body></html>",
            "Common.statistics.user_preference_file_creation_time": "Датум подешавања",
            "Sponsor.sponsoredBy": "Спонзорисано од стране",
            "Common.HelpMenu.AboutMnemonic": "о",
            "Common.updates.errorWritePermissions": "<html>Ово ажурирање се не може извести.<br>Немате дозволу да пишете у {0}.<br>Молим контактирајте вашег систем администратора ради помоћи.<br></html>",
            "ColorChooser.hsbBrightnessText": "Осветљеност",
            "Common.choice.no": "Не",
            "Common.About.WebLink": "Посетите PhET почетну страницу",
            "Common.About.OSVersion": "Верзија ОС-а:",
            "Common.title.warning": "Упозорење",
            "Common.updates.versionComparison": "<html>Ваша тренутна верзија \"{0}\" је {1}.<br>Новија верзија ({2}) је доступна.</html>",
            "Common.statistics.sim_locale_language": "Језик",
            "Common.statistics.user_installation_timestamp": "Датум инсталације",
            "Common.statistics.message_version": "Верзија поруке",
            "Common.ModelSlider.Description": "Недозвољена вредност.",
            "Common.updates.installer.moreMessage": "<html>Одржавање ваше независне PhET вебсајт инсталације ажурном<br>обезбеђује вам приступ најновијим симулацијама<br>и допунским материјалима.<br><br>Ако одлучите да преузмете најновију инсталацију, веб прегледач <br>ће отворити PhET вебсајт, где можете преузети<br>независни ( офлајн)  PhET вебсајт инсталер.</html>",
            "Common.HelpMenu.Help": "Помоћ",
            "Common.updates.errorNotAJar": "{0} није JAR датотека.",
            "ControlPanel.message.confirmResetAll": "Ресетуј сва подешавања?",
            "Games.label.levelControl": "Ниво:",
            "Common.updates.automaticallyCheck": "Аутоматски провери постоји ли новија верзија",
            "Common.sim.speed": "... брзина симулације...",
            "Common.updates.checkForSimUpdate": "Провери ажурирање симулације",
            "XMLPersistenceManager.save.confirm.message": "<html>Фајл који сте одабрали већ постоји.<br>Желите ли да га заменизе фајлом који снимате?</html>",
            "FileChooser.newFolderErrorText": "Грешка при стварању нове фасцикле",
            "Common.About.CreditsButton": "Заслуге...",
            "Common.updates.skipThisUpdate": "Прескочи ову верзију",
            "Common.FileMenu.Save.mnemonic": "С",
            "Common.TeacherMenu": "Наставник",
            "FileChooser.saveDialogTitleText": "Сними",
            "XMLPersistenceManager.load.title": "Учитај конфигурацију",
            "Common.updates.checkForInstallerUpdate": "Провери ажурирања PhET независног (офлајн) вебсајт инсталера",
            "timeseries.control.panel.playback": "Покрени",
            "Sponsor.sponsorMenuItem": "Спонзор...",
            "Common.updates.progressDialogTitle": "Ажурирање",
            "Common.HelpMenu.Title": "Помоћ",
            "Common.TeacherMenu.mnemonic": "Т",
            "ColorChooser.rgbNameText": "Цр.Зел.Пл. (RGB)",
            "FileChooser.fileNameLabelText": "Назив датотеке:",
            "Common.softwareAgreement.title": "Уговор о софтверу",
            "Common.statistics.host_java_version_minor": "Јава верзија (подверзија)",
            "Common.HelpMenu.TitleMnemonic": "п",
            "Common.About.CreditsDialog.interviews": "Консултовани",
            "Common.About.Distribution": "Дистрибуција:",
            "Common.statistics.host_java_webstart_version": "Јава Веб Старт верзија",
            "XMLPersistenceManager.save.error.message": "<html>Грешка при уписивању у датотеку:<br>{0}</html>",
            "Games.label.time": "Време: {0}",
            "FileChooser.openButtonText": "Отвори",
            "ColorChooser.sampleText": "Пробни Текст Пробни Текст",
            "Common.statistics.details.description": "<html>Информације приказане испод биће послате у PhET при сваком покретању симулације.</html>",
            "Common.statistics.host_os_version": "Верзија оперативног система",
            "Common.title.confirm": "Потврди",
            "Common.BasicPhetPanel.LogoToolTip": "Онемогући  потпун оквир",
            "Games.label.score.max": "Укупно: {0}  од {1}",
            "Common.statistics.host_java_timezone": "Временска зона",
            "Common.time.slow": "споро",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.ClockControlPanel.Rewind": "Премотај",
            "Common.softwareAgreement.accept": "Прихватам, настави",
            "message.valueOutOfRange": "Вредност мора бити између {0} и {1}.",
            "Common.updates.updateToDate": "Ажурирано",
            "Common.ClockControlPanel.Pause": "Пауза",
            "PhetApplication.StartupDialog.message": "\"{0}\" се покреће",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Овај програм користи следећи софтвер независних произвођача",
            "XMLPersistenceManager.message.notAConfigFile": "Тај фајл не садржи конфигурацију за ту симулацију",
            "Common.preferences.updates": "Ажурирања",
            "Games.label.score.max.perfect": "Укупно: {0} од  {1} (САВРШЕНО!)",
            "Common.HelpMenu.MegaHelpMnemonic": "в",
            "Common.statistics.enabled": "Дозволи слање информација PhET-u",
            "Common.ClockControlPanel.StepBack": "Корак назад",
            "Common.StopwatchPanel.stop": "Стани",
            "Common.HelpPanel.MegaHelp": "Велика помоћ...",
            "Common.statistics.host_locale_country": "Земља",
            "Common.StopwatchPanel.reset": "Покрени поново",
            "Common.playback": "Покрени",
            "Common.statistics.sim_minor_version": "Верзија симулације (подверзија)",
            "Games.message.confirmNewGame": "<html>Нисте завршили ову игру.<br>Да ли сте сигурни да желите да започнете нову?</html>",
            "Common.updates.tryIt": "Испробај нову верзију пре ажурирања",
            "ColorChooser.rgbBlueText": "Плава",
            "Common.choice.close": "Затвори",
            "Common.ClockControlPanel.Play": "Покрени",
            "Common.statistics.sim_type": "Врста симулације",
            "FileChooser.saveButtonText": "Сними",
            "Common.rewind": "Премотај",
            "Common.StopwatchPanel.start": "Крени",
            "Common.updates.youHaveCurrent": "Имате најновију верзију ({0}) {1}.",
            "Common.statistics.sim_sessions_since": "Број покретања симулације од последњег  онлајн покретања",
            "Common.statistics.host_java_vendor": "Јава произвођач",
            "charts.show-graphs": "Прикажи графиконе:",
            "Common.statistics.message_type": "Тип поруке",
            "Sponsor.sinceDate": "(основано {0})"
        } );