//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_fr.properties
define( {
            "Games.label.level": "Niveau : {0}",
            "Common.updates.errorMessage": "Une erreur est survenue pendant la tentative de mise à jour.<br> Veuillez essayer ultérieurement ou visiter {0}",
            "XMLPersistenceManager.save.error.encode": "<html>Erreur d'encodage du fichier:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Erreur en décodant le fichier:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "f",
            "Common.softwareAgreement.decline": "Sortir",
            "Common.statistics.host_os_name": "Nom de l'OS",
            "Common.statistics.user_total_sessions": "Nombre total de fois où toutes les simulations ont été lancées",
            "Common.statistics.host_java_version_major": "Version de Java (majeure)",
            "FileChooser.openDialogTitleText": "Ouvrir",
            "Common.WhiteBackground": "Fond blanc",
            "Common.statistics.host_java_version_maintenance": "Version de Java (maintenance)",
            "FileChooser.lookInLabelText": "Rechercher",
            "Common.choice.cancel": "Abandonner",
            "Common.updates.seePreferences": "Allez dans Fichier->Préférences pour changer vos préférences.",
            "Common.About.CreditsDialog.software-development": "Développement du logiciel",
            "Common.About.JavaVersion": "Version de Java :",
            "ColorChooser.resetText": "Remise à zéro",
            "wavelength.ir": "IR",
            "translation.credits": "<html>Gwénaël Moreau<br>http://gwenaelm.free.fr<br>Emmanuel Keith<br>et les autres qui ne se<br> sont pas encore inscrits</html>",
            "Common.WhiteBackground.mnemonic": "B",
            "Common.About.CreditsDialog.design-team": "Equipe de design",
            "Common.statistics.sim_total_sessions": "Nombre total de fois où cette simulation a été lancée",
            "Common.FileMenu.PreferencesMnemonic": "p",
            "wavelength.uv": "UV",
            "Games.title.gameSettings": "Paramètres du jeu",
            "XMLPersistenceManager.save.title": "Enregistrer la configuration",
            "XMLPersistenceManager.load.error.contents": "Fichier endommagé ou non créé par cette simulation",
            "Common.statistics.details.title": "Information",
            "Common.statistics.sim_dev_version": "Version de simulation (dev)",
            "FileChooser.saveInLabelText": "Enregistrer dans:",
            "Common.statistics.sim_name": "Nom de la simulation",
            "Save.confirm.message": "<html>Le fichier que vous avez sélectionné existe déjà.<br>Voulez-vous le remplacer par le fichier que vous êtes en train d'enregistrer?</html>",
            "Games.label.score": "Score : {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "Equipe de développement de PhET",
            "Games.button.start": "Départ",
            "Common.statistics.sim_deployment": "Type de déploiement",
            "Common.FileMenu.Save": "Enregistrer la configuration...",
            "Common.About.CreditsDialog.licenseDetails": "Détails sur la license",
            "ColorChooser.hsbSaturationText": "S",
            "Games.radioButton.on": "Activé",
            "FileChooser.acceptAllFileFilterText": "tous les fichiers (*.*)",
            "ColorChooser.hsbNameText": "HSB",
            "Common.ModelSlider.Minimum": "Minimum",
            "Common.FileMenu.Preferences": "Préférences...",
            "Common.FileMenu.Load": "Charger la configuration...",
            "Common.updates.downloadingSimJar": "téléchargement du fichier JAR de la simulation...",
            "Games.radioButton.off": "Inactif",
            "Jme.copyThisToTheClipboard": "Copier cela dans le presse papier",
            "ColorChooser.swatchesRecentText": "Récent:",
            "Common.updates.updateAvailable": "Mise à jour disponible",
            "Common.statistics.host_locale_language": "Langue du système",
            "Common.clear": "Effacer",
            "Games.title.gameOver": "Terminé",
            "FileChooser.filesOfTypeLabelText": "Fichiers de type:",
            "Common.ErrorDialog.detailsTitle": "Détails de l'erreur",
            "Common.HelpMenu.MegaHelp": "MégaAide...",
            "Common.ClockControlPanel.Step": "Pas",
            "Common.statistics.sim_revision": "Version de la simulation (révision)",
            "Common.choice.yes": "Oui",
            "PiccoloPhet.VelocitySensorNode.unknown": "?",
            "Common.FileMenu.Title": "Fichier",
            "Common.value_units": "{0} {1}",
            "Common.statistics.sim_dev": "Est-ce une version en développement?",
            "Common.updates.installer.message": "<html>Votre Installation locale de PhET date du {0}.<br> Une version plus récente est disponible, datée du {1}.<br><br> Voulez vous obtenir la dernière version de PhET?</html>",
            "Common.updates.updateNow": "Mettre à jour maintenant!",
            "Common.record": "Enregistrement",
            "Common.About.CreditsDialog.Title": "Crédits",
            "Common.updates.error.internetConnection": "<html> Impossible de se connecter à {0},<br> vérifier votre connexion onternet s'il vous plait.</html>",
            "Common.time.fast": "rapide",
            "XMLPersistenceManager.load.error.message": "<html>Erreur en lisant le fichier:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Maximum",
            "Common.OptionsMenu": "Options",
            "Common.ClockControlPanel.Restart": "Redémarrer",
            "Common.statistics.sim_version_timestamp": "Version de la simulation ( horodatage)",
            "Common.updates.installer.yes": "Oui !",
            "Common.phetInstaller": "Installateur du site PhET en local",
            "Jme.thisSimulationWasUnableToStart": "Cette simulation n'a pas pu démarrer",
            "Common.HelpMenu.About": "A propos...",
            "Common.ModelSlider.OutOfRange": "Valeur hors limites",
            "Common.About.CreditsDialog.TranslationCreditsTitle": "Traduit par",
            "ColorChooser.previewText": "Prévisualisation",
            "Common.BasicPhetPanel.Title": "Retour",
            "Common.HelpPanel.HideHelp": "Cacher l'aide",
            "Common.statistics.host_os_arch": "type de processeur",
            "Common.preferences.title": "Préférences",
            "Games.button.newGame": "Nouvelle partie",
            "ColorChooser.hsbRedText": "R",
            "ColorChooser.hsbBlueText": "B",
            "Common.ModelSlider.YouEntered": "Vous êtes entrés",
            "Games.label.newBest": "Votre nouveau score !",
            "Common.About.BuildDate": "Date de compilation:",
            "Common.FileMenu.ExitMnemonic": "x",
            "Common.statistics.sim_project": "Nom du projet",
            "Games.label.best": "Meilleur score : {0}",
            "Common.title.message": "Message",
            "Common.updates.downloadingBootstrap": "téléchargement du lanceur de mise à jour...",
            "Common.title.error": "Erreur",
            "Common.FileMenu.Exit": "Sortir",
            "Common.statistics.sim_major_version": "Version de simulation (majeure)",
            "Common.updates.askMeLater": "Me demander plus tard",
            "chart-time-control.go": "Go!",
            "Common.HelpMenu.HelpMnemonic": "h",
            "Common.confirm.clear.graphs": "Etes-vous sur que vous voulez effacer les graphiques",
            "ColorChooser.swatchesNameText": "Echantillons",
            "Common.updates.progressDialogMessage": "Mise à jour en cours de la version {0} vers la version {1}",
            "Common.updates.installer.more": "Je veux en savoir plus ...",
            "XMLPersistenceManager.title.error": "Erreur",
            "ColorChooser.hsbHueText": "H",
            "ControlPanel.button.resetAll": "Tout remettre à zéro",
            "Common.About.AgreementButton": "Licence d'Utilisation...",
            "Common.FileMenu.Load.mnemonic": "L",
            "Common.ErrorDialog.detailsButton": "Détails ...",
            "Common.updates.errorMissingJar": "<html> Cette misa à jour ne peut-être réalisée.<br> Impossible de trouver le fichier JAR: {0}.<br> Veuillez contacter votre administrateur système pour obtenir de l'aide.<br></html>",
            "Common.preferences.privacy": "Vie privée",
            "Common.HelpMenu.AboutTitle": "A propos",
            "ColorChooser.rgbRedText": "Rouge",
            "Common.statistics.sim_locale_country": "Pays",
            "ColorChooser.hsbGreenText": "G",
            "ColorChooser.rgbGreenText": "Vert",
            "Games.format.time.best": "{0} ({1})",
            "Common.HelpPanel.ShowHelp": "Au secours!",
            "PiccoloPhet.VelocitySensorNode.speed": "Vitesse",
            "Common.statistics.sim_distribution_tag": "Version de simulation (distribution)",
            "Common.statistics.description": "PhET est rendu librement disponible par des subventions <br>qui nous obligent à collecter une quantité minimum <br> <a href=\"{0}\">d'informations</a> anonymes pour renseigner le taux d'utilisation <br>de Phet et adapter au mieux le service aux besoins<br> de nos utilisateurs.",
            "Common.softwareAgreement.message": "Dans toutes les simulations de PhET, nous recueillons une quantité minimale<br><a href=\"{0}\">d'informations</a> anonymes à chaque fois que la simulation commence<br>( ex: version de la simulation, OS).<br> Vous pouvez désactiver l'envoi de ces informations<br>n'importe quand par l''item préférences du menu Fichier.<br><br> En cliquant sur  \"Accepter et Continuer\" vous accepter<br>la Licence d'Utilisation de PhET incluant la politique de vie privée,<br> pour cette simulation de Phet et toutes les autres que vous lancerez.<br>(Pour plus de détails; cliquer<a href=\"{1}\">Ici</a>).",
            "Common.choice.ok": "OK",
            "Common.About.Version": "Version:",
            "Common.ErrorDialog.contactPhet": "Si ce problème persiste, envoyer les détails ci-dessous à {0}",
            "Common.About.CreditsDialog.lead-design": "Design principal",
            "Common.OptionsMenu.mnemonic": "O",
            "Jme.moreInformation": "<html><body> Mettre à jour le pilote de votre carte graphique puet résoudre le problème.<br/> Pour plus d'informations vistez {0},<br/> ou copier et coller  dans un email à {1}<br/></body></html>",
            "Common.statistics.user_preference_file_creation_time": "horodatage de la creation du fichier de préférences",
            "Common.HelpMenu.AboutMnemonic": "a",
            "Common.updates.errorWritePermissions": "<html>Cette mise à jour ne peut être réalisée.<br> Vous n'avez pas la permission d'écrire en {0}.<br> Veuillez contacter votre administrateur système pour obtenir de l'aide.<br></html>",
            "ColorChooser.hsbBrightnessText": "B",
            "Common.choice.no": "Non",
            "Common.About.WebLink": "Visiter le site de PhET",
            "Common.About.OSVersion": "Version de l'OS:",
            "Common.title.warning": "Avertissement",
            "Common.updates.versionComparison": "<html>Votre version actuelle of\"{0}\" is {1}.<br>Une version plus récente({2}) est disponible.</html>",
            "Common.statistics.sim_locale_language": "Langue",
            "Common.statistics.user_installation_timestamp": "horodatage de l'installation de PhET",
            "Common.statistics.message_version": "Version du message",
            "Common.ModelSlider.Description": "Valeur non autorisée.",
            "Common.updates.installer.moreMessage": "<html> Pour garder votre installation locale de Phet à jour<br>assurez-vous que vous avez accès aux plus récentes simulations<br> et aux plus récents matériel complémentaires.<br><br>Si vous décidez d'obtenir la version la plus récente, un navigateur internet<br>va ouvrir le site web de PhET ou vous pourrez télécharger cette version.</html>",
            "Common.HelpMenu.Help": "Aide",
            "Common.updates.errorNotAJar": "{0} n'est pas un fichier JAR.",
            "ControlPanel.message.confirmResetAll": "Réinitialiser tous les paramètres?",
            "Games.label.levelControl": "Niveau :",
            "Common.updates.automaticallyCheck": "Vérifier les mises à jour automatiquement",
            "Common.sim.speed": "...vitesse de simulation...",
            "Common.updates.checkForSimUpdate": "Vérifier la mise à jour de la simulation...",
            "XMLPersistenceManager.save.confirm.message": "<html>Le fichier que vous avez sélectionné existe déjà.<br>Voulez-vous le remplacer par le fichier que vous êtes en train d'enregistrer?</html>",
            "FileChooser.newFolderErrorText": "Erreur en créant un nouveau dossier",
            "Common.About.CreditsButton": "Crédits...",
            "Common.updates.skipThisUpdate": "Passer cette version",
            "Common.FileMenu.Save.mnemonic": "S",
            "Common.TeacherMenu": "Professeur",
            "FileChooser.saveDialogTitleText": "Enregistrer",
            "XMLPersistenceManager.load.title": "Charger la configuration",
            "Common.updates.checkForInstallerUpdate": "Vérifier les mises à jour de l'installateur de PhET en local",
            "timeseries.control.panel.playback": "Rejouer",
            "Common.updates.progressDialogTitle": "En cours de mise à jour",
            "Common.HelpMenu.Title": "Aide",
            "Common.TeacherMenu.mnemonic": "P",
            "ColorChooser.rgbNameText": "RVB",
            "FileChooser.fileNameLabelText": "Nom du fichier:",
            "Common.softwareAgreement.title": "Licence d'Utilisation",
            "Common.statistics.host_java_version_minor": "Version de Java (mineure)",
            "Common.HelpMenu.TitleMnemonic": "h",
            "Common.About.CreditsDialog.interviews": "Interviews",
            "Common.About.Distribution": "Distribution :",
            "Common.statistics.host_java_webstart_version": "Version de Java Web Start",
            "XMLPersistenceManager.save.error.message": "<html>Erreur lors de l'écriture dans le fichier:<br>{0}</html>",
            "Games.label.time": "Temps : {0}",
            "FileChooser.openButtonText": "Ouvrir",
            "ColorChooser.sampleText": "Texte Exemple Texte Exemple",
            "Common.statistics.details.description": "<html> Les informations figurant ci dessous seront envoyées à PhET chaque fois que la simulation commence.</html>",
            "Common.statistics.host_os_version": "Version de l'OS",
            "Common.title.confirm": "Confirmer",
            "Common.BasicPhetPanel.LogoToolTip": "Désactiver le plein écran",
            "Games.label.score.max": "Score : {0} sur {1}",
            "Common.statistics.host_java_timezone": "Fuseau horaire",
            "Common.time.slow": "lent",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.ClockControlPanel.Rewind": "Rembobiner",
            "Common.softwareAgreement.accept": "Accepter et Continuer",
            "message.valueOutOfRange": "La valeur doit être comprise entre {0} et {1}.",
            "Common.updates.updateToDate": "Version à jour",
            "Common.ClockControlPanel.Pause": "Pause",
            "PhetApplication.StartupDialog.message": "\"{0}\" démarre",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Ce programme utilise les programmes tiers suivants",
            "XMLPersistenceManager.message.notAConfigFile": "Ce fichier ne contient pas de configuration pour cette simulation",
            "Common.preferences.updates": "Mises à jour",
            "Games.label.score.max.perfect": "Score : {0} sur {1} (Parfait)",
            "Common.HelpMenu.MegaHelpMnemonic": "m",
            "Common.statistics.enabled": "Autoriser l'envoi d'informations à phET",
            "Common.ClockControlPanel.StepBack": "En arrière",
            "Common.StopwatchPanel.stop": "Arrêt",
            "Common.HelpPanel.MegaHelp": "MégaAide...",
            "Common.statistics.host_locale_country": "Pays du système",
            "Common.StopwatchPanel.reset": "Remise à zéro",
            "Common.playback": "Rejouer",
            "Common.statistics.sim_minor_version": "Version de simulation (mineure)",
            "Games.message.confirmNewGame": "<html>Vous n'avez pas terminée cette partie.<br>Etes-vous sûr de vouloir en commencer une nouvelle ?</html>",
            "Common.updates.tryIt": "Essayer la nouvelle version avant de faire la mise à jour.",
            "ColorChooser.rgbBlueText": "Bleu",
            "Common.choice.close": "Fermer",
            "Common.ClockControlPanel.Play": "Play",
            "Common.statistics.sim_type": "Type de simulation",
            "FileChooser.saveButtonText": "Enregistrer",
            "Common.rewind": "Rebobiner",
            "Common.StopwatchPanel.start": "Départ",
            "Common.updates.youHaveCurrent": "Votre version ({0}) de {1} est à jour.",
            "Common.statistics.sim_sessions_since": "Nombre de fois que cette simulation a été lancée depuis la dernière mise en ligne.",
            "Common.statistics.host_java_vendor": "Vendeur de Java",
            "charts.show-graphs": "Montrer les graphiques:",
            "Common.statistics.message_type": "Type de message"
        } );