//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings.properties
define( {
            "root": {
                "Games.label.level": "Level: {0}",
                "Common.updates.errorMessage": "An error was encountered while trying to update.<br>Please try again later, or visit {0}.",
                "XMLPersistenceManager.save.error.encode": "<html>Error encoding file:<br>{0}</html>",
                "XMLPersistenceManager.load.error.decode": "<html>Error decoding file:<br>{0}</html>",
                "Common.FileMenu.TitleMnemonic": "f",
                "Common.softwareAgreement.decline": "Exit",
                "Common.statistics.host_os_name": "Operating system name:",
                "Common.statistics.user_total_sessions": "Total number of times all simulations have been run:",
                "Common.statistics.host_java_version_major": "Java version (major):",
                "FileChooser.openDialogTitleText": "Open",
                "Common.statistics.host_java_version_maintenance": "Java version (maintenance):",
                "Common.WhiteBackground": "White Background",
                "FileChooser.lookInLabelText": "Look In:",
                "Common.choice.cancel": "Cancel",
                "Common.updates.seePreferences": "Go to File->Preferences to change your preferences.",
                "Common.About.CreditsDialog.software-development": "Software Development",
                "Common.About.JavaVersion": "Java Version:",
                "wavelength.ir": "IR",
                "ColorChooser.resetText": "Reset",
                "Common.WhiteBackground.mnemonic": "w",
                "Common.About.CreditsDialog.design-team": "Design Team",
                "Common.statistics.sim_total_sessions": "Total number of times this simulation has been run:",
                "Games.title.gameSettings": "Game Settings",
                "wavelength.uv": "UV",
                "Common.FileMenu.PreferencesMnemonic": "p",
                "XMLPersistenceManager.save.title": "Save configuration",
                "XMLPersistenceManager.load.error.contents": "File is corrupt or was not created by this simulation.",
                "Common.statistics.details.title": "Information",
                "Common.statistics.sim_dev_version": "Simulation version (dev):",
                "FileChooser.saveInLabelText": "Save In:",
                "Common.statistics.sim_name": "Simulation name:",
                "Save.confirm.message": "<html>The file you selected already exists.<br>Do you want to replace it with the file you are saving?</html>",
                "Games.label.score": "Score: {0}",
                "Common.About.CreditsDialog.PhetDevelopmentTeam": "PhET Development Team",
                "Games.button.start": "Start",
                "Common.statistics.sim_deployment": "Deployment type:",
                "Common.FileMenu.Save": "Save configuration...",
                "Common.About.CreditsDialog.licenseDetails": "License Details",
                "ColorChooser.hsbSaturationText": "S",
                "Games.check": "Check",
                "Games.radioButton.on": "on",
                "FileChooser.acceptAllFileFilterText": "All Files (*.*)",
                "ColorChooser.hsbNameText": "HSB",
                "Common.ModelSlider.Minimum": "Minimum",
                "Common.FileMenu.Preferences": "Preferences...",
                "Common.FileMenu.Load": "Load configuration...",
                "Common.updates.downloadingSimJar": "downloading simulation JAR file...",
                "Games.radioButton.off": "off",
                "Jme.copyThisToTheClipboard": "Copy this to the clipboard",
                "ColorChooser.swatchesRecentText": "Recent:",
                "Common.updates.updateAvailable": "Update Available",
                "Common.statistics.host_locale_language": "Host language:",
                "Common.clear": "Clear",
                "Games.title.gameOver": "Game Over",
                "FileChooser.filesOfTypeLabelText": "Files of Type:",
                "Common.ErrorDialog.detailsTitle": "Error Details",
                "Common.HelpMenu.MegaHelp": "MegaHelp...",
                "Games.next": "Next",
                "Common.ClockControlPanel.Step": "Step",
                "Common.statistics.sim_revision": "Simulation version (revision):",
                "Common.choice.yes": "Yes",
                "PiccoloPhet.VelocitySensorNode.unknown": "?",
                "Common.FileMenu.Title": "File",
                "Common.statistics.sim_dev": "Is this a developer version?:",
                "Common.value_units": "{0} {1}",
                "Common.updates.installer.message": "<html>Your PhET Offline Website Installation is dated {0}.<br>A newer version is available, dated {1}.<br><br>Would you like to get the latest PhET Offline Website Installer?</html>",
                "Common.updates.updateNow": "Update Now!",
                "Common.record": "Record",
                "Common.About.CreditsDialog.Title": "Credits",
                "Common.updates.error.internetConnection": "<html>Cannot connect to {0},<br>please check your Internet connection.</html>",
                "Common.time.fast": "fast",
                "XMLPersistenceManager.load.error.message": "<html>Error reading from file:<br>{0}</html>",
                "Common.ModelSlider.Maximum": "Maximum",
                "Common.OptionsMenu": "Options",
                "Common.ClockControlPanel.Restart": "Restart",
                "Common.statistics.sim_version_timestamp": "Simulation version (timestamp):",
                "Common.updates.installer.yes": "Yes!",
                "Common.phetInstaller": "PhET Offline Website Installer",
                "Jme.thisSimulationWasUnableToStart": "This simulation was unable to start.",
                "Common.HelpMenu.About": "About...",
                "Common.ModelSlider.OutOfRange": "Value out of range",
                "Common.About.CreditsDialog.TranslationCreditsTitle": "Translated by",
                "ColorChooser.previewText": "Preview",
                "Common.BasicPhetPanel.Title": "Return",
                "Common.statistics.host_os_arch": "Processor type:",
                "Common.HelpPanel.HideHelp": "Hide Help",
                "Common.preferences.title": "Preferences",
                "Games.button.newGame": "New Game",
                "ColorChooser.hsbRedText": "R",
                "ColorChooser.hsbBlueText": "B",
                "Common.ModelSlider.YouEntered": "You entered",
                "Games.label.newBest": "Your New Best!",
                "Common.About.BuildDate": "Build Date:",
                "Common.FileMenu.ExitMnemonic": "x",
                "Games.label.best": "Your Best: {0}",
                "Common.statistics.sim_project": "Project name:",
                "Common.title.message": "Message",
                "Common.updates.downloadingBootstrap": "downloading updater bootstrap...",
                "Common.title.error": "Error",
                "Games.showAnswer": "Show Answer",
                "Common.FileMenu.Exit": "Exit",
                "Common.statistics.sim_major_version": "Simulation version (major):",
                "Common.updates.askMeLater": "Ask me later",
                "chart-time-control.go": "Go!",
                "Common.HelpMenu.HelpMnemonic": "h",
                "Common.confirm.clear.graphs": "Are you sure you want to clear the graphs?",
                "ColorChooser.swatchesNameText": "Swatches",
                "Common.updates.progressDialogMessage": "Updating \"{0}\" to version {1}",
                "Common.updates.installer.more": "Tell me more...",
                "XMLPersistenceManager.title.error": "Error",
                "ColorChooser.hsbHueText": "H",
                "ControlPanel.button.resetAll": "Reset All",
                "Common.About.AgreementButton": "Software Agreement...",
                "Common.ErrorDialog.detailsButton": "Details...",
                "Common.FileMenu.Load.mnemonic": "L",
                "Common.updates.errorMissingJar": "<html>This update cannot be performed.<br>Could not locate JAR file: {0}.<br>Please contact your system administrator for help.<br></html>",
                "Common.preferences.privacy": "Privacy",
                "Common.HelpMenu.AboutTitle": "About",
                "ColorChooser.rgbRedText": "Red",
                "Common.statistics.sim_locale_country": "Country:",
                "ColorChooser.hsbGreenText": "G",
                "ColorChooser.rgbGreenText": "Green",
                "Games.format.time.best": "{0} ({1})",
                "Common.HelpPanel.ShowHelp": "Help!",
                "PiccoloPhet.VelocitySensorNode.speed": "Speed",
                "Common.statistics.sim_distribution_tag": "Simulation version (distribution):",
                "Common.statistics.description": "PhET is made freely available by grants that<br>require us to collect a minimal amount of<br>anonymous <a href=\"{0}\">information</a> to help document<br>the amount of use of PhET simulations<br>and to better server our users' needs.",
                "Common.softwareAgreement.message": "In all PhET simulations, we collect a minimal amount<br>of anonymous <a href=\"{0}\">information</a> each time the simulation starts<br>(e.g., simulation version, operating system).<br>You can disable the sending of this information<br>at any time via the File->Preferences menu item.<br><br>By clicking \"Agree and Continue\", you agree to PhET''s<br>Software Agreement, including our privacy policy,<br>for this and every PhET simulation you run.<br>(For details, click <a href=\"{1}\">here</a>).",
                "Common.choice.ok": "OK",
                "Common.About.Version": "Version:",
                "Common.ErrorDialog.contactPhet": "If this problem persists, send the details below to {0}",
                "Common.About.CreditsDialog.lead-design": "Lead Design",
                "Common.OptionsMenu.mnemonic": "O",
                "Jme.moreInformation": "<html><body>Upgrading your video card''s drivers may fix the problem.<br/>For further information, visit {0},<br/> or copy and paste the following in an email to {1}.<br/></body></html>",
                "Common.statistics.user_preference_file_creation_time": "Preferences file creation timestamp:",
                "Sponsor.sponsoredBy": "Sponsored by",
                "Common.HelpMenu.AboutMnemonic": "a",
                "Common.updates.errorWritePermissions": "<html>This update cannot be performed.<br>You do not have permission to write to {0}.<br>Please contact your system administrator for help.<br></html>",
                "ColorChooser.hsbBrightnessText": "B",
                "Common.choice.no": "No",
                "Common.About.WebLink": "Visit the PhET Homepage",
                "Common.About.OSVersion": "OS Version:",
                "Common.title.warning": "Warning",
                "Common.updates.versionComparison": "<html>Your current version of \"{0}\" is {1}.<br>A newer version ({2}) is available.</html>",
                "Common.statistics.user_installation_timestamp": "PhET installation timestamp:",
                "Common.statistics.sim_locale_language": "Language:",
                "Common.wavelengthControl.nm": "nm",
                "Common.statistics.message_version": "Message version:",
                "Common.updates.installer.moreMessage": "<html>Keeping your PhET Offline Website Installation up-to-date<br>ensures that you have access to the newest PhET simulations<br>and supplemental materials.<br><br>If you choose to get the newest version, a web browser <br>will open to the PhET website, where you can download<br>the PhET Offline Website Installer.</html>",
                "Common.ModelSlider.Description": "Illegal value.",
                "ControlPanel.message.confirmResetAll": "Reset all settings?",
                "Common.HelpMenu.Help": "Help",
                "Common.updates.errorNotAJar": "{0} is not a JAR file.",
                "Games.label.levelControl": "Level:",
                "Common.updates.automaticallyCheck": "Automatically check for updates",
                "Common.sim.speed": "Sim Speed",
                "Common.updates.checkForSimUpdate": "Check for simulation update...",
                "XMLPersistenceManager.save.confirm.message": "<html>The file you selected already exists.<br>Do you want to replace it with the file you are saving?</html>",
                "Common.wavelengthControl.IR": "IR",
                "FileChooser.newFolderErrorText": "Error creating new folder",
                "Common.updates.skipThisUpdate": "Skip this version",
                "Common.About.CreditsButton": "Credits...",
                "Common.FileMenu.Save.mnemonic": "S",
                "FileChooser.saveDialogTitleText": "Save",
                "Common.TeacherMenu": "Teacher",
                "XMLPersistenceManager.load.title": "Load configuration",
                "Common.wavelengthControl.UV": "UV",
                "timeseries.control.panel.playback": "Playback",
                "Common.updates.checkForInstallerUpdate": "Check for PhET Offline Website Installer update...",
                "Sponsor.sponsorMenuItem": "Sponsor...",
                "Common.updates.progressDialogTitle": "Updating",
                "Common.HelpMenu.Title": "Help",
                "Common.TeacherMenu.mnemonic": "T",
                "FileChooser.fileNameLabelText": "File Name:",
                "ColorChooser.rgbNameText": "RGB",
                "Common.softwareAgreement.title": "Software Agreement",
                "Common.statistics.host_java_version_minor": "Java version (minor):",
                "Common.HelpMenu.TitleMnemonic": "h",
                "Common.About.CreditsDialog.interviews": "Interviews",
                "Common.About.Distribution": "Distribution:",
                "Common.statistics.host_java_webstart_version": "Java Web Start version:",
                "XMLPersistenceManager.save.error.message": "<html>Error writing to file:<br>{0}</html>",
                "Games.label.time": "Time: {0}",
                "FileChooser.openButtonText": "Open",
                "Common.statistics.details.description": "<html>The information shown below will be sent to PhET each time the simulation starts.</html>",
                "ColorChooser.sampleText": "Sample Text Sample Text",
                "Common.statistics.host_os_version": "Operating system version:",
                "Common.title.confirm": "Confirm",
                "Games.label.score.max": "Score: {0} out of {1}",
                "Common.BasicPhetPanel.LogoToolTip": "Disable Full Frame",
                "Common.statistics.host_java_timezone": "Timezone:",
                "Common.time.slow": "slow",
                "FileChooser.newFolderErrorSeparator": ":",
                "Common.softwareAgreement.accept": "Accept and Continue",
                "Common.ClockControlPanel.Rewind": "Rewind",
                "message.valueOutOfRange": "Value must be between {0} and {1}.",
                "Common.updates.updateToDate": "Up To Date",
                "Common.ClockControlPanel.Pause": "Pause",
                "PhetApplication.StartupDialog.message": "\"{0}\" is starting up",
                "Games.tryAgain": "Try Again",
                "Common.About.CreditsDialog.UsesThirdPartySoftware": "This program uses the following third-party software",
                "XMLPersistenceManager.message.notAConfigFile": "This file does not contain a configuration for this simulation.",
                "Common.preferences.updates": "Updates",
                "Games.label.score.max.perfect": "Score: {0} out of {1} (Perfect!)",
                "Common.HelpMenu.MegaHelpMnemonic": "m",
                "Common.statistics.enabled": "Allow sending of information to PhET",
                "Common.ClockControlPanel.StepBack": "Step Back",
                "Common.StopwatchPanel.stop": "Stop",
                "Common.statistics.host_locale_country": "Host country:",
                "Common.HelpPanel.MegaHelp": "MegaHelp...",
                "Common.StopwatchPanel.reset": "Reset",
                "Common.playback": "Playback",
                "Games.message.confirmNewGame": "<html>You haven't finished this game.<br>Are you sure you want to start a new game?</html>",
                "Common.statistics.sim_minor_version": "Simulation version (minor):",
                "Common.updates.tryIt": "Try the new version before you update.",
                "ColorChooser.rgbBlueText": "Blue",
                "Common.choice.close": "Close",
                "Common.ClockControlPanel.Play": "Play",
                "Common.statistics.sim_type": "Simulation type:",
                "FileChooser.saveButtonText": "Save",
                "Common.rewind": "Rewind",
                "Common.StopwatchPanel.start": "Start",
                "Common.updates.youHaveCurrent": "You have the most current version ({0}) of {1}.",
                "Common.statistics.host_java_vendor": "Java vendor:",
                "Common.statistics.sim_sessions_since": "Number of times this simulation has been run since last online:",
                "charts.show-graphs": "Show graphs:",
                "Sponsor.sinceDate": "(since {0})",
                "Common.statistics.message_type": "Message type:"
            },
            "ar": true,
            "ar-sa": true,
            "ca": true,
            "cs": true,
            "da": true,
            "de": true,
            "el": true,
            "es": true,
            "es-co": true,
            "et": true,
            "eu": true,
            "fa": true,
            "fi": true,
            "fr": true,
            "hr": true,
            "hu": true,
            "in": true,
            "it": true,
            "iw": true,
            "ja": true,
            "ka": true,
            "ko": true,
            "lv": true,
            "mk": true,
            "nb": true,
            "nl": true,
            "pt": true,
            "pt-br": true,
            "ro": true,
            "ru": true,
            "sk": true,
            "sl": true,
            "sq": true,
            "sr": true,
            "sv": true,
            "sw": true,
            "tk": true,
            "tr": true,
            "vi": true,
            "zh-cn": true,
            "zh-tw": true
        } );