// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.platetectonics;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Resources (images and translated strings) for "PlateTectonics" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator
 */
public class PlateTectonicsResources {
    public static final String NAME = "plate-tectonics";
    public static final PhetResources RESOURCES = new PhetResources( NAME );

    //Strings
    public static class Strings {
        public static final String COMPOSITION = RESOURCES.getLocalizedString( "composition" );
        public static final String CONTINENTAL_CRUST = RESOURCES.getLocalizedString( "continentalCrust" );
        public static final String COOL = RESOURCES.getLocalizedString( "cool" );
        public static final String MORE_IRON = RESOURCES.getLocalizedString( "moreIron" );
        public static final String MORE_SILICA = RESOURCES.getLocalizedString( "moreSilica" );
        public static final String MY_CRUST = RESOURCES.getLocalizedString( "myCrust" );
        public static final String OCEANIC_CRUST = RESOURCES.getLocalizedString( "oceanicCrust" );
        public static final String ONE_PLATE = RESOURCES.getLocalizedString( "onePlate" );
        public static final String TEMPERATURE = RESOURCES.getLocalizedString( "temperature" );
        public static final String THICK = RESOURCES.getLocalizedString( "thick" );
        public static final String THICKNESS = RESOURCES.getLocalizedString( "thickness" );
        public static final String THIN = RESOURCES.getLocalizedString( "thin" );
        public static final String TWO_PLATES = RESOURCES.getLocalizedString( "twoPlates" );
        public static final String WARM = RESOURCES.getLocalizedString( "warm" );
    }

    //Images
    public static class Images {

    }
}