// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.platetectonics;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Resources (images and translated strings) for "PlateTectonics" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator
 */
public class PlateTectonicsResources {
    public static final String NAME = "plate-tectonics";
    public static final PhetResources RESOURCES = new PhetResources( NAME );

    //Strings
    public static class Strings {
        public static final String ONE_PLATE = RESOURCES.getLocalizedString( "onePlate" );
        public static final String TWO_PLATES = RESOURCES.getLocalizedString( "twoPlates" );
    }

    //Images
    public static class Images {

    }
}