// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.platetectonics;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Resources (images and translated strings) for "PlateTectonics" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator
 */
public class PlateTectonicsResources {
    public static final String NAME = "plate-tectonics";
    public static final PhetResources RESOURCES = new PhetResources( NAME );

    //Strings
    public static class Strings {
        public static final String DOUBLE_PLATE__TITLE = RESOURCES.getLocalizedString( "doublePlate.title" );
        public static final String PLATE__TECTONICS__TITLE = RESOURCES.getLocalizedString( "plate-tectonics.title" );
        public static final String SINGLE_PLATE__TITLE = RESOURCES.getLocalizedString( "singlePlate.title" );
    }

    //Images
    public static class Images {

    }
}