//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_de.properties
define( {
            "ColorChooser.rgbBlueText": "Blau",
            "Common.time.fast": "schnell",
            "FileChooser.acceptAllFileFilterText": "Alle Dateitypen(*.*)",
            "Common.updates.youHaveCurrent": "Du hast bereits die neuste Versiion {0} von {1}.",
            "Common.updates.installer.yes": "Ja!",
            "Common.HelpMenu.AboutTitle": "Über",
            "Common.updates.versionComparison": "<html>Deine gegenwärtige Version ist \"{0}\" von {1}.<br>Eine neuere Version ({2}) ist v erfügbar.</html>",
            "Common.statistics.sim_type": "Simulationsart:",
            "Common.updates.updateAvailable": "Update verfügbar",
            "Games.label.score.max.perfect": "Score: {0} von {1}! (Perfekt!)",
            "Common.statistics.host_os_arch": "Prozessortyp:",
            "Common.HelpMenu.MegaHelpMnemonic": "m",
            "Common.title.message": "Nachricht",
            "Common.updates.progressDialogMessage": "Update von \"{0}\" auf{1}",
            "Common.statistics.user_total_sessions": "Gesamtzahl aller durchgeführten Simulationen:",
            "Common.confirm.clear.graphs": "Willst Du die Grafiken wirklich löschen?",
            "XMLPersistenceManager.save.error.encode": "<html>Datei-Speicherfehler:<br>{0}</html>",
            "Games.message.confirmNewGame": "<html>Du hast das Spiel nicht abgeschlossen.<br>Bist Du sicher, dass Du ein neues Spiel starten willst?</html>",
            "Games.button.newGame": "Neues Spiel",
            "Common.OptionsMenu": "Optionen",
            "Common.updates.updateNow": "Update jetzt!",
            "Common.About.CreditsButton": "Danksagungen...",
            "Save.confirm.message": "<html>Eine Datei mit diesem Namen ist schon vorhanden.<br>Soll sie  ersetzt werden?</html>",
            "Common.HelpPanel.HideHelp": "Hilfe verbergen",
            "Common.statistics.sim_name": "Name der Simulation:",
            "Common.FileMenu.TitleMnemonic": "d",
            "FileChooser.openDialogTitleText": "Öffnen",
            "Common.About.CreditsDialog.TranslationCreditsTitle": "Übersetzt von",
            "Common.About.OSVersion": "BS Version:",
            "XMLPersistenceManager.save.title": "Einstellungen speichern",
            "FileChooser.lookInLabelText": "Schau in:",
            "Common.statistics.message_version": "Nachrichtenversion:",
            "Common.ClockControlPanel.Rewind": "Zurückspulen",
            "Common.choice.no": "Nein",
            "XMLPersistenceManager.title.error": "Fehler",
            "Common.updates.installer.more": "Erzähl mir mehr...",
            "Common.title.warning": "Achtung",
            "FileChooser.saveButtonText": "Speichern",
            "XMLPersistenceManager.save.error.message": "<html>Datei-Schreibfehler:<br>{0}</html>",
            "Common.FileMenu.Title": "Datei",
            "XMLPersistenceManager.load.error.contents": "Die Datei ist beschädigt oder konnte nicht erzeugt werden.",
            "Common.choice.close": "Schliessen",
            "Common.rewind": "Rückspulen",
            "chart-time-control.go": "Los!",
            "Games.label.newBest": "Deine neue Bestleistung!",
            "Common.statistics.message_type": "Nachrichtenart:",
            "Games.title.gameSettings": "Spiel Einstellungen",
            "ColorChooser.sampleText": "Beispieltext Beispieltext",
            "Games.radioButton.on": "Aus",
            "Common.HelpMenu.TitleMnemonic": "h",
            "Common.statistics.user_installation_timestamp": "PhET Installationszeit",
            "Common.updates.errorNotAJar": "{0} ist keine JAR Datei.",
            "Common.title.error": "Fehler",
            "Common.FileMenu.Load": "Lade Einstellungen...",
            "Common.ClockControlPanel.Play": "Wiedergabe",
            "ColorChooser.previewText": "Vorschau",
            "Common.ModelSlider.YouEntered": "Deine Eingabe",
            "XMLPersistenceManager.save.confirm.message": "<html>Eine Datei mit diesem Namen ist schon vorhanden.<br>Soll sie  ersetzt werden?</html>",
            "Games.label.score": "Score: {0}",
            "Common.choice.cancel": "Abbrechen",
            "Common.statistics.sim_locale_country": "Land:",
            "Games.label.best": "Bestleistung: {0}",
            "Common.HelpMenu.Help": "Hilfe",
            "Common.statistics.user_preference_file_creation_time": "Zeitpunkt der Erstellung einer Voreinstellungsdatei(Preferences)",
            "Common.statistics.sim_version_timestamp": "Version der Simulation(Zeitpunkt):",
            "Common.HelpPanel.MegaHelp": "MegaHilfe...",
            "XMLPersistenceManager.load.title": "Einstellungen laden",
            "Common.ModelSlider.OutOfRange": "Außerhalb des Wertebereiches",
            "Common.FileMenu.Exit": "Beenden",
            "ControlPanel.message.confirmResetAll": "Alle Einstellungen zurücksetzen?",
            "Common.About.BuildDate": "Erstelldatum:",
            "Common.sim.speed": "...Sim.-Geschw...",
            "Common.WhiteBackground": "weißer Hintergrund",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Dieses Programm nutzt die folgenden \"3rd party\" (Fremdanbieter) - Software",
            "FileChooser.filesOfTypeLabelText": "Dateityp:",
            "Common.statistics.sim_locale_language": "Sprache:",
            "Common.updates.errorMissingJar": "<html>Dieses Update kann nicht durchgeführt werden.<br>Kann die JAR Datei nicht finden: {0}.<br>Bitte kontaktiere Deinen Systemadministrator.<br></html>",
            "ControlPanel.button.resetAll": "Alles zurücksetzen",
            "Common.preferences.privacy": "Privatsphäre",
            "FileChooser.newFolderErrorText": "Fehler beim Erstellen eines Ordners",
            "Common.updates.skipThisUpdate": "Brich die Version ab.",
            "Common.FileMenu.Save": "Speichere Einstellungen...",
            "Games.radioButton.off": "An",
            "Common.ClockControlPanel.Step": "Schritt",
            "Common.HelpMenu.Title": "Hilfe",
            "Common.HelpMenu.AboutMnemonic": "ü",
            "Common.statistics.host_java_timezone": "Zeitzone",
            "Common.HelpMenu.About": "Über...",
            "FileChooser.fileNameLabelText": "Dateiname:",
            "Common.clear": "Löschen",
            "Common.time.slow": "langsam",
            "Common.updates.progressDialogTitle": "Update läuft",
            "Common.HelpMenu.MegaHelp": "MegaHilfe...",
            "Common.About.CreditsDialog.Title": "Danksagungen",
            "Common.statistics.host_locale_language": "Host(Sprache):",
            "PhetApplication.StartupDialog.message": "\"{0}\" startet",
            "FileChooser.openButtonText": "Öffnen",
            "Common.statistics.host_locale_country": "Host(Land):",
            "Common.ErrorDialog.detailsTitle": "Fehlerdetails",
            "FileChooser.saveInLabelText": "Speichern in:",
            "Common.statistics.sim_sessions_since": "Gesamtzahl der Durchläufe dieser Simulationen seit der letzen Anmeldung:",
            "Common.BasicPhetPanel.Title": "Zurück",
            "Common.ModelSlider.Description": "Ungültiger Wert.",
            "FileChooser.saveDialogTitleText": "Speichern",
            "Common.About.WebLink": "Besuche die PhET Homepage",
            "Common.ClockControlPanel.StepBack": "Schriitt zurück",
            "Common.updates.checkForSimUpdate": "Prüfe auf Simulationsupdate...",
            "Common.statistics.sim_project": "Projektname:",
            "Common.updates.checkForInstallerUpdate": "Prüfe auf ein PhET Offline Webseiten Installer Update...",
            "Common.preferences.title": "Voreinstellungen",
            "Common.ClockControlPanel.Restart": "Neustart",
            "Common.choice.yes": "Ja",
            "ColorChooser.rgbGreenText": "Grün",
            "Common.BasicPhetPanel.LogoToolTip": "Vollbild beenden",
            "Common.updates.askMeLater": "Frag mich später",
            "Games.label.time": "Zeit {0}",
            "Common.HelpPanel.ShowHelp": "Hilfe!",
            "ColorChooser.rgbRedText": "Rot",
            "Common.updates.tryIt": "Probier die neue Version bevor Du ein Update ausführst.",
            "XMLPersistenceManager.load.error.message": "<html>Datei-Lesefehler:<br>{0}</html>",
            "message.valueOutOfRange": "Wert muss zwischen {0} und {1} liegen.",
            "Common.FileMenu.ExitMnemonic": "e",
            "Games.label.score.max": "Score: {0} von {1}",
            "Common.record": "Aufnahme",
            "Common.FileMenu.Preferences": "Voreinstellungen...",
            "XMLPersistenceManager.load.error.decode": "<html>Fehler beim Laden der Datei:<br>{0}</html>",
            "Common.title.confirm": "Bestätigen",
            "Common.HelpMenu.HelpMnemonic": "h",
            "Common.statistics.sim_total_sessions": "Gesamtzahl dieser der Durchläufe dieser Simulationen:",
            "Common.updates.automaticallyCheck": "Automatisch nach Updates suchen"
        } );