// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.buildtools.preprocessor;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.*;

import edu.colorado.phet.common.phetcommon.util.FileUtils;

import static edu.colorado.phet.common.phetcommon.util.FileUtils.filter;

/**
 * Automatically generates resource files for strings provided in the English translation file, and for images in the image directory.
 *
 * @author Sam Reid
 */
public class ResourceGenerator {
    public static void main( String[] args ) throws IOException {
        if ( args.length == 0 ) {
            System.out.println( "Usage: args[0] = full path to simulation directory" );
        }
        File simDir = new File( args[0] );
        new ResourceGenerator().generateResources( simDir );
    }

    private void generateResources( final File simDir ) throws IOException {
        final File englishFile = new File( simDir, "data/" + simDir.getName() + "/localization/" + simDir.getName() + "-strings.properties" );
        final Properties properties = new Properties() {{load( new FileReader( englishFile ) );}};
        final ArrayList<String> list = new ArrayList<String>( properties.stringPropertyNames() );
        Collections.sort( list );

        final ArrayList<String> words = new ArrayList<String>() {{
            StringTokenizer st = new StringTokenizer( simDir.getName(), "-" );
            while ( st.hasMoreElements() ) {
                add( st.nextToken() );
            }
        }};
        final String packagename = new MyStringBuilder() {{
            for ( String word : words ) {
                append( word );
            }
        }}.toString();

        final String className = new MyStringBuilder() {{
            for ( String word : words ) {
                append( upperWord( word ) );
            }
        }}.toString();

        //"public static final String AIR = getString( \"air\" );";
        final String strings = new MyStringBuilder() {{
            for ( String propertyName : properties.stringPropertyNames() ) {
                final String JAVA_FIELD_NAME = propertyName.
                        toUpperCase().
                        replace( '.', '_' ).//Careful, not invertible
                        replace( '-', '_' );
                append( "\tpublic static final String " + JAVA_FIELD_NAME + " = RESOURCES.getLocalizedString( \"" + propertyName + "\" );\n" );
            }
        }}.toString();
        final String fullClassName = className + "Resources";

        String filtered = filter( new HashMap<String, String>() {{
                                      put( "packagename", packagename );
                                      put( "classname", className );
                                      put( "simname", simDir.getName() );
                                      put( "generator", getClass().getName() );
                                      put( "strings", strings );
                                      put( "date", new Date().toString() );
                                      put( "fullclassname", fullClassName );
                                  }}, template ).trim();
        System.out.println( "filtered = \n" + filtered );

        //Store the filtered strings in the resources file
        final File destination = new File( simDir, "src/edu/colorado/phet/" + packagename + "/" + fullClassName + ".java" );
        FileUtils.writeString( destination, filtered );

        System.out.println( "Wrote to dest: " + destination.getAbsolutePath() );
    }

    class MyStringBuilder {
        String s = "";

        public void append( String string ) {
            s = s + string;
        }

        public String toString() {
            return s;
        }
    }

    private String upperWord( String word ) {
        return ( "" + word.charAt( 0 ) ).toUpperCase() + word.substring( 1 );
    }

    public static final String template = "// Copyright 2002-2011, University of Colorado\n" +
                                          "package edu.colorado.phet.@packagename@;\n" +
                                          "\n" +
                                          "import edu.colorado.phet.common.phetcommon.resources.PhetResources;\n" +
                                          "\n" +
                                          "/**\n" +
                                          " * Translated strings for \"@classname@\" are loaded eagerly to make sure everything exists on sim startup, see #2967.\n" +
                                          " * Automatically generated by @generator@ on @date@\n" +
                                          " * See #2967\n" +
                                          " */\n" +
                                          "public class @fullclassname@ {\n" +
                                          "\tprivate static final PhetResources RESOURCES = new PhetResources( \"@simname@\" );\n" +
                                          "\n" +
                                          "@strings@" +
                                          "}";
}
