//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_iw.properties
define( {
            "Games.label.level": "רמה: {0}",
            "Common.updates.errorMessage": "ארעה שגיאה במהלך תהליך העדכון.<br>אנא נסה שוב מאוחר יותר או בקר ב-{0}.",
            "XMLPersistenceManager.save.error.encode": "<html>שגיאה בקידוד הקובץ:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>שגיאה בפיענוח הקובץ:<br>{0}</html>",
            "Common.softwareAgreement.decline": "יציאה",
            "Common.statistics.host_os_name": "שם מערכת ההפעלה",
            "Common.statistics.user_total_sessions": "מספר הפעמים שכל ההדמיות הופעלו",
            "Common.statistics.host_java_version_major": "גרסת ג'אווה (ראשית)",
            "FileChooser.openDialogTitleText": "פתח",
            "Common.statistics.host_java_version_maintenance": "גרסת ג'אווה (תחזוקה)",
            "FileChooser.lookInLabelText": "חפש ב",
            "Common.choice.cancel": "בטל",
            "Common.updates.seePreferences": "לך אל קובץ->העדפות על מנת לשנות את ההעדפות שלך.",
            "Common.About.CreditsDialog.software-development": "פיתוח תוכנה",
            "Common.About.JavaVersion": "גרסת ג'אווה: ",
            "ColorChooser.resetText": "אפס",
            "wavelength.ir": "תת-אדום",
            "Common.About.CreditsDialog.design-team": "צוות עיצוב",
            "Common.statistics.sim_total_sessions": "מספר הפעמים שהדמיה זו הופעלה ",
            "Games.title.gameSettings": "הגדרות המשחק",
            "XMLPersistenceManager.save.title": "שמור קונפיגורציה",
            "XMLPersistenceManager.load.error.contents": "קובץ לא תקין \ לא נוצר ע\"י הדמיה זו.",
            "Common.statistics.details.title": "מידע",
            "Common.statistics.sim_dev_version": "גרסת הדמיה (פיתוח)",
            "FileChooser.saveInLabelText": "שמור ב",
            "Common.statistics.sim_name": "שם הדמיה",
            "Save.confirm.message": "<html>הקובץ שבחרת כבר קיים.<br>האם ברצונך להחליף אותו בקובץ המיועד לשמירה?</html>",
            "Games.label.score": "ניקוד: {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "צוות פיתוח PhET",
            "Games.button.start": "התחל!",
            "Common.statistics.sim_deployment": "סוג פיתוח",
            "Common.FileMenu.Save": "שמור קונפיגורציה...",
            "ColorChooser.hsbSaturationText": "רוויה",
            "Games.radioButton.on": "דולק",
            "FileChooser.acceptAllFileFilterText": "כל הקבצים (*.*)",
            "ColorChooser.hsbNameText": "גוון - רוויה - בהירות",
            "Common.ModelSlider.Minimum": "מינימום",
            "Common.FileMenu.Preferences": "העדפות...",
            "Common.FileMenu.Load": "טען קונפיגורציה...",
            "Common.updates.downloadingSimJar": "מוריד קובץ JAR להדמיה",
            "Games.radioButton.off": "כבוי",
            "ColorChooser.swatchesRecentText": "לאחרונה",
            "Common.updates.updateAvailable": "קיים עדכון",
            "Common.statistics.host_locale_language": "שפת אירוח",
            "Common.clear": "נקה",
            "Games.title.gameOver": "המשחק נגמר",
            "FileChooser.filesOfTypeLabelText": "סוגי קבצים",
            "Common.ErrorDialog.detailsTitle": "פרטי שגיאה",
            "Common.HelpMenu.MegaHelp": "מגה-עזרה...",
            "Common.ClockControlPanel.Step": "צעד",
            "Common.statistics.sim_revision": "גרסת הדמיה (שיפור)",
            "Common.choice.yes": "כן",
            "Common.FileMenu.Title": "קובץ",
            "Common.value_units": "{0} {1}",
            "Common.statistics.sim_dev": "האם זאת גרסת מפתח?",
            "Common.updates.installer.message": "<html>תאריך ההתקנה הלא מקוונת שלך של PhET הוא {0}.<br>קיימת גרסה חדשה יותר מתאריך {1}.<br><br>האם ברצונך להוריד את תכנת ההתקנה הלא מקוונת האחרונה?</html>",
            "Common.updates.updateNow": "עדכן עתה",
            "Common.record": "הקלט",
            "Common.About.CreditsDialog.Title": "תודות",
            "Common.updates.error.internetConnection": "<html>אין אפשרות להתחבר ל-{0}.<br>אנא בדוק את החיבור לאינטרנט שלך.</html>",
            "Common.time.fast": "מהר",
            "XMLPersistenceManager.load.error.message": "<html>שגיאה בקריאה מקובץ:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "מקסימום",
            "Common.OptionsMenu": "אפשרויות",
            "Common.ClockControlPanel.Restart": "התחל מחדש",
            "Common.statistics.sim_version_timestamp": "גרסת הדמיה (חותמת זמן)",
            "Common.updates.installer.yes": "כן!",
            "Common.phetInstaller": "בצורה לא מקוונת PhET תוכנת התקנת אתר",
            "Common.HelpMenu.About": "אודות...",
            "Common.ModelSlider.OutOfRange": "ערך מחוץ לתחום",
            "ColorChooser.previewText": "תצוגה מקדימה",
            "Common.BasicPhetPanel.Title": "חזור",
            "Common.HelpPanel.HideHelp": "הסתר עזרה",
            "Common.statistics.host_os_arch": "סוג מעבד",
            "Common.preferences.title": "העדפות",
            "Games.button.newGame": "משחק חדש",
            "ColorChooser.hsbRedText": "אדום",
            "ColorChooser.hsbBlueText": "כחול",
            "Common.ModelSlider.YouEntered": "הקלדת ",
            "Games.label.newBest": "שיא חדש!",
            "Common.About.BuildDate": "תאריך בנייה",
            "Games.label.best": "שיא: {0}",
            "Common.statistics.sim_project": "שם פרויקט",
            "Common.updates.downloadingBootstrap": "מוריד updater bootstrap ...",
            "Common.title.error": "שגיאה",
            "Common.FileMenu.Exit": "יציאה",
            "Common.statistics.sim_major_version": "גרסת הדמיה (ראשית)",
            "Common.updates.askMeLater": "שאל מאוחר יותר",
            "chart-time-control.go": "התחל!",
            "Common.confirm.clear.graphs": "האם את(ה) בטוח(ה) שברצונך לנקות את הגרפים?",
            "ColorChooser.swatchesNameText": "דוגמאות",
            "Common.updates.progressDialogMessage": "מעדכן את \"{0}\" לגרסה {1}.",
            "Common.updates.installer.more": "ספר לי יותר ...",
            "XMLPersistenceManager.title.error": "שגיאה",
            "ColorChooser.hsbHueText": "גוון",
            "ControlPanel.button.resetAll": "אפס הכל",
            "Common.About.AgreementButton": "הסכם תוכנה",
            "Common.ErrorDialog.detailsButton": "פרטים...",
            "Common.updates.errorMissingJar": "<html>לא ניתן לבצע את העדכון.<br>קובץ JAR בשם {0} לא נמצא.<br>לקבלת עזרה פנה למנהל המערכת שלך.<br></html>",
            "Common.preferences.privacy": "פרטיות",
            "Common.HelpMenu.AboutTitle": "אודות",
            "ColorChooser.rgbRedText": "אדום",
            "Common.statistics.sim_locale_country": "ארץ",
            "ColorChooser.hsbGreenText": "ירוק",
            "ColorChooser.rgbGreenText": "ירוק",
            "Games.format.time.best": "{0} ({1})",
            "Common.HelpPanel.ShowHelp": "הצילו !",
            "Common.statistics.sim_distribution_tag": "גרסת הדמיה (הפצה)",
            "Common.statistics.description": "אנו מעמידים לרשותכם את PhET בחינם בזכות <br> מענקים שמחייבים אותנו לאסוף כמות מינימלית של <br> <a href=\"{0}\">מידע</a> אנונימי<br>כדי שנוכל לתעד את כמות השימוש בהדמיות PhET<br>וכדי שנוכל לשרת טוב יותר את קהל המשתמשים.",
            "Common.softwareAgreement.message": "בכל הדמיות ה-PhET אנו אוספים כמות מינימלית<br>של <a href=\"{0}\">מידע</a>  בכל פעם שהדמיה מאתחלת<br>(למשל: גרסת הדמיה, מערכת הפעלה).<br>תוכל לבטל את שליחת המידע הזה<br>בכל עת דרך התפריט קובץ->העדפות.<br><br>באמצעות לחיצה על \"הסכם והמשך\" הנך מביע הסכמה<br>להסכם התוכנה של PhET כולל מדיניות הפרטיות שלנו<br>בקשר להדמיה זו ולכל הדמית PhET אחרת שתפעיל.<br>(לפרטים לחץ  <a href=\"{1}\">כאן</a>).",
            "Common.choice.ok": "OK",
            "Common.About.Version": "גרסה: ",
            "Common.ErrorDialog.contactPhet": "אם בעיה זו תתמיד, שלח פרטים אל {0}.",
            "Common.About.CreditsDialog.lead-design": "פיתוח ראשי",
            "Common.statistics.user_preference_file_creation_time": "חותמת זמן של הגדרת העדפות ",
            "Common.updates.errorWritePermissions": "<html>לא ניתן לבצע את העדכון.<br>אינך רשאי לכתוב ל-{0}.<br>לקבלת עזרה פנה למנהל המערכת שלך.<br></html>",
            "ColorChooser.hsbBrightnessText": "בהירות",
            "Common.choice.no": "לא",
            "Common.About.WebLink": "PhET בקרו בעמוד הבית של",
            "Common.About.OSVersion": "גרסת מערכת הפעלה: ",
            "Common.updates.versionComparison": "<html>גרסתך הנוכחית של \"{0}\" היא {1}.<br>קיימת גרסה חדשה יותר ({2}).</html>",
            "Common.statistics.sim_locale_language": "שפה",
            "Common.statistics.user_installation_timestamp": "התקנת PhET (חותמת זמן)",
            "Common.statistics.message_version": "גרסת הודעה",
            "Common.ModelSlider.Description": "ערך בלתי-חוקי",
            "Common.updates.installer.moreMessage": "<html>אם תשמור על התקנת PhET הלא-מקוונת שלך מעודכנת<br>תהיה לך גישה להדמיות PhET החדשות ביותר<br>ולחומרי עזר השונים.<br><br>אם תבחר להוריד את הגרסה החדשה ביותר, דפדפן <br>יפתח את אתר PhET, שממנו תוכל להוריד<br>את תוכנת ההתקנה הלא-מקוונת של PhET.</html>",
            "ControlPanel.message.confirmResetAll": "לאפס הכל?",
            "Common.HelpMenu.Help": "עזרה",
            "Common.updates.errorNotAJar": "{0} אינו קובץ JAR.",
            "Games.label.levelControl": "רמה:",
            "Common.updates.automaticallyCheck": "בדיקת עדכונים אוטומטית",
            "Common.sim.speed": "...מהירות סימולציה...",
            "Common.updates.checkForSimUpdate": "בדוק האם קיים עדכון להדמיה זו...",
            "XMLPersistenceManager.save.confirm.message": "<html>הקובץ שבחרת כבר קיים.<br>האם ברצונך להחליף אותו בקובץ המיועד לשמירה?</html>",
            "FileChooser.newFolderErrorText": "שגיאה ביצירת תיקיה חדשה",
            "Common.updates.skipThisUpdate": "דלג על גרסה זו",
            "Common.About.CreditsButton": "תודות",
            "FileChooser.saveDialogTitleText": "שמור",
            "XMLPersistenceManager.load.title": "טען קונפיגורציה",
            "Common.updates.checkForInstallerUpdate": "בדוק האם קיים עדכון ל-PhET Offline Web Installer...",
            "timeseries.control.panel.playback": "הצגה חוזרת",
            "Common.updates.progressDialogTitle": "מעדכן",
            "Common.HelpMenu.Title": "עזרה",
            "FileChooser.fileNameLabelText": "שם הקובץ",
            "ColorChooser.rgbNameText": "אדום-ירוק-כחול",
            "Common.softwareAgreement.title": "הסכם תוכנה",
            "Common.statistics.host_java_version_minor": "גרסת ג'אווה (משנית)",
            "Common.About.CreditsDialog.interviews": "ראיונות",
            "Common.About.Distribution": "הפצה: ",
            "Common.statistics.host_java_webstart_version": "JAVA Web Start גרסת",
            "XMLPersistenceManager.save.error.message": "<html> שגיאה בכתיבה לקובץ: <br>{0}</html>",
            "Games.label.time": "זמן: {0}",
            "FileChooser.openButtonText": "פתח",
            "Common.statistics.details.description": "<html>המידע שמופיע למטה יישלח ל-PhET בכל פעם שההדמיה תאתחל.</html>",
            "ColorChooser.sampleText": "טקסט לדוגמה טקסט לדוגמה ",
            "Common.statistics.host_os_version": "גרסת מערכת ההפעלה",
            "Common.title.confirm": "אשר",
            "Games.label.score.max": "ניקוד: {0} מתוך {1}",
            "Common.BasicPhetPanel.LogoToolTip": "בטל מסך מלא",
            "Common.statistics.host_java_timezone": "אזור זמן",
            "Common.time.slow": "איטי",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.ClockControlPanel.Rewind": "החזר להתחלה",
            "Common.softwareAgreement.accept": "קבל והמשך",
            "Common.updates.updateToDate": "מעודכן",
            "Common.ClockControlPanel.Pause": "הפסק",
            "PhetApplication.StartupDialog.message": "\"{0}\" מאתחל.",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "תוכנית זו עושה שימוש בתוכנות צד שלישי הבאות",
            "XMLPersistenceManager.message.notAConfigFile": "קובץ זה אינו מכיל קונפיגורציה עבור הדמיה זו.",
            "Common.preferences.updates": "עדכונים",
            "Games.label.score.max.perfect": "ניקוד: {0} מתוך {1} (מושלם!)",
            "Common.statistics.enabled": "PhET אפשר שליחת מידע ל",
            "Common.StopwatchPanel.stop": "עצור",
            "Common.HelpPanel.MegaHelp": "מגה-עזרה...",
            "Common.statistics.host_locale_country": "ארץ אירוח",
            "Common.StopwatchPanel.reset": "אפס",
            "Common.playback": "הצגה חוזרת",
            "Games.message.confirmNewGame": "<html>לא סיימת את המשחק.<br>אתה בטוח שאתה רוצה להתחיל משחק חדש?</html>",
            "Common.statistics.sim_minor_version": "גרסת הדמיה (משנית)",
            "Common.updates.tryIt": "נסה גרסה חדשה לפני עדכון.",
            "ColorChooser.rgbBlueText": "כחול",
            "Common.choice.close": "סגור",
            "Common.ClockControlPanel.Play": "התחל",
            "Common.statistics.sim_type": "סוג הדמיה",
            "FileChooser.saveButtonText": "שמור",
            "Common.rewind": "החזר להתחלה",
            "Common.StopwatchPanel.start": "התחל",
            "Common.updates.youHaveCurrent": "בידיך נמצאת הגרסה המעודכנת ביותר ({0}) של {1}.",
            "Common.statistics.sim_sessions_since": "מספר הפעמים שהדמיה זו הופעלה מאז השימוש המקוון האחרון ",
            "Common.statistics.host_java_vendor": "משווק גיאווה",
            "charts.show-graphs": "הראה גרפים: ",
            "Common.statistics.message_type": "סוג הודעה"
        } );