//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_lv.properties
define( {
            "Games.label.level": "Līmenis: {0}",
            "Common.updates.errorMessage": "Radās kļūda, veicot atjaunināšanu.<br>Lūdzu, vēlāk mēģiniet vēlreiz vai apmeklējiet {0}.",
            "XMLPersistenceManager.save.error.encode": "<html>Kļūda kodējot failu:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Kļūda atkodējot failu:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "f",
            "Common.softwareAgreement.decline": "Iziet",
            "Common.statistics.host_os_name": "Operētājsistēmas nosaukums:",
            "Common.statistics.user_total_sessions": "Kopējais visu simulāciju palaišanas reižu skaits:",
            "Common.statistics.host_java_version_major": "Java versija (galvenā):",
            "FileChooser.openDialogTitleText": "Atvērt",
            "Common.WhiteBackground": "Balts fons",
            "Common.statistics.host_java_version_maintenance": "Java versija (uzturēšanas):",
            "FileChooser.lookInLabelText": "Meklēt iekš:",
            "Common.choice.cancel": "Atcelt",
            "Common.updates.seePreferences": "Ejiet uz Fails->Iestatījumi. lai manītu iestatījumus.",
            "Common.About.CreditsDialog.software-development": "Programmatūras izstrāde",
            "Common.About.JavaVersion": "Java versija:",
            "ColorChooser.resetText": "Atiestatīt",
            "wavelength.ir": "IR",
            "translation.credits": "Arvis Lācis (@arvislacis)",
            "Common.About.CreditsDialog.design-team": "Dizaina komanda",
            "Common.statistics.sim_total_sessions": "Kopējais simulācijas palaišanas reižu skaits:",
            "Common.FileMenu.PreferencesMnemonic": "i",
            "wavelength.uv": "UV",
            "Games.title.gameSettings": "Spēles iestatījumi",
            "XMLPersistenceManager.save.title": "Saglabāt konfigurāciju",
            "XMLPersistenceManager.load.error.contents": "Fails ir bojāts vai arī netika izveidots, izmantojot šo simulāciju.",
            "Common.statistics.details.title": "Informācija",
            "Common.statistics.sim_dev_version": "Simulācijas versija (izstr.):",
            "FileChooser.saveInLabelText": "Saglabāt iekš:",
            "Common.statistics.sim_name": "Simulācijas nosaukums:",
            "Save.confirm.message": "<html>Izvēlētais fails jau eksistē.<br>Vai vēlaties to aizstāt ar failu, ko pašlaik saglabājat?</html>",
            "Games.label.score": "Rezultāts: {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "PhET izstrādes komanda",
            "Games.button.start": "Sākt",
            "Common.statistics.sim_deployment": "Izvietošanas veids:",
            "Common.FileMenu.Save": "Saglabāt konfigurāciju...",
            "Common.About.CreditsDialog.licenseDetails": "Licences informācija",
            "ColorChooser.hsbSaturationText": "P",
            "Games.radioButton.on": "ieslēgts",
            "FileChooser.acceptAllFileFilterText": "Visi faili (*.*)",
            "ColorChooser.hsbNameText": "NPG",
            "Common.ModelSlider.Minimum": "Minimums",
            "Common.FileMenu.Preferences": "Iestatījumi...",
            "Common.FileMenu.Load": "Ielādēt konfigurāciju...",
            "Common.updates.downloadingSimJar": "lejupielādē simulācijas JAR failu...",
            "Games.radioButton.off": "izslēgts",
            "ColorChooser.swatchesRecentText": "Nesenie:",
            "Common.updates.updateAvailable": "Pieejams atjauninājums",
            "Common.statistics.host_locale_language": "Resursdatora valoda:",
            "Common.clear": "Notīrīt",
            "Games.title.gameOver": "Spēle beigusies",
            "FileChooser.filesOfTypeLabelText": "Faili no veida:",
            "Common.ErrorDialog.detailsTitle": "Kļūdas informācija",
            "Common.HelpMenu.MegaHelp": "Lielā palīdzība...",
            "Common.ClockControlPanel.Step": "Solis",
            "Common.statistics.sim_revision": "Simulācijas versija (pārskatīšanas):",
            "Common.choice.yes": "Jā",
            "Common.FileMenu.Title": "Fails",
            "Common.value_units": "{0} {1}",
            "Common.statistics.sim_dev": "Vai šī ir izstrādātāja versija?:",
            "Common.updates.installer.message": "<html>PhET bezsaites mājas lapas instalācijas versija datēta {0}.<br>Ir pieejama jaunāka versija, datēta {1}.<br><br>Vai vēlaties iegūt visjaunāko PhET bezsaites mājas lapas instalatora versiju?</html>",
            "Common.updates.updateNow": "Atjaunināt tagad!",
            "Common.record": "Ierakstīt",
            "Common.About.CreditsDialog.Title": "Autori",
            "Common.updates.error.internetConnection": "<html>Nevar savienoties ar {0},<br>lūdzu, pārbaudiet interneta savienojumu.</html>",
            "Common.time.fast": "ātrs",
            "XMLPersistenceManager.load.error.message": "<html>Kļūda nolasot failu:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Maksimums",
            "Common.OptionsMenu": "Opcijas",
            "Common.ClockControlPanel.Restart": "Atsākt",
            "Common.statistics.sim_version_timestamp": "Simulācijas versija (laikspiedogs):",
            "Common.updates.installer.yes": "Jā!",
            "Common.phetInstaller": "PhET bezsaites mājas lapas instalators",
            "Common.HelpMenu.About": "Par...",
            "Common.ModelSlider.OutOfRange": "Vērtība ārpus diapazona",
            "Common.About.CreditsDialog.TranslationCreditsTitle": "Iztulkojis",
            "ColorChooser.previewText": "Priekšskatījums",
            "Common.BasicPhetPanel.Title": "Atgriezties",
            "Common.HelpPanel.HideHelp": "Slēpt palīdzību",
            "Common.statistics.host_os_arch": "Procesora veids:",
            "Common.preferences.title": "Iestatījumi",
            "Games.button.newGame": "Jauna spēle",
            "ColorChooser.hsbRedText": "S",
            "ColorChooser.hsbBlueText": "Z",
            "Common.ModelSlider.YouEntered": "Jūs ievadījāt",
            "Games.label.newBest": "Jauns labākais rezultāts!",
            "Common.About.BuildDate": "Laidiena datums:",
            "Common.FileMenu.ExitMnemonic": "z",
            "Common.statistics.sim_project": "Projekta nosaukums:",
            "Games.label.best": "Labākais rezultāts: {0}",
            "Common.title.message": "Ziņa",
            "Common.updates.downloadingBootstrap": "lejupielādē nepieciešamo informāciju...",
            "Common.title.error": "Kļūda",
            "Common.FileMenu.Exit": "Iziet",
            "Common.statistics.sim_major_version": "Simulācijas versija (galvenā):",
            "Common.updates.askMeLater": "Jautāt vēlāk",
            "chart-time-control.go": "Aiziet!",
            "Common.HelpMenu.HelpMnemonic": "p",
            "Common.confirm.clear.graphs": "Vai tiešām vēlaties notīrīt grafikus?",
            "ColorChooser.swatchesNameText": "Paraugi",
            "Common.updates.progressDialogMessage": "Atjaunina \"{0}\" uz versiju {1}",
            "Common.updates.installer.more": "Papildu informācija...",
            "XMLPersistenceManager.title.error": "Kļūda",
            "ColorChooser.hsbHueText": "N",
            "ControlPanel.button.resetAll": "Atiestatīt visu",
            "Common.About.AgreementButton": "Programmatūras vienošanās...",
            "Common.FileMenu.Load.mnemonic": "k",
            "Common.ErrorDialog.detailsButton": "Sīkāka informācija...",
            "Common.updates.errorMissingJar": "<html>Atjauninājums nevar tikt veikts.<br>Nevar saglabāt JAR failu: {0}.<br>Lūdzu, sazinieties ar savas sistēmas administratoru, lai iegūtu palīdzību.<br></html>",
            "Common.preferences.privacy": "Privātums",
            "Common.HelpMenu.AboutTitle": "Par",
            "ColorChooser.rgbRedText": "Sarkans",
            "Common.statistics.sim_locale_country": "Valsts:",
            "ColorChooser.hsbGreenText": "Z",
            "ColorChooser.rgbGreenText": "Zaļš",
            "Games.format.time.best": "{0} ({1})",
            "Common.HelpPanel.ShowHelp": "Palīdzība!",
            "Common.statistics.sim_distribution_tag": "Simulācijas versija (distribūcija):",
            "Common.statistics.description": "PhET ir brīvi pieejams pateicoties dotācijām,<br>kas liek mums ievākt nelielu anonīmas<br><a href=\"{0}\">informācijas</a> daudzumu, lai palīdzētu datēt<br>PhET simulāciju izmantošanas apjomus<br>un lai mūsu lietotājiem sniegtu labāko.",
            "Common.softwareAgreement.message": "Visās PhET simulācijās mēs ievācam nelielu<br>anonīmas <a href=\"{0}\">informācijas</a> daudzumu, katru reizi, kad simulācija tiek palaista<br>(piem., simulācijas versija, operētājsistēma).<br>Jūs jebkurā laikā varat izslēgt šīs informācijas<br>sūtīšanu, izmantojot Fails->Iestatījumi izvēlnes vienumu.<br><br>Nospiežot \"Piekrist un turpināt\", jūs piekrītat PhET<br>programmatūras vienošanās līgumam, ieskaitot mūsu privāto politiku,<br>šo un katru reizi, kad palaižat PhET simulācijas.<br>(Lai saņemtu sīkāku informāciju, noklikšķiniet <a href=\"{1}\">šeit</a>).",
            "Common.choice.ok": "Labi",
            "Common.About.Version": "Versija:",
            "Common.ErrorDialog.contactPhet": "Ja šī problēma atkārtojas, nosūtīet zemāk redzamo informāciju {0}",
            "Common.About.CreditsDialog.lead-design": "Galvenais dizains",
            "Common.OptionsMenu.mnemonic": "o",
            "Common.statistics.user_preference_file_creation_time": "Iestatījuma faila izveidošanas laikspiedogs:",
            "Common.HelpMenu.AboutMnemonic": "a",
            "Common.updates.errorWritePermissions": "<html>Atjauninājums nevar tikt veikts.<br>Jums nav nepieciešamo tiesību, lai ierakstītu {0}.<br>Lūdzu, sazinieties ar savas sistēmas administratoru, lai iegūtu palīdzību.<br></html>",
            "ColorChooser.hsbBrightnessText": "G",
            "Common.choice.no": "Nē",
            "Common.About.WebLink": "Apmeklēt PhET mājas lapu",
            "Common.About.OSVersion": "OS versija:",
            "Common.title.warning": "Brīdinājums",
            "Common.updates.versionComparison": "<html>Pašreizējā \"{0}\" versija ir {1}.<br>Ir pieejama jaunāka ({2}) versija.</html>",
            "Common.statistics.sim_locale_language": "Valoda:",
            "Common.statistics.user_installation_timestamp": "PhET instalācijas laikspiedogs:",
            "Common.statistics.message_version": "Ziņas versija:",
            "Common.ModelSlider.Description": "Nederīga vērtība.",
            "Common.updates.installer.moreMessage": "<html>Nodrošinot jūsu PhET bezsaites mājas lapas instalācijas visjaunāko versiju,<br>nodrošinās arī to, ka jums ir pieejamas visjaunākās PhET simulācijas<br>un papildu materiāli.<br><br>Ja izvēlēsieties iegūt visjaunāku versiju, pārlūkprogramma <br>atvērs PhET mājas lapu, kurā varēsiet lejupielādēt<br>PhET bezsaites mājas lapas instalatoru.</html>",
            "ControlPanel.message.confirmResetAll": "Atiestatīt visus iestatījumus?",
            "Common.HelpMenu.Help": "Palīdzība",
            "Common.updates.errorNotAJar": "{0} nav JAR fails.",
            "Games.label.levelControl": "Līmenis:",
            "Common.updates.automaticallyCheck": "Automātiski pārbaudīt atjauninājumus",
            "Common.sim.speed": "...sim. ātrums...",
            "Common.updates.checkForSimUpdate": "Pārbaudīt simulācijas versiju...",
            "XMLPersistenceManager.save.confirm.message": "<html>Izvēlētais fails jau eksistē.<br>Vai vēlaties to aizstāt ar failu, ko pašlaik saglabājat?</html>",
            "FileChooser.newFolderErrorText": "Kļūda izveidojot jaunu mapi",
            "Common.About.CreditsButton": "Autori...",
            "Common.updates.skipThisUpdate": "Izlaist šo versiju",
            "Common.FileMenu.Save.mnemonic": "s",
            "FileChooser.saveDialogTitleText": "Saglabāt",
            "XMLPersistenceManager.load.title": "Ielādēt konfigurāciju",
            "Common.updates.checkForInstallerUpdate": "Pārbaudīt PhET bezsaites mājas lapas instalatora versiju...",
            "timeseries.control.panel.playback": "Atskaņošana",
            "Common.updates.progressDialogTitle": "Atjaunina",
            "Common.HelpMenu.Title": "Palīdzība",
            "ColorChooser.rgbNameText": "SZZ",
            "FileChooser.fileNameLabelText": "Faila nosaukums:",
            "Common.softwareAgreement.title": "Programmatūras vienošanās",
            "Common.statistics.host_java_version_minor": "Java apakšversija:",
            "Common.HelpMenu.TitleMnemonic": "b",
            "Common.About.CreditsDialog.interviews": "Intervijas",
            "Common.About.Distribution": "Distribūcija:",
            "Common.statistics.host_java_webstart_version": "Java tīmekļa palaišanas versija:",
            "XMLPersistenceManager.save.error.message": "<html>Kļūda ierakstot failā:<br>{0}</html>",
            "Games.label.time": "Laiks: {0}",
            "FileChooser.openButtonText": "Atvērt",
            "ColorChooser.sampleText": "Teksta paraugs Teksta paraugs",
            "Common.statistics.details.description": "<html>Zemāk redzamā informācija tiks nosūtīta PhET serverim katru reizi, kad simulācija tiks palaista.</html>",
            "Common.statistics.host_os_version": "Operētājsistēmas versija:",
            "Common.title.confirm": "Turpināt",
            "Common.BasicPhetPanel.LogoToolTip": "Izslēgt pilno rāmi",
            "Games.label.score.max": "Rezultāts: {0} no {1}",
            "Common.statistics.host_java_timezone": "Laika zona:",
            "Common.time.slow": "lēns",
            "FileChooser.newFolderErrorSeparator": ": ",
            "Common.ClockControlPanel.Rewind": "Attīt",
            "Common.softwareAgreement.accept": "Piekrist un turpināt",
            "message.valueOutOfRange": "Vērtībai jāatrodas starp {0} un {1}.",
            "Common.updates.updateToDate": "Visjaunākā",
            "Common.ClockControlPanel.Pause": "Pauze",
            "PhetApplication.StartupDialog.message": "\"{0}\" sāk savu darbību",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Šī programma izmanto sekojošo trešo-pušu programmatūru",
            "XMLPersistenceManager.message.notAConfigFile": "Fails nesatur konfigurācijas informāciju šai simulācijai.",
            "Common.preferences.updates": "Atjauninājumi",
            "Games.label.score.max.perfect": "Rezultāts: {0} no {1} (Izcili!)",
            "Common.HelpMenu.MegaHelpMnemonic": "l",
            "Common.statistics.enabled": "Atļaut sūtīt informāciju PhET serverim",
            "Common.ClockControlPanel.StepBack": "Solis atpakaļ",
            "Common.StopwatchPanel.stop": "Apturēt",
            "Common.HelpPanel.MegaHelp": "Lielā palīdzība...",
            "Common.statistics.host_locale_country": "Resursdatora valsts:",
            "Common.StopwatchPanel.reset": "Atiestatīt",
            "Common.playback": "Atskaņošana",
            "Common.statistics.sim_minor_version": "Simulācijas apakšversija:",
            "Games.message.confirmNewGame": "<html>Jūs neesat pabeidzis šo spēli.<br>Vai tiešām vēlaties sākt jaunu spēli?</html>",
            "Common.updates.tryIt": "Izmēģiniet jauno versiju pirms atjaunināšanas.",
            "ColorChooser.rgbBlueText": "Zils",
            "Common.choice.close": "Aizvērt",
            "Common.ClockControlPanel.Play": "Atskaņot",
            "Common.statistics.sim_type": "Simulācijas veids:",
            "FileChooser.saveButtonText": "Saglabāt",
            "Common.rewind": "Attīt",
            "Common.StopwatchPanel.start": "Sākt",
            "Common.updates.youHaveCurrent": "Jums pašlaik ir visjaunākā ({0}) {1} versija.",
            "Common.statistics.sim_sessions_since": "Simulācijas palaišanas reižu skaits kopš pēdējā tiešsaistes savienojuma:",
            "Common.statistics.host_java_vendor": "Java izstrādātājs:",
            "charts.show-graphs": "Rādīt grafikus:",
            "Common.statistics.message_type": "Ziņas veids:"
        } );