//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_pt.properties
define( {
            "Games.label.levelControl": "Nível:",
            "Common.About.LicenseDialog.Title": "Licença",
            "XMLPersistenceManager.save.error.xmlencoder": "XML encoding failed.",
            "Common.HelpMenu.AboutTitle": "Sobre",
            "Common.choice.ok": "OK",
            "Games.label.score.max.perfect": "Resultado: {0} em {1} (PERFEITO)",
            "Common.FileMenu.Save.mnemonic": "S",
            "Common.HelpMenu.MegaHelpMnemonic": "m",
            "XMLPersistenceManager.save.error.encode": "<html>Error encoding file:<br>{0}</html>",
            "Games.message.confirmNewGame": "<html>Não terminou este jogo.<br>Pretende iniciar um novo jogo?</html>",
            "Games.button.newGame": "Novo Jogo",
            "Common.OptionsMenu": "Opções",
            "Common.About.CreditsButton": "Créditos...",
            "Save.confirm.message": "<html>O nome do arquivo que você escolheu já existe.<br>Você quer substituir pelo arquivo que você está salvando?</html>",
            "Common.HelpPanel.HideHelp": "Ocultar Ajuda",
            "Common.FileMenu.TitleMnemonic": "f",
            "XMLPersistenceManager.save.title": "Salvar as configurações",
            "Common.choice.no": "N?o",
            "XMLPersistenceManager.title.error": "Erro",
            "XMLPersistenceManager.save.error.message": "<html>Error writing to file:<br>{0}</html>",
            "Common.OptionsMenu.mnemonic": "O",
            "Common.FileMenu.Title": "Arquivo",
            "XMLPersistenceManager.load.error.contents": "O arquivo é corrompido ou não foi interpretado por esta simulação.",
            "Games.label.newBest": "NOVO RECORD",
            "Games.title.gameSettings": "Definições do Jogo",
            "XMLPersistenceManager.message.notAConfigFile": "Este arquivo não possui configuração compatível com esta simulação.",
            "Games.radioButton.on": "ligar",
            "Common.HelpMenu.TitleMnemonic": "h",
            "Common.ModelSlider.Maximum": "Máximo",
            "Common.FileMenu.Load": "Carregar configuração...",
            "Common.ClockControlPanel.Play": "Iniciar",
            "Common.ModelSlider.YouEntered": "Você entrou",
            "XMLPersistenceManager.save.confirm.message": "<html>O nome do arquivo que você escolheu já existe.<br>Você quer substituir pelo arquivo que você está salvando?</html>",
            "Games.label.score": "Resultado: {0}",
            "Common.choice.cancel": "Cancelar",
            "Common.ClockControlPanel.Pause": "Pausa",
            "Games.label.best": "O Melhor: {0}",
            "Common.HelpMenu.Help": "Ajuda",
            "Common.HelpPanel.MegaHelp": "Grande Ajuda...",
            "XMLPersistenceManager.load.title": "Carregar as configurações",
            "Common.ModelSlider.Minimum": "Minimo",
            "Common.ModelSlider.OutOfRange": "Valor fora da escala",
            "ControlPanel.message.confirmResetAll": "Reiniciar todos os ajustes?",
            "Common.FileMenu.Exit": "Sair",
            "Common.StopwatchPanel.start": "Iniciar",
            "ControlPanel.button.resetAll": "Reiniciar tudo",
            "Games.radioButton.off": "desligar",
            "Common.FileMenu.Save": "Salvar configuração...",
            "Common.HelpMenu.Title": "Ajuda",
            "Common.ClockControlPanel.Step": "Passo a passo",
            "Common.HelpMenu.About": "Sobre...",
            "Common.HelpMenu.AboutMnemonic": "a",
            "Games.label.level": "Nível: {0}",
            "Common.HelpMenu.MegaHelp": "Grande Ajuda...",
            "PhetApplication.StartupDialog.message": "\"{0}\" está a iniciar",
            "Common.About.CreditsDialog.Title": "Créditos",
            "Common.StopwatchPanel.stop": "Parar",
            "Common.BasicPhetPanel.Title": "Retornar",
            "Common.ModelSlider.Description": "Valor Ilegal.",
            "Common.About.WebLink": "Visite a Homepage PhET",
            "Games.button.start": "Iniciar!",
            "Common.FileMenu.Load.mnemonic": "L",
            "Common.About.Version": "Versão:",
            "Common.ClockControlPanel.Restart": "Reiniciar",
            "Common.About.LicenseButton": "Licença...",
            "Common.choice.yes": "Sim",
            "Games.label.time": "Tempo: {0}",
            "Common.BasicPhetPanel.LogoToolTip": "Desabilitar toda a estrutura",
            "Games.title.gameOver": "Jogo Terminado",
            "Common.About.OKButton": "OK",
            "Common.About.JavaVersion": "Java Versão:",
            "Common.HelpPanel.ShowHelp": "Ajuda!",
            "Common.StopwatchPanel.reset": "Recomeçar",
            "XMLPersistenceManager.load.error.message": "<html>Error reading from file:<br>{0}</html>",
            "Common.FileMenu.ExitMnemonic": "x",
            "Games.label.score.max": "Resultado: {0} em {1}",
            "XMLPersistenceManager.load.error.decode": "<html>Error decoding file:<br>{0}</html>",
            "Common.title.confirm": "Confirmar",
            "Common.HelpMenu.HelpMnemonic": "h"
        } );