//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_sq.properties
define( {
            "Games.label.level": "Niveli: {0}",
            "Common.updates.errorMessage": "Gjatë tentativave për azhornim u gjet një gabim.<br>Ju lutemi, provoni më vonë, ose vizitoni {0}.",
            "XMLPersistenceManager.save.error.encode": "<html>Gabim gjatë kodimit të skedarit:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>Gabim gjatë dekodimit të skedarit:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "f",
            "Common.softwareAgreement.decline": "Dil",
            "Common.statistics.host_os_name": "Emri i sistemit të shfrytëzimit:",
            "Common.statistics.user_total_sessions": "Numri total i herëve që janë luajtur të gjitha simulimet:",
            "Common.statistics.host_java_version_major": "Vesrioni i Java (major):",
            "FileChooser.openDialogTitleText": "Hap",
            "Common.statistics.host_java_version_maintenance": "Versioni i Java (mirëmbajtja):",
            "FileChooser.lookInLabelText": "Shiko në:",
            "Common.choice.cancel": "Fshi",
            "Common.updates.seePreferences": "Për të ndryshuar preferencat e juaja, shkoni tek File->Preferenca.",
            "Common.About.CreditsDialog.software-development": "Zhvillimi i Software-it",
            "Common.About.JavaVersion": "Versioni Java:",
            "ColorChooser.resetText": "Rivendos",
            "wavelength.ir": "IR",
            "Common.About.CreditsDialog.design-team": "Skuadra e Projektimit",
            "Common.statistics.sim_total_sessions": "Numri total i herëve që është luajtur ky simulim:",
            "Common.FileMenu.PreferencesMnemonic": "p",
            "wavelength.uv": "UV",
            "Games.title.gameSettings": "Parametra të Lojës",
            "XMLPersistenceManager.save.title": "Ruaj konfigurimin",
            "XMLPersistenceManager.load.error.contents": "Skedari është i dëmtuar ose nuk është krijuar nga ky simulim.",
            "Common.statistics.details.title": "Informacion",
            "Common.statistics.sim_dev_version": "Versioni i simulimit (dev):",
            "FileChooser.saveInLabelText": "Ruaj te:",
            "Common.statistics.sim_name": "Emri i simulimit:",
            "Save.confirm.message": "<html>Skedari që zgjodhët ekziston tashmë.<br>A doni ta zëvendësoni atë me skedarin që po ruani tani?</html>",
            "Games.label.score": "Pikët: {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "Skuadra e Zvhillimit PhET",
            "Games.button.start": "Fillo!",
            "Common.statistics.sim_deployment": "Tipi i zhvillimit:",
            "Common.FileMenu.Save": "Ruaj Konfigurimin...",
            "ColorChooser.hsbSaturationText": "S",
            "Games.radioButton.on": "on",
            "FileChooser.acceptAllFileFilterText": "Të gjithë skedarët (*.*)",
            "ColorChooser.hsbNameText": "HSB",
            "Common.ModelSlider.Minimum": "Minimumi",
            "Common.FileMenu.Preferences": "Preferenca...",
            "Common.FileMenu.Load": "Ngarko Konfigurimin...",
            "Common.updates.downloadingSimJar": "duke shkarkuar skedarin JAR të simulimit",
            "Games.radioButton.off": "off",
            "ColorChooser.swatchesRecentText": "Të fundit:",
            "Common.updates.updateAvailable": "Azhornim i disponueshëm",
            "Common.statistics.host_locale_language": "Gjuha mikpritëse:",
            "Common.clear": "Pastro",
            "Games.title.gameOver": "Loja Mbaroi",
            "FileChooser.filesOfTypeLabelText": "Skedarë të tipit:",
            "Common.ErrorDialog.detailsTitle": "Detaje të gabimit",
            "Common.HelpMenu.MegaHelp": "Ndihmë e madhe",
            "Common.ClockControlPanel.Step": "Hap para",
            "Common.statistics.sim_revision": "Versioni i simulimit (revision):",
            "Common.choice.yes": "Po",
            "Common.FileMenu.Title": "File",
            "Common.value_units": "{0} {1}",
            "Common.statistics.sim_dev": "A është ky një version zhvillimi?:",
            "Common.updates.installer.message": "<html>Instalimi juaj lokal i adresës PhET është i vjetër {0}.<br>Një version i ri është i disponueshëm, {1}.<br><br>Dëshironi të merrni versionin më të fundit të Instalimit Lokal të Faqes PhET></html>",
            "Common.updates.updateNow": "Azhorno Tani!",
            "Common.record": "Regjistro",
            "Common.About.CreditsDialog.Title": "Kredite",
            "Common.updates.error.internetConnection": "<html>Nuk mund të lidhemi me {0},<br>ju lutemi, kontrolloni lidhjen tuaj me internetin.</html>",
            "Common.time.fast": "shpejt",
            "XMLPersistenceManager.load.error.message": "<html>Gabim gjatë leximit të skedarit:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "Maksimumi",
            "Common.OptionsMenu": "Opsione",
            "Common.ClockControlPanel.Restart": "Rifillo",
            "Common.statistics.sim_version_timestamp": "Versioni i simulimit (koha e instalimit):",
            "Common.updates.installer.yes": "Po!",
            "Common.phetInstaller": "Instaluesi i Paketës PhET",
            "Common.HelpMenu.About": "Rreth...",
            "Common.ModelSlider.OutOfRange": "Vlerë jashtë rangut",
            "ColorChooser.previewText": "Pamje",
            "Common.BasicPhetPanel.Title": "Kthehu",
            "Common.HelpPanel.HideHelp": "Fshih Ndihmën",
            "Common.statistics.host_os_arch": "Tipi i procesorit:",
            "Common.preferences.title": "Preferencat",
            "Games.button.newGame": "Lojë e Re",
            "ColorChooser.hsbRedText": "R",
            "ColorChooser.hsbBlueText": "B",
            "Common.ModelSlider.YouEntered": "Ju futët",
            "Games.label.newBest": "Më i miri I RI!",
            "Common.About.BuildDate": "Data e Realizimit",
            "Common.FileMenu.ExitMnemonic": "x",
            "Common.statistics.sim_project": "Emri i projektit:",
            "Games.label.best": "Më i miri: {0}",
            "Common.title.message": "Mesazh",
            "Common.updates.downloadingBootstrap": "duke shkarkuar bootstrap-in e azhornuesit...",
            "Common.title.error": "Gabim",
            "Common.FileMenu.Exit": "Dil",
            "Common.statistics.sim_major_version": "Versioni i simulimit (major):",
            "Common.updates.askMeLater": "Më pyet më vonë",
            "chart-time-control.go": "Ec!",
            "Common.HelpMenu.HelpMnemonic": "h",
            "Common.confirm.clear.graphs": "A jeni të sigurt që doni të pastroni grafikët?",
            "ColorChooser.swatchesNameText": "Orët",
            "Common.updates.progressDialogMessage": "Duke azhornuar \"{0}\" në versionin {1}",
            "Common.updates.installer.more": "Më trego më shumë...",
            "XMLPersistenceManager.title.error": "Gabim",
            "ColorChooser.hsbHueText": "H",
            "ControlPanel.button.resetAll": "Rivendosi të Gjitha",
            "Common.About.AgreementButton": "Marrëveshja për Software-in",
            "Common.FileMenu.Load.mnemonic": "L",
            "Common.ErrorDialog.detailsButton": "Detaje...",
            "Common.updates.errorMissingJar": "<html>Ky azhornim nuk mund të kryhet.<br>Nuk mund të gjehet skedari JAR: {0}.<br>Ju lutemi, kontaktoni administratorin tuaj të sistemit për ndihmë.<br></html>",
            "Common.preferences.privacy": "Privatësia",
            "Common.HelpMenu.AboutTitle": "Rreth",
            "ColorChooser.rgbRedText": "E Kuqe",
            "Common.statistics.sim_locale_country": "Vendi:",
            "ColorChooser.hsbGreenText": "G",
            "ColorChooser.rgbGreenText": "E Gjelbër",
            "Games.format.time.best": "{0} ({1})",
            "Common.HelpPanel.ShowHelp": "Ndihmë!",
            "Common.statistics.sim_distribution_tag": "Versioni i simulimit (shpërndarja):",
            "Common.statistics.description": "PhET bëhet e disponueshme falas me anë të<br>mbledhjes së një sasie të vogël<br><a href=\"{0}\">informacionesh</a> anonime për të ndihmuar<br>në dokumentimin se sa përdoren simulimet PhET<br>dhe për t'iu shërbyer më mirë nevojave të përdoruesve.",
            "Common.softwareAgreement.message": "Në të gjitha simulimet PhET, ne mbledhim një sasi shumë të vogël<br><a href=\"{0}\">informacionesh</a>anonime sa herë që simulimi fillon<br>(p.sh., versioni i simulimit, sistemi i shfrytëzimit)<br>Ju mund ta ndaloni dërgimin e këtij informacioni<br>në çdo kohë me anë të menu-së File->Preferenca.<br><br>Duke klikuar \"Prano dhe Vazhdo\", ju jeni dakort me<br>Marrëveshjen e Software-it të PhET, duke përfshirë<br>marrëveshjen për ruajtjen e privatësisë,<br>për këtë dhe të gjitha simulimet PhET që ju do përdorni.<br>(Për më shumë detaje klikoni këtu <a href=\"{1}\">here</a>).",
            "Common.choice.ok": "OK",
            "Common.About.Version": "Versioni:",
            "Common.ErrorDialog.contactPhet": "Në qoftë se ky problem vazhdon, dërgjini detajet e mëposhtme tek {0}",
            "Common.About.CreditsDialog.lead-design": "Udhëheqësi i Projektit",
            "Common.OptionsMenu.mnemonic": "O",
            "Common.statistics.user_preference_file_creation_time": "Koha e krijimit të skedarëve",
            "Common.HelpMenu.AboutMnemonic": "a",
            "Common.updates.errorWritePermissions": "<html>Ky azhornim nuk mund të kryhet.<br>Ju nuk mund të shkruani tek {0}.<br>Ju lutemi, kontaktoni administratorin tuaj të sistemit për ndihmë.<br></html>",
            "ColorChooser.hsbBrightnessText": "B",
            "Common.choice.no": "Jo",
            "Common.About.WebLink": "Vizitoni faqen PhET",
            "Common.About.OSVersion": "Versioni i Sistemit të Shfrytëzimit:",
            "Common.title.warning": "Kujdes",
            "Common.updates.versionComparison": "<html>Versioni juaj i tanishëm i \"{0}\" është {1}.<br>Një versioni i ri ({2}) është i disponueshëm.</html>",
            "Common.statistics.sim_locale_language": "Gjuha:",
            "Common.statistics.user_installation_timestamp": "Koha e instalimit të PhET:",
            "Common.statistics.message_version": "Versioni i mesazhit:",
            "Common.ModelSlider.Description": "Vlerë e palejuar.",
            "Common.updates.installer.moreMessage": "<html>Mbajta e Instaluesit tuaj Lokal të Faqes PhET të azhornuar<br>ju siguron akses tek simulimet më të fundit PhET<br>dhe materiale shtesë.<br><br>Në qoftë se zgjidhni të merrni versionin më të ri,<br>do iu hapet një web browser <br>tek faqja e PhET ku ju mund të shkarkoni<br>Instaluesin Lokal të Faqes.</html>",
            "ControlPanel.message.confirmResetAll": "Të rivendosen të gjitha parametrat?",
            "Common.HelpMenu.Help": "Ndihmë",
            "Common.updates.errorNotAJar": "{0} nuk është një skedar JAR.",
            "Games.label.levelControl": "Niveli:",
            "Common.updates.automaticallyCheck": "Kontrollo automatikisht për azhornime",
            "Common.sim.speed": "...shpejtësia e simulimit...",
            "Common.updates.checkForSimUpdate": "Kontrollo për azhornime të simulimit",
            "XMLPersistenceManager.save.confirm.message": "<html>Skedari që zgjodhët ekziston tashmë.<br>A doni ta zëvendësoni atë me skedarin që po ruani?</html>",
            "FileChooser.newFolderErrorText": "Gabim në krijimin e dosjes së re",
            "Common.About.CreditsButton": "Kredite...",
            "Common.updates.skipThisUpdate": "Kapërce këtë version.",
            "Common.FileMenu.Save.mnemonic": "S",
            "FileChooser.saveDialogTitleText": "Ruaj",
            "XMLPersistenceManager.load.title": "Ngarko konfigurimin",
            "Common.updates.checkForInstallerUpdate": "Kontrollo për azhornime të instaluesit lokalisht të faqes së PhET...",
            "timeseries.control.panel.playback": "Playback",
            "Common.updates.progressDialogTitle": "Duke azhornuar",
            "Common.HelpMenu.Title": "Ndihmë",
            "ColorChooser.rgbNameText": "RGB",
            "FileChooser.fileNameLabelText": "Emri i skedarit:",
            "Common.softwareAgreement.title": "Marrëveshja e Software-it",
            "Common.statistics.host_java_version_minor": "Versioni i Java (minor):",
            "Common.HelpMenu.TitleMnemonic": "h",
            "Common.About.CreditsDialog.interviews": "Intervista",
            "Common.About.Distribution": "Shpërndarja",
            "Common.statistics.host_java_webstart_version": "Versioni i Java Web Start:",
            "XMLPersistenceManager.save.error.message": "<html>Gabim gjatë shkrimit tek skedari:<br>{0}</html>",
            "Games.label.time": "Koha: {0}",
            "FileChooser.openButtonText": "Hap",
            "ColorChooser.sampleText": "Tekst Shembull Tekst Shembull",
            "Common.statistics.details.description": "<html>Informacioni i treguar më poshtë do dërgohet tek PhET, sa herë që fillon simulimi.</html>",
            "Common.statistics.host_os_version": "Versioni i sistemit të shfrytëzimit:",
            "Common.title.confirm": "Konfirmo",
            "Common.BasicPhetPanel.LogoToolTip": "Çaktivizo të gjithë frame-in",
            "Games.label.score.max": "Pikët: {0} nga {1}",
            "Common.statistics.host_java_timezone": "Zona Orare:",
            "Common.time.slow": "ngadalë",
            "FileChooser.newFolderErrorSeparator": ":",
            "Common.ClockControlPanel.Rewind": "Rikthe",
            "Common.softwareAgreement.accept": "Prano dhe Vazhdo",
            "Common.updates.updateToDate": "I Azhornuar",
            "Common.ClockControlPanel.Pause": "Ndërpre",
            "PhetApplication.StartupDialog.message": "\"{0}\" po fillon.",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "Ky program përdor edhe software-t e mëposhtëm",
            "XMLPersistenceManager.message.notAConfigFile": "Ky skedar nuk përmban ndonjë konfigurim për këtë simulim.",
            "Common.preferences.updates": "Azhornime",
            "Games.label.score.max.perfect": "Pikët: {0} nga {1} (PERFEKTE!)",
            "Common.HelpMenu.MegaHelpMnemonic": "m",
            "Common.statistics.enabled": "Lejo dërgimin e informacionit tek PhET",
            "Common.ClockControlPanel.StepBack": "Hap mbrapa",
            "Common.StopwatchPanel.stop": "Ndalo",
            "Common.HelpPanel.MegaHelp": "Ndihmë e madhe...",
            "Common.statistics.host_locale_country": "Vendi mikpritës:",
            "Common.StopwatchPanel.reset": "Rivendos",
            "Common.playback": "Playback",
            "Common.statistics.sim_minor_version": "Versioni i simulimit (minor):",
            "Games.message.confirmNewGame": "<html>Ju nuk e keni mbaruar akoma këtë lojë.<br>Jeni të sigurt që doni të filloni një lojë të re?</html>",
            "Common.updates.tryIt": "Provo versionin e ri përpara azhornimit.",
            "ColorChooser.rgbBlueText": "Blu",
            "Common.choice.close": "Mbyll",
            "Common.ClockControlPanel.Play": "Luaj",
            "Common.statistics.sim_type": "Tipi i simulimit:",
            "FileChooser.saveButtonText": "Ruaj",
            "Common.rewind": "Rikthe",
            "Common.StopwatchPanel.start": "Fillo",
            "Common.updates.youHaveCurrent": "Ju keni versionin ({0}) më të tanishëm të {1}.",
            "Common.statistics.sim_sessions_since": "Numri i herëve që ky simulim është luajtur që nga hera e fundit online:",
            "Common.statistics.host_java_vendor": "Shpërndarësi i Java:",
            "charts.show-graphs": "Shfaq grafikët:",
            "Common.statistics.message_type": "Tipi i mesazhit:"
        } );