<?php
require_once 'PHPUnit/Framework.php';

require_once 'JavaSimulation.php';

/**
 * Test class for JavaSimulation.
 * Generated by PHPUnit on 2009-02-10 at 16:52:42.
 */
class JavaSimulationTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var    JavaSimulation
     * @access protected
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp()
    {
        $this->object = new JavaSimulation;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetTranslations().
     */
    public function testGetTranslations() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
