// Copyright 2002-2011, University of Colorado
package edu.colorado.phet.balanceandtorque;

import java.awt.image.BufferedImage;

import edu.colorado.phet.common.phetcommon.resources.PhetResources;

/**
 * Resources (images and translated strings) for "BalanceAndTorque" are loaded eagerly to make sure everything exists on sim startup, see #2967.
 * Automatically generated by edu.colorado.phet.buildtools.preprocessor.ResourceGenerator
 */
public class BalanceAndTorqueResources {
    public static final String NAME = "balance-and-torque";
    public static final PhetResources RESOURCES = new PhetResources( NAME );

    //Strings
    public static class Strings {

    }

    //Images
    public static class Images {
        public static final BufferedImage BOY_SITTING = RESOURCES.getImage( "boy-sitting.png" );
        public static final BufferedImage BOY_STANDING = RESOURCES.getImage( "boy-standing.png" );
        public static final BufferedImage GIRL_SITTING = RESOURCES.getImage( "girl-sitting.png" );
        public static final BufferedImage GIRL_STANDING = RESOURCES.getImage( "girl-standing.png" );
        public static final BufferedImage MAN_SITTING = RESOURCES.getImage( "man-sitting.png" );
        public static final BufferedImage MAN_STANDING = RESOURCES.getImage( "man-standing.png" );
        public static final BufferedImage MYSTERY_OBJECT_01 = RESOURCES.getImage( "mystery-object-01.png" );
        public static final BufferedImage MYSTERY_OBJECT_02 = RESOURCES.getImage( "mystery-object-02.png" );
        public static final BufferedImage MYSTERY_OBJECT_03 = RESOURCES.getImage( "mystery-object-03.png" );
        public static final BufferedImage MYSTERY_OBJECT_04 = RESOURCES.getImage( "mystery-object-04.png" );
        public static final BufferedImage MYSTERY_OBJECT_05 = RESOURCES.getImage( "mystery-object-05.png" );
        public static final BufferedImage MYSTERY_OBJECT_06 = RESOURCES.getImage( "mystery-object-06.png" );
        public static final BufferedImage MYSTERY_OBJECT_07 = RESOURCES.getImage( "mystery-object-07.png" );
        public static final BufferedImage MYSTERY_OBJECT_08 = RESOURCES.getImage( "mystery-object-08.png" );
        public static final BufferedImage ROCK_4 = RESOURCES.getImage( "rock_4.png" );
        public static final BufferedImage ROCK_6 = RESOURCES.getImage( "rock_6.png" );
        public static final BufferedImage WOMAN_SITTING = RESOURCES.getImage( "woman-sitting.png" );
        public static final BufferedImage WOMAN_STANDING = RESOURCES.getImage( "woman-standing.png" );
    }
}