#!/bin/bash

# builds all of the html files for all locales

for sim_name in arithmetic blackbody-spectrum charges-and-fields curve-fitting equation-grapher estimation faradays-law friction geometric-optics lunar-lander mass-spring-lab my-solar-system ohms-law pendulum-lab plinko-probability projectile-motion resistance-in-a-wire stern-gerlach vector-addition wave-on-a-string;
do
	
	# sim directories (left for reference, used in restructuring)
	sim_old=old-simulations/${sim_name}
	sim_dir=simulations/${sim_name}
	sim_data=${sim_dir}/data
	sim_deploy=${sim_dir}/deploy
	sim_src=${sim_dir}/src
	sim_data_sub=${sim_data}/${sim_name}
	sim_images=${sim_data_sub}/images
	sim_localization=${sim_data_sub}/localization
	
	# for every XML file in the localization directory
	for file in ${sim_localization}/*.xml;
	do
		# locale string (en_US)
		locale=`echo "${file}" | sed -e 's/[^_]*_\(.*\)\.xml/\1/'`
		
		# split locale string into parts (en US)
		split_locale=`echo "${locale}" | sed -e 's/_/ /'`
		
		echo Building ${sim_name} ${split_locale}
		
		# build the HTML
		java FlashHTMLWriter ${sim_name} ${split_locale}
	done;
	
	# add what might be new to subversion
	for file in ${sim_deploy}/*.html;
	do
		svn add -q $file
	done;
	
	
done;
