#!/bin/bash

# builds all of the html files for all locales


# build the HTML builder!
echo "Building flash-build.jar"
javac -sourcepath build-tools/flash-build/src -d build-tools/flash-build/build build-tools/flash-build/src/edu/colorado/phet/flashbuild/util/FlashHTML.java
javac -sourcepath build-tools/flash-build/src -d build-tools/flash-build/build build-tools/flash-build/src/edu/colorado/phet/flashbuild/GenerateHTML.java
cp build-tools/flash-build/data/* build-tools/flash-build/build/
jar cfm flash-build.jar build-tools/flash-build/manifest -C build-tools/flash-build/build .

# for each sim, build each locale
for sim_name in arithmetic blackbody-spectrum charges-and-fields curve-fitting equation-grapher estimation faradays-law friction geometric-optics lunar-lander mass-spring-lab my-solar-system ohms-law pendulum-lab plinko-probability projectile-motion resistance-in-a-wire stern-gerlach test-flash-project vector-addition wave-on-a-string;
do
	
	# sim directories (left for reference, used in restructuring)
	sim_old=old-simulations/${sim_name}
	sim_dir=simulations/${sim_name}
	sim_data=${sim_dir}/data
	sim_deploy=${sim_dir}/deploy
	sim_src=${sim_dir}/src
	sim_data_sub=${sim_data}/${sim_name}
	sim_images=${sim_data_sub}/images
	sim_localization=${sim_data_sub}/localization

    # copy the needed get_flash.jpg into the deploy directory
	cp build-tools/flash-build/data/get_flash.jpg ${sim_deploy}/
	
	# for every XML file in the localization directory
	for file in ${sim_localization}/*.xml;
	do
		# locale string (en_US)
		locale=`echo "${file}" | sed -e 's/[^_]*_\(.*\)\.xml/\1/'`
		
		# split locale string into parts (en US)
		split_locale=`echo "${locale}" | sed -e 's/^\(..\)$/\1 null/;s/_/ /'`
		
		echo Building ${sim_name} ${split_locale}
		
		# build the HTML
		java -jar flash-build.jar ${sim_name} ${split_locale} phet-website
	done;

	echo Building ${sim_name} pg US
	java -jar flash-build.jar ${sim_name} pg US phet-website
	
	# add what might be new to subversion
	#for file in ${sim_deploy}/*.html;
	#do
	#	svn add -q $file
	#done;
	
done;
