//Conversion from C:\workingcopy\phet\svn-1.7\trunk\simulations-java\common\phetcommon\data\phetcommon\localization\phetcommon-strings_ko.properties
define( {
            "Games.label.level": "레벨: {0}",
            "Common.updates.errorMessage": "업데이트 중 오류가 발생했습니다.<br>다시 한번 시도하거나 {0}을 방문하십시오.",
            "XMLPersistenceManager.save.error.encode": "<html>인코딩 오류:<br>{0}</html>",
            "XMLPersistenceManager.load.error.decode": "<html>디코딩 오류:<br>{0}</html>",
            "Common.FileMenu.TitleMnemonic": "f",
            "Common.softwareAgreement.decline": "나가기",
            "Common.statistics.host_os_name": "운영체제 이름",
            "Common.statistics.user_total_sessions": "전체 시뮬레이션의 총 실행 횟 수",
            "Common.statistics.host_java_version_major": "자바 버전 (주판)",
            "FileChooser.openDialogTitleText": "열기",
            "Common.statistics.host_java_version_maintenance": "자바 버전 (유지 보수)",
            "FileChooser.lookInLabelText": "찾을 위치:",
            "Common.choice.cancel": "취소",
            "Common.updates.seePreferences": "환경설정은 '파일->환경설정'에서 합니다.",
            "Common.About.CreditsDialog.software-development": "소프트웨어 개발",
            "Common.About.JavaVersion": "자바 버전:",
            "ColorChooser.resetText": "초기화",
            "wavelength.ir": "IR",
            "Common.About.CreditsDialog.design-team": "디자인팀",
            "Common.statistics.sim_total_sessions": "이 시뮬레이션이 실행된 총 횟 수",
            "Games.title.gameSettings": "게임 세팅",
            "Common.FileMenu.PreferencesMnemonic": "p",
            "wavelength.uv": "UV",
            "XMLPersistenceManager.save.title": "설정 저장하기",
            "XMLPersistenceManager.load.error.contents": "파일이 잘못되었거나 이 시뮬레이션으로 만들어진 것이 아닙니다.",
            "Common.statistics.details.title": "정보",
            "Common.statistics.sim_dev_version": "시뮬레이션 버전(개발)",
            "FileChooser.saveInLabelText": "저장 위치:",
            "Common.statistics.sim_name": "시뮬레이션 이름",
            "Save.confirm.message": "<html>선택한 파일이 이미 존재합니다.<br>이 파일로 덮어 쓸까요?</html>",
            "Games.label.score": "점수: {0}",
            "Common.About.CreditsDialog.PhetDevelopmentTeam": "PhET 개발팀",
            "Games.button.start": "시작!",
            "Common.statistics.sim_deployment": "개발 형식",
            "Common.FileMenu.Save": "환경설정 저장",
            "ColorChooser.hsbSaturationText": "S",
            "Games.radioButton.on": "켜기",
            "FileChooser.acceptAllFileFilterText": "모든 파일 (*.*)",
            "ColorChooser.hsbNameText": "HSB",
            "Common.ModelSlider.Minimum": "최소값",
            "Common.FileMenu.Preferences": "기본설정...",
            "Common.FileMenu.Load": "환경설정 불러오기",
            "Common.updates.downloadingSimJar": "시뮬레이션 JAR파일 불러오기...",
            "Games.radioButton.off": "끄기",
            "ColorChooser.swatchesRecentText": "최근 사용 :",
            "Common.updates.updateAvailable": "업데이트 가능",
            "Common.statistics.host_locale_language": "사용 언어",
            "Common.clear": "지우기",
            "Games.title.gameOver": "게임 끝",
            "FileChooser.filesOfTypeLabelText": "파일 형식:",
            "Common.ErrorDialog.detailsTitle": "오류 세부사항 ",
            "Common.HelpMenu.MegaHelp": "상세 도움말...",
            "Common.ClockControlPanel.Step": "단계",
            "Common.statistics.sim_revision": "시뮬레이션 버전 (개정)",
            "Common.choice.yes": "예",
            "Common.FileMenu.Title": "파일",
            "Common.value_units": "{0}{1}",
            "Common.statistics.sim_dev": "이것은 개발자 버전입니까?",
            "Common.updates.installer.message": "<html>현 PhET 오프라인 웹사이트 설치일자는 {0}입니다.<br> {1} 일자의 새로운 버전의 설치가 가능합니다.<br><br>최신의 PhET 오프라인 웹사이트를 설치하시겠습니까?</html>",
            "Common.updates.updateNow": "지금 업데이트!",
            "Common.record": "기록",
            "Common.About.CreditsDialog.Title": "제작 참여자",
            "Common.updates.error.internetConnection": "<html>{0}으로 연결할 수 없습니다,<br>인터넷 연결을 확인하십시오.</html>",
            "Common.time.fast": "빠름",
            "XMLPersistenceManager.load.error.message": "<html>파일 읽기 오류:<br>{0}</html>",
            "Common.ModelSlider.Maximum": "최대값",
            "Common.OptionsMenu": "선택",
            "Common.ClockControlPanel.Restart": "재시작",
            "Common.statistics.sim_version_timestamp": "시뮬레이션 버전 (타임스탬프)",
            "Common.updates.installer.yes": "예!",
            "Common.phetInstaller": "PhET 오프라인 웹사이트 설치 파일",
            "Common.HelpMenu.About": "개관...",
            "Common.ModelSlider.OutOfRange": "범위를 벗어난 값",
            "ColorChooser.previewText": "미리 보기",
            "Common.BasicPhetPanel.Title": "돌아가기",
            "Common.HelpPanel.HideHelp": "도움말 숨기기",
            "Common.statistics.host_os_arch": "프로세서 형식",
            "Common.preferences.title": "기본설정",
            "Games.button.newGame": "새로운 게임",
            "ColorChooser.hsbRedText": "R",
            "ColorChooser.hsbBlueText": "B",
            "Common.ModelSlider.YouEntered": "입력한 값",
            "Games.label.newBest": "새로운 최고 점수",
            "Common.About.BuildDate": "데이터 작성:",
            "Common.FileMenu.ExitMnemonic": "x",
            "Games.label.best": "최고점수: {0}",
            "Common.statistics.sim_project": "프로젝트 이름",
            "Common.title.message": "메시지",
            "Common.updates.downloadingBootstrap": "업데이트 부트트랩 불러오기",
            "Common.title.error": "오류",
            "Common.FileMenu.Exit": "나가기",
            "Common.statistics.sim_major_version": "시뮬레이션 버전(주판)",
            "Common.updates.askMeLater": "나중에 질문",
            "chart-time-control.go": "시작",
            "Common.HelpMenu.HelpMnemonic": "h",
            "Common.confirm.clear.graphs": "그래프를 지우시겠습니까?",
            "ColorChooser.swatchesNameText": "색상 견본",
            "Common.updates.progressDialogMessage": " \"{0}\" 을 버전 {1}로 업데이트 함",
            "Common.updates.installer.more": "더 말씀해주세요...",
            "XMLPersistenceManager.title.error": "오류",
            "ColorChooser.hsbHueText": "H",
            "ControlPanel.button.resetAll": "모두 초기화",
            "Common.About.AgreementButton": "소프트웨어 동의서...",
            "Common.FileMenu.Load.mnemonic": "L",
            "Common.ErrorDialog.detailsButton": "세부사항...",
            "Common.updates.errorMissingJar": "<html>이 업데이트는 실행할 수 없습니다 .<br> JAR 파일: {0}을 찾을 수 없습니다.<br>시스템 관리자에게 문의하십시오.<br></html>",
            "Common.preferences.privacy": "개인정보",
            "Common.HelpMenu.AboutTitle": "개관",
            "ColorChooser.rgbRedText": "빨간색",
            "Common.statistics.sim_locale_country": "국가",
            "ColorChooser.hsbGreenText": "G",
            "ColorChooser.rgbGreenText": "녹색",
            "Games.format.time.best": "{0} ({1})",
            "Common.HelpPanel.ShowHelp": "도와 주세요!",
            "Common.statistics.sim_distribution_tag": "시뮬레이션 버전 (배급)",
            "Common.statistics.description": " PhET는 최소한의 무작위 <a href=\"{0}\">정보</a> 수집에 동의하면 <br>자유롭게 사용할 수 있습니다.<br>\n 이 정보는 PhET sims의 사용에 관한 것으로 <br>사용자들의 요구를 더 잘 반영하는데 도움을 <br>줄 것입니다<br>.",
            "Common.softwareAgreement.message": " 모든 PhET 시뮬레이션에서는 시뮬레이션을 실행할 때마다 <br>무작위로<a href=\"{0}\"> </a>정보를 수집합니다( 예, 시뮬레이션 버전, OS).<br> 그러나 파일->환경설정 메뉴에서 이 정보들을 보내지 <br>않게 할 수 있습니다.<br> 만일 '동의 및 계속'을 클릭하시면 실행하는 모든 <br>PhET 시뮬레이션에 대해서 PhET의 소프트웨어 동의서와 <br>개인정보 방침에 동의를 하는 것입니다(상세한 것은 여기 <fa>를 클릭하세요.<<a href=\"{1}\">",
            "Common.choice.ok": "적용",
            "Common.About.Version": "버전:",
            "Common.ErrorDialog.contactPhet": "이 문제가 계속 발생하면,  그 세부사항을  {0} 에 전송하십시오.",
            "Common.About.CreditsDialog.lead-design": "리드디자인",
            "Common.OptionsMenu.mnemonic": "O",
            "Common.statistics.user_preference_file_creation_time": "환경설정 파일 생성 타임 스탬프",
            "Common.HelpMenu.AboutMnemonic": "a",
            "Common.updates.errorWritePermissions": "<html>업데이트를 실행할 수 없습니다.<br>귀하는 {0}에 쓸 수 있는 권한이 없습니다.<br>시스템 관리자에게 문의하십시오<br></html>",
            "ColorChooser.hsbBrightnessText": "B",
            "Common.choice.no": "아니오",
            "Common.About.WebLink": "PhET 홈페이지를 방문하세요",
            "Common.About.OSVersion": "OS 버전:",
            "Common.title.warning": "경고",
            "Common.updates.versionComparison": "<html>사용중인 \"{0}\"의 버전은 {1}입니다.<br>새 버전 ({2})로 바꾸실 수 있습니다.</html>",
            "Common.statistics.sim_locale_language": "언어",
            "Common.statistics.user_installation_timestamp": "PhET 설치 타임 스탬프",
            "Common.statistics.message_version": "메시지 버전",
            "Common.ModelSlider.Description": "잘못된 값.",
            "Common.updates.installer.moreMessage": "<html> PhET 오프라인 웹사이트를 계속  업데이트 하십시오<br>사용하시는 PhET 시뮬레이션과 <br>보조 자료들이 최신 버전인지 확인하십시오<br><br>최신 버전의 설치를 선택하시면, 웹부라우저가 <br> PhET 웹사이트를 열 것이며<br>이 곳에서 최신 PhET 오프라인 웹사이트를 설치할 수 있습니다.</html>",
            "ControlPanel.message.confirmResetAll": "모든 설정을 초기화할까요?",
            "Common.HelpMenu.Help": "도움말",
            "Common.updates.errorNotAJar": "{0}은 JAR파일이 아닙니다.",
            "Games.label.levelControl": "레벨:",
            "Common.updates.automaticallyCheck": "자동으로 업데이트 체크",
            "Common.sim.speed": "...sim 속도...",
            "Common.updates.checkForSimUpdate": "시뮬레이션 업데이트 체크...",
            "XMLPersistenceManager.save.confirm.message": "<html>선택한 파일은 이미 존재합니다.<br>이 파일로 덮어 쓸까요?</html>",
            "FileChooser.newFolderErrorText": "새폴더 만들기 오류",
            "Common.updates.skipThisUpdate": "이 버전을 건너 뜀",
            "Common.About.CreditsButton": "제작참여자...",
            "Common.FileMenu.Save.mnemonic": "S",
            "FileChooser.saveDialogTitleText": "저장",
            "XMLPersistenceManager.load.title": "설정 불러오기",
            "Common.updates.checkForInstallerUpdate": "PhET 오프라인 설치파일 업데이트 체크...",
            "timeseries.control.panel.playback": "재생",
            "Common.updates.progressDialogTitle": "업데이트함",
            "Common.HelpMenu.Title": "도움말",
            "ColorChooser.rgbNameText": "RGB",
            "FileChooser.fileNameLabelText": "파일 이름:",
            "Common.softwareAgreement.title": "소프트웨어 동의서",
            "Common.statistics.host_java_version_minor": "자바 버전 (부판)",
            "Common.HelpMenu.TitleMnemonic": "h",
            "Common.About.CreditsDialog.interviews": "인터뷰",
            "Common.About.Distribution": "배급:",
            "Common.statistics.host_java_webstart_version": "자바 웹 시작 버전",
            "XMLPersistenceManager.save.error.message": "<html>파일 쓰기 오류:<br>{0}</html>",
            "Games.label.time": "시간: {0}",
            "FileChooser.openButtonText": "열기",
            "ColorChooser.sampleText": "견본 글...견본 글...",
            "Common.statistics.details.description": "<html>아래에 보여지는 정보는 시뮬레이션이 시작될 때, PhET에 전송됩니다.</html>",
            "Common.statistics.host_os_version": "운영체제 버전",
            "Common.title.confirm": "확인",
            "Games.label.score.max": "점수: {1} 점 만점에 {0}점",
            "Common.BasicPhetPanel.LogoToolTip": "전체 프레임 보기 금지",
            "Common.statistics.host_java_timezone": "시간대",
            "Common.time.slow": "느림",
            "FileChooser.newFolderErrorSeparator": ": ",
            "Common.ClockControlPanel.Rewind": "되감기",
            "Common.softwareAgreement.accept": "동의 및 진행",
            "Common.updates.updateToDate": "업투데이트",
            "Common.ClockControlPanel.Pause": "정지",
            "PhetApplication.StartupDialog.message": "\"{0}\"을 시작 중입니다.",
            "Common.About.CreditsDialog.UsesThirdPartySoftware": "이 프로그램은 다음의 제3자 소프트웨어를 사용합니다",
            "XMLPersistenceManager.message.notAConfigFile": "이 파일은 본 시뮬레이션의 설정을 포함하고 있지 않습니다.",
            "Common.preferences.updates": "업데이트",
            "Games.label.score.max.perfect": "점수: {1}점 만점에 {0}점 (만점)",
            "Common.HelpMenu.MegaHelpMnemonic": "m",
            "Common.statistics.enabled": "PhET에 정보 전송 동의",
            "Common.StopwatchPanel.stop": "정지",
            "Common.HelpPanel.MegaHelp": "상세 도움말...",
            "Common.statistics.host_locale_country": "해당 국가",
            "Common.StopwatchPanel.reset": "초기화",
            "Common.playback": "재생",
            "Games.message.confirmNewGame": "<html>아직 게임이 끝나지 아니했습니다.<br>새로운 게임을 시작하시겠습니까?</html>",
            "Common.statistics.sim_minor_version": "시뮬레이션 버전(부판)",
            "Common.updates.tryIt": "업데이트에 앞서 새로운 버전을 사용해보세요.",
            "ColorChooser.rgbBlueText": "파란색",
            "Common.choice.close": "닫기",
            "Common.ClockControlPanel.Play": "실행",
            "Common.statistics.sim_type": "시뮬레이션 형식",
            "FileChooser.saveButtonText": "저장",
            "Common.rewind": "되감기",
            "Common.StopwatchPanel.start": "시작 ",
            "Common.updates.youHaveCurrent": "{1}의 최신 버전({0})을 가지고 계십니다.",
            "Common.statistics.sim_sessions_since": "마지막 온라인 이후 이 시뮬레이션이 실행된 횟 수.",
            "Common.statistics.host_java_vendor": "자바 공급자",
            "charts.show-graphs": "그래프보기:",
            "Common.statistics.message_type": "메시지 형식"
        } );